package.json

Option `--ext` is not expected to work with globs, see
http://eslint.org/docs/user-guide/command-line-interface#ext.

Remove `--ext` and use globs for extension names

---

packages/theme-default/src/dialog.css

`popup.css` in package `theme-default` depends on `dialog` package dependencies. `vue-popup` is already required in global context. so this PR removes this dependency :)

resolve cross package dependency for theme-default

---

packages/theme-default/src/step.css

PR内容：
- 去掉竖形步骤条description的`300px`长度：不建议定义这个长度，而且如果不定义`word-wrap: break-word`，里面的文字其实会一直延伸下去。
- 去掉title的`margin-top`而用`line-height`取代：这个视觉效果更好一些

Step: Modify Step styling

---

packages/theme-default/src/alert.css

It's a minor fix to keep the default theme consistent and customizable.

alert.css should use variables for colours instead of hardcoded values

---

packages/theme-default/src/step.css

让Steps里面图标居中 （默认是[base-line](https://github.com/ElemeFE/element/blob/master/packages/theme-default/src/icon.css#L20)）

Steps: add vertical-align: middle

---

CHANGELOG.md
examples/docs/zh-cn/table.md
packages/table/package.json
packages/table/src/table-body.js
packages/table/src/table-column.js
packages/table/src/table-header.js
packages/table/src/table-layout.js
packages/table/src/table-store.js
packages/table/src/table.vue
packages/table/src/util.js
packages/theme-default/src/table.css

1. Add TableStore & TableLayout.
2. Remove customCriteria & customCriteria.
3. Remove fixedColumnCount.
4. Add fixed prop for TableColumn.
5. Add selectable prop for TableColumn[type="selection"].
#293 #264 #60 #180 #258

Improve Table

---

.eslintrc
build/cooking.test.js
packages/slider/src/main.vue
packages/switch/src/component.vue
packages/upload/src/iframe-upload.vue
test/unit/.eslintrc
test/unit/specs/slider.spec.js

Slider: add test

---

CHANGELOG.md
examples/docs/zh-cn/table.md
packages/table/src/table-body.js
packages/table/src/table-column.js
packages/table/src/table-store.js
packages/table/src/table.vue

1. Add rowKey prop for Table.
2. Add clearSelection method for Table.
2. Add reserveSelection prop for TableColumn[type="selection"]
#324 #285

Update Table: add reserveSelection 

---

CHANGELOG.md
packages/menu/src/menu-item.vue
packages/menu/src/menu.vue
packages/theme-default/src/menu.css

Menu improve

---

examples/docs/zh-cn/checkbox.md
test/unit/specs/checkbox.spec.js

add checkbox test

---

examples/docs/zh-cn/pagination.md
packages/pagination/src/pager.vue
packages/pagination/src/pagination.js
test/unit/specs/date-picker.spec.js
test/unit/specs/pagination.spec.js
test/unit/util.js

Pagination: add test

---

.github/CONTRIBUTING.md
examples/docs/zh-cn/table.md
packages/table/src/table-body.js
packages/table/src/table-column.js
src/index.js
test/unit/specs/table.spec.js
test/unit/util.js

Table: add test

---

packages/date-picker/src/panel/date-range.vue
packages/date-picker/src/panel/date.vue
packages/date-picker/src/picker.vue
test/unit/specs/date-picker.spec.js

DatePicker: improve test

---

examples/docs/zh-cn/upload.md

Upload(doc): show-uploadList => show-upload-list, fixed #680

---

packages/message/src/main.vue
packages/notification/src/main.vue

问题描述：
如果我在组件中加入不同的transition或者transition: all duration的形式，
那么this.$el.addEventListener(‘transitioned’,
handeler)就会监听到多次事件，从而导致多次删除，因为节点已经从dom中删除，
所以最后报错：
’main.vue?8f52:44 Uncaught TypeError: Cannot read property 'removeChild' of null’
解决办法：
就是在第一次监听到动画结束事件时，将监听器移除即可。

Message, Notification: fix transitionend bug

---

examples/docs/zh-CN/tabs.md

fix tabs 组件的基础用法示例

---

packages/theme-default/src/table.css

带多选功能的表格若同时设置了 `:striped="true"` 会导致 `tr` 的背景色异常，将背景色设置在 `td` 上可以解决这个问题。

Table: 将 striped table 的背景色设置在 td 元素上

---

examples/docs/en-US/custom-theme.md
examples/docs/zh-CN/custom-theme.md

When `src/main.js` imports `theme/index.css`, the import statement should import `'../theme/index.css'`, not `'./theme/index.css'`.

Docs: fix custom theme import path

---

examples/docs/en-US/table.md
examples/docs/zh-CN/table.md
packages/table/src/table-body.js
packages/table/src/table.vue
test/unit/specs/table.spec.js

Table: add row-style prop. closed #1251

---

packages/date-picker/src/panel/date-range.vue

就是现在清除datetimerange picker的日期时总会在panel editor显示那里留下1970.。。。什么的，
顺便，让时间和日期在panel editor表现一致一些
看测试挂了，，不是我的错。。。12月到了

datetimepicker: fix clear panel date and time show when clear

---

packages/theme-default/src/tag.css

When the width of parent container is too narrow, text in tag will be
break into lines.
當父容器寬度不足時，Tag 文字會產生換行的現象

Tag: Fix text wrap

---

packages/menu/src/menu.vue

Check following gif, as a user, i may specify a route, for example: `/order`. Once the web opened, the `menuitem` matches `defaultActive`  is selected, which is incorrect. The `menuitem` that user specified shall be selected.
Reproduce code:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<script src="https://unpkg.com/vue/dist/vue.js"></script>
<script src="https://unpkg.com/vue-router/dist/vue-router.js"></script>
<script src="https://unpkg.com/element-ui/lib/index.js"></script>
<link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-default/index.css">
</head>
<body>
<div id="app">
<el-menu theme="dark" default-active="1" class="el-menu-demo" mode="horizontal" router>
<el-menu-item index="1" :route="{ path: '/center' }">处理中心</el-menu-item>
<el-menu-item index="2" :route="{ …
```

[ElMenu]: active menuitem which matches user specfied route

---

packages/input-number/src/input-number.vue
packages/theme-default/src/input-number.css
test/unit/specs/input-number.spec.js

input number fix change event & improve

---

packages/alert/src/main.vue
packages/badge/src/main.vue
packages/card/src/main.vue
packages/dialog/src/component.vue
packages/popover/src/main.vue
packages/rate/src/main.vue
packages/select/src/option-group.vue
packages/select/src/option.vue
packages/select/src/select-dropdown.vue
packages/steps/src/step.vue
packages/steps/src/steps.vue
packages/switch/src/component.vue
packages/table/src/filter-panel.vue
packages/table/src/table-column.js
packages/table/src/table-header.js
packages/table/src/table.vue
packages/tabs/src/tab-pane.vue
packages/tabs/src/tabs.vue
packages/tooltip/src/main.vue
packages/tree/src/tree-node.vue
packages/tree/src/tree.vue
packages/upload/src/index.vue

Thanks for bring us Element!
I'm using a DSL library to generate Vue VNode by method call. This works for most component in Element. For example, `vnodeHelper.elCol.elCol()` can correctly generate vnode in the format like `h('elCol')` .
However, some Element component has different naming schema so vnode helper fails to find corresponding components since Vue will not normalize snake case name. 
Given most component names in Element is CamelCase, I think it might be good practice to enforce the rule to every component.
Looking forward to your opinion and Happy new year!

general: normalize name in default export

---

packages/table/src/table-body.js
packages/table/src/table-header.js

I dont know whether it is about #2198 
but I find some of my tables width is totally messed in safari.
I try to wrap `<col>` in `<colgroup>` and it works in safari now.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col

table: wrap col in colgroup to make column width work in safari

---

packages/date-picker/src/panel/date.vue

Changed year label to prevent hyphen immediately followed by a year. Example:

DatePicker: Fix year label space in year picker

---

src/utils/date.js

`src/utils/date.js L237`
typo: `parseFlags.DD = parseFlags.DD;`

Fix: typo in date.js, assign "DD" to itself.

---

packages/table/src/table-header.js

#2324 extend sort and filter click area to th element
将sort和filter的点击范围扩大到th标签。
1. 如果th里只有sort, 则点击th等于点击sort的图标，并发送`header-click`事件。
2. 如果th里只有filter，则点击th等于点击filter, 并发送`header-click`事件。
3. 如果th既有sort又有filter，则点击th无作用，只发送`header-click`事件。

#2324 extend sort and filter click area to th element

---

packages/theme-default/src/collapse.css
packages/theme-default/src/common/transition.css
packages/theme-default/src/tree.css
src/transitions/collapse-transition.js

有两个问题，仅针对safari （Version 9.1 (11601.5.17.1)）
首先是如果元素上有css transition，el.style.height=""重置高度时，safari中transition动画会先到0，再到auto的高度。因此需要在重置高度之前移除css transition。（按理说，没有height不该触发transition）
其次，如果元素上有css transition，如果设置height，nextTick再设置为0，safari中会直接变成0并不触发css动画，但是设置height，在nextTIck加上css transition，再设置height为0，则触发过渡动画。
参考：
对比其他浏览器和safari
http://codepen.io/reverland/pen/PWWedw
ps: 听说可能有定制款＝ ＝ https://github.com/ElemeFE/element/issues/2498#issuecomment-273411891 @Kingwl

collapse-transition: fix strange transition behaviour in safari

---

packages/popover/src/main.vue

This doesn't actually seem to fix the problem completely, but it should be a start.
There are still some VueComponents of the popovers in memory.

remove popover's document click handler, related to #2561

---

packages/autocomplete/src/autocomplete.vue
yarn.lock

This PR is a fix for preventing triggering default keyup and keydown behaviors, which means cursor movements, when navigating the suggestions.
* element-ui version: 1.1.6
Navigating the suggestions without moving the cursor back and forth.
Navigating the suggestions with moving the cursor back and forth.
Check out the official docs: [http://element.eleme.io/#/en-US/component/input#autocomplete](http://element.eleme.io/#/en-US/component/input#autocomplete).
```vue
<template>
<div class="el-autocomplete" v-clickoutside="handleClickoutside">
<el-input
ref="input"
:value="value"
:disabled="disabled"
:placeholder="placeholder"
:name="name"
:size="size"
@change="handleChange"
@focus="handleFocus"
@blur="handleBlur"
@keydown.up.native.prevent="highlight(highlightedIndex - 1)" …
```

Autocomplete: fix bug for keyup or keydown default behavior

---

examples/docs/en-US/input.md
packages/autocomplete/src/autocomplete.vue

This PR adds 'icon' and 'on-icon-click' attributes to Autocomplete component.
* element-ui version: 1.1.6
One can specify icon and clicked handler to Autocomplete.
Currently, Autocomplete doesn't support that.
Check out the official docs: [http://element.eleme.io/#/en-US/component/input#autocomplete](http://element.eleme.io/#/en-US/component/input#autocomplete).

Autocomplete: add 'icon' and 'on-icon-click' attributes

---

packages/date-picker/src/picker.vue

#Please makes sure these boxes are checked before submitting your PR, thank you!
* bug: 主分支在 picker 内部 el-input 中没有阻止其本身 blur 事件（已修复）。
* blur触发时机: 主分支在 el-input 组件 blur 且 浮动层存在时就会触发 picker 的 blur （用户尚未点击浮动层“确认”按钮），这里的 blur 应该在浮动层关闭时触发（已修改）。

picker: fix time and bug for value validate

---

examples/docs/zh-CN/input.md
packages/carousel/src/main.vue
test/unit/specs/carousel.spec.js

Carousel: responsive to item change

---

packages/select/src/select.vue

select:fixed #2890 placeholder recover after options clear

select:fixed #2890 placeholder recover after options clear

---

packages/date-picker/src/basic/time-spinner.vue
packages/date-picker/src/panel/time-range.vue
packages/date-picker/src/picker.vue
packages/date-picker/src/util/index.js
packages/theme-default/src/date-picker/time-picker.css

fixed #2071 change the time-picker style and scroll compute 
Instand the mousewheel event to scroll.
Cause the mousewheel event trigger is on `mousewheel` not `after mousewheel`.
> `index.js` 
```js
const format = 'HH:mm:ss';
date = dateUtil.parse(dateUtil.format(date, format), format);
```
In this way. the date will lost year-month-day info.  like [2016-9-10 8:40:00] after parse. That change to  [currentYear-currentMonth-currentDay 8:40:00],  that well affect the logic behind. So we need to save the Y M D info.
> `time-range.vue`
The `MIN_TIME` default value is `currentYear-currentMonth-currentDay 00:00:00`. When we got a default value like `[new Date(2016, 9, 10, 8, 40), new Date(2016, 9, 10, 9, 40)]`. The MIN_TIME great than we default, that's not ture. We have to change the MIN_TIME …

TimePicker: fixed #2071 change the time-picker style and fixed some bug has not issue yet

---

examples/docs/en-US/tree.md
examples/docs/zh-CN/tree.md
packages/tree/src/model/tree-store.js
test/unit/specs/tree.spec.js

1. Tree: fix setCheckedKeys() not work on node that has childNodes (#2967)
2. Docs(Tree): fix `leafOnly` default value from `true`  to `false`
3. Test(tree.spec): add some test cases for tree methods

Tree: fix setCheckedKeys() not work on node that has childNodes (#2967)

---

examples/docs/en-US/carousel.md

Carousel's default trigger is actually "hover", not "—". Updated accepted values in case anyone gets confused like I did when the documentation didn't match the actual state of the carousel component.

Carousel: Update docs accuracy

---

packages/loading/src/directive.js
packages/loading/src/loading.vue

Get value from `element-loading-text` attribute on directive update hook, then we can update loading text dynamically.
Fix issue #2272.

Loading: keep loading text sync with element-loading-text attribute

---

examples/components/side-nav.vue

1. 修复文档侧边导航文字重叠的问题, 在宽度(850px-1000px)时出现

fix doc side-nav text-overlapping

---

examples/docs/en-US/slider.md
packages/slider/src/button.vue
packages/slider/src/main.vue
test/unit/specs/slider.spec.js

Related to #3397. Adding a simple `show-tooltip` prop to slider, so its possible to hide the tooltip when necessary. 
Also, already added to slider.md doc example, and test spec.

Slider: add show-tooltip prop

---

src/utils/clickoutside.js
test/unit/specs/autocomplete.spec.js
test/unit/specs/input-number.spec.js
test/unit/specs/util.clickoutside.spec.js
test/unit/util.js

When eg. having to choose a color at the edge of the Colorpicker component, it is easy to let your mouse get out of the components box. This will make the Colorpicker disappear which can be frustrating for the user.
I've added a mousedown event in the Clickoutside directive to check whether the mouse' starting point is inside the "popperElm" and prevent the bindings method to be called if it is.
This might add some unwanted results in other components using the clickoutside but shouldn't really be an issue. 
If it is though, I propose adding a modifier to the directive to signal that drag clicking shouldn't call the bindings method. `<element v-clickoutside.allowdrag="hide">`
Note: The test utility method 'triggerClick's  description is translated with Google Translate. So you might want …

Clickoutside: prevent closing on drag click

---

packages/theme-default/src/form.css

use `text-align: left` to display line-wrapped labels properly
form的label-position为"top"时，让label文字靠左对齐。
label文字过长，发生换行时，对齐方式与预期的不一致

theme-default: fix form-item label-top style

---

packages/slider/src/main.vue

Fixing #3473. When `step` was updated on parent component, Slider didn't update the precision, leading to some errors.

Slider: fix step not updating precision

---

build/bin/new.js

Initially it was `en-us`, but the folder is `en-US` .
When creating a new component, the build doesn't work because it hopes a file in the `en-US` folder.

Fix filename of md file for en-US version

---

packages/theme-default/src/table.css

When hovering over striped columns in a table the hover effect is not applied. 
This is because the `.el-table--striped .el-table__body tr:nth-child(2n) td` rule is overriding it.
Adding .el-table__body to the hover rules gives it enough points to apply it.

Table: fixed no hover on striped tables

---

examples/docs/en-US/date-picker.md
examples/docs/zh-CN/date-picker.md
packages/date-picker/src/panel/date-range.vue

DatePicker: add onPick option, close #2921

---

packages/select/src/option.vue

Select component with remote search clears what you typed when the value for each el-option is an object [#3728](https://github.com/ElemeFE/element/issues/3728)

Option: Fix #3728 bug

---

examples/docs/en-US/checkbox.md
examples/docs/zh-CN/checkbox.md
packages/checkbox/src/checkbox-group.vue
packages/checkbox/src/checkbox.vue
test/unit/specs/checkbox.spec.js

Related to #3602 
By adding two props, `minimum` and `maximum` to `checkbox-group` component,
We can now define a range of checkbox to be checked.
I've added a use case in spec.
Please tell me if this PR seems ok for you, or if I have to make some changes.
Hope it will help !

Checkbox group min max

---

packages/theme-default/src/table.css

当table组件同时设置border和stripe属性时，linux系统FF浏览器border显示不全.
解决办法是 修改td的背景裁剪规则。

当table组件同时设置border和stripe属性时，linux系统FF浏览器border显示不全

---

packages/table/src/table-body.js

TableBody uses el-tooltip but does not import the component.

TableBody: Tooltip used but not imported.

---

packages/table/src/table-store.js

filter-change的参数“ filters”返回类型应该为“Object”
https://github.com/ElemeFE/element/issues/3800 fixed

Table: fixed table events:filter-change (#3800)

---

examples/docs/en-US/tooltip.md
examples/docs/zh-CN/tooltip.md

- tooltip内部的form元素为disabled时，只有火狐会触发mouseenter事件（ https://developer.mozilla.org/en-US/docs/Web/Events/mouseenter ）；
- 而el-button最外层的标签就是button，所以会有这个问题。el-input最外层不是input所以没问题；
- 这么改也不知道会不会触发其他问题，或者不改代码在文档处加个提示？
参考#3894

Tooltip: add tips to docs, fixed #3894

---

packages/date-picker/package.json

The repository url for [the npm package `element-datepicker`](https://www.npmjs.com/package/element-datepicker) points to a non-existing page. Missing `-` between `date` and `picker`. Small fix.

DatePicker: Fix repository url

---

examples/docs/en-US/dialog.md

`<el-button>`s for the Dialog component examples in the [documentation ](http://element.eleme.io/#/en-US/component/dialog#customizations)had repeated `text` attributes.

Dialog: Fix documentation errors

---

packages/tabs/src/tab-nav.vue

最新的dev分支已经在 remove tab 时处理了显示逻辑， #3811 
然而还是做了两个微小的工作
- 组件resize时更新状态
- 在`currentOffset === 0`也隐藏箭头，因为用户有可能在有箭头时按左箭头使得`currentOffset === 0`
参考 #3890

Tabs: update on resize, fixed (#3890)

---

packages/upload/src/upload.vue

Without the name or id property the form field cannot be submitted as a regular non-xhr ajax request. I've opted for adding just the name attribute.
The only issue I see with this is that the `handleChange` event will not be called again if a user selects the same file (since path / name is unchanged).

Ensure inner el-upload uses name attribute

---

packages/table/src/table-body.js
packages/tooltip/src/main.js

- 修复 Tooltip 组件现有的问题：在文档示例上将鼠标从 Tooltip 快速移动回 button 上，Tooltip 会消失。
- Tooltip 组件中 `togglePreventClose` 方法存在的意义为 `handleClosePopper` 是异步的，而在 Table 组件中 `handleShowPopper` 是异步的，因此势必要添加 `togglePreventShow` 方法，但这样一来代码会很乱，因此用 `setExpectedState` 来设置期望的状态。
- 除了 Table 组件，Slide 组件也用到了 Tooltip， 但是没有用到 `handleShowPopper` 和 `handleClosePopper` 方法，因此应该不会有影响。
参考 #4044

Table: manage tooltip state better, fixed #4044

---

packages/date-picker/src/panel/date.vue

fix https://github.com/ElemeFE/element/issues/2516 by not set the date model.

DatePicker: fix date not disabled when type=datetime and input by text

---

packages/date-picker/src/basic/time-spinner.vue

when scroll event was ended, adjust the position of number.
see #4323

TimePicker: adjust number position, fixed #4323

---

examples/docs/en-US/i18n.md
examples/docs/zh-CN/i18n.md
src/locale/index.js

i18n: update doc about vue-i18n@6.x

---

packages/date-picker/src/panel/date.vue
packages/date-picker/src/panel/time.vue

[Impovement]
Currently, user has to choose seconds even "format" prop of DateTimePicker doesn't include "ss". It is strange that when user click confirm button, seconds doesn't show on the input.
This PR intends to hide the seconds column in the time spinner by passing timeFormat to timePicker.
[jsfiddle](https://jsfiddle.net/wgmnpqwc/)

DatePicker: When "format" prop of DateTimePicker doesn't include "ss" for seconds, user doesn't need to choose seconds

---

packages/carousel/src/item.vue
packages/carousel/src/main.vue
packages/theme-default/src/carousel.css

Adds an optional label to the indicator buttons on the carousel. Can be used only if required like so:
```
<n-carousel-item label="Slide 1">
<h3>My Slide</h3>
</n-carousel-item>
```

[Carousel] Add an optional label to indicator buttons

---

examples/docs/en-US/i18n.md

i18n returns renderSlot (vm._t) function instead i18n.t
https://kazupon.github.io/vue-i18n/en/api.html

Update vue-i18n@6x support

---

test/unit/specs/table.spec.js

Table: add tests for summary row

---

FAQ.md
examples/docs/en-US/dialog.md
examples/docs/en-US/pagination.md
examples/docs/zh-CN/dialog.md
examples/docs/zh-CN/pagination.md
packages/dialog/src/component.vue
packages/message-box/src/main.js
packages/message-box/src/main.vue
packages/pagination/src/pagination.js
packages/transfer/src/main.vue
packages/transfer/src/transfer-panel.vue
src/utils/popup/index.js
test/unit/specs/message-box.spec.js

add .sync support for Dialog and Pagination

---

packages/date-picker/src/picker.vue
test/unit/specs/date-picker.spec.js

* 修复 DatePicker 的 default-value
* 增加 default-value 的测试脚本
导致default-value失效的commit ：https://github.com/ElemeFE/element/commit/4243920a176aa3e8780a5863c4a4cc00fcb91e50?diff=unified#diff-64b9be7ffdb5a45b56e51e091d251ce6R434
`this.panel.defaultValue` 未传递 `this.defaultValue`（DatePicker组件的`default-value`属性）
https://jsfiddle.net/wacky6/e07oh2om/

DatePicker: fix, add test for default-value

---

packages/color-picker/src/main.vue

- when prop `value` change to a false value, `this.showPanelColor` should be `false`
see #4662

ColorPicker: empty value by v-model, fix #4662

---

packages/table/src/table-column.js
packages/theme-default/src/table.css

对设置了 `show-overflow-tooltip` 属性的元素强制设置宽度
解决 table 组件 `show-overflow-tooltip` 在 Safari 上无效的问题
#2198,#3128

table: setwidth for each td>div.cell.el-tooltip element(#2198,#3128)

---

examples/docs/en-US/dropdown.md
examples/docs/zh-CN/dropdown.md
packages/dropdown/src/dropdown.vue

新增触发下拉框显示隐藏时， 发送visible事件，传递当前下拉框显示状态。
在一些特定的项目中频繁需要对Dropdown的触发按钮做显示和隐藏状态下的区别样式，组件对外发送当前下拉框显示隐藏状态，可以解决此类需求。

Dropdown： 新增触发下拉框显示隐藏时， 发送visible事件，传递当前下拉框显示状态

---

packages/date-picker/src/picker.vue
test/unit/specs/date-picker.spec.js

重开 PR https://github.com/ElemeFE/element/pull/4681
刚才 push dev 把 commit 搞乱了。
修复Issue：https://github.com/ElemeFE/element/issues/4624
pick事件中，如果pick的值与当前值相等，不发射input
修改后的行为参照了原生`<Select>`，仅在选定的值发生变化时才发射input事件：https://jsfiddle.net/wacky6/a7ffgjdt/
增加了以上行为相关的测试代码
https://jsfiddle.net/wacky6/wya53tm9/2/
`type=range`时，它的数据为数组，发射 input 事件中的新建的数组与原数组必然不全等（`===`），触发了watch。
但`type=range`时，它的数据为Date对象，但不会发生Issue所述现象，尚未进一步挖掘原因。
推测 Vue 的 Watcher 有 Date 相关逻辑？

DatePicker: fix, add test for unwanted 'input' event emission

---

packages/dialog/src/component.vue

For using `done(false)` as well as `vue-router.beforeEach` similarly function `next(false)`.
There are cases when it is necessary.

dialog function parameter => done(false)

---

packages/table/src/table-body.js

Table: fix #4692 table[highlight-current-row] with column[type=expand] will highlight wrong row

---

packages/autocomplete/src/autocomplete.vue
test/unit/specs/autocomplete.spec.js

- when select text with mouse, if event `mouseup` was triggered outside the component, `this.isFocus` would become `false`. And `this.suggestionVisible` would also become `false`
- maybe `clickoutside` was duplicated with `blur`? if not, close this.
see #4985

Select: remove clickoutside, fix #4985

---

packages/select/src/select.vue
test/unit/specs/select.spec.js

fix https://github.com/ElemeFE/element/issues/5063
make default-first-option work with async filter/remote method
test is updated to reflect this change

Select: fix default-first-option with async filter/remote

---

packages/switch/src/component.vue
packages/theme-default/src/switch.css
test/unit/specs/switch.spec.js

简化 Switch 的实现，消除不必要的属性，使展示状态仅和 value 有关。
测试代码已包含。
修复Issue：https://github.com/ElemeFE/element/issues/4824
开关操作发Ajax请求到后端，这个请求可能不能满足，此时Switch的值不变（外观不变）
修正前：http://jsfiddle.net/pj9quogd/
修正后：http://jsfiddle.net/pj9quogd/2/
怎么测试：点击Switch
期望行为：Switch绑定的值为true，点击Switch后：外观、value、input的checked属性依旧为true

Switch: 简化内部实现

---

packages/dialog/src/component.vue
packages/message-box/src/main.vue
packages/theme-default/src/dialog.css
packages/theme-default/src/message-box.css
src/utils/popup/popup-manager.js

**What's the problem**
[Dialog](http://element.eleme.io/#/en-US/component/dialog) and [MessageBox](http://element.eleme.io/#/en-US/component/message-box) is unfriendly for accessibility
1. Popup header `close` icon can't be focused.
2. When the popup is shown, with key `tab` pressed, the focus jump outside the popup, and move around the total page.
**What did I do**
1. Surround the `close` icon with button, rewrite the style.
2. Add document listener for `focusin` event to prevent focus jump outside the popup with `tab` key.

Popup(Dialog|MessageBox): friendly for accessibility

---

examples/docs/en-US/input.md
examples/docs/zh-CN/input.md
packages/autocomplete/src/autocomplete-suggestions.vue
packages/autocomplete/src/autocomplete.vue
test/unit/specs/autocomplete.spec.js

[Autocomplete][Feature]add props support

---

packages/theme-default/src/date-picker/picker-panel.css

This fixes overflow issue on date time picker shortcuts panel.

DatePicker: fix date picker shortcut panel overflow

---

packages/dialog/src/component.vue
src/utils/popup/popup-manager.js

#5322
原因是 #4786 的改动造成在 Dialog 打开时，非 Dialog 子元素的元素无法获取焦点。造成问题的代码是为了
> When the popup is shown, with key tab pressed, the focus jump outside the popup, and move around the total page.
现在撤回这部分代码。

Dialog: fix nested popover cannot gain focus

---

examples/docs/en-US/message.md
examples/docs/zh-CN/message.md
packages/message/src/main.js
packages/message/src/main.vue

Regarding issue #5174
Adding VNode support to the message component. Will allow for better markup and links (such as undo links after an action successfully completed).

Message: add 'message' support for VNode

---

packages/table/src/table-body.js
packages/table/src/table-header.js

问题：IE9下点击表格头部无反应，报错‘找不到contains方法’，定位到是classList不支持缘故
解决：查看以往Issues #315，你们已有解决方案，所以照搬处理。

Table:fix table support for IE9

---

examples/docs/en-US/i18n.md
examples/docs/zh-CN/i18n.md

在使用vue-i18n@6.x 时候，pagination total 的i18n使用的是 this.t(key,value)[代码处](https://github.com/ElemeFE/element/blob/dev/packages/pagination/src/pagination.js#L225)
所以如果只用
```
Vue.use(Element, {
i18n: key => i18n.vm._t(key)
})
```
会丢失pagination total 的值。

update element use vue-i18n@6.x and other i18n docs

---

packages/theme-default/src/cascader.css

Cascader label isn't aligned in its parent element.
* [x ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [x ] Add some descriptions and refer relative issues for you PR.

Fix line height of cascader label

---

packages/autocomplete/src/autocomplete-suggestions.vue
packages/autocomplete/src/autocomplete.vue
src/utils/clickoutside.js
test/unit/specs/autocomplete.spec.js

This reverts commit 876cb88ae6de27d11f148ba1c940b58748a2739b.
1.  fix #5146
2. fix #4985 
3. fix clickoutside callback is invoked when not a click event trigger

[Autocomplete][BUG]fix blur bug(#5146)

---

.gitignore
examples/docs/en-US/select.md
examples/docs/zh-CN/select.md
packages/select/src/option.vue
packages/select/src/select.vue
packages/table/src/table-column.js
packages/table/src/util.js
src/utils/util.js
test/unit/specs/select.spec.js

Select: use primitive key on tags

---

packages/date-picker/src/basic/month-table.vue
packages/date-picker/src/basic/year-table.vue

未改之前，设置禁用日期后，年和月的禁用状态不准。因为只选取了年和月的某一天进行判断。修改为年和月的每一天都进行判断。未改前的问题示例 https://jsfiddle.net/liyangworld/mpbyw3cg/5/

date-picker : fix disabledDate bug 。

---

src/locale/lang/nl.js

Removed the suffix "Jaar" from DatePicker. Since this is unnecessary. 
Fixes the same issue as described in #5825 but for the Dutch language.

Removed Dutch "Jaar" suffix from DatePicker

---

packages/popover/src/main.vue

Fix a popover bug:
If cursor leave the trigger element earlier than `open-delay`, the popover will still show up, which is not expected.

Popover: fix: delayed popover appears after mouse left

---

packages/form/src/form.vue

When `<el-form>` missing `model`, validate will `return false`, then throw a warning to facilitate the developer troubleshooting

Form: Add log

---

packages/theme-default/src/table.css

Fix: The background color of highlighted hover-row or hover-row of table with fixed column do not change when hovering.

Table: fix hover-row bgcolor of table with fixed column

---

packages/select/src/select.vue

handleOptionSelect() use $nextTick() to invoke scrollToOption(), but component could be destroyed after select(e.g. routed to another page), "$refs.popper" would be undefined.

Select: check popper exist before invoke scrollIntoView

---

packages/radio/src/radio-button.vue
packages/radio/src/radio-group.vue
packages/radio/src/radio.vue
packages/theme-default/src/radio-button.css
packages/theme-default/src/radio.css

add accessibility for RadioGroup:
1、 add some aria role and attrs for screen reader
2、optimize some Keyboard Interaction：
-  The Tab key moves focus between radio button groups and other widgets.
-  Pressing the Shift+Tab keys exits the group and moves focus to the previous form control.
-  When a radio group receives focus:
If a radio button is checked, focus is set on the checked button.
If none of the radio buttons are checked, focus is set on the first radio button in the group.
-  Space: checks the focused radio button if it is not already checked.
-  Right Arrow and Down Arrow: 
move focus to the next radio button in the group, uncheck the previously focused button, and check 
the newly focused button. If focus is on the last button, focus moves to the first button.
-  Left Arrow …

RadioGroup:add accessibility

---

FAQ.md

FAQ DOC: fix typo `scoped`=>`scope` in 'How do I add buttons in each row of Table to operate data of that row?'

FAQ: fix attribute scope typo

---

packages/date-picker/src/basic/month-table.vue

#6208 
Chrome 的bug，某些日期`setMonth()`会改变时区，但`hour`没变。
测试版本： 60.0.3112.90
```js
var date = new Date('1988-04-01 00:00:00') // Fri Apr 01 1988 00:00:00 GMT+0800 (CST)
date.setMonth(4) // Sun May 01 1988 00:00:00 GMT+0900 (CDT)
```

DatePicker: fix month viewer disable date bug

---

packages/alert/src/main.vue

[demo](https://jsfiddle.net/wt52j5jp/)

Alert: if <el-alert> uses slot, the icon should use 'isBigIcon' class

---

packages/input/src/calcTextareaHeight.js

- Input: fix params type  
Node 没有 `value ` 属性，不存在 `targetNode.value`。命名有错误。
正确的类型应该是 `HTMLTextAreaElement`， 属于 `HTMLElement` 的子类，在`HTMLElementTagNameMap` 中有声明。
[参考这行代码](https://github.com/eleme/element-angular/blob/master/src/input/help.ts#L43)

Input: fix params type

---

packages/date-picker/src/basic/month-table.vue

DatePicker:fix month status check Bug
There are basic rules:
1.For **every day of every month** ,if the 'disabledDate' function's **result is false**.Means that the Month can't be disabled.
2.For **any day of every month** ,if the 'disabledDate' function's **result is false**.Means that the Month can't be disabled.
Examples:
Like '2017-08-30'.The Month is 08
For '2017-08-29' , the result of 'disabledDate' function is true
For '2017-08-28' , the result of 'disabledDate' function is false
At last,the Month 08 should be not disabled.
3.For **every day of every month** ,if the 'disabledDate' function's **result is true**.Means that the Month must be disabled.
#6764

DatePicker:fix month status check Bug

---

packages/pagination/src/pagination.js
test/unit/specs/pagination.spec.js

Jumper value should reassign when internalCurrentPage greater than internalPageCount.

Pagination: fix Jumper value reassign problem

---

packages/rate/src/main.vue
test/unit/specs/rate.spec.js

-----
What I wanted to allow user to rate some items and also see other users's average rating. Until user rates the item herself that average rating should be "muted" (dimmed colors), so I wanted to pass `colors` prop. However, I then noticed that changing that `colors` array at parent component have not impact of the colors at rate component. Looking at the code I can see that `colorMap` is prepared once at the `created` hook. This makes `colors` prop non-reactive which is odd.
I've made `colorMap` a computed value that should be based on `colors` prop.

Fixed reactivity of colors prop for rate component

---

packages/date-picker/src/panel/date-range.vue
test/unit/specs/date-picker.spec.js

date-range 模式下支持 default-value 选项，控制面板默认显示的日期。
实现与 date 模式下相同。
DEMO: https://jsfiddle.net/u2opvyxa/

DatePicker: support default-value for date-range

---

packages/date-picker/src/basic/month-table.vue
packages/date-picker/src/basic/year-table.vue

DatePicker: fix disabled dates for the west hemisphere

---

packages/autocomplete/src/autocomplete-suggestions.vue
packages/select/src/select-dropdown.vue

fix [issue 7227](https://github.com/ElemeFE/element/issues/7227)  use default value
```javascript
// default options
var DEFAULTS = {
// placement of the popper
placement: 'bottom',
gpuAcceleration: true,
// shift popper from its origin by the given amount of pixels (can be negative)
offset: 0,
// the element which will act as boundary of the popper
boundariesElement: 'viewport',
// amount of pixel used to define a minimum distance between the boundaries and the popper
boundariesPadding: 5,
// popper will try to prevent overflow following this order,
// by default, then, it could overflow on the left and on top of the boundariesElement
preventOverflowOrder: ['left', 'right', 'top', 'bottom'],
// the behavior …
```

Select Autocomplete: change dropdown popper default options (#7227)

---

packages/select/src/select.vue
test/unit/specs/form.spec.js

https://github.com/ElemeFE/element/issues/6011
本应该和 https://github.com/ElemeFE/element/pull/5360 在一起。
修正后，仅在用户修改时会触发校验 -> 通过程序修改时不会触发。
** 感觉 FormItem 应该新增一个清空验证状态的方法。 **

select: fix el.form.change emission

---

examples/docs/en-US/date-picker.md
examples/docs/en-US/datetime-picker.md
examples/docs/en-US/time-picker.md
examples/docs/zh-CN/date-picker.md
examples/docs/zh-CN/datetime-picker.md
examples/docs/zh-CN/time-picker.md
packages/date-picker/src/basic/date-table.vue
packages/date-picker/src/basic/month-table.vue
packages/date-picker/src/basic/time-spinner.vue
packages/date-picker/src/basic/year-table.vue
packages/date-picker/src/panel/date-range.vue
packages/date-picker/src/panel/date.vue
packages/date-picker/src/panel/time-range.vue
packages/date-picker/src/panel/time-select.vue
packages/date-picker/src/panel/time.vue
packages/date-picker/src/picker.vue
packages/date-picker/src/picker/date-picker.js
packages/date-picker/src/picker/time-picker.js
packages/date-picker/src/picker/time-select.js
packages/date-picker/src/util/index.js
test/unit/specs/date-picker.spec.js
test/unit/specs/form.spec.js
test/unit/specs/time-picker.spec.js
test/unit/specs/time-select.spec.js

大规模重构 *-Picker
* 回退 https://github.com/ElemeFE/element/pull/6214 ，移除 user flag
* Panel 接受 date 和 value 属性，date 控制 panel 显示的状态，value 为 picker 绑定值
* date-panel / {date, month, year}-table ：year/month/week 改成 date 的 computed
* time-panel, time-spinner: hours, minutes, seconds 改成 date 的 computed
* time-spinner：refs、属性名统一
* 参考 Immutable 思路，修改 Date 时返回新 Date，移除 resetDate
* {next, prev} {month, year} 实现
* 键盘操作重构，区分 picker (Enter, Tab) 和 panel (Arrows) 操作
* 修正 https://github.com/ElemeFE/element/issues/7079
* change 事件发射行为：https://github.com/ElemeFE/element/issues/6011
* 新增、完善测试代码
* 具备 reactivity 特性，panel 创建后可修改
* date-range 新增支持数组形式的 default-value（见远期改进）
* {date, month, year}-table 高亮改为三种 classname：default, current, today 分别对应 default-value，控件 value，今天（今年、当前月） 。**CSS 还没加，呼叫视觉设计师**。 怀念 1.0 today …

[Carbon] *-Picker 重构

---

packages/autocomplete/src/autocomplete.vue

修复 autocomplete 组件 IE11 下使用搜狗输入法，无法输入中文的问题

fix #5813  component could not use Sogou input method in Chinese IE 11

---

packages/color-picker/src/components/picker-dropdown.vue

Added explicit ElButton reference as `el-button` is used in the template. Fixes error when ColorPicker is used on-demand.

ColorPicker: Fixed `Unknown custom element: <el-button>` error

---

packages/date-picker/src/basic/date-table.vue
packages/date-picker/src/basic/month-table.vue
packages/date-picker/src/basic/year-table.vue
packages/date-picker/src/util/index.js
test/unit/specs/date-picker.spec.js

修复 date-table 夏令时/冬令时切换月份时高亮显示不正确
测试已包含：
* 运行时指定时区：`TZ=Australia/Sydney yarn test`
* 用 2016 年夏令时测试

[Carbon] DatePicker Daylight Saving Time

---

packages/theme-default/src/date-picker/date-picker.css
packages/theme-default/src/date-picker/picker-panel.css

fix "**last item** been **overlapped by DateTimePicker's footerbar** bug" when sidebar items are too more。Even overflow can not solve this problem, it is not the same thing. 
the details you can see https://dulinrain.github.io/elementui/ElementUI%E4%B9%8B%E6%97%B6%E9%97%B4%E6%8F%92%E4%BB%B6Bug.html

fix "last item been overlapped by DateTimePicker's footerbar bug" when sidebar items are too more。

---

examples/docs/en-US/dropdown.md
packages/dropdown/src/dropdown.vue

Dropdown: Allow change show/hide timeout by props

---

types/carousel.d.ts
types/component.d.ts
types/index.d.ts
types/loading.d.ts
types/message-box.d.ts
types/message.d.ts
types/notification.d.ts
types/tree.d.ts

Make the definitions compliant with the option `--noImplicitAny` of [typescript's compiler](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

Remove implicit any in type definition

---

packages/theme-chalk/src/common/var.scss

This allows to override transitions parameters (for example if you want them slower or faster) the same way you would tweak the primary/accent colors.
In my case, I'd need to speed up the animations a little bit, but I can't do that since the values for the $--xx-transition variables are erased during the import.
* [ X ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [ X ] Make sure you are merging your commits to `dev` branch.
* [ X ] Add some descriptions and refer relative issues for you PR.

Var: Allow overriding transitions variables

---

examples/docs/en-US/table.md
examples/docs/zh-CN/table.md
packages/table/README.md
packages/table/src/table-column.js
packages/table/src/table-store.js
packages/table/src/util.js
test/unit/specs/table.spec.js

* Table 支持按 `sort-by` 排序，如对 `status_title` 列排序时，按照 `status_code` 排序：
```html
<el-table-column prop="status_title" sort-by="status_code"></el-table-column>
```
* 以前使用 `Array.prototype.sort` 没有考虑排序的[稳定性](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability)，修复该问题
* 以前的排序，会对同一个 item 多次调用 `getValueByPath` 方法，现在只会对每个 item 调用 `getValueByPath` 一次

Table: support sort-by

---

packages/date-picker/src/picker.vue

…ke 2014/12/29
我发现了一个bug并且尝试修复。我在使用DatePicker选择周的时候，发现：如果周在跨年的状态下，会出现年份错误。
例如: 当我查看2014年12月29日的周数的时候，得到的是2014年1月。
所以我查看了源码发现没有更新年份，因此我尝试解决。

DatePicker: fix bug for wrong year number when week cross the year

---

examples/docs/en-US/upload.md
examples/docs/zh-CN/upload.md
packages/theme-chalk/src/collapse.scss
packages/theme-chalk/src/upload.scss

1、修复collapse点击时闪现 outline的bug
2、修改upload组件的 upload框框点击时outline的bug，新增:focus样式(同:hover样式一致)，因为浏览器原生的input=file组件在上传文件完成后，焦点会保留在input上，因此upload框框在上传文件后，依然会保持聚焦行为，和浏览器原生行为保持一致；

[bugfix] remove outline for collapse & upload

---

types/notification.d.ts

According to [notification components docs](http://element.eleme.io/#/en-US/component/notification#basic-usage), all needed properties of notification options is only `title` and `message`. But now, all properties are defined as required in type difinitions. 
So I fixed the other properties to be optional.

Notification: fix unnecessary required type definitions

---

.gitignore
packages/menu/src/menu-item.vue
packages/menu/src/menu.vue

This PR fixes #7656. It adds `String` as an allowed prop type for the `route` attribute of the `MenuItem` component.

[MenuItem]: Fix #7656

---

src/locale/lang/zh-CN.js
src/locale/lang/zh-TW.js

这几项中英文或数字之间都有空格：
1. `noCheckedFormat: '共 {total} 项'` 
2. `titles: ['列表 1', '列表 2']`
3. `total: '共 {total} 条'`
唯独它「`deleteTip: '按delete键可删除'`」是没有空格的。

Add spaces between Chinese, English and numbers.

---

packages/breadcrumb/src/breadcrumb-item.vue
packages/breadcrumb/src/breadcrumb.vue

* [x ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [x ] Add some descriptions and refer relative issues for you PR.
if l want  add some animation to breadcrumb ,like
```
<el-breadcrumb separator="/">
<transition-group  name="slide">
<el-breadcrumb-item key='1' :to="{ path: '/' }">首页</el-breadcrumb-item>
<el-breadcrumb-item key='2'>活动管理</el-breadcrumb-item>
<el-breadcrumb-item key='3'>活动列表</el-breadcrumb-item>
<el-breadcrumb-item key='4'>活动详情</el-breadcrumb-item> …
```

Breadcrumb: use provide/inject instead of this.$parent

---

packages/cascader/src/main.vue
packages/cascader/src/menu.vue

When cursor moves between menus, the submenus switch immediately, it is hard to select the desired item.
A better way is to include a bit of a delay when activating submenus, but it will make the menu switch slowly.
The perfect UX is to keep menus switch fast, only hold it when we want to select the submenus. 
Here is a solution:
Idea from OSX. The red area prevent menus switch for a short time.

Cascader: optimize hover to expand experience

---

packages/menu/src/menu.vue

Fix color testing regex to allow color values contain "0".

Menu: fix invalid hover color of nav menu when background color contains 0

---

src/utils/clickoutside.js

found while investigating https://github.com/ElemeFE/element/issues/7465
clickoutside directive didn't clean up properties it added to elements when they were bound. 
this added unnecessary function references to element's own methods that prevented garbage collection.

clickoutside: fix memory leak

---

packages/table/src/table-body.js

Table: fix table column show-overflow-tooltip bug, low version Firefox without innerText, add textContent

Table: fix table column show-overflow-tooltip bug

---

packages/dialog/src/component.vue

The event emit is not necessary according to my understanding.

remove unnecessary event

---

examples/docs/en-US/input.md
examples/docs/zh-CN/input.md
packages/autocomplete/src/autocomplete.vue

【需求】
```html
<el-autocomplete suffix-icon="el-icon-search"></el-autocomplete>
```
【当前情况】
只允许使用 $slot 进行设置 autocomplete 组件的 `suffix-icon` 或者 `prefix-icon`

Input: autocomplete support suffixIcon & prefixIcon

---

packages/message-box/src/main.js

Fixed issue [#5667](https://github.com/ElemeFE/element/issues/5667) and [#7672](https://github.com/ElemeFE/element/issues/7672). 
---

MessageBox : fix unclosed overlay after called close()

---

examples/docs/en-US/input.md
packages/input/src/input.vue
packages/theme-chalk/src/common/var.scss
packages/theme-chalk/src/input.scss

Adds `clearable` prop to el-input. When set to `true`, if the input is not empty and it's focused or hovered, it shows a clear icon, which, when clicked, clears the input.
Resolves #8469.

Add clearable to el-input

---

examples/docs/en-US/message-box.md
examples/docs/zh-CN/message-box.md

Add an attribute 'showClose' to explain whether to show 'close' button on the right top.
MessageBox: 文档中添加一个属性：showClose。 用来解释是否显示 MessageBox 右上角的关闭按钮。改属性，已经在源码中声明。

MessageBox: Add attribute 'showClose' to doc

---

examples/docs/en-US/pagination.md
examples/docs/zh-CN/pagination.md
packages/pagination/src/pagination.js
packages/theme-chalk/src/pagination.scss

Pagination: add background prop

---

packages/date-picker/src/basic/time-spinner.vue
packages/date-picker/src/panel/time-range.vue
packages/date-picker/src/panel/time.vue
test/unit/specs/time-picker.spec.js

date-picker: add am/pm mode in time selector

---

packages/select/src/option.vue

Component: `select ` multiple
Scene: Dynamic form item from server
If v-model default value is null, it report `Cannot read property 'indexOf' of undefined`.
https://github.com/ElemeFE/element/blob/f5aa24e41943dfc7505fd23b48fac9c8fdd060cf/packages/select/src/option.vue#L104
If no set default value, it report `Cannot read property 'length' of undefined`.
https://github.com/ElemeFE/element/blob/f5aa24e41943dfc7505fd23b48fac9c8fdd060cf/packages/select/src/option.vue#L77

limitReached：Improve robustness when it does not set a default value

---

packages/dropdown/src/dropdown.vue
test/unit/specs/dropdown.spec.js

* [x ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x ] Add some descriptions and refer relative issues for you PR.
Click to open dropdown ignored the `show-timeout` attribute.
Rewrote the click handler to use `open/close` methods instead of manipulating `visible` directly.
If possible, please release a new patch version with this fix as soon as possible. 
Thanks

Dropdown: Click open uses `show-timeout` attribute

---

packages/select/src/select.vue
packages/theme-chalk/src/select.scss

* [ √] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ √] Make sure you are merging your commits to `dev` branch.
* [ √] Add some descriptions and refer relative issues for you PR.
目前设置 collapse-tags 为 true 时只显示文字。与设置为false 的显示风格不统一。比较建议更好点的显示方式，以及更好的可操作性。

modify set collapse-tags just show text

---

packages/tabs/src/tab-bar.vue
packages/theme-chalk/src/tabs.scss

基础样式标签页（Tabs），top/bottom模式下，第一个标签页的padding-left被清零，然而右侧最后一个的padding-right并没有，如此，若整个选项卡居中或者靠右对齐，整体右侧将多出20px空白，导致不能严格对齐，如图：
由于此处牵涉底层js代码：
```
if (sizeName === 'width') {
tabSize -= index === 0 ? 20 : 40;
}
```
不能以css样式覆盖方式解决，因此，有必要从底层解决，谢谢。

Tabs: fix right padding of last tab item in top/bottom position

---

packages/table/src/table-column.js

example: https://github.com/ElemeFE/element/issues/8489
当 el-table-column 被再次封装成组件时，this.$parent 会出现使用有错误。
本次提交进行了对 parent 查找的优化，能够解决被再次封装成组件使用的乱序和 columnId 错误问题。

Table: fix table-column order disorder when made the assembly again

---

examples/docs/en-US/upload.md
examples/docs/zh-CN/upload.md
packages/upload/src/index.vue

upload: add before-remove function. It can support a function returns a boolean or Promise.
#8399 requests this feature.

upload: add before-remove function

---

packages/theme-chalk/src/common/var.scss
packages/theme-chalk/src/table.scss

$--table-header-background is defined but never used
`$--table-header-background` is defined but never used

Table:chalk theme add $--table-header-background

---

examples/pages/template/component.tpl

increase the 'z-index' of class 'page-component-up'
the scroll to top component was coverted by the table element,
thus the z-index of this component should be more than 4

docs:  increase page-component-up z-index

---

examples/docs/en-US/collapse.md
examples/docs/es/collapse.md
examples/docs/zh-CN/collapse.md

collapse(折叠面板) 文档中 `@change` 事件处理函数`handleChange` 缺失,  现已补齐.
提前预祝元旦快乐,  happy new year~

update collapse doc

---

packages/theme-chalk/src/table.scss

按需引入 Table 时，`show-overflow-tooltip` 需要引入 Tooltip 的样式文件。

Table: add missing tooltip style when imported on demand

---

examples/docs/en-US/select.md
packages/select/src/select.vue
test/unit/specs/select.spec.js

If one sets both `collapse-tags` and `filtering` for select component, if it is not wide enough, tags + input take 2 lines while select has still same height. Please see the screenshot:
Basically select component should expand itself even if collapse tags are enabled as long as filtering is enabled too:
-----

Select filterable collapse tags

---

src/utils/popper.js

dropmenu下拉列表定位，在获取滚动父元素时，只用scrollTop是否有值来判断滚动父元素是html还是body，这样在上下无滚动、左右有滚动情况下，滚动父元素会一直是body，应该用scrollTop和scrollLef一起判断

popper.js: getScrollParent is defined by using scrollLeft or scrollTop

---

packages/loading/src/directive.js

There is situations, when flag loading fast change from _true_ to _false_ overlay of loading show.
It happens when this line runed(flag already false):
https://github.com/ElemeFE/element/blob/837354df3b24463457817a8c701b7327f6d82378/packages/loading/src/directive.js#L40
then run line:
https://github.com/ElemeFE/element/blob/837354df3b24463457817a8c701b7327f6d82378/packages/loading/src/directive.js#L68
and event _after-leave_ don't call.
I use flag instance.hiding for fix it.
Also there is leak memory in 
https://github.com/ElemeFE/element/blob/837354df3b24463457817a8c701b7327f6d82378/packages/loading/src/directive.js#L40
because _$on_ add listener many times. So use $once instead $on.

fix show loading, leak memory

---

examples/docs/en-US/tree.md
examples/docs/zh-CN/tree.md
types/upload.d.ts

[upload file object](https://github.com/ElemeFE/element/blob/dev/packages/upload/src/index.vue#L128-L142). file object should have an optional url property.
BTW, there is a  suggestion by the MDN that we should call revokeObjectURL to release the result of createObjectURL.
> Each time you call createObjectURL(), a new object URL is created, even if you've already created one for the same object. Each of these must be released by calling URL.revokeObjectURL() when you no longer need them. Browsers will release these automatically when the document is unloaded; however, for optimal performance and memory usage, if there are safe times when you can explicitly unload them, you should do so. …

Tree: update  doc and  upload typing

---

examples/docs/en-US/date-picker.md
examples/docs/en-US/datetime-picker.md
examples/docs/en-US/time-picker.md
packages/date-picker/src/picker.vue

Added the possibilitie to pass custom prefix and suffix icon class with same props as usual (prefix-icon and suffix-icon)

[DatePicker] Added the possibilitie to pass custom prefix and suffix icons

---

packages/popover/src/main.vue
packages/theme-chalk/src/popover.scss

Fix #9195 : use focusin & focusout instandof focus & blur.
Fix #9243 : add focus & blur for popover element.

fix popover trigger prop not work properly in some condition

---

examples/docs/en-US/date-picker.md
examples/docs/zh-CN/date-picker.md
packages/date-picker/src/panel/date-range.vue
packages/date-picker/src/picker.vue
test/unit/specs/date-picker.spec.js

DatePicker: add attribute defaultTime

---

packages/date-picker/src/panel/date-range.vue
test/unit/specs/date-picker.spec.js

Fix interaction issue introduced in https://github.com/ElemeFE/element/pull/9094#issuecomment-357947605

DatePicker: fix incorrect interaction on range change when defaultTime provided

---

packages/input-number/src/input-number.vue

support input-number undefined value

---

packages/menu/src/menu-item.vue

I did to don't bubbling event click when item of menu is disabled. Because use prop _disabled_ don't implemented.
Thanks

[el-menu-item] fix disabled

---

packages/table/src/table-column.js

Fix: #7326.
This is a break change, when checkbox that display in table column with type selection is clicked: 
1. Current version trigger row-click event twice before select event. [https://jsfiddle.net/breadadams/pj71jkyw/599/](https://jsfiddle.net/breadadams/pj71jkyw/599/)
2. This pr do not trigger row-click event before select event

make table column with type selection do not trigger row-click event

---

packages/date-picker/src/panel/date-range.vue

NeoKylin OS default browser is Firefox 37 and the Date function required two-digit month value.

DateTimePicker: fix invalid month value bug for Firefox 37

---

packages/date-picker/src/panel/date-range.vue
test/unit/specs/date-picker.spec.js

修复了：
unlink-panels 为 true，minDate 和 maxDate 在同年同月的情况下，左右时间面板相同的bug。

date-picker: bugfix

---

packages/table/src/table-body.js
packages/table/src/table-store.js

Fix Table with rowKey's expandRows collapse when data change

---

examples/docs/en-US/date-picker.md
examples/docs/en-US/datetime-picker.md
examples/docs/en-US/time-picker.md
examples/docs/zh-CN/date-picker.md
examples/docs/zh-CN/datetime-picker.md
examples/docs/zh-CN/time-picker.md
packages/date-picker/src/picker.vue
test/unit/specs/date-picker.spec.js

https://github.com/ElemeFE/element/issues/9281
DEMO: https://jsfiddle.net/pkyefx4b/
先别合，TODOS:
* 格式字串用什么？现在是timestamp
* 写文档
* 把日期格式单独拿出来做一个 section ？
* 大家一起来找bug （滑稽

date-picker: add timestamp format

---

packages/form/src/form.vue

In my use case, the rules provided to form change dynamically. The form validating itself every time is not welcome.
I would add this validateOnRuleChange boolean value, that can be changed to false to prevent this behavior.
Also the watcher didn't provide a callback to the validate() so the rejected promise escaped to console and was shown as error.

[Form]: added validateOnRuleChange

---

packages/table/src/table-column.js
packages/table/src/table-store.js

Table: add disabled state to multiple selection header checkbox

---

packages/table/src/layout-observer.js
packages/table/src/table-body.js
packages/table/src/table-column.js
packages/table/src/table-footer.js
packages/table/src/table-header.js
packages/table/src/table-layout.js
packages/table/src/table-store.js
packages/table/src/table.vue
packages/theme-chalk/src/table.scss

Improve Table performance after table inner width/height changes:
1. Manual update TableHeader、TableFooter、TableBody styles instead of in `render` function.
2. Remove some nonsense `doLayout`.
3. Show scrollbar only when current scrollX、scrollY is true.
Fixed: #7681
Fixed: #7948
Fixed: #6276
Fixed: #7997
Fixed: #7530
Fixed: #7897

Improve Table Performance

---

examples/docs/en-US/dropdown.md
examples/docs/es/dropdown.md
examples/docs/zh-CN/dropdown.md
packages/dropdown/src/dropdown.vue

Dropdown: remove transition delay when trigger is click

---

packages/theme-chalk/src/checkbox.scss

Fixed #9677
在 [issue #9677](https://github.com/ElemeFE/element/issues/9677)中，实际上不是table组件的bug，而是checkbox组件中，input设置left: -999px后，当label获得焦点的时候，焦点会到input上，而input实际上是left-999px的，所以滚动条会往左边移动。因此需要去除掉input的定位偏差，否则在父容器有滚动条的时候，每次点击，父容器的滚动条都会被移动。
[这里是重现bug的代码](https://jsfiddle.net/oo7wfequ/1/)

CheckBox: fix issue #9677

---

src/locale/lang/ku.js

Kurdish translation

---

src/utils/popper.js
src/utils/vue-popper.js

- When the route changed on click, the `doDestroy` method of vue-popper was returning right away without actually destroying the popper due to `showPopper` being true. `forceDestroy` parameter is added to handle this case. An alternative fix could be to set `showPopper` to `false` in `beforeDestroy` before calling `doDestroy`, but the parameter approach was chosen as it can be reused.
- After the above fix, the `destroy` method of popper.js was being successfully called, which in turn called `_removeEventListeners`. The `target` that this method was removing the `scroll` event listener from was not the same element to which the listener was added (this is due to `getScrollParent` not being able to find the correct element as some of the top level nodes had already been destroyed). This …

Popper: Fix memory leak on route change (#7715)

---

CHANGELOG.es.md
examples/docs/es/menu.md
examples/docs/es/select.md
examples/docs/es/transfer.md
examples/docs/es/tree.md

Changelog: update for 2.2.0

---

packages/upload/src/index.vue

fix: #6080 
if file in fileList (props) exist 'status', uploadFiles use its default 'status'

Upload: fix default status of fileList

---

packages/menu/src/menu.vue

看了一下 vue-router对router.push 源码的处理，在onAbort的处理上有两种方式，一种是有错误回调 另一种是无错误回调所以我个人认为不能单纯的忽略掉onAbort的回调参数。应该加一个判断

Menu: routeToItem 错误处理

---

build/bin/build-locale.js

如果 lang 中存在非正常语言文件，会报错。目前在 Mac 上遇到了这种情况，具体问题如下：
`fs.readdirSync` 读取目录中的文件时，读到了系统自动生成的 .DS_Store，导致报错。
```
/Project/element-ui/src/locale/lang/.DS_Store: Unexpected character '' (1:0)
```

Fix build locales, make sure only read `js` files from locale directory

---

test/unit/specs/date-picker.spec.js

See: https://github.com/ElemeFE/element/pull/9921
Ran 100 times in travis-ci, appeared to be fine after this fix.
Build log: https://travis-ci.org/wacky6/element/builds/347057627
* add delay between `mousemouve` and `click`
* nuke beforeEach's vm before creating custom one

Fix date-picker flaky test

---

packages/select/src/select.vue
test/unit/specs/select.spec.js

make the option layer only open when the select wrapper div is clicked , not the input in it focused

Select: make select click show options layer not focus (#9821)

---

examples/docs/en-US/input.md
examples/docs/es/input.md
packages/date-picker/src/picker.vue
types/autocomplete.d.ts
types/input.d.ts

- Prefix icon on the date/time input is now clickable on no range pickers
- In english and spanish documentation, remove `on-icon-click` hook function in `el-input` component
- Remove `onIconClick` type definition in `input.d.ts`
**Fixed** [#9687](https://github.com/ElemeFE/element/issues/9687)

Date Picker: make prefix icon on the input clickable on no range pickers (#9687)

---

examples/docs/en-US/color.md
examples/docs/es/color.md
examples/docs/zh-CN/color.md

In docs [Component | color](http://element.eleme.io/#/zh-CN/component/color).
When in phone:
After fixed:
---

Color: fix demo-color-box in docs respnsive layout

---

packages/date-picker/src/picker.vue
test/unit/specs/date-picker.spec.js

https://github.com/ElemeFE/element/issues/9984

date-picker: fix change event on clear

---

packages/date-picker/src/basic/date-table.vue

date-range support select reverse

---

test/unit/specs/date-picker.spec.js

date-picker 反向选择，做了最基本的测试。没判断 mousemove 过程中的高亮。（如果高亮不对的话估计后面选出来的结果也不对，所以没覆盖这个）
把正向选择的测试抄了一下然后改了一下 click 顺序（逃

test: add date-picker date-range reverse selection

---

examples/docs/en-US/pagination.md
examples/docs/es/pagination.md
examples/docs/zh-CN/pagination.md
packages/pagination/src/pager.vue
packages/pagination/src/pagination.js
packages/theme-chalk/src/pagination.scss
yarn.lock

new feature: add disabled for pagination

---

packages/message-box/src/main.js
packages/message-box/src/main.vue

Fix when multiple messagebox with duplicate title, for-example, the first one has title option, but the second one hasn't, and click the first one then the second one has the first title.
[jsfiddle] (https://jsfiddle.net/maj51e8z/3/)

Message-box: fix multiple messagebox with duplicate title

---

packages/menu/src/menu-item.vue

Sometimes there may be only one icon in menu item and has no $slots.title.
There are some problems in this situation.
Online demo: https://jsfiddle.net/bfsj2px0/2/
**Or** sometimes,  I don't want to use `el-tooltips`, I want to use custom styles instead.

Menu: check $slots.title

---

examples/docs/en-US/menu.md
examples/docs/zh-CN/menu.md
packages/menu/src/menu.vue
types/menu.d.ts

Sometime we dont need collapse transition

Menu: add menu attribute - collapseTransition

---

examples/docs/en-US/table.md
examples/docs/es/table.md
examples/docs/zh-CN/table.md
packages/table/src/table-store.js
packages/table/src/table.vue

Makes the behavior of the select-all checkbox same as GMail -- to deselect in "indeterminate" state of checkbox:

Multi-select Table: Add selectOnIndeterminate prop to control master checkbox behavior

---

types/message-box.d.ts

inputType is added in source code, but not for typescript file

MessageBox: Add "inputType" support for TypeScript

---

examples/docs/zh-CN/tree.md
packages/theme-chalk/src/tree.scss
packages/tree/src/model/tree-store.js
packages/tree/src/tree-node.vue
packages/tree/src/tree.vue

Tree node can drag and drop

---

examples/docs/en-US/datetime-picker.md
packages/date-picker/src/panel/date-range.vue
packages/date-picker/src/panel/date.vue
packages/date-picker/src/picker.vue
packages/date-picker/src/util/index.js
test/unit/specs/date-picker.spec.js

DatePicker: added correct extracting time format and date format from `format` property (datatimepicker). And added special property `date-format` and `time-format`, for manual set
https://github.com/ElemeFE/element/issues/10173

DatePicker: added correct set time and date formats

---

examples/docs/en-US/progress.md
examples/docs/es/progress.md
examples/docs/zh-CN/progress.md
packages/progress/src/progress.vue
test/unit/specs/progress.spec.js

[Progress](http://element-cn.eleme.io/#/zh-CN/component/progress)
进度条添加 `color` 属性，可以使用十六进制颜色代码或 rgba() 自定义色彩。 `color` 会覆盖 `status` 属性所带的色彩。
```
<el-progress :percentage="80" color="rgba(142, 113, 199, 0.7)"></el-progress>
```
```
<el-progress type="circle" :percentage="80" color="#8e71c7"></el-progress>
```
---

Progress: add color attribute

---

examples/docs/en-US/input.md
examples/docs/es/input.md
examples/docs/zh-CN/input.md
packages/input/src/input.vue
types/input.d.ts

Input: add blur method

---

examples/docs/en-US/tree.md
examples/docs/es/tree.md
examples/docs/zh-CN/tree.md
packages/theme-chalk/src/tree.scss
packages/tree/src/model/node.js
packages/tree/src/model/tree-store.js
packages/tree/src/model/util.js
packages/tree/src/tree-node.vue
packages/tree/src/tree.vue

Update Tree drag & drop logic.

---

.github/ISSUE_TEMPLATE.md
examples/docs/en-US/tree.md
examples/docs/es/tree.md
examples/docs/zh-CN/tree.md
packages/tree/src/tree.vue

Tree: update drag and drop docs

---

examples/docs/en-US/card.md
examples/docs/es/card.md
examples/docs/zh-CN/card.md
packages/card/src/main.vue
packages/theme-chalk/src/card.scss
test/unit/specs/card.spec.js

[Card](http://element-cn.eleme.io/#/zh-CN/component/card)
卡片增加 `shadow` 属性，可以对设置卡片阴影出现情况。默认值为 `always` 。
`always` 总是出现阴影，`hover` 鼠标悬浮时出现，`never` 从不出现阴影。
---

Card: add shadow attribute

---

packages/tooltip/src/main.js

`doDestroy` is not invoked when the tooltip is disabled because `<transition>` won't call `onAfterLeave`  when its content is not shown.
So `:popper-options="{removeOnDestroy:true}"` won't work when the tooltip is disabled.
https://jsfiddle.net/blackmiaool/3okg7754/4/
This pr solves this problem.

Tooltip: invoke 'doDestory' by hand when disabled

---

examples/docs/en-US/menu.md
examples/docs/es/menu.md
examples/docs/zh-CN/menu.md
packages/menu/src/submenu.vue
packages/theme-chalk/src/menu.scss
types/submenu.d.ts

Menu: add popper-append-to-body for SubMenu

---

packages/theme-chalk/src/tabs.scss

For tabs of style "border-card", don't set the color property on hover
if it is disabled.

Theme-Chalk: No tab color on hover when tab is disabled

---

types/submenu.d.ts

Fix the following error when using Typescript.
```
ERROR in [at-loader] ./node_modules/element-ui/types/submenu.d.ts:12:3 
TS2300: Duplicate identifier 'showTimeout'.
```

Fix TS2300: Duplicate identifier 'showTimeout'

---

packages/upload/src/upload.vue

Upload: fix duplicated handleClick due to keydown bubbling

---

packages/pagination/src/pagination.js
test/unit/specs/pagination.spec.js

Pagination component breaks when `NaN` is passed on the prop `currentPage` or `pageSize`. Here is a demo reproducing the issue.
https://jsfiddle.net/xroupdkf/2/
I added a little protection code to keep it safe from `NaN`.
- With `NaN`, `pageSize` returns default value (which is `1`).
- `currentPage` already had a nice handling code inside `internalCurrentPage` watcher but it is not invoked at initial phase, so I made it to be called immediately.
It passes all of the test cases and I added more of it.
Thank you for maintaining this amazing repository.

Pagination: handle NaN on props

---

src/locale/lang/es.js

In spanish has no sense "2018 año diciembre", it has to be 'diciembre 2018' or '2018 diciembre', so I changed the translation of `year: 'Año' ` to `´year:''´`

Fix spanish translation for year display in datepicker

---

packages/input/src/input.vue
packages/select/src/select.vue
src/utils/shared.js

Input&Select: fix cursor goes to the end of the text(#10611)

---

packages/date-picker/src/picker.vue
test/unit/specs/date-picker.spec.js

https://github.com/ElemeFE/element/issues/10719
https://github.com/ElemeFE/element/issues/9790
Is a simple fix, valid values are handled in handleChange, just nuke userInput on close.

date-picker: nuke invalid input on close

---

src/locale/lang/da.js

Translate remaining strings. Clear translation for `datepicker.year` since it shouldn't be used for this locale (like the English locale).

i18n: Update Danish locale

---

packages/date-picker/src/panel/date.vue
packages/date-picker/src/util/index.js

see issue https://github.com/ElemeFE/element/issues/10890
Caused by `[val]` being coerced to `val.toString()` during `new Date()`.
Changes:
1. strict type check in `isDate`
2. in dates selection, do not reset panel date unless value is falsy.

date-picker: fix dates selection date jump

---

packages/date-picker/src/picker.vue
test/unit/specs/date-picker.spec.js

fixes #11013
这个问题似乎2.0发布以后，不知道为什么之前都没发现。（似乎应该搞一波TDD了
emitInput 里面的 `dates` 判断似乎没啥用，去掉了。 @Leopoldthecoder 大佬看一下

date-picker: fix valueEquals for array

---

packages/table/src/table-store.js
test/unit/specs/table.spec.js

Fix #10177 that after set new table data, the expanded cells will not be able to unexpand.
When no `rowKey`, use the same logic as #10241 .

Table: update expandRows when setData.

---

packages/upload/src/ajax.js
packages/upload/src/upload.vue

Upload: fix a TypeError when upload a processed file from the `beforeUpload` hook

---

packages/autocomplete/src/autocomplete.vue
packages/input/src/input.vue

bugfix #11199 
修改后在 `window 7 / [chrome 66 | ie11]` 下能正常使用. 受开发环境限制, 没有进行其他兼容性测试, 建议进一步测试.
另外没有处理韩文相关经验, commit里只简单保留了相关判断, 并简单用朝鲜语IME输入试了下没问题, 不太清楚对 #10611 是否有影响.
产生原因:
上一个文字键入后`currentValue`发生变化, 并在vue同步变化到dom前又迅速键入了其他字符, 触发输入法选择. 此时dom上的内容包括了新键入的字符, 但`currentValue`不包含. 
vue将`currentValue`变化同步到dom上时将`currenValue`的值替换掉实际dom上的值使得光标跳到末尾处.
解决方案:
在`isOnComposition`为`true`时也修改`currentValue`, 但不emit `input`事件和`el.form.change`事件, 保持内部`currentValue`与dom上`value`保持一致.
保存`compositionstart`事件触发时dom上的值到`valueBeforeComposition`, 在`isOnComposition`为`true`时只有新值与`valueBeforeComposition`不同时才能修改`currentValue`, 应对组件`props.value`的其他变动能正确反映到`currentValue`上.
其他修改:
由于input组件进行了`composition`相应处理, autocomplete无需再处理一次, 因此移除了相关处理.

input: fix cursor goes to the end when typing chinese quickly

---

packages/theme-chalk/src/button.scss

让circle button也支持size属性控制，padding的大小根据size属性的```button-padding-vertical```确定

button: circle button add size support

---

packages/upload/src/upload.vue
types/upload.d.ts

related commit: https://github.com/ElemeFE/element/commit/117f731f6eda217ce5901379f8bd467a6a2acb7d
related review comment: [assign name and uid to processedFile in beforeUpload hook](https://github.com/ElemeFE/element/pull/11210/files/8ba2a4cf63ae050a0b77cf39691b7c17331da63e)

Upload: fix Error when `beforeUpload` hook return promise of file object

---

examples/docs/en-US/input-number.md
examples/docs/es/input-number.md
examples/docs/zh-CN/input-number.md
packages/input-number/src/input-number.vue
test/unit/specs/input-number.spec.js
types/input-number.d.ts

InputNumber: add precision attribute

---

examples/docs/en-US/tabs.md
examples/docs/es/tabs.md
packages/radio/src/radio-group.vue
types/tab-pane.d.ts

 Radio: support switching radio with keyborard in ff. Fixes #8198

---

CHANGELOG.es.md
examples/docs/es/input-number.md
examples/docs/es/input.md
examples/docs/es/table.md
examples/docs/es/tabs.md

Update Spanish Doc 2.4

---

packages/date-picker/src/panel/date-range.vue
packages/date-picker/src/panel/date.vue
packages/date-picker/src/util/index.js
test/unit/specs/date-picker.spec.js

Regression introduced during 2.0 refactor. Quite surprised that it took 7 months for someone to spot this bug. 😂
`modifyWithDefaultTime` changed to `modifyWithTimeString` to reflect what it does.

date-time-picker: fix incorrect date on time pick

---

packages/table/src/table-footer.js

Table: improve the performance of summary-method

---

packages/popover/src/directive.js

https://jsfiddle.net/akifo/eywraw8t/64650/
Clarify that the vComponent referenced by a " `var popper = vnode.context.$refs[_ref];` " should be one
```
<div v-for="i in loop">
<div v-for="j in loop2">
<el-popover
:ref="i + '_' +j"
placement="right"
title="Title1"
width="200"
trigger="focus"
content="this is content, this is content, this is content">
</el-popover>
<el-button v-popover="i + '_' +j">Focus to activate</el-button>
</div>
</div>
```

Popover: Fix set reference in loop

---

CHANGELOG.es.md
examples/docs/es/dialog.md
examples/docs/es/tabs.md

update Doc Spanish 2.4.1

---

packages/select/src/select.vue
test/unit/specs/form.spec.js

https://github.com/ElemeFE/element/issues/11548
Will trigger form validation whenever select's bounded value changes. The behavior is now similar to el-input.

select: fix form change validation

---

examples/docs/en-US/tabs.md
examples/docs/es/tabs.md
examples/docs/zh-CN/tabs.md
packages/tabs/src/tabs.vue
types/tabs.d.ts

Tabs: add activeName and oldActiveName parameters to before-leave hook

---

.eslintignore

在windows下执行npm run test 以后eslint检查字体文件的时候会报错

eslint ignore font file

---

CHANGELOG.es.md

Spanish Doc 2.4.2

---

examples/docs/zh-CN/form.md

line 412: `...并 Form-Item 的...` -->> `...并将 Form-Item 的...`

[doc] Update zh-CN/form.md

---

examples/docs/en-US/form.md
examples/docs/es/form.md
examples/docs/zh-CN/form.md
packages/form/src/form.vue
test/unit/specs/form.spec.js
types/form.d.ts

Form: clearValidate supports prop names

---

examples/docs/en-US/message-box.md
examples/docs/es/message-box.md
examples/docs/zh-CN/message-box.md
packages/message-box/src/main.js
packages/message-box/src/main.vue
test/unit/specs/message-box.spec.js
types/message-box.d.ts

MessageBox: add distinguishCancelAndClose

---

packages/table/src/table-body.js
packages/table/src/table-store.js

避免在 `highlight-current-row` 为 false 时，点击某一行触发重新渲染。参考：#11836。

Table: update getRowClass

---

examples/docs/en-US/time-picker.md
examples/docs/es/time-picker.md

Time-Picker: Add missing translation

---

examples/components/side-nav.vue
packages/date-picker/src/basic/date-table.vue
packages/date-picker/src/basic/time-spinner.vue
packages/date-picker/src/panel/date-range.vue
packages/date-picker/src/panel/date.vue
packages/rate/src/main.vue
packages/slider/src/main.vue

Changed to explicitly grant implicitly given key.
Reason 1. If key is not specified for v-for item with standard Vue Lint setting, Lint error will occur.
Reason 2. People make mistakes better. It is difficult to judge whether you implicitly did not specify the key or forgot it.
For the above reasons, you should not expect to implicitly apply the key.
https://vuejs.org/v2/guide/list.html#key

Any: Fix where key is not specified for v-for

---

packages/radio/index.js

When using 'On demand' mode and load `Radio`. `<ElRadio>` can not used in the template, must use `<el-radio>`.
I fix it.

Radio: fix hardcoded component name

---

packages/theme-chalk/src/table.scss

Table: fix empty slot position

---

packages/tree/src/tree.vue

Tree: fix defaultCheckedKeys and emptyText bug

---

CHANGELOG.es.md

Update Spanish doc 2.4.4

---

packages/date-picker/src/picker.vue

TimeSelect: fix fieldReset when initialValue is empty string

---

types/message.d.ts

ElMessageOptions 类型定义中，message选项无法设置为VNode, 故增加VNode可选类型选项

Message: fix type definition of ElMessageOptions, support VNode as message type

---

packages/date-picker/src/panel/date-range.vue
packages/date-picker/src/panel/date.vue

I believe I've discovered an issue with the date/date range components when being used on Internet Explorer. These components use an inline expression with arrow functions. I suspect that Babel isn't able to identify that these expressions need to be parsed (or it's simply unable to parse them) and so it can't convert them back to the traditional function syntax for older browsers.
By moving these expressions into normal Vue methods it should allow these components to be handled by Babel correctly and work on Internet Explorer 11.

Date,DateRange: Remove arrow functions from inline expressions

---

packages/date-picker/src/basic/date-table.vue
test/unit/specs/date-picker.spec.js

date-table `watch.maxDate` 里面的 `$emit` 意义不明。从功能上来说，pick是选择日期才会触发（用户点日期的时候），而不应该在 maxDate 改变的任何时候都触发。
目前 panel 的状态使用 data() + picker proxy的，所以创建的时候 panel 中 date-table maxDate 为 null，proxy 时触发更新，这时触发了 pick 时间，从而导致时间被 defaultTime 重设。
---
测试没挂，如果发布了真有大问题，再追加 patch 版本吧 😂

date-picker: fix #11152

---

CHANGELOG.en-US.md
CHANGELOG.es.md
CHANGELOG.zh-CN.md

Changelog: update for 2.4.5

---

packages/menu/src/menu.vue

fix bug #10622 
对Menu的参数命名觉得奇怪，`defaultActive`是指默认状态，从命名上来看应该是只在初始化时生效，如果要动态改变menu的active item，应该命名为`active`或`active-index`，这样更好理解一些

Menu: save menu state when change collapse and expand menu(#10622)

---

examples/docs/en-US/popover.md
examples/docs/es/popover.md
examples/docs/zh-CN/popover.md

Docs: improve docs

---

types/message-box.d.ts
types/tree.d.ts

- 让 ElMessageBoxOptions.message 允许 VNode 类型
http://element.eleme.io/#/zh-CN/component/message-box#options
- `TreeNode`（实际上是 Data） 改名 `TreeData`
- `TreeData ` 添加泛型支持，允许用户自定义类型（配合 `props`）
- 添加新的 `TreeNode` 类型（真实的 Node），其中有个 `text` 字段似乎没被使用，被我忽略掉
- 添加 `TreeStore` 类型，由于时间有限，我了解不深，只添加了一个我在使用的 `_getAllNodes`，用户使用时有其他需要可以强制转为 any 处理（希望有更熟悉的人完善下）
- 为 ElTree 添加泛型支持，添加 `store` 属性
- 修复 ElTree 的 `getHalfCheckedNodes` 和 `getHalfCheckedKeys` 的返回值类型
- 格式化了代码

[Tree][MessageBox] fix type definition

---

examples/docs/en-US/input.md
examples/docs/es/input.md
examples/docs/zh-CN/input.md
packages/autocomplete/src/autocomplete.vue
types/autocomplete.d.ts
types/select.d.ts

Autocomplete: add `popper-append-to-body` attribute

---

examples/docs/en-US/pagination.md
examples/docs/es/pagination.md
examples/docs/zh-CN/pagination.md
packages/pagination/src/pagination.js

Pagination: make page-size attribute supports .sync

---

examples/docs/en-US/menu.md
examples/docs/es/menu.md
examples/docs/zh-CN/menu.md

Menu: fix docs

---

packages/date-picker/src/picker.vue
test/unit/specs/form.spec.js

https://github.com/ElemeFE/element/issues/12311

date-picker: fix form change validation

---

examples/docs/en-US/date-picker.md
examples/docs/es/date-picker.md
examples/docs/zh-CN/date-picker.md
packages/date-picker/src/basic/date-table.vue
packages/date-picker/src/basic/month-table.vue
packages/date-picker/src/basic/year-table.vue
packages/date-picker/src/panel/date.vue
packages/date-picker/src/picker.vue
src/utils/util.js
test/unit/specs/date-picker.spec.js

fix https://github.com/ElemeFE/element/issues/12323
其实是把日期多选重构了一下，现在：
* 干掉了 `selectedDate`，复用 value / parsedValue 的一系列机制
* 遵守 immutable 的思路
* 月/年表 **会高亮** 选中的日期
* 文档修正：空值应当为 `falsy`；空数组会被认为是真值，可能会导致奇怪的问题。
---
什么时候不要支持 IE 了，就改成原生 `Array.{find, findIndex}`
合进 next 也可以，这样的话就先用 https://github.com/ElemeFE/element/pull/12339 糊弄一下 dev （逃

Date picker refactor dates selection: fix 12323

---

packages/date-picker/src/picker.vue

补充 pr https://github.com/ElemeFE/element/pull/12328
因为 time-picker 内部实现的问题，每次选择时间都会触发表单验证 （更合理的行为应该是 在用户确定时，和程序改变值的时候 触发）； pr https://github.com/ElemeFE/element/pull/12347 重构日期多选后会有类似的问题。
所以，`watch.value`会判断面板是否可见，从而决定是否触发表单验证。
虽然存在边缘情况，但应该能满足绝大多数场景

date-picker: improve form change validation

---

packages/theme-chalk/src/menu.scss

选中submenu下的菜单，submenu没有激活样式式象错误
官网样式
修改后样式

Menu: submenu is-active  bug

---

packages/color-picker/src/components/sv-panel.vue

https://github.com/ElemeFE/element/blob/b70da53f157ee25ec6cd3a763e5b8ce3882a24ee/packages/color-picker/src/components/sv-panel.vue#L48-L53
```
const el = this.$el;
// let { width, height } = el.getBoundingClientRect();
// if (!height) height = width * 3 / 4; 
let { clientWidth: width, clientHeight: height } = el;
```
1. 选色容器的 宽高比应为 14/9 , 非 4/3
2. 此处获取的width,height是给取点定位用的, 不应该使用getBoundingClientRect(), getBoundingClientRect() 获取的数值受CSS transform 影响, 导致打开取色面版的动画期间取值为0,或取值错误, 使用 `clientWidth` , `clientHeight` 属性更好, 不受CSS transform 影响

ColorPicker: 一些情况下取色光标定位不准问题修复

---

examples/docs/en-US/dialog.md
examples/docs/en-US/form.md
examples/docs/en-US/input.md
examples/docs/en-US/select.md
examples/docs/es/dialog.md
examples/docs/es/form.md
examples/docs/es/input.md
examples/docs/es/select.md
examples/docs/zh-CN/dialog.md
examples/docs/zh-CN/form.md
examples/docs/zh-CN/input.md
examples/docs/zh-CN/select.md
packages/input/src/input.vue
packages/select/src/select.vue
types/input.d.ts
types/select.d.ts

Input: fix autocomplete property is not compatible with native #12513

---

examples/docs/en-US/form.md
examples/docs/es/form.md
examples/docs/zh-CN/form.md

Adds improved documentation to the el-form `label-position` attribute, which behaves differently when used with and without `label-width`.  Specifically, `label-position` does not take effect for values 'left' and 'right' if no `label-width` is provided. This has been a source of confusion for myself and others, but is evidently expected behavior:
https://github.com/ElemeFE/element/issues/8477
Thanks!

Docs: Document el-form label-position attribute

---

examples/docs/en-US/upload.md
examples/docs/es/upload.md
examples/docs/zh-CN/upload.md
types/upload.d.ts

Upload: add missing definition

---

packages/tabs/src/tab-pane.vue
packages/tabs/src/tabs.vue
test/unit/specs/tabs.spec.js

- Closes #12549
- 一个类似的 pr #12577 
更改 Tabs 的部分实现，Tabs 中的 panes 属性完全由 default slot  计算出来，这样避免了排序之后，TabNav 没有渲染的问题。
这种解决方案有一个弊端是：TabPane 不能被其他元素包裹。不过一般情况下，也不会出现这种问题。

Tabs: fix order of TabNav when array is sorted

---

examples/docs/en-US/i18n.md
examples/docs/es/i18n.md
examples/docs/zh-CN/i18n.md

doc: update i18n doc for Serbian language

---

examples/docs/en-US/form.md
examples/docs/es/form.md
examples/docs/zh-CN/form.md
packages/form/src/form-item.vue

Form: Emits error message on validate event

---

packages/input/src/input.vue

A textarea element can also have an autocomplete attribute.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

[input]: Fix autocomplete support on textareas

---

packages/theme-chalk/src/table.scss

Hi, I found a bug related to the table column default alignment that exists already for almost 2 year :) https://github.com/gabskoro/element/commit/56ed21df4a125ef4c8599e902d72bcf0be12fda0
In the documentation it's written that it should be aligned to the left but actually it's centered.
The header is by default aligned to the left, so I removed the code from there and put it together inside the `td, th` definition

Table: Fix table column default alignment

---

types/tree.d.ts

- 为 `TreeData` 添加 `disabled` 属性
- 为 `TreeNode` 添加 `label` 属性
- 添加 `TreeProps` 类型，用于 `ElTree.props`
- 修复 getNode 的返回值错误，更正为 `TreeNode`

[Tree] fix type definition

---

CHANGELOG.en-US.md
CHANGELOG.es.md
CHANGELOG.zh-CN.md

changelog for 2.4.8

---

examples/docs/en-US/dropdown.md
examples/docs/es/dropdown.md
examples/docs/zh-CN/dropdown.md

Added slots section in English to documentation for Dropdown component. Chinese and Spanish translation missing (I placed an English version semi-translated).
* [√] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [√] Make sure you are merging your commits to `dev` branch.
* [√] Add some descriptions and refer relative issues for you PR.

Dropdown: Added slots to documentation

---

examples/docs/zh-CN/slider.md
packages/input-number/src/input-number.vue

InputNumber: fix style when `controls-position` is right

---

packages/form/src/form.vue

here's the explain, when we pass a string type param to `form.clearValidate` method it also will work, but in some situation it perform weird, e.g. if we have two `form-item`, their props contain same keyword, like` 'password'` and `'re-password'`, then if we use `form.clearValidate('re-password')`,both of them's status will be clear, but I only want to clear `re-password`.
I know the doc tell us to pass a array type param, but I think string type param should be supported.

Form: fix string type param bug

---

packages/cascader/src/main.vue
packages/select/src/select.vue
src/utils/util.js

readonly 添加 edge 浏览器判断
closes #13025

Select: Fix (#13025)

---

packages/select/src/select.vue
packages/theme-chalk/src/select.scss

Fix for Writing space become small when collapse-tags prop is added & input takes new line even if space is available when filterable & multiple props are true
- Closes #12329 
- Closes #12327

Select: Fix (#11392 & #12327)

---

examples/docs/en-US/table.md
examples/docs/es/table.md
examples/docs/zh-CN/table.md
packages/table/src/table-column.js

Fixes #4909 
Fixes #4908
Related #11807
Related #6573 
Now it is possible to assign custom headers directly to templates, exactly as renderHeader does.

Table: Adds header rendering slot

---

packages/table/src/table-body.js

- Closes #13111
表格内overflow-tooltip的内容优先使用innerText的返回值，innerText不会返回被隐藏的文本内容。overflow-tooltip根据特性名应显示的是溢出的内容，而不是把隐藏的文本都显示出来

Table: tooltip content prefer to use innerText instead of textContent

---

.travis.yml

自昨天起，Node.js LTS 变成了 v10。目前使用的 node-sass 不支持最新版本的 Node。
指定版本号，暂时不升级 sass 依赖了。

Chore: specify travis Node.js versions

---

packages/table/src/table-store.js

- Closes #3023
如果table包含`row-key`，当表格数据变化时，如果新数据内某行包含有相同的rowKey，则将其设为currentRow

Table: current row will set to the row which has the same rowKey when data changes

---

examples/docs/en-US/table.md
examples/docs/es/table.md
examples/docs/zh-CN/table.md
packages/table/src/table-store.js
packages/table/src/table.vue
packages/table/src/util.js

- Closes #13126 
添加`resetFilter`方法，可以重置单列的filter

Table: add method resetFilter which can reset filter of a column

---

packages/color-picker/src/components/picker-dropdown.vue
packages/color-picker/src/main.vue

#12994 Color default value is #ff0000, without immediate, the default value has no change.
* [-] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [-] Make sure you are merging your commits to `dev` branch.
* [-] Add some descriptions and refer relative issues for you PR.

ColorPicker:(fix) default color red dont activate watch

---

examples/docs/en-US/date-picker.md
examples/docs/es/date-picker.md
examples/docs/zh-CN/datetime-picker.md
packages/date-picker/src/picker.vue

Currently, the only possible option for "range-selector" is a string, would be nice to use a slot, so we could have custom svg-icon there.
* [ x ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ x ] Make sure you are merging your commits to `dev` branch.
* [ x ] Add some descriptions and refer relative issues for you PR.

DatePicker: Allowed to customize range-seprator with a slot

---

packages/theme-chalk/src/date-picker/time-picker.scss

Many projects will increase the following css globally.
```css
*,
*:before,
*:after {
box-sizing: inherit;
}
```
Such as [minireset](https://github.com/jgthms/minireset.css/blob/master/minireset.css), [bootstrap](https://github.com/twbs/bootstrap/blob/f803fb9903abd2daa033081894d310f97a371e70/scss/bootstrap-grid.scss) Or [article](https://www.paulirish.com/2012/box-sizing-border-box-ftw/).
But time-pick hs a display bug, because it will inherit  `el-date-range-picker__time-header` attr.
[Online demo](https://jsfiddle.net/tkdys3p0/)

TimePicker: explicit declare box-sizing: content-box

---

packages/date-picker/src/basic/date-table.vue

简化内部实现
* issue https://github.com/ElemeFE/element/issues/12980 的问题在 2.0.0 的时候就有了
* `rangeState.{row, column}` 改到 date-table 内部了，这个没必要暴露给外面的组件。
* pr #8156 引入了会高亮已禁用日期的 bug，一并修了
删代码真开心 （x

date table: simplify implementation, fix #12980, follow up #8156

---

packages/tree/src/model/node.js
test/unit/specs/tree.spec.js

fix #12383 
bug 原因: 
异步的情况下会执行 doCreateChildren , 如果刚好children 的前两个或多个是 default-checked-keys 中设置的, 那么会将 parent.checked 设置为 true.
在 `callback` 中 会执行 `setChecked(true, true)`, 将所有的 children 的 check 的设置为true
解决办法:
在 执行 callback 之前, 再次检查该节点的 children.
---
~~如果需要的话 可以添加 tests, 但是我碰到有个问题, 在 windows 环境下 测试跑不通~~

[Tree]: fix #12383

---

examples/docs/en-US/progress.md
examples/docs/es/progress.md
examples/docs/zh-CN/progress.md
packages/progress/src/progress.vue
test/unit/specs/progress.spec.js
types/progress.d.ts

Hi there
With the current version of ElementUI, we can not use the special text inner circle progress content, and I have added this feature, for instance:
```javascript
<Progress :percentage="100" :stroke-width="10" :width="100" status="text" type="circle">Done</Progress>
```
And it will be:
I hope it will be useful.

Progress: add text status

---

examples/docs/en-US/input.md
packages/autocomplete/src/autocomplete.vue
packages/input/src/input.vue
types/autocomplete.d.ts

This PR allows `el-autocomplete` to be clearable, just like `el-input`.

Autocomplete: add clearable prop

---

examples/docs/en-US/input-number.md
examples/docs/es/input-number.md

https://github.com/ElemeFE/element/pull/11281 的时候 英文 和 西语 的文档没加上 `num9`
这么久竟然没有国际友人发现这个bug。。。

doc: input-number, fix missing num9 declaration

---

packages/date-picker/src/panel/date-range.vue
packages/input-number/src/input-number.vue
packages/input/src/input.vue
packages/pagination/src/pagination.js
test/unit/specs/date-picker.spec.js
test/unit/specs/input.spec.js
test/unit/specs/pagination.spec.js

* remove el-input's `currentValue`
* update components that depends on the legacy currentValue behavior
* el-input now strictly follows one-way data flow and will always show the bounded value
* remove Korean IME / Composition fix (https://github.com/ElemeFE/element/pull/10648)
* add hack for MSIE's incorrect `input` event emission when placeholder is set
* update some tests
JSFiddle playground: https://jsfiddle.net/xd754jk2/1/
**Semver minor**: Unlikely to break existing applications, unless they use internal APIs.
* Demo: https://jsfiddle.net/mdfha1zk/
* Demo: https://jsbin.com/vinuvizoju/1/edit
* Verified the fix on Windows 10 + IE 11; Need community verification
* Verified the fix on Windows 10 + IE 11 + Native Korean IME; Need community verification
* Will not deal with third-party …

simplify el-input implementation

---

packages/table/src/table-header.js

点击箭头排序时，比如是`ascending`，再次点击向上的箭头，一直保持`ascending`状态。
本次的pr，可以在`ascending`下再次点击按钮，恢复到未排序状态。
---
When clicking the arrow to sort, for example, `ascending`, click the up arrow again to keep the `ascending` state.
This time pr, you can click the button again under `ascending` to return to the unsorted state.

ElTable: enhanced table sorting when clicking on the arrow

---

types/cascader.d.ts

Allows `children` and `disabled` to be undefined

Cascader: Correct type definitions of CascaderOption

---

packages/theme-chalk/src/table.scss

Fix the table empty text vertical alignment issue(pushed top of empty container).
Please refer to attached screenshot:
Thank you!
**Environment**
- Windows 10
- Internet Explorer 10+

Table: fix empty text vertical alignment issue on IE10+

---

packages/carousel/src/main.vue

Carousel: stop timer before component destroyed (#13820)

---

packages/autocomplete/src/autocomplete.vue
packages/input/src/input.vue

close #13803 
also fix el-autocomplete when type is `textarea`

fix input issue when type is `textarea`

---

packages/tree/src/tree-node.vue
packages/tree/src/tree.vue

在使用 `Tree` 组件的过程中发现一个问题，在我将一个 `Tree` 组件的 `show-checkbox` 属性的值从 `true` 修改为 `false` 之后，`Tree` 组件的子组件 `tree-node` 依然显示 `Checkbox` 组件并且处于可选状态，看过源码后发现 `tree-node` 的 `show-checkbox` 属性并非 `props` 传入，而是在 `created` 的时候读取其父组件的值，这是导致了这个 Bug 的原因。

Tree: fix a bug that caused `showCheckbox` props on `Tree` can not affect their children `tree-node`

---

packages/theme-chalk/src/date-picker/month-table.scss
packages/theme-chalk/src/date-picker/year-table.scss

When `el-date-picker` type is `month` or `year`,  current month or this year has not to highlight. The pull request could be fixed

DatePicker: add current month & current year highlight style

---

build/webpack.conf.js

Webpack UMD modules are broken currently: [webpack/webpack#6525](https://github.com/webpack/webpack/issues/6525)

Build: Fix UMD bundle error used in node env

---

examples/components/search.vue
examples/docs/en-US/input.md
examples/docs/es/input.md
examples/docs/zh-CN/input.md
packages/autocomplete/src/autocomplete.vue

This PR adds a prop to enable a user to have the first item highlighted by default when using remote search.
I have also applied this to the Algolia search component in the header for quick demoing, and because I feel this is a speedier approach for people navigating the docs. Could be removed though.
This addresses/ fixes this issue
https://github.com/ElemeFE/element/issues/14270

Autocomplete: prop to highlight first item

---

packages/input-number/src/input-number.vue

There is nothing different between two parseFloat and one parseFloat.

input-number: remove unnecessary parseFloat

---

packages/theme-chalk/src/tree.scss

There is a `color` difference between the tree and the table empty-text.And I think use `$--color-text-secondary` is  more sense.

Tree: Empty-text tips are different from tables

---

packages/table/src/table-body.js
packages/table/src/table-store.js
test/unit/specs/table.spec.js

Table: remove some html DOM operations (#13643)

---

examples/docs/en-US/select.md
examples/docs/es/select.md
examples/docs/zh-CN/select.md
packages/select/src/select.vue
test/unit/specs/select.spec.js

Select: Add slot `empty` (#13769)

---

packages/table/src/table-store.js

fix #14075 .
All instances of TableStore share the same toggleAllSelection method in TableStore.prototype.mutations.Since the toggleAllSelection method is a debounce function which create a closure, all TableStore's instances share the same Lexical scope while they call the toggleAllSelection method. The time interval between two tables call `toggleAllSelection` is less than the debouncing delay(10), so the first call doesn't work.
This commit make the actual toggleAllSelection method an instance method.

Table: make toggleAllSelection method an instance method(#14075)

---

src/utils/popup/index.js

fix: getDOM递归问题

---

examples/docs/en-US/date-picker.md

MInor change that updates `costume` to `custom`.

[Docs]:  Fix minor spelling issue in en-US datepicker documentation

---

examples/docs/en-US/switch.md
examples/docs/es/switch.md
examples/docs/fr-FR/switch.md
examples/docs/zh-CN/switch.md
packages/switch/src/component.vue
packages/theme-chalk/src/popover.scss
types/switch.d.ts

- Closes #14008
- Closes #13987

Switch: trigger form validation if value changes

---

examples/docs/en-US/date-picker.md
examples/docs/es/date-picker.md
examples/docs/fr-FR/date-picker.md
examples/docs/zh-CN/date-picker.md
packages/date-picker/src/basic/month-table.vue
packages/date-picker/src/panel/month-range.vue
packages/date-picker/src/picker.vue
packages/date-picker/src/picker/date-picker.js
packages/theme-chalk/src/date-picker/date-range-picker.scss
packages/theme-chalk/src/date-picker/month-table.scss
packages/theme-chalk/src/date-picker/picker.scss
test/unit/specs/date-picker.spec.js

为组件的type属性新增了monthrange可选值
新增了 month-range.vue 文件
更新了 month-table.vue、picker.vue、date-picker.js、month-table.scss  docs/zh-CN/date-picker.md 文件
此扩展是根据date-range.vue 文件进行的改造，同时调整了原本的month-table.vue文件，但是不影响原本的功能；暂时只更新了对应的中文示例文档

DatePicker: add monthrange for type attribute (#4204)

---

packages/date-picker/src/picker.vue

- Closes #13746
when type=='week', value-format parser is bypassed
---
暂时方案， week 的 value-format 依然不支持 week-number。
type===week时， 禁止用户输入。原先的 parser 没有作用 （永远返回 null） 替换成了 date 的 parser。
远期修改加到了 https://github.com/ElemeFE/element/issues/9878

date-picker: fix week picker's value-format

---

packages/steps/src/step.vue
packages/steps/src/steps.vue
test/unit/specs/steps.spec.js

Steps: fixes issue #14502

---

examples/assets/styles/common.css

You can see the example of issue on picture above.
This tiny CSS fix for issue with highlighting all controll elements on touch screens in Webkit browsers.

fix highlighting control elements for Webkit touch

---

packages/date-picker/src/panel/date-range.vue

date-range: fix default-value daylight saving

---

packages/cascader/src/main.vue
test/unit/specs/cascader.spec.js

修复文字重叠问题：https://codepen.io/ziyoung/pen/wOYbGe
相关 pr #14572

Cascader: remove unnecessary DOM operation

---

packages/theme-chalk/src/tabs.scss

el-tab其中一个选择器默认颜色不是变量，导致修改主色调后，这个属性的默认颜色还是 ‘#409eff’

tabs:修复el-tab其中一个选择器默认颜色不是变量的问题

---

packages/menu/src/submenu.vue

The `showTimeout` duration of `popupMenu` does not need to be the same as `inlineMenu`.
If it
set too long, it will cause the submenu pop again bug when you quickly click on the menu.
To fix https://github.com/ElemeFE/element/issues/12512

Menu: fix click el-submenu trigger childMenu pop again bug

---

examples/docs/en-US/table.md
examples/docs/es/table.md
examples/docs/fr-FR/table.md
examples/docs/zh-CN/table.md
packages/table/src/table-body.js
packages/table/src/table-column.js
packages/table/src/table-store.js
packages/table/src/table.vue
packages/theme-chalk/src/table.scss
test/unit/specs/table.spec.js
types/table.d.ts

Table: support tree structure data

---

packages/dropdown/src/dropdown-menu.vue
packages/dropdown/src/dropdown.vue

Dropdown: compatible with 2.6 new v-slot syntax

---

packages/tree/src/model/node.js
test/unit/specs/tree.spec.js

Tree: revert pr #13349

---

examples/docs/en-US/form.md
examples/docs/es/form.md
examples/docs/fr-FR/form.md
examples/docs/zh-CN/form.md
packages/form/src/form-item.vue
packages/form/src/form.vue
packages/form/src/label-wrap.vue
packages/theme-chalk/src/form.scss
test/unit/specs/form.spec.js

Form: label-width supports width auto

---

packages/form/src/label-wrap.vue
packages/theme-chalk/src/form.scss

Form: fix style when label-width is auto

---

packages/form/src/form.vue
packages/form/src/label-wrap.vue
packages/theme-chalk/src/form.scss

Form: fix label style

---

build/webpack.demo.js

恢复成升级 webopack 之前的 `Project is running at http://0.0.0.0:8085/` 提示

chore: Display dev server info by default

---

src/directives/repeat-click.js

Prevent creation of new Date object to get time in ms. see [performace test](https://jsperf.com/date-now-vs-new-date)

Repeat-click: use Date.now() instead of new Date()

---

examples/docs/en-US/loading.md
examples/docs/en-US/message-box.md
examples/docs/en-US/radio.md
examples/docs/en-US/rate.md
examples/docs/en-US/select.md
examples/docs/es/loading.md
examples/docs/es/message-box.md
examples/docs/es/radio.md
examples/docs/es/rate.md
examples/docs/es/select.md
examples/docs/fr-FR/loading.md
examples/docs/fr-FR/message-box.md
examples/docs/fr-FR/radio.md
examples/docs/fr-FR/rate.md
examples/docs/fr-FR/select.md
examples/docs/zh-CN/loading.md
examples/docs/zh-CN/message-box.md
examples/docs/zh-CN/radio.md
examples/docs/zh-CN/rate.md
examples/docs/zh-CN/select.md

Docs:rename variable in Loading,MessageBox,Radio,Rate,Select docs

---

packages/theme-chalk/src/common/var.scss
packages/theme-chalk/src/notification.scss

fix: Fix Notification title word break

---

packages/theme-chalk/src/dialog.scss

Dialog: Fix dialog body correctly break long words

---

packages/tabs/src/tabs.vue

The uncaught rejection was bubbling up our application. And since we're using an error logger like Sentry, it was catching those and logging them. The error isn't really an error at all, so it needs to be caught and ignored in this case.

Fixed issue where Promise rejection was hitting application

---

packages/tree/src/model/tree-store.js
test/unit/specs/tree.spec.js

Tree: delete current node then call getCurrentNode method should return null

---

packages/select/src/option.vue
packages/select/src/select.vue
test/unit/specs/select.spec.js

check if value is empty before slice it 

Select: fix slice of value when value is undefined or null

---

examples/docs/en-US/input-number.md
examples/docs/es/input-number.md
examples/docs/fr-FR/input-number.md
examples/docs/zh-CN/input-number.md
packages/input-number/src/input-number.vue
test/unit/specs/input-number.spec.js
types/input-number.d.ts

add multiple-of-step attribute

InputNumber: add step-strictly attribute

---

packages/table/src/table.vue

Closes #13751.
This PR is an attempt to close the referenced issue since I'm not sure if it breaks something...
Since the `max-height` is calculated [this way](https://github.com/ElemeFE/element/blob/dev/packages/table/src/table.vue#L510), if you specify it with a unit other than `px` (an integer), it doesn't calculate properly, therefore, doesn't show the scrollbar.
I looked into _why_ it's calculated like that and couldn't figured out, so I tried to replace it with the same calculation used for `height` and it worked as expected. Even [this example](http://element.eleme.io/#/en-US/component/table#fluid-height-table-with-fixed-header-and-columns), created in the [PR that originated the `max-height` feature](https://github.com/ElemeFE/element/pull/1674), just worked as before.
I checked …

Table: equal behaviour for height and max-height

---

packages/calendar/src/main.vue

Calendar:fix October disappear bug

---

types/table-column.d.ts

Table-column: add  'custom'  to the  `sortable` type

types: update sortable type

---

packages/input-number/src/input-number.vue

Replace toFixed() by Math.round(), because toFixed() follow Banker's Round 
https://blog.csdn.net/fjnpysh/article/details/79077997
Close #15292

Input-Number: Fix precision problem (#15292)

---

packages/theme-chalk/src/input.scss

Input: fix clear icon is not centered.
Before:
After:

Input: fix clear icon is not centered

---

packages/table/src/table-header.js

As explained in #15010 this fixes the behavior of `sort-change` events on Tables.
Is expected to a handler of this particular event to track all the changes of the sorting condition to a column.
See the issue for more details.

Table: Fix sort-change behaviour when sort condition is null (#15010)

---

examples/docs/en-US/progress.md
examples/docs/es/progress.md
examples/docs/zh-CN/progress.md
packages/progress/src/progress.vue
test/unit/specs/progress.spec.js
types/progress.d.ts

Reverts ElemeFE/element#13198
Because `status` and `text` has no relation, we will find another approach to show text.

Progress: revert adding text status

---

packages/image/src/main.vue
test/unit/specs/image.spec.js

原有的 [`Image`](https://element.eleme.cn/#/zh-CN/component/image) 组件不支持 `attrs` 与 事件传递，无法满足特定场景需求，举例来说：
1. 无法监听click事件
1. 无法传递 [`crossorigin`](https://devdocs.io/html/cors_enabled_image) 参数，图像无法在canvas复用
所以提交PR，谢谢。

Image: add support for transmit "attrs" and "listeners"

---

packages/theme-chalk/src/input.scss

**when el-form being set size attribute like medium\etc. and then the style of el-input's show-word-limit is sad.**
repair:

Input: fix show-word-count style in el-form

---

components.json
examples/docs/en-US/backtop.md
examples/docs/es/backtop.md
examples/docs/fr-FR/backtop.md
examples/docs/zh-CN/backtop.md
examples/nav.config.json
examples/pages/template/component.tpl
packages/backtop/index.js
packages/backtop/src/main.vue
packages/theme-chalk/src/backtop.scss
packages/theme-chalk/src/common/var.scss
packages/theme-chalk/src/index.scss
src/index.js
test/unit/specs/backtop.spec.js
types/backtop.d.ts
types/element-ui.d.ts

Backtop: Add backtop component

---

examples/docs/en-US/progress.md
examples/docs/es/progress.md
examples/docs/fr-FR/progress.md
examples/docs/zh-CN/progress.md
packages/progress/src/progress.vue
packages/theme-chalk/src/progress.scss
test/unit/specs/progress.spec.js
types/progress.d.ts

- add dashboard progress bar
- add `format` attribute
- `color` supports pass `function` or `array`
- closes #11769

Progress: add dashboard progress bar

---

examples/docs/en-US/message.md
examples/docs/es/message.md
examples/docs/fr-FR/message.md
examples/docs/zh-CN/message.md
packages/message/src/main.js
packages/message/src/main.vue
packages/theme-chalk/src/message.scss

Message: display in stack mode

---

examples/docs/en-US/date-picker.md
examples/docs/es/date-picker.md
examples/docs/fr-FR/date-picker.md
examples/docs/zh-CN/date-picker.md
src/utils/date.js
test/unit/specs/date-picker.spec.js

DatePicker:  Support literal strings

---

build/bin/version.js
build/deploy-ci.sh
build/deploy-faas.sh

Chore: update build script

---

types/element-ui.d.ts

Chore: add missing import in element-ui.d.ts

---

packages/theme-chalk/src/table.scss

The normal table sets background color of hovered row by pseudo-class `:hover`, and the complex one sets by adding class `hover-row`. However, the background color of the hovered row of normal table and complex table is different.
Before(Please see the second row of normal table and the third row of complex table): 
After(Please see the second row of normal table and the third row of complex table):

Table: fix background color of hovered rows in complex table

---

packages/menu/src/submenu.vue

To Fixed https://github.com/ElemeFE/element/issues/13005
Relate problem https://github.com/PanJiaChen/vue-element-admin/issues/2004
The cause of the problem: When the `popper-append-to-body` property is added, `mouseLeave` event will only close the current submenu, and its parent menu will not be closed.

Menu: fixed submenu hidden bug after adding popper-append-to-body

---

packages/tree/src/model/node.js
src/utils/util.js
test/unit/specs/tree.spec.js

Fix issue [#15538](https://github.com/ElemeFE/element/issues/15538).
原来逻辑只是判断数组对象有没有 `NODE_KEY` 属性，如果一个对象已经被第一颗树渲染过，在第二颗树的判断中就被认为已经存在，导致出现 #15538 的bug。
PR 中修改了数组项判断的逻辑，判断数组项是否在 `oldData` 数组中。

Tree: fix #15538 by adding more detect logic.

---

src/locale/lang/uz-UZ.js

Added Uzbek language

---

examples/docs/en-US/button.md
examples/docs/es/button.md
examples/docs/fr-FR/button.md
examples/docs/zh-CN/button.md
packages/theme-chalk/src/button.scss
packages/theme-chalk/src/common/var.scss

- relate: #14850 #15644 
- I'm not sure what word is best to say "compact" in Chinese. I picked "極小" so far.

Button: add compact size

---

packages/dialog/src/component.vue

Dialog: Fix close bug (#15000)

---

components.json
examples/components/theme/components-preview.vue
examples/demo-styles/avatar.scss
examples/demo-styles/index.scss
examples/docs/en-US/avatar.md
examples/docs/es/avatar.md
examples/docs/fr-FR/avatar.md
examples/docs/zh-CN/avatar.md
examples/nav.config.json
examples/play/index.vue
packages/avatar/index.js
packages/avatar/src/main.vue
packages/theme-chalk/src/avatar.scss
packages/theme-chalk/src/common/var.scss
packages/theme-chalk/src/index.scss
src/index.js
test/unit/specs/avatar.spec.js
types/avatar.d.ts
types/element-ui.d.ts

Avatar: Add avatar component

---

examples/docs/en-US/alert.md
examples/docs/es/alert.md
examples/docs/fr-FR/alert.md
examples/docs/zh-CN/alert.md

Was:
`<el-alert description="content" /> // content`
`<el-alert>content</el-alert> // content`
`<el-alert description="content props">content slots</el-alert> // -`
Now:
`<el-alert description="content" /> // content`
`<el-alert>content</el-alert> // content`
`<el-alert description="content props">content slots</el-alert> // content slots`
+removed extra v-if

Docs: add missing description to Alert component

---

CHANGELOG.en-US.md
CHANGELOG.es.md
CHANGELOG.fr-FR.md
CHANGELOG.zh-CN.md
examples/docs/fr-FR/form.md

Docs: Add 2.10.1 change log

---

src/locale/lang/uz-UZ.js

corrected translations of Uzbek language

---

examples/docs/zh-CN/table.md

Docs: fix typo in table documents

---

types/element-ui.d.ts
types/tree.d.ts

现在有一个场景, 就是当我需要写
```typescript
import { Tree } from 'element-ui';
/**/
(this.$refs.tree as Tree).getCheckedNodes().map(node => {
// 对 node 操作
console.log(node.somethingElse); // 这里会报 node 类型里不存在 somethingElse 属性的错误
});
```
根据 `Tree.getCheckedNodes` 的函数签名
```typescript
getCheckedNodes(leafOnly?: boolean, includeHalfChecked?: boolean): D[];
```
上文的的 `node` 是由 ElTree 的默认泛类型 `TreeData` 
```typescript
interface TreeData {
id?: any;
label?: string;
disabled?: boolean;
isLeaf?: boolean;
children?: TreeData[];
}
```
而在实际的需求中, `TreeData` 的结构往往不一定和默认定义的一直, 这样就会导致一个问题, 如果要跳过这个地方就需要强行使用 `node as any` 来把 node 转换成一个任意类型, 失去了本来的意义.
此处的改动就是将 `element-ui.d.ts` 暴露出去的 `Tree` 类型从普通的类型定义改为了泛类型定义, Tree 类型可以接受两个类型参数 `<K, D extends TreeData>`, 用来修饰这两个类型, 从而使得上面的代码可以用这种写法
```typescript
import { Tree } from …
```

Tree 组件的类型定义为泛类型

---

packages/theme-chalk/src/dropdown.scss

Before fix, the caret of split-button dropdown default type is white background, and the caret is invisible.
After fix, I add a `mix($--button-default-border-color, transparent, 50%)`  (`rgba(220, 223, 230, 0.5)`)  background to default type split-button dropdown, so that the caret is obvious and match the whole style.  
修复前，default类型的分离按钮样式 dropdown 看不到分隔符，因为其颜色是和背景近似的半透明白色。
修复后，给上述类型的 dropdown 分隔符添加了和整体风格一致的 `mix($--button-default-border-color, transparent, 50%)` 颜色，以便于能看到这个分隔符。
CodePen Demo: 
https://codepen.io/JuniorTour/pen/RmqYLy?editors=1100#0

Dropdown: fix split-button caret default color

---

packages/menu/src/submenu.vue

Issue
----
#16289 #16329
Description
---
1. `append-to-body` prop will append dom in body that they will lose relationship between parent and child event. So it should fix this relationship not just clear `openedMenus` when leave in child. 
2. `submenu` component leave have two situation, one is leave to `transition` component, it should emit parent `submenu` leave event to clear the `openedMenus`, other is leave to title warp component that just need to leave itself.
Description-CN
---
1.  `append-to-body`属性会让`dom`从`document.body`创建，意味此属性的多个`submenu`的事件（`mouseleave`和`mouseenter`）触发不存在父子关系。因此需要在`append-to-body`的时候修复这种关系而不能直接清空。
2.  `mouseleave`事件修复存在两种清空，一种是离开右侧弹出内容的部分，这部分需要触发父级的`mouseleave`事件递归清空。一种是离开title所包裹的 …

Submenu: fix prop append-to-body . #16289

---

packages/table/src/store/tree.js

Table: Fix tree table when updating data

---

examples/components/header.vue
examples/components/theme/loader/api.js

Chore: Update inner network check

---

components.json
examples/demo-styles/drawer.scss
examples/demo-styles/index.scss
examples/docs/en-US/drawer.md
examples/docs/es/drawer.md
examples/docs/fr-FR/drawer.md
examples/docs/zh-CN/drawer.md
examples/nav.config.json
packages/drawer/index.js
packages/drawer/src/main.vue
packages/theme-chalk/src/drawer.scss
packages/theme-chalk/src/index.scss
src/index.js
test/unit/specs/drawer.spec.js
types/drawer.d.ts
types/element-ui.d.ts

有些时候, `Dialog` 可以提供的操作空间非常有限, 虽然说有全屏模式, 但是有时候需要的是一种并非全屏模式的模式, `Drawer` 组件就很好的补充了这一点, 并且许多 UI 库也都有这个一个组件.
https://ant.design/components/drawer-cn/
https://material-ui.com/api/drawer/
- 一个全新的扩展组件, 拥有和 Dialog 几乎一致的 API 和交互模式, 可以使得用户的交互更加丰富.
- 对应的 Demo
- 对应的 单元测试
- 对应的 使用文档
- 对应的类型定义

Drawer: Add drawer component

---

packages/cascader-panel/src/store.js

Cascader: fix display errors

---

examples/docs/en-US/cascader.md
examples/docs/es/cascader.md
examples/docs/fr-FR/cascader.md
examples/docs/zh-CN/cascader.md
packages/cascader-panel/src/cascader-panel.vue
packages/cascader/src/cascader.vue

Cascader: expose getCheckedNodes and fix options change bug

---

CHANGELOG.en-US.md
CHANGELOG.es.md
CHANGELOG.fr-FR.md
CHANGELOG.zh-CN.md

Docs: fix changelog

---

packages/theme-chalk/src/common/var.scss
packages/theme-chalk/src/icon.scss

Currently, I'm working on optimizing our website to boost its performance
By running Chrome Lighthouse audits, the results warn me about this web font not having a [`font-display`](https://developers.google.com/web/updates/2016/02/font-display) property set
I've solved this problem by declaring the font face with the new property added
I think it can be useful to add this declaration to improve performance of the webfont loading and rendering
Reference:
https://github.com/FortAwesome/Font-Awesome/issues/14387#issuecomment-454062536
https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_variables.scss#L6
https://github.com/FortAwesome/Font-Awesome/blob/master/scss/solid.scss#L11

Icon: Adding font-display to @font-face declaration

---

examples/docs/en-US/date-picker.md
examples/docs/en-US/datetime-picker.md
examples/docs/es/date-picker.md
examples/docs/es/datetime-picker.md
examples/docs/fr-FR/date-picker.md
examples/docs/fr-FR/datetime-picker.md
examples/docs/zh-CN/date-picker.md
examples/docs/zh-CN/datetime-picker.md
packages/date-picker/src/basic/date-table.vue
packages/date-picker/src/panel/date-range.vue
packages/date-picker/src/panel/date.vue
test/unit/specs/date-picker.spec.js

Date-Picker: add className picker option

---

.github/CONTRIBUTING.en-US.md
.github/CONTRIBUTING.es.md
.github/CONTRIBUTING.fr-FR.md
.github/CONTRIBUTING.zh-CN.md

docs: Update contributing guide

---

examples/docs/en-US/drawer.md
examples/docs/es/drawer.md
examples/docs/fr-FR/drawer.md
examples/docs/zh-CN/drawer.md

[doc]change Direction Acceptable Values "tbb" --> "btt"

---

packages/calendar/src/date-table.vue

Moved variable `WEEK_DAYS` declaration in `root` to `data()`.
In root declaration, `getI18nSettings()` couldn't get changed i18n settings.

Calendar : Fix weekdays i18n issue

---

examples/docs/en-US/popover.md
examples/docs/es/popover.md
examples/docs/fr-FR/popover.md
examples/docs/zh-CN/popover.md
packages/popover/src/main.vue
test/unit/specs/popover.spec.js
types/popover.d.ts

Makes it possible to turn off the delay before an `<el-popover>` starts to fade out.
The previous PR has a good description & demo, but was closed: https://github.com/ElemeFE/element/pull/13398
The differences to the previous PR are that I added the code path for `this.closeDelay == 0` that skips the `setTimeout`, updated docs and added a test.

Popover: add close-delay prop

---

packages/input/src/input.vue

fix: #11665 
There is a code to handle Korean inputs in [select.vue](https://github.com/ElemeFE/element/blob/bc407e57c43ef51fa4b01411e42fcf96a146c32a/packages/select/src/select.vue#L443), but it was missing in input.vue. 
- before this commit (tested with IE11, windows 10)
I typed '안녕하세요' (in qwerty, 'dkssudgktpdy')
- after this commit (tested with IE11, windows 10)
```
<template>
<div>
<el-input v-model="input"></el-input>
<div v-for="log in logs">
{{ log }}
</div>
</div>
</template>
<script>
export default {
data() {
return {
input: '',
logs: []
};
},
watch: {
input (newValue, oldValue) {
this.logs.push(newValue)
}
},
};
</script>
```

Input: Fix Korean composition event

---

packages/table/src/table.vue
packages/theme-chalk/src/table.scss
test/unit/specs/table.spec.js

Table: fix wrong empty block height

---

packages/checkbox/src/checkbox.vue

Checkbox labels are not read aloud by the popular NVDA screen reader. Rather than applying `aria-hidden` to the native checkbox elements it would be better to follow the [first rule of ARIA use](https://www.w3.org/TR/using-aria/#rule1) and rely on the native element. Simply removing all the aria attributes results in a much better experience. 
This PR does attempt to preserve the aria attributes for checkboxes in the indeterminate state, but it seems an `id` may be necessary to get that working. In other words, indeterminate checkboxes are no better or worse off with this PR.
Two videos show the screen reader experience [before](https://www.loom.com/share/294b09685e9a498380ba1bdbfdd14b5a) and [after](https://www.loom.com/share/346bc75bfc70428da2a785ae053b0900) this update.

Checkbox: Improve screen reader experience

---

packages/table/src/table-layout.js

Table: fix chrome crash when set thead css display to none issue (#16427)

---

packages/table/src/store/index.js
test/unit/specs/table.spec.js

Close #17110
Ref #14625
Ref #15709
This pr #14625 fixed the bug, but it missed in code refactor by pr #15709.

Table : fix trigger sort-change when mounted

---

packages/table/src/store/current.js
packages/table/src/store/index.js
test/unit/specs/table.spec.js

- closes #16767
- closes #16779
- related pr #16776

Table: fix setCurrentRow unable to clear highlight row

---

packages/table/src/store/tree.js

Table: fix expand-row-keys not work when data is loaded asynchronously

---

packages/date-picker/src/panel/date-range.vue

close #17191
当时间范围选择时，只选择最小时间，关闭弹窗，再打开选择弹窗时，第一次点击无法触发选中的问题。
修正为：能够正常触发选中。

DatePicker: fix bug of only select min date of date range problem (#17191)

---

packages/backtop/src/main.vue

Use `requestAnimationFrame`(more smoothly) and cubic bezier(acceleration until halfway, then deceleration) for scrolling.
**DEMO**
After: <https://jsfiddle.net/lon/ye1fq9u8/>
Before: <https://jsfiddle.net/lon/8p5q974z/>

BackTop: use requestAnimationFrame and cubic bezier for scrolling

---

examples/docs/es/drawer.md

The fix in #16848 is overwritten by #16961. This PR is to fix the documentation typo for Spanish version again.

Docs: fix Drawer attribute accepted value typo in es

---

packages/theme-chalk/src/tree.scss

If a Tree control has no data, a empty-text, e.g. "No Data", will be shown. But its font-size is 16px which is by default. It should be 14px, just like empty-text for Table control.

Tree: font-size for empty-text is 16px, it should be 14px

---

packages/table/src/table-column.js

Table: column header can be costumed

---

packages/date-picker/src/basic/time-spinner.vue

After scrolling up or down in the time picker's text box, the selected text is lost and the cursor goes to the end of the input (though scrolling continues to work). This fixes the problem by calling `emitSelectRange` at the end of the `scrollDown` method.
`this.$nextTick(() => this.emitSelectRange(this.currentScrollbar));`
Fixes #16866 - [Bug Report] Time picker doesn't visually select the part being edited via directional keys

TimePicker: Set the selection range after scrolling up or down

---

types/form.d.ts

Fix: https://github.com/ElemeFE/element/issues/8756
Currently we must pass undefined ( but null ) as callback function to avoid this issue, which is ugly.

Form: callback of validateField should be optional

---

types/cascader.d.ts

Fix error: 导入声明与“CascaderOption”的局部声明冲突

Cascader: fix TypeScript 3.7 compatibility

---

packages/infinite-scroll/src/main.js
test/unit/specs/infiniteScroll.spec.js

InfiniteScroll: Skip trigger event on invisible element

---

packages/image/src/image-viewer.vue
packages/image/src/main.vue

close #16796 
el-image 的 preview 在使用方向键↑↓进行缩放时，屏蔽页面的滚动。

Image: Fix shield the page when preview big image (#16796)

---

packages/table/src/layout-observer.js
packages/table/src/table-layout.js
packages/table/src/table.vue

Table: fix header gutter not display

---

examples/docs/en-US/select.md
examples/docs/es/select.md
examples/docs/fr-FR/select.md
examples/docs/zh-CN/select.md
packages/select/src/option.vue

close #17199 #16845
解决 multiple 模式下，被选中的 option 组件 destroy 时清除缓存，导致 tag 展示不正确的问题。

Select: Fix tag show value or empty issue (17199)

---

examples/docs/en-US/input.md
examples/docs/es/input.md
examples/docs/fr-FR/input.md
examples/docs/zh-CN/input.md

update input doc, add input event
the issue is #7592

docs:  add input event in input Events Table

---

packages/theme-chalk/src/transfer.scss

Issue #17835 mentioned this bug.

Transfer: fix incorrect line-height of el-transfer's first list item when it was used with  el-form-item

---

packages/input-number/src/input-number.vue

`input-number.vue` incorrectly calculates `inputNumberDisabled` when the prop `disabled` is set to false as well as `elForm` not existing. `inputNumberDisabled` returns `"undefined"` instead of `false` which is treated as a truthy value on `aria-disabled`.
No issue has been created, I just noticed the issue while debugging some of my own code. Will create and link issue if that is expected.
Fixed #18440

[Input Number] Correctly compute inputNumberDisabled when false

---

examples/docs/en-US/input.md
examples/docs/es/input.md
examples/docs/fr-FR/input.md
examples/docs/zh-CN/input.md
packages/autocomplete/src/autocomplete.vue

为 Autocomplete 添加 change 事件
add change event for Autocomplete

Autocomplete: add change event

---

packages/autocomplete/src/autocomplete-suggestions.vue

fix issue [#15013](https://github.com/ElemeFE/element/issues/15013)
Before the fix:
After the fix:

Autocomplete:  fix autocomplete-suggestions issue when type is `textarea`(#15013)

---

packages/image/src/main.vue

修复问题：Image 不需要预览效果，没有previewSrcList的时候，点击一下会触发clickHandler事件，导致body被加上overflow = 'hidden'样式。

Image: don't show image-viewer when preview is false

---

src/locale/lang/ru-RU.js

Updated missing translations of popconfirm.cancelButtonText and popconfirm.cancelButtonText

locale: Fix the translation ru-RU popconfirm

---

src/locale/lang/pt-br.js

A simple fix to translate the popconfirm button's text to Brazilian Portuguese.

[Popconfirm] Fix button's text translation

---

examples/docs/en-US/calendar.md

This simple change just fixes some Chinese text in English docs and corrects some phrasing.

Calendar: Correct some text in the English docs

---

src/locale/lang/ru-RU.js

Translated missing translations in "pageHeader.header" and "image.error".
Fixed translation in "upload.preview", because a "preview" is a anglicism, in russian correct to say "предпросмотр".

Update Russian locale (ru-RU.js) 

---

src/locale/lang/ua.js

Translated missing translations in "colorpicker.confirm", "image.error",  "pageHeader. title", "popconfirm. confirmButtonText" and "popconfirm. cancelButtonText"
Fixed translation in "colorpicker.confirm", because a "OK" is a anglicism, in ukrainian correct to say "Обрати".

fix: Update Ukrainian locale (ua.js)

---

packages/select/src/select.vue

如 #17527 所描述，el-select在vue-i18n@5.x下 placeholder 不会更改。
vue-i18n更改语言后会调用`vm.$forceUpdate`，而这不会重新计算 props 中的 default 值，因此改为使用计算属性来显示正确的 placeholder。

Select: fix i18n bug of placeholder

---

examples/docs/en-US/progress.md
examples/docs/es/progress.md
examples/docs/fr-FR/progress.md
examples/docs/zh-CN/progress.md

Docs: add format attribute description to the progress component

---

packages/image/src/image-viewer.vue

Image: fix z-index and keydown event add stopPropagation

---

CHANGELOG.en-US.md
CHANGELOG.es.md
CHANGELOG.fr-FR.md
CHANGELOG.zh-CN.md

feat: add change log

---

examples/docs/en-US/form.md
examples/docs/zh-CN/form.md

Docs: fix form hide-required-asterisk description

---

src/utils/dom.js

In IE browser, If the reference element(slot="reference") under the popover component is a SVG element, an error will be reported.
[#21048](https://github.com/ElemeFE/element/issues/21048)

fix(utils.dom): fix utils.dom error

---

src/utils/dom.js

`overlay` behaves the same as `auto`, but now `isScroll` method can't match the scroll wrap with `overlay`.

Utils: fix isScroll

---

packages/radio/src/radio-group.vue

Use `<component :id="'el-radio-group'">` causes exception. fix #17908
```vue
<template>  
<component
:is="tag"
>
</component>
</template>
<script>
export default {
data() {
return {
tag: 'el-radio-group'
}
}
}
</script>
```
```bash
[Vue warn]: Unknown custom element: <component> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in
---> <ElRadioGroup> at packages/radio/src/radio-group.vue
```

fix(RadioGroup): used in component causes exception #17908

---

packages/cascader-panel/src/cascader-panel.vue
packages/cascader-panel/src/store.js
packages/cascader/src/cascader.vue

Cascader: fix emitPath

---

packages/select/src/select.vue

标题：
修复select组件在filterable属性下，使用win10微软中文输入法输入时不触发检索的问题；
问题原因：
chrome环境下win10微软中文输入法使用数字键选择输入字符后，未触发@keyup.native事件；
解决方法：
使用@input代替@keyup.native触发debouncedOnInputChange函数；
ps：
该问题在multiple与filterable属性同时出现时不存在
原因也是因为当属性为multiple时，现有代码使用的@input触发检索而非@keyup.native
* [✔] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [✔] Make sure you are merging your commits …

[select]修复select组件在filterable属性下，使用win10微软中文输入法输入时不触发检索的问题

---

CHANGELOG.en-US.md
CHANGELOG.es.md
CHANGELOG.fr-FR.md
CHANGELOG.zh-CN.md

feat: add changelog

---

examples/docs/en-US/dropdown.md
examples/docs/es/dropdown.md
examples/docs/fr-FR/dropdown.md
examples/docs/zh-CN/dropdown.md
packages/dropdown/src/dropdown.vue
packages/theme-chalk/src/button.scss
packages/theme-chalk/src/dropdown.scss
test/unit/specs/dropdown.spec.js
types/dropdown.d.ts

This PR proposes adding `disabled` property to the `el-dropdown`.
Around this, an issue #11823 was requested previously and a PR #11843 was sent, but they were closed without being merged. However there are still some people who say they need this feature. So, I'm requesting this PR again.
---

Dropdown: Add a 'disabled' property to the el-dropdown

---

packages/select/src/select.vue

fix issue #21117 
when filtering is turned on, clicking icon cannot trigger dropdown

Select: fix #21117 click icon triggering dropdown

---

packages/table/src/config.js
packages/table/src/store/index.js
packages/table/src/table-body.js
packages/table/src/table-layout.js
packages/table/src/table-row.js
packages/table/src/table.vue

Both the left fixed table and the right fixed table render full columns from the DOM. Change to render only the required columns.

Table: optimize performance

---

CHANGELOG.en-US.md
CHANGELOG.es.md
CHANGELOG.fr-FR.md
CHANGELOG.zh-CN.md

chore: add changelog

---

examples/docs/en-US/input.md
examples/docs/es/input.md
examples/docs/fr-FR/input.md
examples/docs/zh-CN/input.md

* [ x Add some descriptions and refer relative issues for you PR.
fix the typo about input's size, it not support `large`, and should be `medium`

Docs: update input typo about size attribute

---

examples/docs/en-US/installation.md
examples/docs/es/installation.md
examples/docs/fr-FR/installation.md
examples/docs/zh-CN/installation.md
packages/table/src/table.vue

fix: codepen vue version

---

examples/docs/zh-CN/popover.md

docs: Update popover.md

---

packages/cascader/src/cascader.vue
packages/date-picker/src/picker.vue

Fix: #21802
fix the dropdown animation direction of cascader and datepicker
**before**
**fixed**

fix (DatePicker & Cascader): fix the dropdown animation direction of cascader and datepicker

---

packages/cascader-panel/src/cascader-panel.vue

Scenes:
"cascader" changes depending on the change of a certain A field. After returning, change the A field, clear the "value" of "cascader" and the "options" of "cascader", and initiate an interface request at the same time, get data A after the request, and put the data A is assigned to "cascader options", and an error occurs
problem causes:
The watch queue of the cascader-panel file is ["options", "value"]. When the value is cleared and the options are cleared, the execution order is the options monitoring event, and then the value monitoring event. The function call chain in the options monitoring event is as follows,
Function call chain:
options(handler) > initStore > syncMenuState > syncActivePath > …

fix: “cascader” repair unexpected error

---

packages/theme-chalk/src/common/var.scss

remove unused scss variable & wrong comment
`$--input-width` is never used, and the comment is irrelevant.

[Input]: remove unused scss variable

---

packages/table/src/table-row.js

Table:fix el-checkbox not imported issue(#21796,#20625)

---

packages/date-picker/src/picker.vue

!!! This error is on the current production version 2.15.9 , please quick fix
fix this error
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "placement"
found in
---> <ElDatePicker> at packages/date-picker/src/picker.vue
```
because this PR https://github.com/ElemeFE/element/pull/21806  add props `placement` to erroneously changed "placement" `data` -> `props`
detail in issues https://github.com/ElemeFE/element/issues/21905

 date-picker: fix  modify props "placement" error

---

examples/docs/en-US/popover.md
examples/docs/es/popover.md
examples/docs/fr-FR/popover.md
examples/docs/zh-CN/popover.md

docs: Update all versions of popover.md.

---

examples/docs/en-US/date-picker.md
examples/docs/es/date-picker.md
examples/docs/zh-CN/date-picker.md
packages/date-picker/src/basic/month-table.vue
packages/date-picker/src/basic/year-table.vue
packages/date-picker/src/panel/date.vue
packages/date-picker/src/picker.vue

DatePicker: add months And years type

DatePicker: add months And years type

---

examples/docs/en-US/date-picker.md
examples/docs/es/date-picker.md
examples/docs/fr-FR/date-picker.md
examples/docs/zh-CN/date-picker.md

#20402 
DatePicker组件在model中使用时，高度不够会出现闪退，有时会出现不跟随滚动，通过配置append-to-body:false属性，即可解决该问题，DatePicker组件内部实际是支持append-to-body传参的，但是文档上面没有。

DatePicker:文档补充append-to-body字段

---

packages/tree/src/model/node.js

[issue(#21932)](https://github.com/ElemeFE/element/issues/21932)
由于懒加载后doCreateChildren函数使用foreach的方式新增child，每次新增一个child都会执行reInitChecked函数对父节点的选中状态重置。所已第一个child选中后，第二个节点在选中时reInitChecked认为所有子节点（本来有n>2个子节点，只是foreach刚创建2个而已）都选中了，然后导致后面所有新增的child都会因为父节点已选中而被设置为选中。
将节点的loading状态放到doCreateChildren函数完成之后并在reInitChecked计算父节点选中状态时对loading中的节点不处理。等loading完成后由回调函数重新计算父节点的选中状态。

Tree:fix Tree懒加载默认选中问题 issue(#21932)

---

src/locale/lang/nb-NO.js

Finishes the last norwegian translations

Finish norwegian translations

---

package.json
web-types.json

This contribution is to heavily improve coding experience in JetBrains IDEs (e.g. WebStorm). It contains information about components (props, events, slots) and directives. Each element is documented with a link to the documentation. With this file included, you get following experience:

Add Web Types to improve code assistance in WebStorm IDE and other JetBrains IDEs

---

packages/progress/src/progress.vue
packages/select/src/option.vue

fix: issues #22065, el-progress添加底色，文字颜色的属性

---

examples/docs/zh-CN/statistic.md
packages/statistic/src/main.vue
packages/theme-chalk/src/statistic.scss

statistic:Optimize each item

---

examples/docs/en-US/image.md
examples/docs/es/image.md
examples/docs/fr-FR/image.md
examples/docs/zh-CN/image.md
packages/image/src/image-viewer.vue
packages/image/src/main.vue
types/image.d.ts

custom image preview image index
close #21657
close #20026

Image: add initialIndex prop

---

web-types.json

type属性少了个引号，会导致webstorm无法识别type="text"的情况

Button: fix web-types type props

---

examples/docs/en-US/statistic.md
examples/docs/es/statistic.md
examples/docs/fr-FR/statistic.md
examples/docs/zh-CN/statistic.md

docs:[Statistic] 修复案例代码缩进；修复外语文档第二个案例中stop变量未声明bug；去除案例代码中未使用的变量和类选择器

---

examples/docs/en-US/table.md
examples/docs/es/table.md
examples/docs/fr-FR/table.md
examples/docs/zh-CN/table.md
packages/table/src/table-body.js
packages/table/src/table.vue
packages/table/src/util.js
packages/theme-chalk/src/table.scss
types/table.d.ts

对应issues：https://github.com/ElemeFE/element/issues/22342
对应demo：https://ui.const.team/#/component/table#duo-xuan

Table: table add highlight selection row

---

examples/docs/en-US/statistic.md
examples/docs/es/statistic.md
examples/docs/fr-FR/statistic.md
examples/docs/zh-CN/statistic.md
examples/nav.config.json
packages/statistic/src/main.vue

[statistic] :fix doc; Optimized  code;
