ElemeFE/element

packages/theme-default/src/date-picker.css, packages/theme-default/src/time-picker.css
=> DatePicker: add missing styles

packages/steps/src/step.vue, packages/steps/src/steps.vue
=> Steps: dynamic update step, fixed #2512

examples/docs/en-US/steps.md, examples/docs/zh-CN/steps.md, packages/steps/src/step.vue, packages/steps/src/steps.vue
=> Steps: space prop support percentage

src/locale/lang/fi.js
Added a Finnish translation into locale.
=> Add Finnish translation

examples/docs/en-US/dialog.md, examples/docs/zh-CN/dialog.md, packages/dialog/src/component.vue, src/utils/popup/index.js
=> Dialog: add modalAppendToBody

examples/app.vue, examples/pages/template/index.tpl, packages/theme-default/src/reset.css
加了个 css helper， 使用的话就是
```css
@import 'element-ui/lib/theme-default/reset.css'
```
@reverland 看下需要啥
=> Add reset.css into theme-deafult

packages/date-picker/src/util/index.js
=> DatePicker: fix toDate, fixed #2538

packages/select/src/select.vue
=> Select: fix incorrect popper updating when filterable

examples/docs/en-US/date-picker.md, examples/docs/en-US/datetime-picker.md, examples/docs/zh-CN/date-picker.md, examples/docs/zh-CN/datetime-picker.md, packages/date-picker/src/picker.vue
=> DatePicker: add range-separator prop, close #2568

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, examples/app.vue
=> Changelog: update for 1.1.6

src/locale/lang/sv-SE.js
Added Swedish language translations.
=> Added Swedish

packages/select/src/select.vue
Trigger 'query-change' event to the ElOptionGroup
=> Fix #2596 filterable group select

examples/docs/en-US/tag.md, examples/docs/zh-CN/tag.md
=> Tag: fix a doc issue, fixed #2611

examples/docs/en-US/dialog.md, examples/docs/zh-CN/dialog.md
=> Dialog: unify api format

src/locale/lang/el.js
Added Greek language translations.
=>  Added Greek

packages/form/src/form-item.vue
=> form-item: fix the validateState issue.

examples/docs/en-US/menu.md, packages/menu/src/menu-item.vue, test/unit/specs/menu.spec.js
=> Click event #2551

packages/theme-default/src/common/var.css
=> Theme: paramaterize missing colors for Tag

packages/table/src/table-store.js
=> Table: fix data is an array of numbers, fixed #2108

packages/theme-default/src/slider.css
=> Slider: restore destroyed styles

packages/scrollbar/src/main.js, packages/select/src/select.vue
=> Scrollbar: return if component gets destroyed in mounted hook

packages/theme-default/src/radio.css
=> fix radio-button active style(fix #2656)

packages/theme-default/src/collapse.css
=> fix collapse nest style(fix #2649)

examples/docs/en-US/dialog.md, examples/docs/zh-CN/dialog.md, packages/dialog/src/component.vue
=> Dialog: add title slot

examples/docs/en-US/tag.md, examples/docs/zh-CN/tag.md
=> tags docs improve

packages/carousel/src/item.vue, packages/theme-default/src/carousel-item.css, packages/theme-default/src/carousel.css
=> Carousel: apply infinite sliding in non-card mode

packages/tooltip/src/main.js, test/unit/specs/tooltip.spec.js
=> Tooltip: prevent hidding when hovering tooltip, close #2633

examples/docs/en-US/table.md
* [X ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [ X ] Make sure you are merging your commits to `dev` branch.
* [ X ] Add some descriptions and refer relative issues for you PR.
=> Example/table: fixed misspelling

packages/autocomplete/src/autocomplete.vue
=> AutoComplete: fix key enter, Fixed #2632

src/locale/lang/bg.js, src/locale/lang/da.js, src/locale/lang/de.js, src/locale/lang/es.js, src/locale/lang/fa.js, src/locale/lang/fr.js, src/locale/lang/id.js, src/locale/lang/it.js, src/locale/lang/ja.js, src/locale/lang/ko.js, src/locale/lang/nb-NO.js, src/locale/lang/nl.js, src/locale/lang/pl.js, src/locale/lang/pt-br.js, src/locale/lang/pt.js, src/locale/lang/ru-RU.js, src/locale/lang/th.js, src/locale/lang/tr-TR.js, src/locale/lang/vi.js, src/locale/lang/zh-TW.js
=> Locale: update cascader configs

packages/autocomplete/src/autocomplete.vue
=> fix autocomplete suggestions show(fix #2537)

packages/menu/src/menu-item-group.vue, packages/menu/src/menu-item.vue, packages/menu/src/menu-mixin.js, packages/menu/src/submenu.vue, packages/tabs/src/tab-pane.vue, packages/tabs/src/tabs.vue
=> normalize export syntax(fix #2677)

build/gen-single-config.js
=> fix eslint error in gen-single-config.js

examples/docs/en-US/input.md, examples/docs/zh-CN/input.md, packages/autocomplete/src/autocomplete-suggestions.vue, packages/autocomplete/src/autocomplete.vue, packages/theme-default/src/autocomplete.css, test/unit/specs/autocomplete.spec.js
=> autocomplete dropdown use el-scrollbar（#2676）

packages/badge/src/main.vue
=> Badege: hidden when no value, fixed #2733

packages/select/src/select.vue
=> Select: fix incorrect scrollTop on first popup

build/cooking.demo.js, examples/entry.js, package.json, yarn.lock
=> Docs: add offline plugin

build/cooking.demo.js, packages/date-picker/src/basic/date-table.vue
=> DatePicker: fix marks are displaced when type is range, fixed #2612

packages/theme-default/src/date-picker/date-table.css, packages/theme-default/src/date-picker/month-table.css, packages/theme-default/src/date-picker/year-table.css
=> Datepicker: fix incorrect disabled style and add today style

examples/docs/en-US/tag.md, examples/docs/zh-CN/tag.md
=> Tags: fix a doc style

packages/theme-default/src/form.css
=> [form] fix style when error

packages/input/src/calcTextareaHeight.js, packages/input/src/input.vue, test/unit/specs/input.spec.js
=> Input: fix invalid resize prop, Fixed #2836 

examples/docs/en-US/input.md, examples/docs/en-US/tree.md, examples/docs/zh-CN/input.md, examples/docs/zh-CN/tree.md, packages/theme-default/src/message-box.css, packages/tree/src/tree-node.vue, packages/tree/src/tree.vue
=> Tree: add indent, update docs

packages/table/src/table-header.js
=> Table: Fix wrong header with fixed right columns.

examples/docs/en-US/menu.md, examples/docs/zh-CN/menu.md, packages/menu/src/menu.vue
=> fix menu when not index active(#2600)

packages/autocomplete/src/autocomplete-suggestions.vue, packages/theme-default/src/autocomplete.css
=> fix autocomplete dropdown position(#2868)

examples/docs/en-US/slider.md, examples/docs/zh-CN/slider.md, packages/slider/src/button.vue, packages/slider/src/main.vue, test/unit/specs/slider.spec.js
=> Slider: add range support

examples/components/demo-block.vue, examples/docs/en-US/cascader.md, examples/docs/en-US/select.md, examples/docs/zh-CN/cascader.md, examples/entry.js, examples/nav.config.json, packages/cascader/src/main.vue, packages/cascader/src/menu.vue, packages/theme-default/src/cascader.css, src/locale/lang/pt.js, test/unit/specs/cascader.spec.js
主要做了三件小事：
- 根据 UED 意见修改 UI 和部分交互
- 新增 `props`、`show-all-level` 属性和 `active-item-change` 事件
- 更新文档
当然，还有一些比如搜索支持大小写模糊，这些都是小事了，主要还是上面三件。
很惭愧，做了一点围小的工作，谢谢大家。
=> Cascader: update

packages/table/package.json
=> table: fix the wrong repository field

src/locale/lang/th.js
=> change short date in thai locale

examples/components/header.vue
The header is not reactive because [`scrollTop` always return 0 in Firefox](http://stackoverflow.com/questions/28633221/document-body-scrolltop-firefox-returns-0-only-js), I fixed it.
=> fix the header is not reactive

examples/docs/en-US/upload.md, examples/docs/zh-CN/upload.md
1. 使用 Dialog 进行上传图片的预览
2. 增加文件列表的控制例子（#2241）
=> improve upload docs

packages/tabs/src/tabs.vue
=> fix tab insert index(#2646)

examples/docs/en-US/checkbox.md, examples/docs/zh-CN/checkbox.md
本来做了#2783，但是发现这个组件是有slot的，所以对文档说辞做了些修改。
意见：既然有`slot`组件值的属性名就没必要叫做label了，或许叫做value之类的更合适。改动过大，就不放在这个pr了。
=> Checkbox: fix confused document

packages/message/src/main.vue, packages/theme-default/src/message.css
=> Message: fix content not vertically aligned

packages/theme-default/src/tabs.css
=> fix tabs nav style

packages/theme-default/src/input.css
fixes https://github.com/ElementUI/theme-default/issues/9#issue-199611117
=> use '--input-border-radius' variable in input.css

packages/theme-default/src/upload.css
=> fix upload style

examples/docs/en-US/input.md, examples/docs/zh-CN/input.md, packages/input/src/input.vue
=> add input step prop

packages/theme-default/src/color-picker.css
=> improve svpanel style

packages/theme-default/src/upload.css
=> Upload: fix css

packages/color-picker/src/components/alpha-slider.vue, packages/color-picker/src/components/hue-slider.vue, packages/color-picker/src/components/picker-dropdown.vue, packages/color-picker/src/main.vue
=> ColorPicker: hide the dropdown when clicking on another colorpicker.

examples/index.tpl
=> Docs: fix vue-router version, fixed #2935, fixed #2116

packages/input-number/src/input-number.vue
=> fix input-number style problem

examples/docs/en-US/color-picker.md, examples/docs/zh-CN/color-picker.md, examples/nav.config.json, packages/color-picker/src/color.js, packages/color-picker/src/components/alpha-slider.vue, packages/color-picker/src/components/picker-dropdown.vue, packages/color-picker/src/components/sv-panel.vue, packages/color-picker/src/draggable.js, packages/color-picker/src/main.vue, packages/theme-default/src/color-picker.css
=> ColorPicker: update

examples/docs/en-US/message-box.md, examples/docs/zh-CN/message-box.md, packages/message-box/src/main.js, packages/message-box/src/main.vue
=> MessageBox: add inputValue

packages/scrollbar/src/main.js, packages/theme-default/src/date-picker/time-spinner.css
=> Scrollbar: fix style

examples/docs/en-US/checkbox.md, examples/docs/en-US/i18n.md, examples/docs/zh-CN/i18n.md, examples/docs/zh-CN/table.md, packages/theme-default/src/common/var.css, packages/theme-default/src/date-picker/time-picker.css, packages/tree/src/tree.vue
=> misc doc updates

packages/table/src/table-body.js
=> Table: Remove extra render in cells.

packages/input/src/input.vue, test/unit/specs/cascader.spec.js, test/unit/specs/input.spec.js
=> fix input change time

packages/date-picker/src/util/index.js, packages/theme-default/src/date-picker/time-spinner.css
=> DatePicker: fix time spinner style

examples/docs/en-US/upload.md, examples/docs/zh-CN/upload.md
=> fix docs upload action

examples/docs/zh-CN/checkbox.md
=> fix checkbox docs

packages/date-picker/src/panel/time.vue, packages/date-picker/src/util/index.js
=> DatePicker: fix time range

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, build/bin/version.js, examples/components/footer.vue, examples/pages/template/changelog.tpl, packages/theme-default/src/notification.css, packages/theme-default/src/select-dropdown.css
=> Changelog: update for 1.2.0

packages/color-picker/src/components/alpha-slider.vue, packages/color-picker/src/components/hue-slider.vue, packages/color-picker/src/components/picker-dropdown.vue, packages/color-picker/src/components/sv-panel.vue, packages/color-picker/src/main.vue
=> fix SSR regression

examples/docs/en-US/table.md, examples/docs/zh-CN/table.md, packages/table/src/table-body.js
=> Table: Add cell-dblclick.

packages/table/src/table.vue
=> Table: Fix wrong height when switch prop height.

packages/form/src/form-item.vue
=> fix inline form label width

examples/docs/en-US/table.md, examples/docs/zh-CN/table.md, packages/table/src/table-header.js
=> Table: Add header-dragend.

packages/cascader/src/main.vue
=> Cascader: fix menu popper update timing

packages/theme-default/src/tabs.css
=> fix tabs nav scrollable bug

examples/docs/en-US/upload.md, examples/docs/zh-CN/upload.md
=> Upload: add missing doc styles

packages/badge/src/main.vue
now element 2.2.1 Badge:isDot is not show
=> Badge: fix isDot not show

packages/select/src/select.vue
=> Select: fix an undefined bug

examples/docs/en-US/cascader.md, examples/docs/zh-CN/cascader.md, packages/color-picker/src/components/sv-panel.vue, packages/theme-default/src/color-picker.css, test/unit/specs/carousel.spec.js, test/unit/specs/color-picker.spec.js, test/unit/specs/menu.spec.js
=> improve tests

packages/cascader/src/main.vue, packages/cascader/src/menu.vue
=> Cascader: fix z-index not increasing issue

packages/table/src/table-body.js
@Leopoldthecoder @QingWei-Li  先放一个临时的修复一下吧，我再去想办法，，，
=> Table: Fix wrong fixed height temporary.

packages/cascader/src/menu.vue
修复当存在级数不同的选项时，`change` 事件的参数错误问题 #3006
=> Cascader: fix parameter in change event

packages/tooltip/src/main.js, src/utils/vdom.js
=> Tooltip: fix content slot, fixed #2999

packages/slider/src/button.vue, test/unit/specs/slider.spec.js
=> Slider:Prevent text selection on mouse drag

packages/form/src/form-item.vue, packages/theme-default/src/form.css
This reverts commit d76d28dd54f9f02222d5190182a3e6d8790bcbe6.
fix form inline label bug
#3012
=> fix form inline label bug

examples/docs/zh-CN/tabs.md
=> zh-CN docs [tabs]: v-model bind property name is not the same

examples/docs/en-US/color-picker.md, packages/color-picker/src/main.vue
Like the other input components I think the ColorPicker component should fire the change event too.
I've added the event for both confirmValue and clearValue methods.
=> ColorPicker: Fire change event

packages/scrollbar/src/main.js, packages/scrollbar/src/util.js, src/locale/format.js, src/utils/util.js, src/utils/vdom.js
=> support vue 2.2

src/utils/popup/index.js
参考 https://github.com/vuejs/vue/issues/5001
=> Popup: prepare for the upcoming change of Vue 2.2.0

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, build/deploy-ci.sh, examples/docs/en-US/tree.md, examples/docs/zh-CN/color-picker.md, examples/docs/zh-CN/custom-theme.md, examples/docs/zh-CN/tree.md
=> Changelog: update for 1.2.2

build/bin/gen-cssfile.js, packages/theme-default/src/index.css
=> remove redundant style files

examples/docs/en-US/table.md, examples/docs/zh-CN/table.md, packages/table/README.md
=> Table(doc): remove context prop

build/deploy-ci.sh, packages/tooltip/src/main.js
=> Tooltip: fix router-link, fixed #3042

packages/tooltip/src/main.js
=> Tooltip: fix bug in ssr, fixed #3050

packages/tooltip/src/main.js
=> Tooltip: fix vue-router, fixed #3166

packages/tooltip/src/main.js
=> Tooltip: fix bug in ssr, fixed #3152

packages/carousel/src/main.vue
=> Carousel: fix async item not refreshing view issue

examples/docs/en-US/upload.md, examples/docs/zh-CN/upload.md
=> Upload(doc): fix api

examples/docs/zh-CN/form.md
=> improve docs (#3217)

examples/docs/zh-CN/upload.md, examples/pages/template/design.tpl
=> update upload doc and design page template

packages/table/src/table-body.js, test/unit/specs/table.spec.js
=> Table: Add handleEvent.

packages/theme-default/src/tabs.css
=> fix nested tab style

packages/form/src/form-item.vue
not accurate use `if(value)` when resetField()
value could be `boolean`
=> form-item: fix #3226

packages/theme-default/src/select.css
=> fix select style problem(#3230)

packages/theme-default/src/form.css
=> fix inline form style bug(#3218)

packages/cascader/src/menu.vue
cascader:bug fix #3191. when menuIndex = 0 edge case
=> cascader:bug fix #3191. when menuIndex = 0 edge case

examples/pages/template/component.tpl, src/utils/date.js, src/utils/resize-event.js
=> Doc: add back-to-top icon in components page

packages/theme-default/src/cascader.css
=> Cascader: fix initial value not displaying when disabled

packages/theme-default/src/col.css
=> col-0 support(#3282)

examples/docs/en-US/upload.md, examples/docs/zh-CN/upload.md, packages/upload/src/index.vue, packages/upload/src/upload.vue
=> Revert "自定义ajax模块"

examples/docs/en-US/upload.md, examples/docs/zh-CN/upload.md, packages/table/src/table-header.js
=> update upload doc and add arrow click sorting for table

packages/date-picker/src/picker.vue
=> DatePicker: fix range-separator not working with more than one instances

examples/components/demo-block.vue
=> Should it be https?

packages/tooltip/src/main.js
=> Tooltip: fix ssr, fixed #3173

examples/docs/en-US/upload.md, examples/docs/zh-CN/upload.md, packages/upload/src/ajax.js, packages/upload/src/index.vue, packages/upload/src/upload.vue
=> add custom http requrest(#3359)

packages/slider/src/main.vue
=> Slider: fix incorrect initial value when min>0 and showInput is true

.github/ISSUE_TEMPLATE.md
=> Add eleme-issue.

packages/autocomplete/src/autocomplete-suggestions.vue
fix  [autocomplete] el-scrollbar not register ElemeFE/element#3021
=> fix  [autocomplete] el-scrollbar not register ElemeFE/element#3021

packages/theme-default/src/common/var.css
```css
--button-paddding: 5px 20px; /* useless */
```
=> Remove useless var `button-paddding`

packages/theme-default/src/radio.css
=> Radio: fix disabled style bug #3441

examples/docs/en-US/tooltip.md
=> Tooltip: Remove Chinese in English docs.

src/utils/popper.js
=> Table: Fixed shaking table.

packages/upload/src/index.vue
=> Upload: fix migrating message typo

packages/theme-default/src/col.css
=> Col: hide cols with xs/sm/md/lg assigned to 0

packages/tree/src/tree.vue
=> remove unused

src/locale/lang/ja.js
=> Improve Japanese translation

packages/table/src/table-layout.js, packages/table/src/table.vue
=> Table: Fixed wrong height.

packages/collapse/src/collapse.vue
=> Collapse: fix accordion panel name=0 closing issue

packages/message-box/src/main.js
=> Msgbox: fix second param not passed to callback

packages/dialog/src/component.vue, packages/theme-default/src/dialog.css
=> Dialog: remove unnecessary inline style

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
=> Changelog: update for 1.2.5

packages/upload/src/index.vue, packages/upload/src/upload.vue
=> fix file not remote when before-upload reject

examples/docs/en-US/upload.md, examples/docs/zh-CN/upload.md, packages/upload/src/upload.vue
=> fix upload docs typo bug

README.md
=> Docs: Fixed README.md

packages/slider/src/button.vue
Related to #3661: fixes the slider jumping to left when it's really big.
=> Slider: fix slider jumping left

examples/docs/en-US/rate.md, examples/docs/zh-CN/rate.md, packages/rate/src/main.vue
=> Rate(doc): fix text-color default value, fixed #3206

packages/theme-default/src/radio-button.css, packages/theme-default/src/radio-group.css, packages/theme-default/src/radio.css
=> RadioButton: move radio-button css to radio-button.css file, fixed #3276

packages/input-number/src/input-number.vue
- 在setInterval之前clearInterval，防止按住左键的情况下再按右键导致的timer未清除问题
参考 #3514
=> InputNumber: clearInterval before setInterval (#3514)

packages/theme-default/src/step.css
=> Steps: fix step last child style

packages/popover/src/main.vue
=> Popover: fix destroy the events, fixed #3555

build/cooking.demo.js, examples/app.vue, examples/docs/en-US/tooltip.md, examples/docs/zh-CN/tooltip.md, examples/pages/template/component.tpl
=> Tooltip(doc): add router-link description

packages/date-picker/src/panel/date.vue, packages/date-picker/src/picker.vue
=> DatePicker: fix format week, fixed #2774

src/locale/lang/pt-br.js, src/locale/lang/pt.js
=> update portuguese translation

examples/docs/en-US/select.md, examples/docs/zh-CN/select.md, packages/select/src/select.vue, test/unit/specs/select.spec.js
- 给 Select 增加 delete-tag 事件
- 补充了 Select 中英文文档
- 提供了单元测试
参考 #3632
=> Select: add delete-tag event

packages/table/src/table.vue
=> Table: Change debounce invoke atBegin.

packages/switch/src/component.vue
=> Switch: compatible with vue ssr, fixed #3752

packages/date-picker/src/panel/time-range.vue
=> TimePicker: fix time calculation error, fixed #3479

examples/docs/en-US/steps.md, examples/docs/zh-CN/steps.md, packages/steps/src/step.vue
=> Steps: add status prop, close #3722

examples/docs/zh-CN/form.md
=> form(doc): fix form docs typo

examples/docs/en-US/quickstart.md, examples/docs/zh-CN/quickstart.md
=> Docs(quickstart): add full example for on-demand

packages/select/src/select.vue
=> Select: exec removeResizeListener in beforeDestroy hook, fixed #3797

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
=> Changelog: update for 1.2.6

packages/scrollbar/src/main.js
=> Scrollbar: compatible with vue 2.2.6, fixed #3797

examples/docs/en-US/table.md, examples/docs/zh-CN/table.md, packages/table/src/table-body.js, packages/table/src/table-column.js, packages/table/src/table.vue
=> Table: improve performance for rendering tooltip, fixed #3478

README.md
=> Update README.md to refresh GitHub image cache

packages/message-box/src/main.vue
=> MessageBox: add enter event for prompt

packages/cascader/src/main.vue, packages/theme-default/src/cascader.css
=> fix cascader style bug

packages/form/src/form-item.vue
- 当表单项初始值为Array时，重新生成数组
- 修改原来的resetField函数，使得resetField时真正如文档所说的 将所有字段重置为初始值
参考 #3830
=> Form: fix form-item resetFields (#3830)

packages/date-picker/src/panel/date-range.vue, packages/date-picker/src/panel/date.vue, packages/date-picker/src/panel/time-range.vue
=> DatePicker: fix setMonth, fixed #3923

packages/upload/src/index.vue, packages/upload/src/upload.vue
添加支持[httpRequest](https://github.com/ElemeFE/element/pull/3387) Promise
=> Add support for httpRequest Promise

packages/table/src/table-store.js, packages/table/src/table.vue
=> Table: Hack for dynamics change columns.

packages/theme-default/src/switch.css
=> Switch: remove button and text z-index, fixed #3932

test/unit/util.js
ref: https://github.com/ElemeFE/element/issues/3981
* [*] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [*] Make sure you are merging your commits to `dev` branch.
* [*] Add some descriptions and refer relative issues for you PR.
=> remove unnecessary declaration

packages/theme-default/src/input.css
=> Theme: Update input.css to use already defined variables

examples/docs/en-US/message.md, examples/docs/zh-CN/message.md, packages/message/src/main.js, test/unit/specs/message.spec.js
- add closeAll method to Message
- add doc
- add test
see #3941
=> Message: add ability to close all Messages #3941

packages/slider/src/main.vue
- Slider 组件 emit change 事件时，触发 ElFormItem 的表单验证
参考 #3968
=> Slider: triggers validator when value changed, fixed #3968

packages/table/src/table-body.js
=> Table: improve performance for init tooltip, fixed #3836

examples/docs/en-US/carousel.md, examples/docs/zh-CN/carousel.md
=> Carousel: fix a docs error

examples/docs/en-US/popover.md, examples/docs/en-US/tooltip.md, examples/docs/zh-CN/popover.md, examples/docs/zh-CN/tooltip.md, src/utils/vue-popper.js
=> Popper: add onUpdate support

packages/select/src/select.vue
=> Select: fix single mode allow-create not working in Vue 2.2.x

packages/table/src/table-body.js
=> Table: delete duplicate declaration "ElTooltip", fixed #4046

packages/table/src/filter-panel.vue
解决嵌套dialog，table的filter panel 被遮罩的问题  #3896
=> Table: Fixed #3896

packages/theme-default/src/reset.css
Adds some basic CSS styles for `<hr>` tag. Can be modifed later if needed.
---
=> Add basic <hr> CSS styles

packages/theme-default/src/col.css
=> support layout grid 0(#3975)

packages/table/src/table-store.js, packages/table/src/table.vue
=> Table: init filters.

examples/index.tpl, packages/dialog/src/component.vue
=> change mask icon source to github

packages/tabs/src/tabs.vue
=> disable tab remove when tab disabled

packages/radio/src/radio-button.vue
=> Radio: radio button box-shadow, fixed #3978

examples/docs/en-US/message.md, examples/docs/zh-CN/message.md
=> doc: fix sample code typo in Message

.github/CONTRIBUTING.en-US.md, build/bin/new.js
Currently, only Chinese error message is displayed when running make new command without arguments.
---
=> Add make new English error message

packages/tree/src/model/tree-store.js
- 没有正确使用 `Array.sort` 函数，错误使用的情况下浏览器默认表现不同。
- `Array.sort` 函数只在 Tree 和 Table 中使用，Table 中是正确使用的。
参考 #4006
=> Tree: sort correctly, fix #4006

packages/table/src/table-body.js
=> Table: fix a handleClosePopper bug, fixed #3888

packages/theme-default/src/radio-button.css
=> Radio: fix radio-button not working when other texts are selected

src/locale/lang/tk.js
=> Lang: Added Turkmen locale

packages/select/src/select.vue
- 递归调用导致调用栈溢出。
- 递归之前重新计算 `this.optionsAllDisabled` 来判断是否需要执行。
参考 #4106
=> Select: avoid stack overflow, fix #4106

examples/docs/en-US/pagination.md, examples/docs/zh-CN/pagination.md
The code of example has error.
=> Fixed error code

packages/theme-default/src/cascader.css
- 调整 close icon 的 z-index
参考 #4084
=> Cascader: adjust close icon z-index, fix #4084

packages/theme-default/src/upload.css, packages/upload/src/upload-list.vue
=> fix upload file remove can't remove when auto-upload is false

examples/docs/en-US/notification.md, packages/notification/src/main.vue
Added an event handler on click of notification's div
=> Notification: add onClick handler

packages/date-picker/src/picker.vue
- emit event input when delete value via el-input
- set default value `''` when click clear icon
see #4135
=> DatePicker: set default value when clear, fix #4135

packages/theme-default/src/select.css
=> Select: fix width changes when clear icon shows, fixed #4202

examples/docs/en-US/tooltip.md, examples/docs/zh-CN/tooltip.md, packages/tooltip/src/main.js
=> Tooltip: add hide-on-hover

examples/docs/zh-CN/notification.md, packages/theme-default/src/color-picker.css
=> ColorPicker: fix style when nested in form-item

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, examples/docs/en-US/i18n.md, examples/docs/zh-CN/i18n.md
=> Changelog: update for 1.2.9

examples/docs/en-US/slider.md, examples/docs/zh-CN/slider.md, packages/slider/src/button.vue, packages/slider/src/main.vue, packages/theme-default/src/slider.css
Slider 滑块的竖向模式
* 组件增加了 `vertical` 和 `size` 参数
* 修改了部分属性命名以适配语义
* 增加了 vertical 模式下的 css 样式
* 添加文档
=> Slider: add vertical mode

examples/docs/en-US/table.md, examples/docs/zh-CN/table.md, packages/table/src/table.vue
=> Table: add setCurrentRow

examples/docs/zh-CN/checkbox.md
=> Checkbox: update doc

src/locale/lang/th.js
=> edit sunday short date thai locale

examples/docs/en-US/dialog.md, examples/docs/zh-CN/dialog.md, packages/dialog/src/component.vue, packages/select/src/select.vue
=> Dialog: add before-close

examples/docs/en-US/upload.md, examples/docs/zh-CN/upload.md, packages/upload/src/iframe-upload.vue, packages/upload/src/index.vue, packages/upload/src/upload-dragger.vue, packages/upload/src/upload.vue
=> add disabled feature

examples/docs/en-US/upload.md, examples/docs/zh-CN/upload.md, packages/upload/src/index.vue
=> Feature: invoke on-change hook when file select(#4401)

packages/select/src/option.vue, packages/theme-default/src/option.css
=> Select: optimize performance of long option list

packages/autocomplete/src/autocomplete.vue
This PR fixes the problem when input with Chinese input method, which fixes https://github.com/ElemeFE/element/issues/3645.
=> Autocomplete: fix problem when input with Chinese input method

examples/docs/en-US/slider.md, examples/docs/zh-CN/slider.md, packages/slider/src/button.vue, packages/slider/src/main.vue, packages/theme-default/src/slider.css, test/unit/specs/slider.spec.js
=> Slider: update vertical mode

packages/upload/src/upload.vue
=> fix upload can't select the same file(#4461)

examples/docs/en-US/switch.md, examples/docs/zh-CN/switch.md, packages/switch/src/component.vue, test/unit/specs/switch.spec.js
Switch 新增两个状态值 'on-value' 与 'off-value'. 
参考 #4371
=> Switch:feat add expand value

packages/col/src/col.js, packages/row/src/row.vue
=> support use transitiongroup in el-col(#3428)

examples/docs/en-US/date-picker.md, examples/docs/zh-CN/date-picker.md, packages/date-picker/src/panel/date.vue, packages/date-picker/src/picker.vue
DatePicker：clear、value为空时可指定Picker的默认值
Demo：https://jsfiddle.net/wacky6/a0hag1cv/3/
Issue：https://github.com/ElemeFE/element/issues/4143
7月举办会议。参会者4月预订酒店时，DatePicker默认显示7月的日历
=> [Feature]: DatePicker: 支持Picker默认值

examples/docs/en-US/transition.md, examples/docs/zh-CN/transition.md
=> Transition: update docs

packages/theme-default/src/radio-group.css
=> Radio: fix radio-button style when nested in a form-item

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, build/bin/version.js, build/deploy-ci.sh, package.json, packages/transfer/src/transfer-panel.vue, src/index.js
=> Changelog: update for 1.3.0-beta.1

examples/index.tpl
=> update docs vue version

packages/select/src/select.vue, test/unit/specs/select.spec.js
Fixing [issue #2231](https://github.com/ElemeFE/element/issues/2231)
=> [Bugfix] el-select multiple with vuex

packages/checkbox/src/checkbox-group.vue, packages/checkbox/src/checkbox.vue, packages/form/src/form-item.vue, packages/form/src/form.vue
=> Form: remove emitter

packages/theme-default/src/checkbox.css
Checkbox: fix a typo in checkbox.css.
=> Checkbox: fix a typo in checkbox.css

examples/docs/en-US/i18n.md, examples/docs/en-US/quickstart.md, examples/docs/zh-CN/i18n.md, examples/docs/zh-CN/quickstart.md
=> Docs(quickstart): update babel config

examples/docs/en-US/table.md, examples/docs/zh-CN/table.md, packages/table/src/table-column.js, packages/table/src/table-header.js, packages/theme-default/src/index.css
Table: Add filter-placement for table filter Popper;
If the column is too wide, the popper's position will be improper;
https://jsfiddle.net/whitewang/obpsLcva/7/
=> Table: Add filter-placement for table filter Popper

build/release.sh, examples/docs/zh-CN/tag.md, packages/checkbox/src/checkbox-group.vue, packages/checkbox/src/checkbox.vue, packages/form/src/form-item.vue, packages/form/src/form.vue, packages/theme-default/src/input.css, packages/theme-default/src/table-column.css, test/unit/specs/date-picker.spec.js
=> fix datepicker test, revert emitter-removing attempt

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, examples/docs/en-US/table.md, examples/docs/zh-CN/table.md
=> Changelog: update for 1.3.0-beta.3

examples/docs/en-US/form.md, examples/docs/zh-CN/form.md, packages/form/src/form-item.vue
=> Form: Add label slot

packages/theme-default/src/upload.css, packages/upload/src/upload-list.vue
=> upload fix (#4613)

packages/dialog/src/component.vue
=> Dialog: fix visible.sync compatibility with before-close

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, examples/components/footer.vue
=> Changelog: update for 1.3.0

packages/autocomplete/src/autocomplete.vue
=> Autocomplete: fix a Chinese composition bug

packages/table/src/table.vue
=> Table: fix summary row scroll

src/utils/popup/popup-manager.js
=> Dialog: fix closeOnPressEsc

packages/switch/src/component.vue
=> Switch: fix change event parameter

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
=> Changelog: update for 1.3.1

packages/collapse/src/collapse-item.vue, packages/menu/src/submenu.vue, packages/select/src/option.vue, packages/tree/src/tree-node.vue
=> declare el-collapse-transition in its dependents

examples/docs/en-US/layout.md, examples/docs/en-US/tabs.md, examples/docs/en-US/upload.md
`i.e.` means `in other words`.
`e.g.` means `for example`
=> docs: fix confused syntax

examples/docs/en-US/input-number.md, examples/docs/zh-CN/input-number.md, packages/input-number/src/input-number.vue
- when user type invalid value like chinese, reset display value
- when user type value too large or too small that leads to `oldVal === newVal`, reset display value
- when user clear input, directly return to wait for typing
see #4661
=> InputNumber: improve user experience when typing, fix #4661

examples/docs/en-US/transition.md, examples/docs/zh-CN/transition.md
=> doc: add load transiton on demand, fixed #4758

examples/docs/en-US/upload.md, examples/docs/zh-CN/upload.md, packages/pagination/src/pagination.js
=> Pagination: fix default layout style in firefox

packages/date-picker/src/panel/date.vue
=> DatePicker: update week when value changes

packages/table/src/table-layout.js, packages/table/src/table.vue
=> Table: fix table body height calculations

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, README.md, examples/components/footer-nav.vue, examples/components/footer.vue, examples/components/side-nav.vue, examples/docs/en-US/cascader.md, examples/docs/en-US/upload.md, examples/docs/zh-CN/cascader.md, examples/docs/zh-CN/upload.md, examples/nav.config.json, examples/route.config.js
=> Changelog: update for 1.3.2

src/locale/lang/vi.js
I'm vietnamese developer, so i finished your translate locate! 
Hope you merge my pull request , thanks you ^^
=> Update better vietnamese translate. :octocat:

build/cooking.demo.js, examples/components/footer.vue, examples/route.config.js
=> feat: split doc files

packages/cascader/src/main.vue
=> Cascader: Add default before-filter

packages/theme-default/src/date-picker/time-spinner.css
=> TimePicker: strange css behavior, fix #4813

src/utils/popup/popup-manager.js
keydown esc, when modal has beforeClose function
=> key.esc no modal and msgbox with promises

packages/message-box/src/main.js, packages/message-box/src/main.vue, packages/theme-default/src/checkbox.css, packages/theme-default/src/dropdown.css, src/utils/popup/popup-manager.js
=> some bug fixes

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
=> Changelog: update for 1.3.3

examples/docs/en-US/alert.md, examples/docs/en-US/button.md, examples/docs/en-US/carousel.md, examples/docs/en-US/cascader.md, examples/docs/en-US/collapse.md, examples/docs/en-US/color-picker.md, examples/docs/en-US/color.md, examples/docs/en-US/date-picker.md, examples/docs/en-US/datetime-picker.md, examples/docs/en-US/dialog.md, examples/docs/en-US/dropdown.md, examples/docs/en-US/icon.md, examples/docs/en-US/input-number.md, examples/docs/en-US/layout.md, examples/docs/en-US/loading.md, examples/docs/en-US/menu.md, examples/docs/en-US/pagination.md, examples/docs/en-US/popover.md, examples/docs/en-US/rate.md, examples/docs/en-US/select.md, examples/docs/en-US/switch.md, examples/docs/en-US/table.md, examples/docs/en-US/tag.md, examples/docs/en-US/time-picker.md, examples/docs/en-US/transfer.md, examples/docs/en-US/transition.md, examples/docs/en-US/tree.md, examples/docs/en-US/typography.md, examples/docs/en-US/upload.md
=> doc: add the missing styles for english docs

examples/docs/en-US/select.md, examples/docs/zh-CN/select.md, packages/select/src/select.vue, test/unit/specs/select.spec.js
Select 允许筛选（`filterable`）时，在输入框按下回车键默认选择第一个选项。
不影响现有上下键或鼠标悬停后回车的行为。
https://jsfiddle.net/8nLbcgd1/
省市区选择，输入拼音筛选，直接按下回车，选择最匹配的一项
是否有必要检测输入为空的情况，并禁止在这种情况下选择默认值？
=> select: default to first option on keydown.enter

examples/docs/zh-CN/switch.md
=> doc: remove dangling tag in switch

examples/docs/en-US/switch.md, examples/docs/zh-CN/switch.md
=> doc: fix wrong indent in select.md

packages/table/src/table-body.js, packages/table/src/table.vue, packages/theme-default/src/table.css
=> Table: fix wrong stripe style with expandable rows

packages/select/src/select.vue
=> Select: fix emptyText display when allow for create

packages/select/src/select.vue, src/locale/lang/ta.js
=> Adding tamil language support

src/locale/lang/pt-br.js
This PR adds some missing translations to the pt-br lang file, also it fixes a small typo on the word ``` pagina ``` the correct spelling is ``` página ``` with an acute accent.
=> Add missing translations pt-BR

packages/carousel/src/main.vue
* [*] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [*] Make sure you are merging your commits to `dev` branch.
* [*] Add some descriptions and refer relative issues for you PR.
可以方便的在父组件中改变走马灯的自动播放状态
=> carousel: be able to switch autoplay state

build/bin/new.js
=> fix `make new` error

packages/table/src/table.vue
=> Table: fix incorrect expression

packages/cascader/src/main.vue
=> fix when value is null(#5085)

packages/theme-default/src/input-number.css
=> fix input number style(#5103、#2726)

packages/date-picker/package.json
Date picker was updated, but npm need version bump to update package.
=> DatePicker: bump version

packages/theme-default/src/input.css
=> fix input style bug in firefox(#3916)

packages/theme-default/src/input.css
=> fix input-group style(#4798)

src/locale/lang/lv.js
Added Latvian translation file (lv.js) for locale.
=> Locale: Add Latvian translation file.

packages/cascader/src/menu.vue, src/utils/shared.js, test/unit/specs/cascader.spec.js
=> Cascader: fix invalid zero value (#3470)

packages/autocomplete/src/autocomplete.vue
=> fix keydown event not bubble(#4965)

packages/upload/src/upload.vue
=> fix input value is null before upload submit actually(#4852)

examples/docs/en-US/select.md, examples/docs/zh-CN/select.md, packages/select/src/select.vue
=> Select: add clear event

examples/docs/en-US/table.md, examples/docs/en-US/tree.md, examples/docs/zh-CN/table.md, examples/docs/zh-CN/tree.md, packages/cascader/src/main.vue
=> Cascader: update popper when change-on-select

packages/date-picker/src/basic/date-table.vue
=> DatePicker: timezone

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, examples/docs/en-US/i18n.md, examples/docs/zh-CN/i18n.md, packages/switch/src/component.vue
=> Changelog: update for 1.3.5

packages/color-picker/src/color.js, test/unit/specs/color-picker.spec.js
=> fix nocorrect rgb value (#5179)

README.md
=> README: add atom helper

src/locale/lang/af.js
i18n: Added Afrikaans (af-ZA) locale
=> Added Afrikaans (af-ZA) locale

packages/color-picker/src/components/hue-slider.vue, packages/color-picker/src/components/sv-panel.vue, test/unit/specs/color-picker.spec.js
=> ColorPicker: fix invalid hue bar click when saturation is zero (#5080)

src/locale/lang/ee.js
=> Add Estonian language

packages/dropdown/src/dropdown-menu.vue, packages/select/src/select-dropdown.vue
=> Dialog: fix incorrect updatePopper calls

packages/date-picker/src/basic/date-table.vue, src/utils/resize-event.js
=> fix DatePicker and Select bug

examples/docs/en-US/input.md, examples/docs/zh-CN/input.md, packages/autocomplete/src/autocomplete-suggestions.vue, packages/autocomplete/src/autocomplete.vue, test/unit/specs/autocomplete.spec.js
=> add props support (#5188)

packages/date-picker/src/picker.vue
Picker `esc` closing and stopPropagation
=> Picker: esc => close and stop

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, package.json, packages/pagination/src/pagination.js
=> Changelog: update for 1.3.6

src/locale/lang/tk.js
=> Locale: [tk] translated new strings

src/locale/lang/sl.js
Added Slovenian translation file (sl.js)
=> Translations: Slovenian translation

examples/docs/zh-CN/checkbox.md, packages/table/src/table.vue
=> Table: fix hidden summary row with async data

packages/pagination/src/pagination.js
=> Pagination: fix jumper responsive bug

examples/components/demo-block.vue, examples/docs/en-US/table.md, examples/docs/zh-CN/table.md
=> Table: update sorting docs

src/utils/popper.js
=> Tooltip: fix arrow separating from tooltip

src/utils/clickoutside.js, test/unit/specs/dropdown.spec.js, test/unit/specs/form.spec.js, test/unit/specs/menu.spec.js
=> ClickOutside: fix 'Cannot read property target of undefined'

src/utils/scrollbar-width.js
=> ScrollBar: cache bar width calculation

packages/theme-default/src/switch.css
=> Switch: remove user-select

packages/form/src/form-item.vue
=> support dynamic form item rule required(#4161)

packages/checkbox/src/checkbox.vue
=> fix checkbox not trigger input event bug

packages/carousel/src/item.vue, packages/carousel/src/main.vue
=> Carousel: fix initial-index

packages/form/src/form.vue, packages/slider/src/main.vue
=> add two warns

packages/date-picker/src/panel/date.vue
=> DatePicker: Fix year picker

packages/steps/src/step.vue, packages/steps/src/steps.vue
=> Steps: Add dynamic add and remove support

packages/theme-default/src/tree.css
https://github.com/ElementUI/theme-default/issues/25
=> Tree: use font size variable

packages/select/src/select.vue
See: https://github.com/ElemeFE/element/issues/5430#issuecomment-309445013
=> Select: fix dropdown scroll

packages/dropdown/src/dropdown-item.vue, test/unit/specs/dropdown.spec.js
Allows for dynamic `command` prop for dropdown items, see feature request #5261
=> Dropdown: Allow all types for command prop

examples/docs/en-US/table.md, examples/docs/zh-CN/table.md, packages/table/src/util.js
Let getRowIdentity simply support the _.get method similar to lodash.
```javascript
var getRowIdentity = (row, rowKey) => {
if (!row) throw new Error('row is required when get row identity');
if (typeof rowKey === 'string') {
if (rowKey.indexOf('.') < 0) {
return row[rowKey];
}
let key = rowKey.split('.')
let current = row
for (let i = 0; i < key.length; i++) {
current = current[key[i]]
}
return current
} else if (typeof rowKey === 'function') {
return rowKey.call(null, row);
}
};
var data = {
key: 'hi',
b: {
c: {
d: 123
}
}
}
console.log(getRowIdentity(data, 'key'))   // hi
console.log(getRowIdentity(data, 'b.c.d')) // 123
```
=> Let getRowIdentity simply support the _.get method similar to lodash.

examples/docs/en-US/form.md, examples/docs/zh-CN/form.md, packages/form/src/form-item.vue, packages/theme-default/src/form.css
=> fix form-item style

packages/date-picker/src/panel/date.vue
=> DatePicker: set milliseconds to 0

packages/upload/src/upload.vue
=> clear inptu value when uploader click again

examples/docs/zh-CN/quickstart.md
updating document quickstart.md
文档中，按需引入部分的组件列表中没有Notification，已补上，防止使用者不会使用。
=> quickstart: updating document

examples/pages/template/changelog.tpl
=> Changelog: reserve anchor elements

examples/docs/en-US/tag.md, examples/docs/zh-CN/tag.md, packages/message-box/src/main.js
=> MessageBox: reject all cancel actions

packages/rate/src/main.vue
=> Rate: fix initial display of decimal value

packages/theme-default/src/step.css
Steps: Make progress line to be exactly 50% size
See: https://github.com/ElemeFE/element/issues/5703
=> Step: make progress line to be exactly 50% size

src/locale/lang/de.js
=> Removed German "Jahr" suffix from DatePicker

examples/docs/en-US/popover.md, packages/popover/src/main.vue
From [Feature Request] #5820 I've added delay on hover component.
=> [Popover]: Open Delay Attribute

packages/upload/src/index.vue, packages/upload/src/upload-list.vue
=> Upload: remove delete icon when disabled

packages/loading/src/directive.js
When two elements of one parent element are bound to the v-loading.body property at the same time, if one of the elements is in the hidden state, then there will be a bug occur when the other child element is loading
=> fixed hidden dom element loading bug

packages/table/src/table-column.js
=> 添加接口计算原来的列值

examples/docs/en-US/table.md, examples/docs/zh-CN/popover.md, examples/docs/zh-CN/table.md, packages/upload/src/upload-list.vue, test/unit/specs/menu.spec.js
=> Upload: fix against non-primitive key warn in Vue 2.4

packages/pagination/src/pager.vue
#5852 bug fix:  no test case added(sorry, i don't know how to add test cases)
=> pagination:fix bug Pagination page number display problem

packages/form/src/form-item.vue
=> fix form-item label bug(#5895)

packages/tooltip/src/main.js
=> Tooltip: fix compatibility issue with Vue 2.4.x

packages/cascader/src/menu.vue, packages/date-picker/src/panel/time-select.vue, packages/select/src/select.vue, src/utils/scroll-into-view.js
Relevant components: Select, Cascader, TimeSelect
重新设计 Select 弹出菜单：弹出前将列表滚动到位。
将以上设计添加到 Cascader 和 TimeSelect
参见：https://github.com/ElemeFE/element/issues/5430
https://jsfiddle.net/whm0ys1y/
=> Rework Dropdown Scroll

packages/date-picker/src/picker.vue
=> DatePicker: fix align=center

packages/table/src/table.vue
=> Table:修复table取不到selection的BUG

examples/docs/en-US/menu.md, examples/docs/zh-CN/menu.md, packages/menu/src/menu-item-group.vue, packages/menu/src/menu-item.vue, packages/menu/src/menu-mixin.js, packages/menu/src/menu.vue, packages/menu/src/submenu.vue, packages/theme-default/src/common/transition.css, packages/theme-default/src/menu.css
=> feature menu collapse

examples/docs/en-US/checkbox.md, examples/docs/zh-CN/checkbox.md
=> [Doc error] The change event is base on el-checkbox

examples/docs/en-US/tree.md, examples/docs/zh-CN/tree.md, packages/tree/src/model/node.js, packages/tree/src/model/tree-store.js, packages/tree/src/tree-node.vue, packages/tree/src/tree.vue, test/unit/specs/tree.spec.js
=> Tree: checkbox can be disabled

build/deploy-ci.sh, examples/app.vue
=> update doc sub-folder

packages/menu/src/menu-mixin.js, packages/menu/src/menu.vue
=> Menu: compensate for Vue regression

packages/tree/src/model/node.js
=> Tree: tree expand once when checked

packages/upload/README.md
=> Upload: correct documentation

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, examples/components/footer.vue, packages/date-picker/src/panel/time-select.vue
=> Changelog: update for 1.4.0

examples/docs/en-US/tree.md, examples/docs/zh-CN/tree.md, packages/tree/src/model/tree-store.js, packages/tree/src/tree.vue, test/unit/specs/tree.spec.js
=> add Tree component current node method

examples/docs/en-US/tree.md, examples/docs/zh-CN/tree.md, packages/tree/src/model/tree-store.js, packages/tree/src/tree.vue, test/unit/specs/tree.spec.js
=> add Tree updateKeyChildren method

examples/docs/en-US/form.md
find all `validae` to `validate` in en-US docs
=> Fix typo `validae` to `validate`

packages/tree/src/tree-node.vue
=> Tree: checkbox stopPropagation

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
=> Changelog: fix typo

packages/tree/src/model/node.js
=> Tree: select fix

packages/date-picker/src/panel/date-range.vue
=> DatePicker: fix emit pick

examples/docs/en-US/form.md, examples/docs/zh-CN/form.md, packages/form/src/form-item.vue
=> Form: direct child items should inherit label-width

examples/docs/zh-CN/menu.md, packages/menu/src/menu.vue
=> fix menu bug

packages/tabs/src/tabs.vue
=> fix tabs bug

packages/select/src/select.vue, test/unit/specs/select.spec.js
修正Select的change事件
只要value改变就会发射change
https://jsfiddle.net/geqmu5q0/
只对用户输入操作发射change
https://jsfiddle.net/fefmaavq/
参考select标签，通过js代码改变值不会触发change。
=> Select: fix change event

packages/select/src/select.vue
fix https://github.com/ElemeFE/element/pull/5789#discussion_r130217940
Note: When `multiple` is true, on menu open, will not scroll to selected option.
=> Select: fix dropdown scroll for multiple select

examples/docs/en-US/form.md, packages/select/src/option.vue, packages/select/src/select.vue
=> Select: fix isObject bug

packages/date-picker/src/panel/date.vue
Close TimePicker before `dodestroy`
=> DatePicker: close timepicker before dodestroy

packages/date-picker/src/panel/time-select.vue, packages/date-picker/src/picker/time-select.js
=> TimeSelect support select with up & down

examples/docs/en-US/tabs.md, examples/docs/zh-CN/tabs.md, packages/tabs/src/tab-bar.vue, packages/tabs/src/tab-nav.vue, packages/tabs/src/tabs.vue, packages/theme-default/src/tabs.css, test/unit/specs/tabs.spec.js
=> [Feature] Vertical tab

packages/date-picker/src/basic/time-spinner.vue, packages/date-picker/src/panel/time-range.vue, packages/date-picker/src/panel/time.vue, packages/date-picker/src/picker/time-picker.js
=> TimePicker: support keyboard control

packages/cascader/src/menu.vue
=> Cascader: fixed hover unexpected

examples/docs/en-US/menu.md, examples/docs/zh-CN/menu.md
=> Menu: update collapse doc

packages/date-picker/src/panel/date.vue, packages/date-picker/src/picker/date-picker.js, test/unit/karma.conf.js
=> DatePicker: support keyboard control

build/cooking.demo.js, examples/app.vue, examples/docs/en-US/message-box.md, examples/docs/zh-CN/message-box.md, examples/pages/template/component.tpl, packages/message-box/src/main.js, packages/message-box/src/main.vue
=> MessageBox: add closeOnHashChange, update docs

packages/menu/src/menu.vue
=> Menu: close menus on collapse change

examples/docs/en-US/dropdown.md, examples/docs/zh-CN/dropdown.md, packages/dropdown/src/dropdown-item.vue
=> fix dropdown command

packages/switch/src/component.vue, test/unit/specs/switch.spec.js
fix https://github.com/ElemeFE/element/issues/6176
=> Switch: set checkbox checked property

packages/switch/src/component.vue
fix https://github.com/ElemeFE/element/issues/6308
=> Switch: fix input and change emission sequence

examples/index.tpl
=> chore(*): replace CDN with jsDelivr

packages/date-picker/src/panel/time.vue, packages/date-picker/src/picker.vue
=> DatePicker: picker interaction

packages/slider/src/button.vue, packages/slider/src/main.vue
=> Slider: reset size on resize

packages/autocomplete/src/autocomplete.vue
=> Autocomplete: hide suggestions on blur

examples/docs/en-US/message-box.md, examples/docs/zh-CN/message-box.md, packages/message-box/src/main.js, packages/message-box/src/main.vue, test/unit/specs/message-box.spec.js
=> Msgbox: add dangerouslyUseHTMLString

examples/docs/en-US/notification.md, examples/docs/zh-CN/notification.md, packages/notification/src/main.js, packages/notification/src/main.vue, packages/theme-default/src/notification.css, test/unit/specs/notification.spec.js
=> Notification: add position

packages/date-picker/src/panel/date-range.vue
=> DateTimePicker: add timeformat for datetimerange

packages/color-picker/src/components/picker-dropdown.vue, test/unit/specs/color-picker.spec.js
=> ColorPicker: support user input

packages/tree/src/tree-node.vue, test/unit/specs/tree.spec.js
=> Tree: render when node expand

packages/tree/src/model/node.js, packages/tree/src/tree.vue, test/unit/specs/tree.spec.js
Add attribute `check-descendants`
Description: Expand all node when checked in lazy mode
=> Tree: add check-descendants attribute

examples/docs/en-US/dialog.md, examples/docs/zh-CN/dialog.md, packages/dialog/src/component.vue, packages/theme-default/src/common/var.css, packages/theme-default/src/dialog.css, src/utils/popup/index.js, test/unit/specs/dialog.spec.js
=> Dialog: remove v-model, add append-to-body

packages/select/src/navigation-mixin.js, packages/select/src/option.vue, packages/select/src/select.vue, packages/theme-default/src/input.css, packages/theme-default/src/select.css, test/unit/specs/select.spec.js
=> Select: remove resetIndex

examples/docs/zh-CN/checkbox.md, packages/alert/src/main.vue, packages/breadcrumb/src/breadcrumb-item.vue, packages/breadcrumb/src/breadcrumb.vue, packages/button/src/button.vue, packages/checkbox/src/checkbox-button.vue, packages/checkbox/src/checkbox-group.vue, packages/checkbox/src/checkbox.vue, packages/theme-default/src/checkbox.css
【Alert】
1、add role="alert" for element
【Button】
1、You can add aria-* for Button , such as role,  aria-labelledby, aria-haspopup
2、Press Space or Enter can Activates the button
【Breadcrumb】
1、add aria-* for Button for screen reader
2、you can Tab through Breadcrumb items
【checkbox】
1、add aria-* for Button for screen reader
2、add id for checkbox and controls for Indeterminate checkbox
=> [Button] add accessibility

packages/pagination/src/pagination.js
Pagination:fix IE onchange doesn't work Bug
#6221 
#6222 
#6224
=> Pagination:fix IE onchange doesn't work Bug

src/locale/lang/ar.js
Added ar ( Arabic ) language locale file
=> added arabic language locale file

packages/slider/src/button.vue
=> Slider: fix button jumping to 0 when clicked

packages/date-picker/src/util/index.js
=> DatePicker: fix fecha i18n not responsive

packages/autocomplete/src/autocomplete.vue
=> Autocomplete: support autofocus

packages/table/src/table.vue, packages/table/src/util.js, packages/theme-default/src/table.css
=> Table: hide table when nested in an invisible container

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, examples/docs/en-US/i18n.md, examples/docs/zh-CN/i18n.md
=> Changelog: update for 1.4.2

examples/docs/en-US/dropdown.md, examples/docs/zh-CN/dropdown.md, packages/dropdown/src/dropdown-item.vue, packages/dropdown/src/dropdown-menu.vue, packages/dropdown/src/dropdown.vue
=> support dropdown placement

examples/docs/en-US/pagination.md, examples/docs/zh-CN/pagination.md, packages/pagination/src/pagination.js
=> Pagination: add popperClass

packages/date-picker/src/panel/date.vue, packages/date-picker/src/panel/time.vue
=> DateTimePicker: limit timepicker

packages/slider/src/button.vue, packages/slider/src/main.vue, test/unit/specs/slider.spec.js
=> Slider: change event only triggers on user input

examples/docs/en-US/rate.md, examples/docs/zh-CN/rate.md, packages/rate/src/main.vue
=> Rate: add show-score, fix change event timing

packages/theme-default/src/progress.css, test/unit/specs/progress.spec.js
https://jsfiddle.net/wtxc0m1p/
=> Progress: fix incorrect vertical align if percent is zero

examples/docs/en-US/upload.md
=> Upload: fix en doc

packages/carousel/src/item.vue, packages/carousel/src/main.vue, packages/theme-default/src/carousel-item.css
=> Carousel: fix flashing items

examples/docs/en-US/icon.md, examples/docs/zh-CN/icon.md
=> Icon: add docs on third-party icon integration

examples/docs/en-US/checkbox.md, examples/docs/zh-CN/checkbox.md, packages/checkbox/src/checkbox-button.vue, packages/checkbox/src/checkbox.vue, packages/transfer/src/transfer-panel.vue, packages/tree/src/tree-node.vue, test/unit/specs/cascader.spec.js, test/unit/specs/checkbox.spec.js, test/unit/specs/tree.spec.js
=> Checkbox: change event only triggers on user input

packages/menu/src/menu-item.vue, packages/menu/src/menu.vue
fix typo: `activedIndex` -> `activeIndex`
=> Menu: fix typo activedIndex -> activeIndex

packages/cascader/src/menu.vue
=> Cascader: fix duplicate prop name

src/utils/popup/index.js
=> Popup: fix missing padding-right when overflow-y is scroll

packages/autocomplete/src/autocomplete.vue
=> Autocomplete: Don't prevent form submit

packages/button/src/button.vue
=> Button: avoid click event bubbling when disabled

packages/theme-default/src/menu.css
=> Menu: optimize collapse animation

packages/date-picker/src/util/index.js
=> DatePicker: support amPm i18n

src/locale/lang/tk.js
=> Locale: [tk] improved translation

packages/loading/src/directive.js, packages/loading/src/index.js
=> Loading: use getStyle

packages/date-picker/src/util/index.js, packages/table/src/table.vue
bug description: useing mouse wheel, triggers event with deltaX equals negative zero, this will cause scrollLeft change going wrong
=> Table: fix scroll delta check bug

packages/slider/src/button.vue, packages/slider/src/main.vue
=> Slider: reset size on click / drag

packages/select/src/option.vue, packages/select/src/select.vue
=> Select: remove onOptionDestroy event

packages/theme-default/src/dialog.css
=> Dialog: fix close button style

packages/theme-default/src/pagination.css
=> Pagination: fix editor style in firefox

packages/theme-default/src/input-number.css
=> InputNumber: fix style when nested in form item

examples/docs/en-US/button.md, examples/docs/zh-CN/button.md
=> Button: fix doc

packages/table/src/table-footer.js
=> Table: fix toFixed parameter overflow

packages/pagination/src/pagination.js, packages/select/src/select.vue, src/utils/util.js, test/unit/specs/pagination.spec.js
=> Pagination: current-change only triggers on user input

packages/date-picker/src/basic/time-spinner.vue
=> TimePicker:fix hour selection can't select 23 bug

packages/menu/src/menu.vue, packages/menu/src/submenu.vue
* [ no docs change] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [yes ] Make sure you are merging your commits to `dev` branch.
* [yes ] Add some descriptions and refer relative issues for you PR.
Remove the useless parameters of the `closeMenu` method, in `el-menu` and `el-submenu` components.
=> Remove useless parameters

packages/table/src/table-body.js
=> Table: fix undefined popper

packages/dropdown/src/dropdown.vue
=> Dropdown: take care of disabled triggering element

examples/docs/en-US/checkbox.md, examples/docs/en-US/radio.md, examples/docs/zh-CN/checkbox.md, examples/docs/zh-CN/radio.md, packages/checkbox/src/checkbox-button.vue, packages/checkbox/src/checkbox-group.vue, packages/checkbox/src/checkbox.vue, packages/radio/src/radio.vue, packages/theme-chalk/src/checkbox.scss, packages/theme-chalk/src/color-picker.scss, packages/theme-chalk/src/common/var.scss, packages/theme-chalk/src/date-picker/date-table.scss, packages/theme-chalk/src/date-picker/picker.scss, packages/theme-chalk/src/form.scss, packages/theme-chalk/src/menu.scss, packages/theme-chalk/src/radio-button.scss, packages/theme-chalk/src/radio-group.scss, packages/theme-chalk/src/radio.scss, test/unit/specs/radio.spec.js
=> add api for radio and checkbox

examples/docs/en-US/slider.md, examples/docs/zh-CN/slider.md, packages/slider/src/main.vue
Add the prop `debounce` for the component Slider.
为 Slider 组件添加上`debounce`属性。
=> Add the prop `debounce` for the component Slider.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
=> Changelog: update for 1.4.4

packages/table/src/table-header.js, packages/theme-default/src/table.css
=> Table: sortable header discoverability

src/locale/lang/ru-RU.js, src/locale/lang/ua.js
Hi, my main language is Russian, and my native language is Ukranian. So I decided to update your translations
1. Fixed Ukrainian slang.
2. Add [ua] translation for table & transfer
2. Add [ru-RU] translation for table & transfer
=> add translations [ru-RU], [ua]

packages/tree/src/model/node.js
=> Tree: fix current-node-key === 0 bug

packages/dropdown/src/dropdown.vue
=> dropdown: reactive disabled trigger element

packages/tooltip/src/main.js
=> Tooltip: avoid adding handler repeatedly

packages/theme-chalk/src/collapse.scss, packages/theme-chalk/src/common/var.scss
=> Collapse: add chalk theme

examples/docs/en-US/transfer.md, examples/docs/zh-CN/transfer.md, packages/theme-chalk/src/common/var.scss, packages/theme-chalk/src/transfer.scss, packages/transfer/src/main.vue, packages/transfer/src/transfer-panel.vue, test/unit/specs/transfer.spec.js
=> Transfer: add chalk theme

examples/docs/en-US/switch.md, examples/docs/zh-CN/switch.md, packages/switch/src/component.vue, packages/theme-chalk/src/common/var.scss, packages/theme-chalk/src/switch.scss, test/unit/specs/switch.spec.js
=> Switch: add chalk theme

src/utils/clickoutside.js
=> Clickoutside: id should be unique among all nodes

packages/theme-chalk/src/tabs.scss
=> Tabs: add chalk theme

packages/popover/src/main.vue, packages/theme-chalk/src/common/var.scss, packages/theme-chalk/src/mixins/mixins.scss, packages/theme-chalk/src/popover.scss
=> Popover: add chalk theme

examples/docs/en-US/card.md, examples/docs/zh-CN/card.md, packages/theme-chalk/src/card.scss, packages/theme-chalk/src/common/var.scss, packages/theme-chalk/src/tree.scss
=> Card: add chalk theme

examples/docs/en-US/tag.md, examples/docs/zh-CN/tag.md, packages/theme-chalk/src/common/var.scss, packages/theme-chalk/src/tag.scss
=> Tag: add chalk theme

packages/date-picker/src/panel/time.vue
=> TimePicker: fix cancel button

examples/docs/en-US/color-picker.md, examples/docs/zh-CN/color-picker.md, packages/color-picker/src/main.vue, packages/theme-chalk/src/color-picker.scss, packages/theme-chalk/src/common/var.scss
=> ColorPicker: add chalk theme

packages/select/src/select.vue, test/unit/specs/select.spec.js
=> Select: move setSelect to mounted hook

examples/docs/en-US/input.md, examples/docs/en-US/tooltip.md, examples/docs/zh-CN/input.md, examples/docs/zh-CN/tooltip.md, packages/tooltip/src/main.js
=> Tooltip: update zh-CN doc

packages/upload/src/ajax.js
forEach is much better in this situation.
=> Upload: convert map to forEach

packages/upload/src/index.vue
=> Upload: convert var to const and let

examples/docs/en-US/message-box.md, examples/docs/zh-CN/message-box.md
=> MessageBox: update docs

examples/docs/en-US/menu.md, examples/docs/zh-CN/menu.md, packages/menu/src/menu-item-group.vue, packages/menu/src/menu-item.vue, packages/menu/src/menu.vue, packages/menu/src/submenu.vue, packages/theme-chalk/src/aside.scss, packages/theme-chalk/src/common/var.scss, packages/theme-chalk/src/menu.scss, test/unit/specs/menu.spec.js
=> Menu: add chalk theme

examples/docs/en-US/i18n.md, examples/docs/zh-CN/i18n.md, packages/table/src/filter-panel.vue, src/locale/lang/he.js
=> Table: fix single filter active state

packages/upload/src/upload.vue
=> Upload: fix handleRemove param error

packages/cascader/src/main.vue, packages/theme-chalk/src/cascader.scss, packages/theme-chalk/src/common/var.scss, packages/theme-chalk/src/option.scss, packages/theme-chalk/src/select-dropdown.scss, packages/theme-chalk/src/select.scss, test/unit/specs/cascader.spec.js, test/unit/specs/color-picker.spec.js
=> update Select and Cascader chalk theme

packages/loading/src/directive.js
=> Loading: 应该使用 const

packages/form/src/form-item.vue
=> Form-item: fix typo

packages/date-picker/src/panel/date.vue
=> DatePicker: fix date input format

packages/select/src/select.vue
=> Select: return when query is null

packages/slider/src/button.vue
=> Slider: fix button jumping to previous value when clicked

examples/docs/en-US/input.md, examples/docs/zh-CN/input.md, packages/autocomplete/src/autocomplete-suggestions.vue, packages/autocomplete/src/autocomplete.vue, packages/table/src/table-column.js, packages/theme-chalk/src/autocomplete.scss, test/unit/specs/autocomplete.spec.js, test/unit/specs/table.spec.js
=> Autocomplete: support scoped slot as custom template

packages/cascader/src/menu.vue
=> Cascader: fix filter

examples/docs/en-US/tree.md, examples/docs/zh-CN/tree.md, packages/tree/src/model/node.js
=> Tree: get prop from data if not specified in `props`

examples/docs/en-US/notification.md, examples/docs/zh-CN/notification.md, packages/cascader/src/main.vue, packages/cascader/src/menu.vue, packages/theme-chalk/src/cascader.scss, packages/theme-chalk/src/index.scss, test/unit/specs/cascader.spec.js
=> update notification docs

examples/docs/zh-CN/slider.md, packages/menu/src/menu-item.vue, packages/menu/src/menu.vue, packages/menu/src/submenu.vue, packages/slider/src/button.vue, packages/slider/src/main.vue, packages/theme-chalk/src/menu.scss, src/utils/aria-utils.js, src/utils/menu/aria-menubar.js, src/utils/menu/aria-menuitem.js, src/utils/menu/aria-submenu.js, test/unit/specs/cascader.spec.js, test/unit/util.js
【Unit test】
1、add vm.$destory to testunit and fixbug for cascader.spec   
【Menu】
1、add Keyboard Interaction when horizontal
you can use tab and shift tab to through in menubar items 
when focus menuitem, you can use left/right/down/up to  moveto and interact with  submenu
use space and enter to select one menuitem
2、add role menubar and menuitem and some aria attrs for screen reader
【Slider】
1、add Keyboard Interaction
you can tab to a slider and use left/right/down/up to change value for it
2、add role and some aria attrs for screen reader
=> 【Menu & Slider】 add accessibility

packages/date-picker/src/panel/date-range.vue
=> DatePicker: fix initial value of [] in range type

examples/app.vue, examples/docs/en-US/button.md, examples/docs/en-US/color.md, examples/docs/en-US/icon.md, examples/docs/zh-CN/button.md, examples/docs/zh-CN/color.md, examples/docs/zh-CN/icon.md, packages/button/src/button.vue, test/unit/specs/button.spec.js
=> update color docs

build/bin/version.js, build/deploy-ci.sh, build/git-release.sh, build/release.sh
=> update release & deploy scripts

examples/app.vue
=> add 2.0 alpha notification

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, examples/app.vue, examples/components/demo-block.vue, examples/components/footer.vue, examples/components/side-nav.vue, examples/docs/en-US/installation.md, examples/docs/zh-CN/installation.md, examples/pages/template/changelog.tpl, packages/date-picker/src/basic/time-spinner.vue, packages/theme-chalk/src/menu.scss, packages/theme-chalk/src/transfer.scss
=>  Changelog: update for 2.0.0-alpha.1

examples/components/header.vue, examples/pages/template/component.tpl
=> fix backToTop button

packages/form/src/form-item.vue
=> Form-item: fix "required" attribute is not effective for validation

packages/menu/src/menu-mixin.js, packages/menu/src/menu.vue, src/utils/menu/aria-menubar.js, src/utils/menu/aria-menuitem.js, src/utils/menu/aria-submenu.js
=> Menu: fix setAttribute error

examples/components/demo-block.vue, examples/components/side-nav.vue, examples/docs/en-US/color-picker.md, examples/docs/en-US/dropdown.md, examples/docs/en-US/switch.md, examples/docs/en-US/transition.md, examples/docs/en-US/upload.md, examples/docs/zh-CN/color-picker.md, examples/docs/zh-CN/dropdown.md, examples/docs/zh-CN/switch.md, examples/docs/zh-CN/transition.md, examples/docs/zh-CN/upload.md, examples/index.tpl, examples/pages/template/changelog.tpl, examples/pages/template/component.tpl, examples/pages/template/index.tpl, examples/pages/template/resource.tpl, packages/dropdown/src/dropdown-menu.vue
=> Dropdown: fix duplicate visibleArrow declaration

examples/app.vue, examples/components/header.vue, examples/pages/template/component.tpl, packages/theme-chalk/src/common/var.scss
=> docs responsive

examples/components/header.vue, examples/components/theme-picker.vue, examples/docs/en-US/color-picker.md, examples/docs/en-US/loading.md, examples/docs/zh-CN/color-picker.md, examples/docs/zh-CN/loading.md, packages/color-picker/src/main.vue, packages/theme-chalk/src/common/var.scss
=> update primary color & add popper-class for ColorPicker

examples/components/theme-picker.vue, packages/button/src/button.vue
=> Button: fix disabled attribute

examples/components/theme-picker.vue
=> update docs theme switcher

examples/components/theme-picker.vue
=> fix docs theme switch bug

packages/table/src/table-header.js
=> Table: Add `important` rule to `col-resize` cursor

packages/date-picker/src/panel/date.vue, packages/date-picker/src/panel/time.vue, test/unit/specs/date-picker.spec.js
* fix https://github.com/ElemeFE/element/pull/7367#discussion_r143962493
* add tests
=> Carbon fix date time picker cancel

test/unit/specs/date-picker.spec.js
fix test.
There were warnings emitted in previous version
=> test: fix date-picker

examples/docs/zh-CN/message-box.md, packages/message-box/src/main.vue, packages/message/src/main.vue, packages/radio/src/radio-button.vue, packages/radio/src/radio.vue, packages/tabs/src/tab-nav.vue, packages/tabs/src/tab-pane.vue, packages/tabs/src/tabs.vue, packages/theme-chalk/src/message.scss, packages/theme-chalk/src/radio-button.scss, packages/theme-chalk/src/radio.scss, packages/theme-chalk/src/tabs.scss, src/utils/aria-dialog.js, src/utils/popup/popup-manager.js, test/unit/specs/message-box.spec.js
message
1、add aria role & attrs & props
2、you can use esc close message and delete key to cancel the duration limit and any other key continue duration
3、focus will back to the previous element when message-box closed
message-box
1、add aria role & attrs & props
2、you can use tab key moves focus to the tabbable element inside the message-box
3、focus will back to the previous element when message-box closed
tabs
1、add aria role & attrs & props
2、you can use tab key moves into the tab list,places focus on the active tab element and use left/right/up/down key tab through tab list
radio style
1、add :focus style for radios
=> 	add accessibility for message & message-box & tabs

.gitignore, CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, examples/app.vue, examples/docs/en-US/switch.md, examples/docs/zh-CN/switch.md
=> Changelog: update for 1.4.7

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, examples/docs/en-US/form.md, examples/docs/en-US/quickstart.md, examples/docs/zh-CN/form.md, examples/docs/zh-CN/quickstart.md, examples/pages/template/changelog.tpl, packages/autocomplete/src/autocomplete.vue, test/unit/specs/menu.spec.js
=> Changelog: update for 2.0.0-alpha.3

package.json
feat(form): validate() return promise
=> feat(form): validate() return promise

packages/date-picker/src/picker.vue, packages/date-picker/src/util/index.js, test/unit/specs/date-picker.spec.js
see https://github.com/ElemeFE/element/pull/7367#issuecomment-336879651
修 bug
修错别字 😅🌚
=> date-picker: fix typo, fix value-format parsing

packages/date-picker/src/picker.vue, test/unit/specs/date-picker.spec.js
Follow up: https://github.com/ElemeFE/element/pull/7518
=> DatePicker: fix value format change params

src/locale/lang/tk.js
=> Locale: [tk] translated new strings and improved old ones

packages/input/src/calcTextareaHeight.js, packages/input/src/input.vue, packages/message-box/src/main.vue, packages/select/src/select.vue, yarn.lock
=> minor fixes for select, message-box and textarea

packages/theme-chalk/src/tag.scss
* [✔️ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [✔️ ] Make sure you are merging your commits to `dev` branch.
* [✔️] Add some descriptions and refer relative issues for you PR.
=> Fix padding for mini Tag without close

examples/components/demo-block.vue, examples/docs/en-US/icon.md, examples/docs/zh-CN/icon.md, examples/pages/template/component.tpl, packages/date-picker/src/picker.vue, packages/theme-chalk/src/date-picker/picker.scss, packages/theme-chalk/src/icon.scss, packages/theme-chalk/src/menu.scss, packages/theme-chalk/src/tabs.scss
=> DatePicker: fix disabled in range mode

packages/menu/src/menu.vue, packages/theme-default/src/menu.css
=> Menu: fix close menu bug

examples/docs/en-US/date-picker.md, examples/docs/en-US/layout.md, examples/docs/en-US/select.md, examples/docs/en-US/switch.md, examples/docs/zh-CN/date-picker.md, examples/docs/zh-CN/layout.md, examples/docs/zh-CN/select.md, examples/docs/zh-CN/switch.md, packages/col/src/col.js, packages/select/src/select.vue, packages/switch/src/component.vue, packages/theme-chalk/src/col.scss, packages/theme-chalk/src/common/var.scss, packages/theme-chalk/src/select-dropdown.scss, test/unit/specs/switch.spec.js, types/col.d.ts, types/switch.d.ts
=> Layout: add xl breakpoint

examples/docs/en-US/layout.md, packages/theme-chalk/src/display.scss
=> Carbon: fix hide to hidden in display.scss

examples/docs/en-US/table.md, examples/docs/zh-CN/table.md, packages/table/src/table-body.js, packages/table/src/table-column.js, packages/table/src/table-header.js, packages/table/src/table-layout.js, packages/table/src/table-store.js, packages/table/src/table.vue, packages/table/src/util.js, packages/theme-chalk/src/mixins/mixins.scss, packages/theme-chalk/src/table.scss
=> Carbon: Table add features and fix bugs

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, examples/docs/en-US/table.md, examples/docs/zh-CN/table.md, yarn.lock
=> Changelog: update for 2.0.0-beta.1

examples/app.vue, examples/index.tpl
=> update beta notice

examples/docs/en-US/form.md, examples/docs/zh-CN/form.md, packages/form/src/form-item.vue, packages/form/src/form.vue, packages/input/src/input.vue
=> Form: add clearValidate

packages/theme-chalk/src/mixins/_button.scss
=> Button: fix round button sizes

build/deploy-faas.sh, build/release.sh, examples/components/footer.vue, examples/docs/en-US/input.md, examples/docs/en-US/tree.md, examples/docs/zh-CN/input.md, examples/docs/zh-CN/tree.md, examples/pages/template/index.tpl, package.json, packages/autocomplete/src/autocomplete.vue, test/unit/specs/autocomplete.spec.js, types/autocomplete.d.ts
=> Autocomplete: add value-key

packages/collapse/src/collapse-item.vue, packages/collapse/src/collapse.vue
=> fix collapse  bug

examples/docs/en-US/custom-theme.md, examples/docs/en-US/form.md, examples/docs/zh-CN/custom-theme.md, examples/docs/zh-CN/form.md, packages/select/src/select.vue
=> update custom theme docs

packages/input/src/input.vue
=> Input: remove textarea extra close tag

packages/date-picker/src/picker.vue
https://github.com/ElemeFE/element/issues/6045#issuecomment-339322157
=> date-picker: support array for name attr

packages/date-picker/src/picker.vue, packages/select/src/select.vue
Increases accessibility by providing a way to set the ```id``` attribute on the input inside of ```el-date-picker``` and ```el-select```
Fixes #7728
=> Fixes #7728 by ensuring id attribute gets set to input

packages/date-picker/src/picker.vue
used fix for 2.0 from #7725 to address #6045
=> date-picker: added name attr support

test/unit/specs/input-number.spec.js
=> test: add change event test for input-number

examples/pages/template/index.tpl, packages/date-picker/src/picker.vue, packages/form/src/form-item.vue, packages/select/src/select.vue, types/index.d.ts
=> misc updates and fixes

packages/date-picker/src/panel/date-range.vue, packages/date-picker/src/panel/date.vue, packages/date-picker/src/panel/time-range.vue, packages/date-picker/src/panel/time-select.vue, test/unit/specs/date-picker.spec.js
fix https://github.com/ElemeFE/element/issues/7730
原来的测试有问题：https://jsfiddle.net/0hva15Lc/1/
=> picker: fix clear value

build/deploy-ci.sh, build/deploy-faas.sh, build/git-release.sh, build/release.sh, packages/form/src/form-item.vue
=> Form: fix validateDisabled

build/deploy-ci.sh, build/deploy-faas.sh, build/git-release.sh, build/release.sh, examples/components/demo-block.vue, examples/components/header.vue, examples/docs/en-US/installation.md, examples/docs/en-US/quickstart.md, examples/docs/zh-CN/installation.md, examples/docs/zh-CN/quickstart.md
=> update release scripts

src/utils/util.js
=> fix getPropByPath error

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, README.md, examples/app.vue, examples/docs/en-US/quickstart.md, examples/docs/zh-CN/quickstart.md, examples/i18n/page.json, examples/pages/template/index.tpl, packages/collapse/src/collapse-item.vue, packages/tabs/src/tab-bar.vue, packages/theme-chalk/src/tabs.scss
=> Changelog: update for 2.0.0

examples/docs/en-US/i18n.md, examples/docs/en-US/installation.md, examples/docs/zh-CN/i18n.md, examples/docs/zh-CN/installation.md
=> lock CDN resource version for 1.x docs

build/deploy-faas.sh, packages/checkbox/src/checkbox-button.vue, packages/checkbox/src/checkbox-group.vue, packages/checkbox/src/checkbox.vue
=> Checkbox: fix change event param

src/directives/repeat-click.js
=> RepeatClick: ignore right button down

packages/form/src/form.vue
修复 element 2.x 表单异步验证结果不正确的 bug。
> 如果表单项有异步验证，form.validate 方法没有等到异步验证结果就完成验证了
=> Form: fix async validate bug

packages/input-number/src/input-number.vue
input-number allow input '.' '-'
=> input-number allow input '.' '-'

examples/docs/en-US/installation.md, examples/docs/en-US/quickstart.md, examples/docs/zh-CN/installation.md, examples/docs/zh-CN/quickstart.md
=> add CDN tips

packages/tree/src/model/tree-store.js
=> Tree: reserve node expanding state while filtering

packages/theme-chalk/src/upload.scss, packages/upload/src/upload-list.vue
=> Upload: fix icons in list type

packages/select/src/select.vue
=> Select: fix input height of mini size

FAQ.md
=> FAQ: update attribute `slot-scope` for Vue 2.5.0+

examples/docs/en-US/notification.md, examples/docs/zh-CN/notification.md
- Notification: improve position option
=> Notification: improve position option

README.md
=> chore: remove cooking

packages/upload/src/upload.vue
[Can the upload file type of [Feature Request] upload component support the Blob type?]https://github.com/ElemeFE/element/issues/7628
=> upload: Increase support for Blob types

packages/theme-chalk/src/tabs.scss
=> Tabs: fix padding-left for nested tabs

packages/message/src/main.vue
=> Message: restore focus only when target in viewport

build/bin/build-entry.js
See #7939, #7940 
@Leopoldthecoder
=> Fix inconsistency of the TypeScript definitions

build/bin/version.js, examples/components/footer-nav.vue, examples/components/side-nav.vue, examples/docs/en-US/custom-theme.md, examples/docs/en-US/form.md, examples/docs/en-US/installation.md, examples/docs/en-US/quickstart.md, examples/docs/zh-CN/custom-theme.md, examples/docs/zh-CN/form.md, examples/docs/zh-CN/installation.md, examples/docs/zh-CN/quickstart.md, examples/docs/zh-CN/upload.md, examples/nav.config.json, packages/theme-chalk/src/collapse.scss, packages/theme-chalk/src/common/var.scss, packages/theme-chalk/src/select.scss, packages/theme-chalk/src/table.scss, packages/upload/src/upload-list.vue, src/index.js
=> Chore: misc fixes and updates

packages/select/src/select.vue, packages/theme-chalk/src/select.scss
=> Select: show dropdown on input focus

packages/menu/src/menu-item.vue
=> Menu: register el-tooltip

packages/tree/src/model/tree-store.js
=> Tree: fix updateKeyChildren

packages/theme-chalk/src/slider.scss, packages/theme-chalk/src/tabs.scss
=> Chalk: fix styles for vertical Slider and nested Tabs

examples/docs/en-US/switch.md
=> Switch: fix an en doc typo

packages/menu/src/menu.vue, packages/theme-chalk/src/container.scss, packages/theme-chalk/src/pagination.scss
=> Container: add min-width

src/locale/lang/fr.js
=> Complete french translation 🇫🇷

examples/docs/es/color.md
=> [Color]: Spanish translation

examples/docs/es/alert.md, examples/docs/es/badge.md, examples/docs/es/breadcrumb.md, examples/docs/es/button.md
=> docs/es - translation to Spanish

packages/theme-chalk/src/tree.scss, packages/tree/src/tree-node.vue, packages/tree/src/tree.vue, yarn.lock
1、使用tab键可导航至组件，有选中项时 聚集到第一个选中项，没有则聚焦到第一个元素，你可以使用up/down依次操作treeitem,可以使用left/right键展开 treeitem节点，使用enter/space键选中带checkbox的节点；
2、为组件添加了 role= tree等相关的ARIA属性
=> 【accessibility】Tree

examples/docs/zh-CN/popover.md, examples/docs/zh-CN/tooltip.md, packages/message/src/main.vue, packages/notification/src/main.vue, packages/popover/src/main.vue, packages/theme-chalk/src/tooltip.scss, packages/tooltip/src/main.js
popover & tooltip
1、when you  focus the trigger element , the tooltip will show and  notice the AT
message & Notification
1、when you  focus the trigger element , press enter key the message will show and notice the AT
=> 【accessibility】popover & tooltip & message & Notification

examples/app.vue, examples/docs/zh-CN/popover.md, examples/docs/zh-CN/tooltip.md, examples/nav.config.json, packages/menu/src/submenu.vue, packages/message/src/main.vue, packages/radio/src/radio-group.vue, packages/theme-chalk/src/checkbox.scss, packages/theme-chalk/src/common/var.scss, packages/theme-chalk/src/radio.scss, packages/tree/src/model/tree-store.js
=> Tree: fix updateChildren

examples/docs/es/container.md
=> [Container] Spanish translation

examples/docs/es/custom-theme.md
=> [custom-theme] Spanish translation

examples/docs/es/checkbox.md, examples/docs/es/collapse.md, examples/docs/es/color-picker.md
=> Translated to spanish - checkbox, collapse and color-picker

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, packages/upload/src/ajax.js, test/unit/specs/upload.spec.js
=> Changelog: update for 2.0.4

examples/docs/es/switch.md
=> switch.md spanish version

examples/docs/es/upload.md
=> [upload] Spanish Translation

examples/docs/es/installation.md, examples/docs/es/layout.md, examples/docs/es/menu.md, examples/docs/es/pagination.md, examples/docs/es/popover.md, examples/docs/es/progress.md
=> Spanish translations.

packages/popover/src/main.vue, packages/theme-chalk/src/popover.scss
=> Popover: fix click trigger

examples/docs/en-US/select.md, examples/docs/zh-CN/select.md, packages/select/src/select.vue, packages/table/src/table-header.js, packages/theme-chalk/src/select.scss, packages/theme-chalk/src/table.scss
=> Table: sort arrow nostalgia

examples/docs/es/loading.md
=> [loading] Spanish translation

examples/docs/es/select.md
=> update es Select doc

packages/breadcrumb/src/breadcrumb.vue, packages/tree/src/tree.vue
=> Tree & Breadcrumb: fix setAttribute to undefined bug

examples/docs/es/message.md
=> Documentation message Spanish

examples/docs/es/tabs.md, examples/docs/es/time-picker.md, examples/docs/es/tooltip.md
Translated the documentation for Tabs, Time-picker and Tooltip to Spanish using the provided Markup.
=> Docs translation (tabs, time-picker, tooltip)

examples/docs/es/table.md
=> [table] Spanish translation

packages/message-box/src/main.vue
=> MessageBox: ensure to get input element

packages/tree/src/tree.vue
=> Tree: fix keyboard event

packages/input/src/input.vue, test/unit/specs/message-box.spec.js
followup: https://github.com/ElemeFE/element/pull/8279, https://github.com/ElemeFE/element/issues/8269
=> input: fix focus

examples/docs/es/transfer.md, examples/docs/es/transition.md, examples/docs/es/tree.md
=> Added spanish documentation for Transfer, Transition and Tree

src/locale/lang/nl.js
=> Complete Dutch Translation

src/locale/lang/ko.js
=> Translate korean

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
=> Changelog: update for 2.0.5

CONTRIBUTING.es.md, FAQ-zh-en-es.md
=> Spanish Translation of CONTRIBUTING.md

examples/docs/es/select.md
=> select.md spanish version update

src/locale/lang/fa.js
translate some words in farsi lang
=> Translate some words

packages/tag/src/tag.vue
=> Button: fix closeEvent bug

examples/docs/en-US/select.md, examples/docs/zh-CN/select.md, packages/select/src/select.vue, packages/theme-chalk/src/select.scss
=> Select: fix filter input display in multiple mode

packages/date-picker/src/panel/date-range.vue
1.no init data
2.click start time and comfirm
3.click end time and comfirm(the end time is not change)
4.error
reason:
not evaluate 'maxDate' value in step2
I will show more details in conversation
=> [date-time-picker]:fix bug

examples/docs/es/notification.md, examples/docs/es/select.md
=> notification.md spanish version

packages/dropdown/src/dropdown-menu.vue
=> dropdown-menu size

examples/docs/es/date-picker.md, examples/docs/es/datetime-picker.md, examples/docs/es/dialog.md
=> datepicker. Spanish doc

examples/docs/en-US/cascader.md, examples/docs/zh-CN/cascader.md, packages/cascader/src/main.vue
=> Cascader: add separator prop

packages/select/src/select.vue
=> Select: fix input height when props.size not assigned

packages/table/src/table-column.js
=> Table: expand column supports label

packages/theme-chalk/src/button.scss
=> Button: fix disabled text button style

examples/docs/en-US/input.md, examples/docs/zh-CN/input.md
=> Chore: update input docs

src/locale/lang/mn.js
=> Complete Mongolian translation :mn:

src/locale/lang/kz.js
=> Added Kazakh language to the locale :)

examples/docs/en-US/date-picker.md, examples/docs/en-US/datetime-picker.md, examples/docs/en-US/time-picker.md, examples/docs/zh-CN/date-picker.md, examples/docs/zh-CN/datetime-picker.md, examples/docs/zh-CN/time-picker.md, packages/date-picker/README.md
Add Document for AM/PM `A` time format
#8270
=> Add Document for AM/PM `A` time format

CHANGELOG.es-SP.md
=> changelog spanish

packages/tooltip/src/main.js
=> Tooltip: fix extra spaces before class 'focusing' when focus multi times

src/locale/lang/hu.js
Added Hungarian language to the locale
* [x ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ x] Add some descriptions and refer relative issues for you PR.
=> Added Hungarian language to the locale

packages/form/src/form-item.vue
=> Form: support nested rules

examples/docs/en-US/custom-theme.md, examples/docs/zh-CN/custom-theme.md
[scss-loader](https://github.com/webpack-contrib/sass-loader#imports) has been updated.
> The sass-loader uses node-sass' custom importer feature to pass all queries to the webpack   resolving engine. Thus you can import your Sass modules from node_modules. Just prepend them with a ~ to tell webpack that this is not a relative import:
=> update scss import

examples/docs/en-US/date-picker.md, examples/docs/en-US/datetime-picker.md, examples/docs/en-US/time-picker.md, examples/docs/es/date-picker.md, examples/docs/es/datetime-picker.md, examples/docs/es/time-picker.md, examples/docs/zh-CN/date-picker.md, examples/docs/zh-CN/datetime-picker.md, examples/docs/zh-CN/time-picker.md, packages/date-picker/src/picker.vue, test/unit/specs/date-picker.spec.js, test/unit/specs/time-picker.spec.js, test/unit/specs/time-select.spec.js
=> Picker: fix blur event

CHANGELOG.en-US.md, CHANGELOG.es.md, CHANGELOG.zh-CN.md, examples/docs/en-US/i18n.md, examples/docs/es/i18n.md, examples/docs/zh-CN/i18n.md, packages/form/src/form-item.vue
=> Changelog: update for 2.0.8

packages/select/src/select.vue
=> Select: fix default-first-option on created options

packages/table/src/table-header.js, packages/theme-chalk/src/table.scss
=> Table: replace sorting arrow icons with borders to avoid overlap

CHANGELOG.es.md
=> Update changelog spanish

examples/docs/zh-CN/i18n.md
=> Doc:fix use vue-i18n@6.x typo

packages/carousel/src/main.vue
=> Carousel: add type="button" to navigation buttons

examples/docs/en-US/color.md, examples/docs/en-US/i18n.md, examples/docs/en-US/select.md, examples/docs/en-US/upload.md, examples/docs/es/color.md, examples/docs/es/i18n.md, examples/docs/zh-CN/i18n.md, examples/docs/zh-CN/select.md, examples/docs/zh-CN/upload.md, packages/tree/src/tree.vue, packages/upload/src/index.vue
=> Chore: misc updates

packages/form/src/form-item.vue
=> Form: fix initial error message

packages/loading/src/directive.js, test/unit/specs/loading.spec.js
=> loading directive customClass

packages/autocomplete/src/autocomplete.vue, packages/theme-chalk/src/popover.scss
=> Autocomplete: support maxlength and minlength

packages/table/src/table-column.js
=> fix: the width prop of el-table-column is invalid when it is 0

.gitignore, README.md, examples/assets/images/tipe.svg, examples/components/footer.vue, examples/docs/en-US/table.md, examples/docs/es/table.md, examples/docs/zh-CN/table.md, examples/pages/template/index.tpl
=> add sponsor logo

packages/form/src/form-item.vue
=> Form: fix support for dot-separated rule key

packages/theme-chalk/src/date-picker/picker.scss
=> Picker: perf el-icon-circle-close hover effect

types/element-ui.d.ts, types/time-select.d.ts
=> Types: add missing definition for TimeSelect

packages/loading/src/directive.js
=> Loading: remove parent class when directive is unbound

packages/theme-chalk/src/switch.scss
=> Switch: fix style

packages/table/src/util.js
=> Table: Add eventListener option passive

examples/docs/zh-CN/menu.md
=> docs: update menu.md

examples/docs/en-US/tree.md, examples/docs/zh-CN/tree.md, packages/tree/src/tree-node.vue, packages/tree/src/tree.vue
=> Tree: add renderAfterExpand

CHANGELOG.es.md, examples/docs/es/tree.md, examples/docs/es/upload.md
=> Changelog: update for 2.0.9

packages/notification/src/main.js, packages/notification/src/main.vue, packages/theme-chalk/src/common/var.scss, packages/theme-chalk/src/notification.scss
=> Notification: fix style when message prop is omitted

packages/slider/src/main.vue
see discussion in: https://github.com/ElemeFE/element/issues/8989
=> Slider: mitigate high cpu usage (#8989)

packages/theme-chalk/src/table.scss
=> Table: Fix wrong compiled color

examples/docs/en-US/input.md, examples/docs/es/input.md, examples/docs/zh-CN/input.md, packages/input/src/input.vue
=> Input: Add el-input tabindex props(#9038)

packages/theme-chalk/src/table.scss
=> Table: Make thead cell inline-flex

packages/table/src/table.vue
=> Table: Fix wrong max height in fixed table

src/locale/lang/ro.js
=> i18n: Create ro.js

packages/date-picker/src/picker.vue
[issue#9027](https://github.com/ElemeFE/element/issues/9027)
=> Picker: Only emit 'change' event when value is changed.

examples/index.tpl
=> Docs: Replace cdn

build/bin/new.js
=> Chore: update 'make new' script

src/locale/lang/fr.js
cf: https://github.com/ElemeFE/element/pull/9053
Add a comment to explain why year must be empty, because we definitely will not remember that!
(I am the one who filled it the last time :/)
=> Add a comment in fr.js

README.md
=> docs: update docs link, fixed #9071

packages/theme-chalk/src/table.scss
=> revert: Revert table thead inline-flex

CHANGELOG.es.md, examples/docs/es/input.md
=> Changelog: update for 2.0.10

packages/tabs/src/tab-bar.vue
=> Tabs: fix active bar width when only one tab

packages/theme-chalk/src/input.scss
=> Input: remove blue border of Select when prepended/appended

packages/select/src/select.vue
=> Select: fix remove-tag event param

packages/menu/src/menu.vue, test/unit/specs/menu.spec.js
=> feat(Menu): rerender activeIndex when menus changed, fixed #9092

packages/theme-default/src/tabs.css
Tab:fix browser crash bug
#6773
=> Tab:fix browser crash bug

src/locale/lang/pt-br.js
5 terms translated from en to pt-br
=> Locale: update pt-br translations

src/utils/vdom.js
=> fix the case parameter node is null

packages/table/src/table-body.js, packages/table/src/table-column.js
1. remove condition due to rows has been accessed prior
2. change el-tooltip style from string to object
=> refactor: fix some code issues

examples/docs/en-US/menu.md, examples/docs/es/menu.md, examples/docs/zh-CN/menu.md, packages/menu/src/submenu.vue, types/submenu.d.ts
=> el-submenu add show-timeout,hide-timeout attributes

packages/theme-chalk/src/table.scss
=> Table: align sort arrows

packages/theme-chalk/src/common/var.scss
=> Transition: remove transition delay for fade transitions

packages/table/src/table-header.js
ISSUE RELATED：[#9099](https://github.com/ElemeFE/element/issues/9099)
=> TABLE: fix sort bug-- can't sort the same prop after clearSort

packages/tabs/src/tab-bar.vue, packages/tabs/src/tab-nav.vue, packages/tabs/src/tabs.vue, packages/theme-chalk/src/tabs.scss
=> Tabs: fix style bug when nested with different tab positions

CHANGELOG.en-US.md, CHANGELOG.es.md, CHANGELOG.zh-CN.md, examples/docs/en-US/menu.md, examples/docs/en-US/select.md, examples/docs/es/menu.md, examples/docs/zh-CN/menu.md, examples/route.config.js
=> Changelog: update for 2.0.11

examples/docs/en-US/input-number.md, examples/docs/es/input-number.md, examples/docs/zh-CN/input-number.md, packages/input-number/src/input-number.vue, test/unit/specs/input-number.spec.js
https://github.com/ElemeFE/element/issues/9116
=> input-number: fix user input parsing

src/locale/lang/cs-CZ.js
=> Locale: corrected czech translations

examples/docs/en-US/input.md, examples/docs/es/input.md
=> Input: Fix sample code typo

packages/message/src/main.vue, packages/theme-chalk/src/message.scss
=> Message: add content right padding when closable

types/form.d.ts
overload validate method
add clearValidate method
=> fix types (#9242)

examples/docs/en-US/cascader.md, examples/docs/zh-CN/cascader.md, packages/cascader/src/main.vue, test/unit/specs/cascader.spec.js
=> add cascader blur & focus event

.eslintignore, examples/app.vue, examples/docs/en-US/tree.md, examples/docs/zh-CN/tree.md
=> Chore: exclude play file from eslint, remove es-doc notification

examples/docs/en-US/table.md, examples/docs/es/table.md, examples/docs/zh-CN/table.md, packages/table/src/table-store.js
扩展`el-table-column` 的 `filter-method` 参数
具体需求, 参见 #9193
=> [el-table-column] expand filter-method param

examples/docs/es/date-picker.md, examples/docs/es/datetime-picker.md, examples/docs/es/table.md, examples/docs/es/time-picker.md, examples/docs/zh-CN/date-picker.md, examples/docs/zh-CN/datetime-picker.md, examples/docs/zh-CN/time-picker.md
=> Chore: update picker docs

packages/theme-chalk/src/upload.scss
=> fix overflow

packages/theme-chalk/src/table.scss
=> fix last table column border dispear in some condition

packages/theme-chalk/src/input.scss
=> hide input default clear button on ie

examples/index.tpl, packages/loading/src/directive.js, packages/loading/src/index.js, src/utils/after-leave.js
Fix #8894, current loading implementation have two problems:
1. Can not make sure after-leave will called.
2. Will not bind after-leave event in some condition.
=> Fixed loading: #8894

packages/tooltip/src/main.js
=> Tooltip: move event handlers adding to the mounted hook

src/utils/vue-popper.js
=> Fixed #9315: Update popper element zIndex after show again

examples/docs/en-US/date-picker.md, examples/docs/en-US/datetime-picker.md, examples/docs/es/date-picker.md, examples/docs/es/datetime-picker.md, examples/docs/zh-CN/date-picker.md, examples/docs/zh-CN/datetime-picker.md
=> DatePicker: update docs for default-time

packages/table/src/table-column.js, packages/table/src/table-header.js, packages/table/src/table.vue
Fixed:
1. fix table column width bug in safari #7833 
2. hide shadow of fixed when scrollX is false #8172
=> Fix two table style issue

src/locale/lang/tr-TR.js
=> incomplete tr-TR translation completed

packages/theme-chalk/src/transfer.scss
=> add max-height to transfer-panel

packages/cascader/src/main.vue, packages/date-picker/src/picker.vue, packages/pagination/src/pagination.js, packages/popover/src/main.vue, packages/theme-chalk/src/autocomplete.scss, packages/theme-chalk/src/cascader.scss, packages/theme-chalk/src/date-picker/picker-panel.scss, packages/theme-chalk/src/date-picker/time-picker.scss, packages/theme-chalk/src/select-dropdown.scss, src/utils/popper.js, src/utils/vue-popper.js
=> Popper: fix arrow position

packages/dialog/src/component.vue, packages/select/src/select.vue
=> Select: remove unnecessary query when focused

packages/menu/src/menu-item.vue
=> support composite menu-item

packages/table/src/table-column.js, packages/table/src/table-store.js
=> fix: multi-header table remove column

packages/table/src/table-column.js, packages/table/src/table-store.js
=> Table: fix multi-header remove column (#9377)

packages/theme-chalk/src/date-picker/date-table.scss
=> dateTimePick: add today bold style

packages/date-picker/src/picker.vue, test/unit/specs/date-picker.spec.js, test/unit/specs/form.spec.js
https://github.com/ElemeFE/element/issues/9276
=> date-picker: fix #9276

packages/loading/src/directive.js
=> fix export default for loading directive to avoid grammar error

packages/date-picker/src/picker.vue
=> date-picker: fixed range type can not focus

build/bin/build-entry.js, packages/theme-chalk/src/common/var.scss, packages/theme-chalk/src/dialog.scss, src/index.js
=> Dialog: update paddings

examples/docs/en-US/select.md, examples/docs/es/select.md, examples/docs/zh-CN/select.md, packages/select/src/select.vue
=> Select: add auto-complete

packages/date-picker/src/panel/date.vue, test/unit/specs/date-picker.spec.js
https://github.com/ElemeFE/element/issues/9346
顺便修一下以前一段放错位置的daterange测试（捂脸
=> date-time-picker: changeToNow cheks disabledDate

packages/steps/src/step.vue
=> Step: fix flex-basis when align-center is true

README.md, examples/components/footer.vue, examples/nav.config.json, packages/select/src/select.vue, packages/theme-chalk/src/select.scss
=> Select: keep input height if not expanded

packages/tabs/src/tab-nav.vue, packages/theme-chalk/src/tabs.scss
=> tabs: add focus style

package.json, packages/table/src/table.vue, packages/table/src/util.js, src/directives/mousewheel.js, yarn.lock
=> Forward fixed column's mousewheel event to entire table

examples/docs/en-US/upload.md, examples/docs/es/upload.md, examples/docs/zh-CN/upload.md, packages/theme-chalk/src/input.scss
=> Input: el-input styles should override el-textarea

examples/docs/en-US/table.md
=> Doc: update Table's header-dragend description

examples/docs/en-US/message.md, examples/docs/en-US/notification.md, examples/docs/es/message.md, examples/docs/es/notification.md, examples/docs/zh-CN/message.md, examples/docs/zh-CN/notification.md, packages/notification/src/main.js
=> Notification: add closeAll

packages/loading/src/directive.js, packages/loading/src/index.js, packages/theme-chalk/src/loading.scss
=> Loading: use popup-manager to handle fullscreen z-index

examples/docs/en-US/form.md, examples/docs/es/form.md, examples/docs/zh-CN/form.md, packages/cascader/src/main.vue, packages/checkbox/src/checkbox-button.vue, packages/checkbox/src/checkbox.vue, packages/color-picker/src/main.vue, packages/date-picker/src/picker.vue, packages/form/src/form.vue, packages/input-number/src/input-number.vue, packages/input/src/input.vue, packages/radio/src/radio-button.vue, packages/radio/src/radio.vue, packages/rate/src/main.vue, packages/select/src/select.vue, packages/slider/src/button.vue, packages/slider/src/main.vue, packages/switch/src/component.vue, packages/theme-chalk/src/slider.scss, packages/upload/src/index.vue, types/form.d.ts
=> Form: add disabled

examples/docs/en-US/table.md, examples/docs/es/table.md, examples/docs/zh-CN/table.md, packages/table/src/table-header.js
Adding contextmenu event for column header.
=> [Table] Column header's contextmenu event for right click

examples/docs/en-US/dialog.md, examples/docs/es/dialog.md
Remove a t I don't think is meant to be there
----
=> Docs: Fix typo

examples/docs/zh-CN/table.md, packages/theme-chalk/src/input.scss
=> Input: fix appended button style in IE11

packages/pagination/src/pagination.js
=> Pagination: add keyup event to jumper so it works in IE11

packages/table/src/table-column.js
This indeterminate state when only some rows are selected will make the component behavior consistent with that of the Transfer component.
Fixed #9508
=> Table: Add indeterminate & disabled state to multiple selection header checkbox

types/notification.d.ts
Notification: add position definition for ElNotificationOptions
=> Notification: add position definition for ElNotificationOptions

packages/theme-chalk/src/table.scss
=> fix Table expand row hover style

packages/table/src/table-store.js
=> change arg selection to cloned array of Table selection-change event

packages/collapse/src/collapse-item.vue, packages/theme-chalk/src/collapse.scss
=> Collapse: fix nested collapse-item style

examples/docs/en-US/table.md, examples/docs/zh-CN/table.md, packages/table/src/table-layout.js, test/unit/specs/table.spec.js
Fixed #8896 
Fixed #7596 
Fixed #4109.
=> Improve table height prop usage

packages/date-picker/src/panel/date-range.vue, packages/date-picker/src/panel/date.vue, packages/date-picker/src/util/index.js, test/unit/specs/date-picker.spec.js
https://github.com/ElemeFE/element/issues/9572
=> date-picker: fix date clamping during navigation

packages/popover/src/directive.js
=> v-popover指令不能使用变量值问题

examples/docs/en-US/menu.md, examples/docs/es/menu.md, examples/docs/zh-CN/menu.md, packages/menu/src/submenu.vue
=> Menu: add popper-class for SubMenu

packages/table/src/table-store.js
=> Table: update selection isAllSelected

examples/docs/en-US/input.md, examples/docs/es/input.md, examples/docs/zh-CN/input.md
`valueKey` should be `value-key` for better naming consistency, see also https://github.com/ElemeFE/element/issues/9322
=> Input: fix prop valueKey doc 

packages/table/src/table-body.js, packages/table/src/table-column.js
=> Table: stop expansion click from bubbling

packages/theme-chalk/src/container.scss, packages/theme-chalk/src/main.scss
=> Layout: add flex-basis so it works in IE11

packages/table/src/table-layout.js
=> Table: initial value of height can be 0

packages/table/src/table.vue
=> fix table do not update layout in some condition

packages/table/src/table.vue
=> fix table summary row position drift when table has horizontal scrollbar

packages/table/src/table-layout.js
=> fix table will crash when initial columns is empty

examples/docs/en-US/tree.md, examples/docs/es/tree.md, examples/docs/zh-CN/tree.md, packages/tree/src/tree-node.vue, test/unit/specs/tree.spec.js
=> Tree: support scoped slot

.eslintignore, packages/table/src/table.vue
=> Chore: update .eslintignore

packages/collapse/src/collapse-item.vue
=> Collapse: add active class on el-collapse-item
