ElemeFE/element

- examples/docs/menu.md
- packages/checkbox/src/checkbox.vue
- packages/menu/src/menu-item-group.vue
- packages/menu/src/menu-item.vue
- packages/menu/src/menu.vue
- packages/menu/src/submenu.vue
- packages/theme-default/src/menu.css
- packages/theme-default/src/tree.css
1. 增加水平方向的子级菜单支持
2. 默认模式调整为 "horizontal"
> Menu fixed

- examples/docs/button.md
- examples/docs/dropdown.md
- examples/docs/icon.md
- examples/docs/input-number.md
- examples/docs/pagination.md
等pagination的select修复就应该跟UED一样了。
> update icon/input-number/pagination/button/dropdown docs

- .github/PULL_REQUEST_TEMPLATE.md
- LICENSE
- README.md
- package.json
> fix contribution url

- examples/components/footer-nav.vue
- examples/docs/pagination.md
- examples/entry.js
- examples/nav.config.json
- examples/pages/component.vue
- packages/select/src/select.vue
- packages/table/src/table-body.js
- packages/theme-default/src/pagination.css
- packages/theme-default/src/select.css
@baiyaaaaa @QingWei-Li @csvwolf
> add footer-nav

- examples/docs/popover.md
- packages/popover/src/main.vue
- src/utils/vue-popper.js
> Popover: add reference slot

- CHANGELOG.md
- package.json
- packages/table/src/table.vue
- scripts/cooking.common.js
- scripts/cooking.component.js
> Update config, default require commonjs package

- CHANGELOG.md
- packages/theme-default/src/input.css
> fix textarea style in form

- CHANGELOG.md
- packages/upload/src/index.vue
> Upload: missing headers

- bin/build-all.js
- bin/build-entry.js
- bin/iconInit.js
- bin/new.js
- package.json
- packages/message-box/cooking.conf.js
- packages/notification/cooking.conf.js
- packages/pagination/cooking.conf.js
- packages/popover/cooking.conf.js
- packages/progress/cooking.conf.js
- packages/radio/cooking.conf.js
- packages/rate/cooking.conf.js
- packages/row/cooking.conf.js
- packages/select-dropdown/cooking.conf.js
- packages/select/cooking.conf.js
- packages/slider/cooking.conf.js
- packages/spinner/cooking.conf.js
- packages/steps/cooking.conf.js
- packages/switch/cooking.conf.js
- packages/table/cooking.conf.js
- packages/tabs/cooking.conf.js
- packages/tag/cooking.conf.js
- packages/theme-default/gulpfile.js
- packages/tooltip/cooking.conf.js
- packages/tree/cooking.conf.js
- packages/upload/cooking.conf.js
- scripts/cooking.component.js
- scripts/cooking.demo.js
- src/utils/strip-tags.js
加了 eslint，锁定了 vue 的版本，升级 vue 手动改版本号
> package: add lint script & lock vue version

- package.json
> v1.0.0-rc.2

- examples/docs/upload.md
> Upload: update doc

- packages/theme-default/src/step.css
> Steps: fix line

- Makefile
- package.json
> package: remove postinstall hook

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- README.md
> Update gitter link

- examples/docs/tag.md
- packages/theme-default/src/input-number.css
> Input-number: fix input-number style in form & Tag: fix a mistake in the doc

- examples/docs/time-picker.md
- packages/date-picker/src/panel/time-range.vue
- packages/date-picker/src/panel/time.vue
- packages/date-picker/src/picker.vue
- packages/select/src/option-group.vue
> TimePicker: set default value

- package.json
> update cooking version

- packages/table/src/table.vue
> Table : 解决固定某一列的时候滚动条在冻结列不能被拖动的问题

- CHANGELOG.md
- packages/date-picker/src/basic/time-spinner.vue
- packages/date-picker/src/css/time-picker.css
- packages/date-picker/src/css/time-spinner.css
> TimePicker: scrollable time picker

- CHANGELOG.md
- examples/docs/button.md
- examples/docs/datetime-picker.md
- examples/docs/input.md
- examples/docs/popover.md
- examples/docs/select.md
- examples/docs/tooltip.md
- packages/select/src/select.vue
- packages/theme-default/src/select.css
- packages/theme-default/src/slider.css
> update popover/tooltip docs

- Makefile
- package.json
- packages/table/src/table.vue
> Add homepage

- examples/app.vue
- examples/components/demo-block.vue
- examples/components/footer-nav.vue
- examples/components/footer.vue
- examples/components/header.vue
- examples/components/side-nav.vue
- examples/docs/color.md
- examples/docs/icon.md
- examples/docs/layout.md
- examples/pages/changelog.vue
- examples/pages/component.vue
- packages/slider/src/main.vue
> misc visual updates - round 2

- packages/table/src/table-header.js
> Table: fix gutter width,  #80, #78

- examples/pages/component.vue
- examples/pages/guide.vue
- packages/theme-default/src/col.css
> fixed col box style

- .gitignore
- examples/docs/development.md
> Update development page

- examples/docs/table.md
> table docs update

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- examples/pages/component.vue
- examples/pages/guide.vue
@furybean 贡献指南改了一些语句。准备以此为基础抽一个公共的模板出来（感觉把 element 相关的内容去掉就可以）
> update contributing guide

- examples/app.vue
- examples/nav.config.json
- examples/pages/index.vue
> update component classification

- examples/index.tpl
- scripts/cooking.demo.js
> fix template file

- CHANGELOG.md
- examples/docs/date-picker.md
- packages/date-picker/src/css/picker.css
> TimePicker: fix icon style, fixed #92

- examples/docs/table.md
- packages/table/src/table-body.js
- packages/table/src/table-column.js
- packages/table/src/table-header.js
- packages/theme-default/src/table.css
> TableColumn: add align attribute, #78

- CHANGELOG.md
- examples/docs/quickstart.md
- examples/pages/resource.vue
- package.json
- packages/dialog/package.json
- packages/message-box/package.json
- packages/message-box/src/main.vue
- packages/select/src/select.vue
> bug fixes/add resource download url

- bin/build-entry.js
- src/index.js
> Add 'version' attribute

- CHANGELOG.md
- examples/docs/date-picker.md
- packages/autocomplete/src/autocomplete.vue
- packages/date-picker/src/css/picker.css
- packages/date-picker/src/picker.vue
- 顺带修复了 TimePicker 的 icon
- Autocomplete 引入局部 clickoutside
> DatePicker: add align attribute

- examples/docs/quickstart.md
> doc: update quickstart

- examples/docs/date-picker.md
- examples/docs/datetime-picker.md
- examples/docs/message.md
> TimePicker: fix doc demo, fixed #92

- packages/table/src/table-column.js
- packages/table/src/table-header.js
> Table: el-table-column的type="index"并且如果设置了label 优先显示label

- src/utils/clickoutside.js
> clickoutside: fix incorrect unbind, and add update method

- packages/date-picker/src/css/picker.css
> TimePicker: update icon size

- examples/components/footer.vue
> add contributing guide in footer

- CHANGELOG.md
- packages/table/src/table.vue
> TableColum: fix first calc columns, #78

- packages/table/src/table.vue
> TableColumn: properly fix first calc columns, #78

- packages/theme-default/src/table.css
> TableColumn: fix TableColumn align style

- examples/docs/quickstart.md
> doc: add cdn usage, #134

- README.md
> doc: add size badge in readme

- packages/theme-default/src/table.css
> Table: fix table style

- README.md
> add starter links

- examples/docs/message-box.md
- package.json
- packages/dialog/package.json
- packages/message-box/package.json
- packages/message-box/src/main.js
- packages/message-box/src/main.vue
> add padding-right when popup shows

- CHANGELOG.md
- src/utils/vue-popper.js
> utils: import popper fail in vue-popper file, fixed #143

- README.md
> add browser support standard

- README.md
- examples/docs/development.md
- examples/docs/quickstart.md
> text unification

- examples/docs/table.md
> add resizable on table doc

- index.html
> (gh-pages) Update index.html

- examples/index.tpl
> Replace cdn into jsdelivr

- CHANGELOG.md
- examples/docs/date-picker.md
- examples/docs/time-picker.md
- packages/date-picker/src/util/index.js
> DatePicker: fix initial value is string, #157

- CHANGELOG.md
- packages/pagination/src/pager.vue
> Pagination: fix icon style, fixed #163

- build/bin/new.js
- build/cooking.component.js
- components.json
> Update component list

- CHANGELOG.md
- examples/docs/layout.md
- packages/theme-default/src/row.css
> fixed row flex align bug

- examples/app.vue
> fixed docs style

- build/release.sh
> fix release shell

- CHANGELOG.md
- examples/docs/tabs.md
- packages/tabs/src/tab-pane.vue
- packages/tabs/src/tabs.vue
> fixed tabs bug when close tab

- package.json
> fix 'dist' task, fixed #176, #175

- examples/docs/zh-cn/dropdown.md
> update dropdown doc

- packages/date-picker/src/basic/date-table.vue
- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/picker.vue
- packages/date-picker/src/util/index.js
> DatePicker: fix set initial value

- examples/docs/zh-cn/table.md
> add fit in table api

- CHANGELOG.md
- packages/theme-default/src/table.css
> Table: fix cell style,fixed #204

- CHANGELOG.md
- examples/docs/zh-cn/dialog.md
- examples/docs/zh-cn/message-box.md
- examples/docs/zh-cn/progress.md
- package.json
- packages/dialog/package.json
- packages/dialog/src/component.vue
- packages/message-box/package.json
- packages/message-box/src/main.js
- packages/message-box/src/main.vue
> add lockScroll in msgbox and dialog

- CHANGELOG.md
- examples/docs/zh-cn/input.md
- packages/input/src/calcTextareaHeight.js
- packages/input/src/input.vue
- packages/theme-default/src/input.css
> add rows and autosize property

- CHANGELOG.md
- examples/docs/zh-cn/message.md
- examples/docs/zh-cn/notification.md
- packages/message/src/main.js
- packages/notification/src/main.js
> add .type on Notification and Message

- CHANGELOG.md
- examples/docs/zh-cn/menu.md
- packages/menu/src/menu.vue
> fix default-active bug

- packages/select/src/select.vue
> show dropdown when input is focused via tab

- src/utils/clickoutside.js
> fix clickoutside bug in JSX render

- components.json
- examples/docs/zh-cn/dropdown.md
- packages/dropdown-menu/index.js
- packages/dropdown/src/dropdown-menu.vue
- packages/dropdown/src/dropdown.vue
- packages/theme-default/src/button.css
- packages/theme-default/src/dropdown.css
- packages/theme-default/src/icon.css
- src/index.js
Now We can use anything as the dropdown trigger and we can style the dropdown-menu.
> Dropdown Reconstruction

- CHANGELOG.md
- examples/docs/zh-cn/tree.md
- packages/tree/src/model/tree.js
- packages/tree/src/tree-node.vue
> add callbacks on tree

- CHANGELOG.md
- examples/docs/zh-cn/date-picker.md
- examples/docs/zh-cn/datetime-picker.md
- examples/docs/zh-cn/time-picker.md
- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/panel/date.vue
> DatePicker: add 'disabledDate' option, fixed #253

- packages/tree/src/model/node.js
- packages/tree/src/tree.vue
> Fix Tree Bug: set data does not work

- packages/tree/src/model/node.js
> Fix Tree: clear children when setData

- packages/table/src/resize-event.js
- packages/table/src/table.vue
- packages/theme-default/src/table.css
> Improve Table: use element reisze event instead of window resize event

- build/bin/build-entry.js
- src/index.js
> exclude Message in component registration

- examples/docs/zh-cn/popover.md
> Popover: add reference slot description, #246

- CHANGELOG.md
- examples/docs/zh-cn/dropdown.md
- packages/dropdown/src/dropdown.vue
> dropdown bug fix & docs update

- build/config.js
- packages/dialog/package.json
- packages/message-box/package.json
> dialog and msgbox import the global vue-popup

- src/utils/popper.js
> Fix popper.js bug in IE, #291

- CHANGELOG.md
- packages/select/src/option.vue
- packages/select/src/select.vue
> fix Select automatically expand issue

- CHANGELOG.md
- packages/menu/src/menu-item.vue
- packages/menu/src/menu.vue
> fix menu router prop bug when vertical mode

- CHANGELOG.md
- examples/docs/zh-cn/dialog.md
- packages/dialog/src/component.vue
- packages/theme-default/src/dialog.css
> add top to Dialog, #277

- packages/menu/src/menu.vue
> fix menu auto collapse after router change

- package.json
- packages/loading/package.json
- packages/loading/src/spinner.js
- packages/message-box/package.json
- packages/message-box/src/main.vue
- packages/rate/package.json
- packages/rate/src/main.vue
- packages/select/package.json
- packages/select/src/select.vue
- packages/slider/src/main.vue
> replace classList with wind-dom

- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/panel/time-range.vue
- packages/date-picker/src/panel/time-select.vue
- packages/date-picker/src/panel/time.vue
- src/mixins/emitter.js
> DatePicker: fix i18n

- packages/autocomplete/src/autocomplete.vue
- packages/input/src/input.vue
> fix autocomplete event bug

- packages/tree/src/tree-node.vue
tree component support dom template
related to #338
> feature(tree): tree component support dom template

- packages/dropdown/src/dropdown.vue
> fixed dropdown splitButton

- packages/steps/src/step.vue
- packages/theme-default/src/step.css
> Steps: fix icon style

- packages/pagination/src/pagination.js
> Pagination: fix input value

- examples/docs/zh-cn/input.md
- package.json
- packages/date-picker/src/picker.vue
- packages/input/src/input.vue
> fix dynamic input type bug

- CHANGELOG.md
- packages/dropdown/src/dropdown-menu.vue
- packages/dropdown/src/dropdown.vue
- packages/popover/src/main.vue
- packages/theme-default/src/index.css
- src/utils/vue-popper.js
> DropdownMenu: fix popper, fixed #342, #194

- examples/docs/zh-cn/form.md
- packages/form/src/form-item.vue
> fix form validate bug

- examples/docs/zh-cn/dropdown.md
- packages/dropdown/src/dropdown.vue
> dropdown split button prop size

- packages/date-picker/src/css/picker-panel.css
- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/panel/date.vue
- packages/date-picker/src/panel/time-range.vue
- packages/date-picker/src/panel/time-select.vue
- packages/date-picker/src/panel/time.vue
- packages/select-dropdown/src/select-dropdown.vue
- src/utils/vue-popper.js
> fix some styles

- examples/docs/zh-cn/badge.md
- packages/date-picker/src/css/date-picker.css
- packages/date-picker/src/css/date-range-picker.css
- packages/date-picker/src/css/picker-panel.css
- packages/date-picker/src/css/time-range-picker.css
- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/panel/date.vue
- packages/date-picker/src/panel/time-range.vue
- packages/date-picker/src/panel/time-select.vue
- packages/date-picker/src/panel/time.vue
- packages/dropdown/src/dropdown-menu.vue
- packages/steps/src/step.vue
> DatePicker/Dropdown/Steps/Badge(docs): fix style bug

- CHANGELOG.md
- packages/theme-default/src/icon.css
- packages/tree/src/tree-node.vue
> fix tree checkbox bug

- examples/docs/zh-cn/dropdown.md
- examples/docs/zh-cn/form.md
- packages/theme-default/src/dropdown.css
- packages/theme-default/src/form.css
> fix inline form style

- packages/message-box/src/main.vue
- packages/theme-default/src/message-box.css
- packages/theme-default/src/slider.css
> add some missing css

- build/bin/gen-cssfile.js
- package.json
> feat: auto generator cssfile

- CHANGELOG.md
- examples/docs/zh-cn/breadcrumb.md
- packages/breadcrumb/src/breadcrumb-item.vue
- packages/theme-default/src/breadcrumb.css
> add breadcrumb router props

- examples/docs/zh-cn/dialog.md
> fix a dialog doc typo

- packages/dropdown/src/dropdown.vue
- packages/theme-default/src/dropdown.css
> fix dropdown style

- examples/components/footer.vue
- examples/docs/zh-cn/popover.md
- packages/popover/src/main.vue
- packages/steps/src/step.vue
> Popover: add popperClass; Steps: update style prop

- CHANGELOG.md
- packages/select/src/select.vue
> fix select icon animation

- CHANGELOG.md
- packages/date-picker/src/picker.vue
> DatePicker: fix blur event

- packages/theme-default/src/step.css
> Steps: fix line style in vertical mode

- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/picker.vue
- packages/date-picker/src/util/index.js
> DatePicker: fix tab key

- packages/theme-default/src/table.css
> fix tooltip display in table

- packages/input/src/input.vue
> fix input password type

- build/cooking.common.js
> fix build commonjs config

- src/utils/clickoutside.js
> optimize clickoutside

- examples/docs/zh-cn/form.md
- packages/theme-default/src/input.css
> fix input line-height

- packages/autocomplete/src/autocomplete.vue
> fix autocomplete lose vnode.context.popperElm

- src/utils/vue-popper.js
> Popover: fix the arrow appears, fixed #412

- package.json
> add padding-right only when body has overflow #414

- examples/docs/zh-cn/input.md
- packages/input/src/input.vue
> fix input type

- LICENSE
- package.json
> Update package.json dependencies

- packages/menu/src/menu.vue
> Menu: fix indexPath of undefined

- build/config.js
- build/cooking.conf.js
> Fix build common config

- .eslintignore
- examples/docs/zh-cn/time-picker.md
- package.json
- packages/date-picker/src/basic/time-spinner.vue
- test/unit/specs/time-picker.spec.js
- test/unit/util.js
> TimePicker: add unit test

- examples/docs/zh-cn/time-picker.md
- package.json
- packages/date-picker/src/panel/time-select.vue
- test/unit/specs/time-select.spec.js
> TimeSelect: add testcase of setting default value

- CHANGELOG.md
- examples/docs/zh-cn/message-box.md
- packages/message-box/src/main.vue
> remove errorMessage when prompt is closed

- Makefile
- build/bin/new.js
> fix `make new` running error

- examples/docs/zh-cn/tree.md
- packages/theme-default/src/tree.css
- packages/tree/src/model/node.js
- packages/tree/src/model/tree.js
- packages/tree/src/transition.js
- packages/tree/src/tree-node.vue
- packages/tree/src/tree.vue
1. Add props: renderContent, highlightCurrent
2. Fix Bug: tree do not change when data changed
#404 #261 #294
> Improve Tree

- CHANGELOG.md
- packages/date-picker/src/css/date-picker.css
- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/panel/date.vue
> DatePicker: fix panel style, #318

- CHANGELOG.md
- examples/docs/zh-cn/input.md
- packages/input/src/input.vue
- packages/theme-default/src/input.css
> add input icon click event

- .babelrc
- .travis.yml
- examples/docs/zh-cn/date-picker.md
- examples/docs/zh-cn/datetime-picker.md
- package.json
- packages/date-picker/src/basic/time-spinner.vue
- packages/date-picker/src/panel/date.vue
- packages/date-picker/src/panel/time-range.vue
- packages/date-picker/src/panel/time.vue
- packages/date-picker/src/picker.vue
- packages/date-picker/src/picker/date-picker.js
- packages/theme-default/package.json
- test/unit/specs/date-picker.spec.js
- test/unit/specs/time-picker.spec.js
> DatePicker: add test

- FAQ.md
- README.md
> update FAQ and README

- package.json
- test/unit/specs/util.vue-popper.spec.js
> VuePopper: add test

- build/bin/build-entry.js
- src/index.js
- test/unit/specs/tooltip.spec.js
> Tooltip: add test

- CHANGELOG.md
- packages/input/src/input.vue
> fix textarea autosize bug

- examples/docs/zh-cn/input-number.md
- packages/input-number/src/input-number.vue
- packages/theme-default/src/breadcrumb.css
> fix input-number min max prop && breadcrumb align

- packages/rate/src/main.vue
- test/unit/specs/rate.spec.js
> Rate: add test

- .travis.yml
- build/cooking.demo.js
- build/deploy-ci.sh
> Update travis config

- examples/docs/zh-cn/table.md
> Table: update an example

- test/unit/specs/button.spec.js
> button test

- .travis.yml
- Makefile
- build/cooking.test.js
- build/deploy-ci.sh
- package.json
> Update test config

- test/unit/specs/col.spec.js
> col test improve

- test/unit/specs/alert.spec.js
> Alert: add test

- Makefile
- packages/popover/index.js
- packages/popover/src/directive.js
- packages/popover/src/main.vue
- src/utils/vue-popper.js
- test/unit/specs/popover.spec.js
- test/unit/specs/tooltip.spec.js
- test/unit/util.js
> Popover: add test

- test/unit/specs/loading.spec.js
> Loading: add test

- test/unit/specs/radio.spec.js
> add radio test

- test/unit/specs/tag.spec.js
> Tag: add test

- packages/input/src/input.vue
- test/unit/specs/input.spec.js
> input test improve

- packages/card/src/main.vue
- test/unit/specs/card.spec.js
> Card: add test

- test/unit/specs/badge.spec.js
> Badge: add test

- .travis.yml
- build/deploy-ci.sh
- examples/docs/zh-cn/upload.md
- examples/index.tpl
> Upload: fix links in the doc

- test/unit/specs/tag.spec.js
> tag test improve

- packages/input-number/src/input-number.vue
- packages/theme-default/src/input-number.css
- packages/theme-default/src/slider.css
> fix input-number style

- packages/message/src/main.vue
- test/unit/specs/message.spec.js
> Message: add test

- packages/slider/src/main.vue
- test/unit/specs/slider.spec.js
- test/unit/util.js
> Slider: improve test

- examples/docs/zh-cn/upload.md
- packages/theme-default/src/step.css
- test/unit/specs/steps.spec.js
> Steps: add test

- test/unit/specs/notification.spec.js
> Notification: add test

- test/unit/specs/input-number.spec.js
- test/unit/specs/input.spec.js
> add input-number test

- examples/docs/zh-cn/table.md
- packages/table/src/table-body.js
- packages/table/src/table-store.js
- packages/table/src/table.vue
> [Table] Remove prop: selectionMode & allowNoCurrentRow

- test/unit/specs/alert.spec.js
- test/unit/specs/slider.spec.js
- test/unit/specs/switch.spec.js
> fix some potential test err

- examples/docs/zh-cn/progress.md
- packages/progress/src/progress.vue
- test/unit/specs/progress.spec.js
> add progress test

- test/unit/specs/menu.spec.js
> add menu test

- build/config.js
- packages/popover/src/main.vue
- src/utils/clickoutside.js
- src/utils/resize-event.js
- src/utils/vue-popper.js
- test/unit/specs/util.clickoutside.spec.js
- test/unit/specs/util.vue-popper.spec.js
> Clickoutside: add test & improve vue-popper test

- packages/table/src/table-body.js
- packages/table/src/table-header.js
- packages/table/src/table-layout.js
- packages/table/src/table-store.js
- packages/table/src/table.vue
- packages/theme-default/src/table.css
> [Table] Improve fixed implement method.

- test/unit/specs/tooltip.spec.js
> Tooltip: Improve hover test

- packages/input/src/input.vue
> fix input native props

- packages/theme-default/src/tabs.css
> fix tabs style

- test/unit/specs/message.spec.js
- test/unit/specs/notification.spec.js
> Message/Notification: improve test

- CHANGELOG.md
- examples/docs/zh-cn/slider.md
- packages/slider/src/main.vue
- packages/theme-default/src/common/var.css
- packages/theme-default/src/slider.css
- test/unit/specs/slider.spec.js
> Slider: add disabled/use tooltip

- examples/docs/zh-cn/tooltip.md
- packages/tooltip/src/main.vue
- test/unit/specs/tooltip.spec.js
> Tooltip: add manual feature

- examples/docs/zh-cn/message-box.md
- examples/pages/component.vue
- package.json
- packages/message-box/src/main.vue
- packages/theme-default/src/message-box.css
- test/unit/specs/message-box.spec.js
> MessageBox: update animation/add test

- .gitattributes
https://github.com/github/linguist#overrides
好像这样就可以变成 Vue 项目了 23333
> Override linguist language

- src/index.js
- src/utils/sync.js
- test/unit/specs/sync.spec.js
- test/unit/util.js
> Add v-sync directive.

- packages/autocomplete/src/autocomplete.vue
> add autocomplete size

- test/unit/specs/alert.spec.js
> Alert: improve test

- test/unit/specs/sync.spec.js
> Improve v-sync test.

- .gitattributes
- packages/date-picker/src/basic/month-table.vue
- packages/date-picker/src/basic/time-spinner.vue
- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/panel/date.vue
- packages/date-picker/src/panel/time-range.vue
- packages/date-picker/src/panel/time-select.vue
- packages/date-picker/src/panel/time.vue
- packages/date-picker/src/picker.vue
> DatePicker: fix trigger multiple watch, fixed #597

- packages/theme-default/src/table.css
> Table: add hover background.

- src/utils/vue-popper.js
> vue-popper: fix a node removal bug

- CHANGELOG.md
- examples/docs/zh-cn/tabs.md
- packages/tabs/src/tabs.vue
- test/unit/specs/tabs.spec.js
> add tabs test

- test/unit/specs/dropdown.spec.js
> add dropdown test

- test/unit/specs/breadcrumb.spec.js
> breadcrumb: add test

- examples/docs/zh-cn/badge.md
- examples/docs/zh-cn/button.md
- examples/docs/zh-cn/dropdown.md
- examples/docs/zh-cn/progress.md
- packages/button/src/button.vue
- packages/input-number/src/input-number.vue
- packages/input/src/input.vue
- packages/message-box/src/main.vue
- packages/radio/src/radio-button.vue
- packages/theme-default/src/button.css
- packages/theme-default/src/checkbox.css
- packages/theme-default/src/dropdown.css
- packages/theme-default/src/icon.css
- packages/theme-default/src/input-number.css
- packages/theme-default/src/input.css
- packages/theme-default/src/radio.css
- packages/theme-default/src/tree.css
- test/unit/specs/button.spec.js
- test/unit/specs/input.spec.js
- test/unit/specs/message-box.spec.js
> fix masses style

- build/config.js
> Fix import src file multiple times, fixed #634 #630

- examples/docs/zh-cn/select.md
- packages/select/src/option-group.vue
- packages/select/src/option.vue
- packages/select/src/select.vue
- test/unit/specs/select.spec.js
> Select: add test

- test/unit/specs/alert.spec.js
- test/unit/specs/rate.spec.js
- test/unit/specs/select.spec.js
- test/unit/specs/slider.spec.js
- test/unit/specs/switch.spec.js
- test/unit/util.js
> Test: add destroy

- packages/date-picker/src/panel/time-select.vue
- test/unit/specs/time-select.spec.js
> TimeSelect: improve test

- packages/table/src/table.vue
- packages/theme-default/src/table.css
> Table: add empty text

- packages/input-number/src/input-number.vue
> add support for change by keyboard event

- packages/date-picker/src/basic/time-spinner.vue
- packages/date-picker/src/panel/time-range.vue
- packages/date-picker/src/panel/time.vue
- test/unit/specs/time-picker.spec.js
> TimePicker: improve test

- CHANGELOG.md
- examples/docs/zh-cn/menu.md
- packages/menu/src/menu.vue
- packages/menu/src/submenu.vue
- test/unit/specs/menu.spec.js
> Menu: add menu-trigger prop

- CHANGELOG.md
- examples/docs/zh-cn/pagination.md
- packages/pagination/src/pager.vue
- packages/pagination/src/pagination.js
- packages/table/src/table.vue
- src/mixins/migrating.js
- test/unit/specs/pagination.spec.js
> Pagination: rename currentchange & sizechange.

- src/utils/vue-popper.js
> Popper: set base zIndex to 2000

- test/unit/specs/dialog.spec.js
- test/unit/specs/mixin.vue-popup.spec.js
> Test: add Dialog and vue-popup

- build/cooking.demo.js
> fixed no-unused-vars

- package.json
> Fix build src folder, #fixed 665

- packages/upload/src/iframe-upload.vue
- packages/upload/src/index.vue
- packages/upload/src/upload.vue
> iframe upload use post message to get the res content

- packages/tree/src/model/node.js
- test/unit/specs/tree.spec.js
> Tree: add test

- build/config.js
> Update build config

- CHANGELOG.md
- examples/docs/zh-cn/table.md
- packages/table/src/dropdown.js
- packages/table/src/filter-panel.vue
- packages/table/src/table-body.js
- packages/table/src/table-column.js
- packages/table/src/table-header.js
- packages/table/src/table-store.js
- packages/table/src/table.vue
- packages/table/src/util.js
- packages/theme-default/src/index.css
- packages/theme-default/src/table-column.css
- packages/theme-default/src/table.css
- src/locale/lang/en.js
- src/locale/lang/zh-cn.js
- test/unit/specs/table.spec.js
> Table: add filter feature.

- examples/docs/zh-cn/table.md
- packages/table/src/table-column.js
- packages/table/src/table-header.js
- packages/table/src/table-store.js
- packages/table/src/util.js
> Table: add column remote/custom sort.

- README.md
- examples/docs/zh-cn/table.md
- packages/table/src/filter-panel.vue
- packages/table/src/table-column.js
- packages/table/src/table-header.js
- test/unit/index.js
- test/unit/specs/table.spec.js
- test/unit/specs/time-picker.spec.js
> Table: add filter test

- test/unit/index.js
> Fix test config

- packages/dropdown/src/dropdown-item.vue
- packages/dropdown/src/dropdown.vue
> fix dropdown menu visible bug

- examples/docs/zh-cn/installation.md
- examples/nav.config.json
> doc: add installation

- packages/theme-default/src/input-number.css
> InputNumber: fix button style

- src/locale/format.js
- src/locale/index.js
> Locale: add format

- examples/docs/zh-cn/button.md
- packages/button/src/button.vue
- test/unit/specs/button.spec.js
> Button: add click event

- packages/pagination/src/pagination.js
- src/locale/lang/en.js
- src/locale/lang/zh-cn.js
> Pagination: add missing i18n config

- FAQ.md
- examples/docs/zh-cn/table.md
- examples/route.config.js
> misc updates

- build/deploy-ci.sh
> Add auto build lib

- src/locale/lang/de.js
> i18n: add German config

- build/deploy-ci.sh
> travis: fix shell

- README.md
- examples/docs/zh-cn/quickstart.md
> doc: add ignore locale

- build/deploy-ci.sh
> travis: auto build site

- build/deploy-ci.sh
> Deploy-ci: fix shell

- examples/docs/zh-cn/dialog.md
> Dialog: update doc

- packages/message-box/src/main.js
> MessageBox: fix a callback overwriting bug

- examples/docs/zh-cn/table.md
> Table: fix a doc typo

- examples/docs/zh-cn/table.md
- examples/docs/zh-cn/tooltip.md
- packages/table/src/table-body.js
- packages/theme-default/src/table.css
> Table: fix show tooltip, fixed #714

- build/bin/new.js
- src/utils/clickoutside.js
- test/unit/specs/util.clickoutside.spec.js
> Clickoutside: fix id of undefined, fixed #720

- examples/docs/zh-cn/table.md
> Table(doc): update inline-template, #726

- examples/docs/zh-cn/button.md
- packages/button/src/button.vue
- packages/message-box/src/main.vue
> support button autofocus && autofocus message box confirm button

- packages/checkbox/src/checkbox-group.vue
- packages/checkbox/src/checkbox.vue
- packages/menu/src/menu-item-group.vue
- packages/menu/src/menu-item.vue
- packages/menu/src/menu-mixin.js
- packages/menu/src/menu.vue
- packages/menu/src/submenu.vue
> replace _componentTag to componentName

- build/cooking.component.js
> Update the cjs files naming

- packages/message-box/src/main.vue
> MessageBox: autofocus confirm button

- README.md
- examples/docs/zh-cn/quickstart.md
- i18n.md
> Docs: add i18n.md

- packages/date-picker/src/panel/date-range.vue
- src/locale/lang/de.js
- src/locale/lang/en.js
- src/locale/lang/zh-cn.js
> DatePicker: fix dont select the time on the same day

- CHANGELOG.md
- examples/docs/zh-cn/dropdown.md
- packages/dropdown/src/dropdown-item.vue
- packages/dropdown/src/dropdown.vue
- test/unit/specs/dropdown.spec.js
> dropdown: add command api

- examples/docs/zh-cn/table.md
> Table: add min-width prop doc, fixed #747

- examples/docs/zh-cn/form.md
> Form(doc): fix submit event

- examples/docs/zh-cn/select.md
- packages/theme-default/src/alert.css
- packages/theme-default/src/common/var.css
- packages/theme-default/src/dialog.css
- packages/theme-default/src/message-box.css
- packages/theme-default/src/message.css
- packages/theme-default/src/notification.css
- packages/theme-default/src/option-group.css
- packages/theme-default/src/option.css
- packages/theme-default/src/rate.css
- packages/theme-default/src/select-dropdown.css
- packages/theme-default/src/select.css
- packages/theme-default/src/slider.css
- packages/theme-default/src/switch.css
> Theme-default: add variables

- packages/pagination/src/pagination.js
> Pagination: emit 'current-page' when sizes change, closed #729

- build/deploy-ci.sh
> travis: remove files but ignore readme.md

- packages/theme-default/src/tooltip.css
> Tooltip: fix arrow offset style

- CHANGELOG.md
- packages/theme-default/src/date-picker/time-spinner.css
> TimePicker: hidden scrollbar in IE10

- test/unit/specs/date-picker.spec.js
> DatePicker: fix test

- packages/input-number/src/input-number.vue
- packages/theme-default/src/input-number.css
- test/unit/specs/input-number.spec.js
> input-number: style fix && experience improve

- CHANGELOG.md
- packages/theme-default/src/alert.css
- packages/theme-default/src/common/var.css
- packages/theme-default/src/message-box.css
- packages/theme-default/src/slider.css
> Slider: fix display issue inside Form

- packages/select/src/select.vue
> Select: fix an input initial height bug

- examples/docs/en-us/alert.md
- examples/docs/en-us/badge.md
- examples/docs/en-us/breadcrumb.md
- examples/docs/en-us/button.md
- examples/docs/en-us/dropdown.md
- examples/docs/en-us/input.md
- examples/docs/en-us/layout.md
- examples/docs/en-us/loading.md
- examples/docs/en-us/menu.md
- examples/docs/en-us/notification.md
- examples/docs/en-us/select.md
- examples/docs/en-us/table.md
- examples/docs/en-us/tooltips.md
- examples/docs/en-us/upload.md
> Review: alert/badge/breadcrumb

- packages/table/src/table-body.js
- packages/table/src/table-header.js
- test/unit/specs/table.spec.js
> Table: fixed firefox bug. fixed #766.

- packages/table/src/table-body.js
- packages/table/src/table-header.js
- test/unit/specs/table.spec.js
> Table: rename hidden class to is-hidden.

- build/release.sh
- examples/app.vue
- package.json
还有这里 https://github.com/ElementUI/theme-default/pull/1
> Update build theme config

- README.md
- custom-theme.md
> doc: add custom theme

- examples/docs/en-us/button.md
- examples/docs/en-us/checkbox.md
> Review: button/checkbox

- packages/select/src/select.vue
> Select: fix a form validation bug

- test/unit/specs/autocomplete.spec.js
- test/unit/specs/badge.spec.js
- test/unit/specs/breadcrumb.spec.js
- test/unit/specs/button.spec.js
- test/unit/specs/card.spec.js
- test/unit/specs/checkbox.spec.js
- test/unit/specs/col.spec.js
- test/unit/specs/date-picker.spec.js
- test/unit/specs/dropdown.spec.js
- test/unit/specs/form.spec.js
- test/unit/specs/input-number.spec.js
- test/unit/specs/input.spec.js
- test/unit/specs/loading.spec.js
- test/unit/specs/menu.spec.js
- test/unit/specs/pagination.spec.js
- test/unit/specs/popover.spec.js
- test/unit/specs/progress.spec.js
- test/unit/specs/radio.spec.js
- test/unit/specs/row.spec.js
- test/unit/specs/steps.spec.js
- test/unit/specs/tabs.spec.js
- test/unit/specs/tag.spec.js
- test/unit/specs/time-picker.spec.js
- test/unit/specs/time-select.spec.js
- test/unit/specs/tooltip.spec.js
> unit test vm destroy improve

- CHANGELOG.md
- examples/docs/zh-cn/table.md
- packages/table/src/table-column.js
- packages/table/src/table-store.js
- packages/table/src/table.vue
> Table: let table compatible with vuex.

- packages/table/src/table-body.js
- packages/theme-default/src/table.css
> Table: update hover effect.

- examples/docs/en-us/card.md
- examples/docs/en-us/color.md
> Review: color

- packages/loading/src/directive.js
> Loading: fix a potential node removal bug

- examples/docs/en-us/date-picker.md
- examples/docs/en-us/datetime-picker.md
- examples/docs/en-us/form.md
- examples/docs/en-us/message box.md
- examples/docs/en-us/message.md
- examples/docs/en-us/pagination.md
- examples/docs/en-us/progress.md
- examples/docs/en-us/rate.md
- examples/docs/en-us/switch.md
- examples/docs/en-us/tabs.md
- examples/docs/en-us/time-picker.md
> Remaining translations completed

- packages/table/src/table-store.js
> Table: clear selection after change data, fixed #813.

- packages/table/src/table.vue
- packages/table/src/util.js
> Table: support header mousewheel scroll.

- examples/docs/en-us/color.md
- examples/docs/en-us/date-picker.md
- examples/docs/en-us/datetime-picker.md
- examples/docs/en-us/time-picker.md
> Review: date-picker, time-picker, datetime-picker

- examples/docs/zh-cn/dropdown.md
- packages/dropdown/src/dropdown-item.vue
- packages/dropdown/src/dropdown-menu.vue
- packages/theme-default/src/dropdown.css
> dropdown-item add disabled && divided

- examples/docs/zh-cn/upload.md
> Upload: fix upload docs

- packages/select/src/option.vue
- packages/select/src/select.vue
> Select: fix an illegal filter regexp bug

- packages/tabs/src/tab-pane.vue
> fix $el null bug

- CHANGELOG.md
- examples/docs/zh-cn/table.md
- packages/table/src/table-body.js
- packages/table/src/table-store.js
- packages/table/src/table.vue
- packages/theme-default/src/table.css
- test/unit/specs/table.spec.js
> Table: add current-change event & highlight-current-row prop.

- package.json
- packages/message-box/src/main.js
- packages/table/src/table-column.js
- packages/tree/src/model/node.js
- src/utils/merge.js
> Table/MessageBox/Tree: remove object-assign

- packages/message/src/main.js
- packages/notification/src/main.js
- packages/theme-default/src/message.css
- packages/theme-default/src/notification.css
> Message/Notification: manage z-index with PopupManager

- packages/date-picker/src/basic/month-table.vue
- packages/date-picker/src/basic/year-table.vue
- packages/date-picker/src/panel/date.vue
- packages/theme-default/src/date-picker/date-table.css
- packages/theme-default/src/date-picker/month-table.css
- packages/theme-default/src/date-picker/year-table.css
> DatePicker: disabled year or month, fixed #758

- packages/select/src/select.vue
> select improve

- CHANGELOG.md
- examples/docs/zh-cn/pagination.md
- packages/pagination/src/pagination.js
- test/unit/specs/pagination.spec.js
> Pagination: enable not set total,  add page-count prop.

- src/locale/lang/pt.js
Hey,
I'm using this awesome set of Vue elements in a really huge project, but I need a portuguese translation, so there is my contribution 🙂
> Add Portuguese translation

- build/cooking.demo.js
> Site: update output filename

- packages/select/src/select.vue
- test/unit/specs/pagination.spec.js
> Select: fix clear value & remote label

- CHANGELOG.md
- examples/docs/zh-cn/table.md
- packages/table/src/table-column.js
- test/unit/specs/table.spec.js
> Table Column: watch more prop & rename showTooltipWhenOverflow.

- CHANGELOG.md
- examples/docs/zh-cn/table.md
- examples/docs/zh-cn/tree.md
- packages/table/src/table-body.js
- packages/table/src/table-column.js
- packages/table/src/table-header.js
- test/unit/specs/table.spec.js
> Table: add renderHeader prop.

- packages/table/src/table-layout.js
- test/unit/specs/table.spec.js
> Fix Table Bug: body-wrapper should not set height when table not set height.

- build/cooking.demo.js
- src/utils/popper.js
> fix ie bounding top bug

- examples/docs/zh-cn/dropdown.md
> Dropdown: fix a doc typo

- build/cooking.demo.js
> Improves build demo speed

- examples/docs/zh-cn/form.md
> Form: fix some doc typos

- packages/theme-default/src/tabs.css
> Tabs: fix a close button style overwriting bug, fixed #847

- examples/docs/en-us/form.md
> Review: form

- packages/message-box/src/main.vue
- packages/theme-default/src/message-box.css
- test/unit/specs/message-box.spec.js
> MessageBox: fix text blur due to translating half pixel

- build/config.js
- build/cooking.test.js
> fix browsers config bug

- examples/docs/zh-cn/button.md
- examples/docs/zh-cn/pagination.md
- examples/docs/zh-cn/rate.md
- examples/docs/zh-cn/tooltip.md
> fix docs in ie9

- examples/docs/zh-cn/input-number.md
> InputNumber: update doc

- examples/app.vue
- examples/index.tpl
- examples/pages/changelog.vue
- package.json
> Changelog(doc): auto generate links

- .babelrc
- package.json
> Remove use strict

- packages/switch/src/component.vue
- test/unit/specs/switch.spec.js
> fix switch style bug in ie9

- packages/theme-default/src/radio.css
> fix zIndex -1

- .babelrc
- build/bin/build-entry.js
- package.json
- src/index.js
- src/locale/index.js
> Locale: fallback default config

- examples/docs/zh-cn/input.md
- packages/theme-default/src/input.css
> fix input icon loading

- examples/docs/zh-cn/table.md
- packages/theme-default/src/button.css
> Button: update text button style

- examples/docs/en-us/button.md
- examples/docs/en-us/icon.md
- examples/docs/en-us/input-number.md
- examples/docs/en-us/input.md
> Review: icon/input/input number

- packages/table/src/table.vue
> Table: remove mouse wheel prevent default.

- examples/docs/zh-cn/input.md
- packages/theme-default/src/autocomplete.css
> autocomplete style fix

- packages/slider/src/main.vue
- packages/theme-default/src/slider.css
> Slider: fix an inputValue initiation bug

- CHANGELOG.md
- packages/date-picker/src/panel/date.vue
- packages/date-picker/src/picker.vue
- test/unit/specs/date-picker.spec.js
> DatePicker: fix reset value, fixed #878

- packages/theme-default/src/button.css
> Button: avoid button splitting in button-group

- examples/i18n/page.json
- examples/pages/template/changelog.tpl
- examples/pages/template/component.tpl
- package.json
> fix some building bug

- packages/theme-default/src/common/var.css
> Theme-default: improve vars

- examples/docs/en-us/layout.md
- examples/docs/en-us/loading.md
- examples/docs/en-us/menu.md
> Review: layout/loading/menu

- examples/docs/zh-CN/form.md
> improve form docs

- build/cooking.demo.js
- build/strip-tags.js
- examples/components/demo-block.vue
> Add jsfiddle in demo

- build/cooking.demo.js
- examples/components/demo-block.vue
- examples/docs/zh-CN/loading.md
- examples/docs/zh-CN/message.md
- examples/docs/zh-CN/slider.md
- examples/docs/zh-CN/tree.md
> Homepage: jsfiddle online

- examples/docs/zh-CN/table.md
> Table: add highlight current row example.

- examples/docs/zh-CN/upload.md
- packages/input/src/input.vue
> docs improve

- packages/tabs/src/tab-pane.vue
> fix node remove bug

- packages/theme-default/src/radio.css
- packages/theme-default/src/rate.css
> fix inline-block style

- examples/components/header.vue
> i18n: update header style

- build/cooking.demo.js
- examples/components/demo-block.vue
- examples/docs/zh-CN/input.md
- examples/docs/zh-CN/layout.md
- examples/docs/zh-CN/radio.md
现在可以在 `demo-block` 里写 `style` 标签了，然后会一起带到 JSFiddle 里。目前有些例子因为没有在 `demo-block` 里写 `script` 和 `style`，在 JSFiddle 里是跪的，后面要集中加一波。
> JSFiddle demo: add <style> support

- examples/docs/zh-CN/input.md
- i18n.md
> Input(doc): add api doc

- packages/pagination/src/pagination.js
> Pagination: fix currentPage may be 0 in some condition.

- FAQ.md
- README.md
- build/release.sh
- custom-theme.md
- examples/components/demo-block.vue
- examples/docs/zh-CN/installation.md
- examples/docs/zh-CN/quickstart.md
- i18n.md
> remove 'next' and 'rc' for 1.0.0 release

- packages/table/src/table-store.js
- test/unit/specs/table.spec.js
> Table: fire selection-change when row is removed.

- examples/docs/zh-CN/tabs.md
> Tabs: update doc

- examples/components/header.vue
- examples/route.config.js
- packages/theme-default/package.json
> i18n: sync with master

- packages/select/src/select.vue
> Select: fix value clear bug when value is initialized in mounted hook

- examples/docs/zh-CN/pagination.md
- packages/pagination/src/pagination.js
- test/unit/specs/pagination.spec.js
> Pagination: fix current-change emit too many.

- build/deploy-ci.sh
- package.json
> fix dev deploy

- examples/docs/en-US/message-box.md
- examples/docs/zh-CN/message-box.md
> MessageBox(doc): add two missing attributes

- examples/components/header.vue
- examples/route.config.js
> Improve example lang.

- packages/theme-default/src/common/var.css
- packages/theme-default/src/switch.css
> Switch: fix style inside Form

- packages/upload/src/cover.vue
- packages/upload/src/upload-list.vue
> Upload: fix missing progress, fixed #1013

- .github/CONTRIBUTING.md
> Doc: add componet doc

- packages/table/src/table-body.js
- packages/table/src/table-column.js
> Table: fix hover effect is slow when data > 200.

- examples/app.vue
- examples/play/component.vue
- examples/play/index.vue
- examples/route.config.js
> Add /play to debug component.

- examples/docs/en-US/steps.md
- examples/docs/zh-CN/steps.md
- packages/steps/src/step.vue
- packages/steps/src/steps.vue
> Step: add align-center, fixed #994

- package.json
- packages/table/src/table-column.js
> Table: fix render fail in vue-loader 9.9.0

- packages/switch/src/component.vue
- packages/theme-default/src/switch.css
- test/unit/specs/switch.spec.js
> Switch: update change event triggering mechanism

- packages/loading/src/directive.js
> Loading: fix a overflow hidden bug

- packages/table/src/table-body.js
- packages/table/src/table-store.js
- packages/table/src/util.js
> Table: render rows with row-key.

- packages/form/src/form-item.vue
> Form: fix reset value, fixed #937

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
- packages/table/src/table-body.js
- packages/table/src/table-column.js
- packages/table/src/table-header.js
- test/unit/specs/table.spec.js
> Add column class-name to the table header and update documentation

- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/panel/date.vue
- packages/date-picker/src/panel/time-range.vue
- packages/date-picker/src/panel/time-select.vue
- packages/date-picker/src/panel/time.vue
- packages/date-picker/src/picker.vue
- test/unit/specs/date-picker.spec.js
> DatePicker: add clear value, closed #759

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- examples/docs/en-US/message.md
- examples/docs/en-US/notification.md
- examples/docs/zh-CN/message.md
- examples/docs/zh-CN/notification.md
- packages/message/src/main.js
- packages/message/src/main.vue
- packages/notification/src/main.js
- packages/notification/src/main.vue
> Notification/Message: return instance for manual close

- examples/route.config.js
> Homepage: fix a navigator.language bug

- .babelrc
- FAQ.md
- build/config.js
- package.json
- packages/theme-default/README.md
- packages/theme-default/gulpfile.js
- packages/theme-default/salad.config.json
关于 css-loader 压缩代码后会去掉前缀的问题，目前看来解决方法就是等 css-loader 发新版了。。。
> fix salad config, #1037

- packages/loading/src/directive.js
- packages/theme-default/src/loading.css
- test/unit/specs/loading.spec.js
> Loading: remove unnecessary inline styles

- packages/checkbox/src/checkbox.vue
> fix checkbox name

- examples/docs/en-US/checkbox.md
- examples/docs/en-US/radio.md
- examples/docs/zh-CN/checkbox.md
- examples/docs/zh-CN/radio.md
> Checkbox/Radio: add 'name' on doc

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
> Add missing changelog

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- examples/docs/en-US/layout.md
- examples/docs/zh-CN/layout.md
- packages/col/src/col.vue
- packages/theme-default/src/col.css
- test/unit/specs/col.spec.js
> responsive layout

- examples/docs/en-US/badge.md
- examples/docs/en-US/card.md
- examples/docs/en-US/date-picker.md
- examples/docs/en-US/dialog.md
- examples/docs/en-US/form.md
- examples/docs/en-US/input-number.md
- examples/docs/en-US/input.md
- examples/docs/en-US/layout.md
- examples/docs/en-US/loading.md
- examples/docs/en-US/menu.md
- examples/docs/en-US/popover.md
- examples/docs/en-US/radio.md
- examples/docs/en-US/rate.md
- examples/docs/en-US/switch.md
- examples/docs/en-US/time-picker.md
- examples/docs/en-US/tooltip.md
- examples/docs/zh-CN/badge.md
- examples/docs/zh-CN/card.md
- examples/docs/zh-CN/date-picker.md
- examples/docs/zh-CN/dialog.md
- examples/docs/zh-CN/input.md
- examples/docs/zh-CN/layout.md
- examples/docs/zh-CN/loading.md
- examples/docs/zh-CN/menu.md
- examples/docs/zh-CN/popover.md
- examples/docs/zh-CN/rate.md
- examples/docs/zh-CN/switch.md
- examples/docs/zh-CN/time-picker.md
- examples/docs/zh-CN/tooltip.md
- examples/i18n/component.json
> JSFiddle: add missing <style> and <script>

- packages/dialog/src/component.vue
> Dialog : add prototype "showClose"

- examples/docs/en-US/date-picker.md
- examples/docs/en-US/datetime-picker.md
- examples/docs/en-US/dialog.md
- examples/docs/en-US/time-picker.md
- examples/docs/zh-CN/dialog.md
> Docs: misc updates

- packages/switch/src/component.vue
> Switch: fix a 'width' attribute init bug

- examples/docs/en-US/quickstart.md
- examples/docs/zh-CN/quickstart.md
> doc: update quickstart, fixed ElementUI/element-starter#7 #1089

- package.json
- packages/dialog/src/component.vue
- test/unit/specs/dialog.spec.js
> Dialog: remove v-model dependency of manual manipulation

- packages/message-box/src/main.js
> MessageBox: swap 'message' and 'title' when called with 'this.$msgbox'

- packages/date-picker/src/panel/date.vue
- packages/theme-default/src/date-picker/year-table.css
> DatePicker: fix select year in month type, fixed #1070

- src/locale/index.js
> Locale: compatible vue-i18n, fixed #973

- examples/docs/en-US/popover.md
- examples/docs/zh-CN/popover.md
- packages/popover/src/main.vue
- test/unit/specs/popover.spec.js
> Popover: add manual

- packages/date-picker/src/panel/date.vue
- test/unit/specs/date-picker.spec.js
> DatePicker: update view when setting default value, fixed #1050

- examples/docs/en-US/tree.md
- examples/docs/zh-CN/tree.md
- packages/theme-default/src/tree.css
- packages/tree/src/model/node.js
- packages/tree/src/model/tree.js
- packages/tree/src/tree-node.vue
- packages/tree/src/tree.vue
- src/locale/lang/de.js
- src/locale/lang/en.js
- src/locale/lang/pt.js
- src/locale/lang/zh-CN.js
- test/unit/specs/tree.spec.js
> Tree: add defaultExpandKeys & defaultCheckedKeys.

- packages/tabs/src/tabs.vue
> Tabs: fix a 'activeName' attribute init bug

- examples/docs/en-US/tabs.md
- examples/docs/zh-CN/tabs.md
> uodate tab docs

- packages/theme-default/src/table.css
> Table: fix tooltip style

- examples/docs/en-US/tree.md
> Tree: update English doc

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
> Changelog: add 1.0.1

- Makefile
- examples/i18n/page.json
- examples/pages/template/index.tpl
> update index links

- src/locale/lang/fr.js
> fr translation

- src/locale/lang/fr.js
> Fix a typo in fr.js

- examples/docs/zh-CN/layout.md
- packages/theme-default/src/col.css
- src/locale/lang/fr.js
> fix responsive style compile bug

- src/locale/lang/da.js
Added danish translation of texts.
> Added Danish translation

- packages/theme-default/src/button.css
- packages/theme-default/src/mixins/_button.css
> Button: add focus style, fixed #982

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
> add dev notice in contributing guide

- examples/docs/en-US/installation.md
- examples/docs/en-US/quickstart.md
> fix doc typos

- examples/docs/en-US/alert.md
- examples/docs/zh-CN/alert.md
- packages/alert/src/main.vue
- test/unit/specs/alert.spec.js
> Alert: add render-content, fixed #568

- packages/message-box/src/main.js
- packages/message-box/src/main.vue
- packages/select/src/select.vue
- packages/table/src/table.vue
- packages/tree/src/tree.vue
- src/locale/lang/en.js
- src/locale/lang/zh-CN.js
> Locale: fix dynamic change locale

- packages/theme-default/src/input.css
> Input: fix input-group line height, fixed #1075

- src/utils/popper.js
> fix popperjs modifer preventOverflow bug

- src/locale/lang/it.js
Added the Italian locale file.
> Italian Locale File

- build/deploy-ci.sh
> CI: add element bot

- src/locale/lang/nb-NO.js
Norway got two different written languages, this is the most common one.
> Added Norwegian bokmål

- packages/table/src/table.vue
> Table: fix fixed column won't disappear in some condition.

- examples/docs/zh-CN/table.md
- packages/table/src/table-body.js
- packages/table/src/table-column.js
- packages/table/src/table.vue
> Table: add context prop

- examples/docs/en-US/table.md
> Table: update English doc

- examples/docs/en-US/i18n.md
- examples/docs/zh-CN/i18n.md
> i18n: update language list

- packages/date-picker/src/panel/time-select.vue
> TimeSelect: fix 00:00 is disabled, fixed #676

- examples/docs/en-US/i18n.md
> i18n: use the right parentheses

- build/git-release.sh
- build/release.sh
- package.json
> Fix release script

- packages/switch/src/component.vue
> Switch: fix @change timing bug, fixed #1162

- packages/table/src/table-store.js
- packages/theme-default/src/table.css
- test/unit/specs/table.spec.js
> Table: fix selection-change not fire in some condition.

- examples/docs/en-US/table.md
- packages/select/src/select.vue
> Select: add focus listener, fixed #966

- examples/docs/en-US/form.md
- examples/docs/zh-CN/form.md
> improve form validate docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- examples/components/side-nav.vue
> Changelog: update to 1.0.2

- build/release.sh
- packages/table/src/table-column.js
> Update: release script

- build/cooking.demo.js
- examples/index.tpl
- examples/pages/template/index.tpl
> Fix some bug

- examples/docs/en-US/form.md
- examples/docs/zh-CN/form.md
- packages/form/src/form.vue
> fix dynamic form item validate bug

- packages/theme-default/src/common/var.css
- packages/theme-default/src/radio.css
> fix radio-button style

- src/locale/lang/nl.js
The full Dutch translations. I'm prepared to add future additional translations.
> Add Dutch translations

- src/locale/lang/vi.js
> Added Vietnamese translation

- src/locale/lang/ja.js
Fix some wrong translations.
其实有些也不是错译，只是用词不是特别恰当😂
> Fix japanese translation

- examples/docs/en-US/form.md
- examples/docs/zh-CN/form.md
- packages/form/src/form-item.vue
- test/unit/specs/form.spec.js
> add a error prop for setting the error message manually

- build/deploy-ci.sh
> Update rlease sh

- examples/docs/en-US/dialog.md
- examples/docs/en-US/form.md
- examples/docs/en-US/installation.md
- examples/docs/en-US/loading.md
- examples/docs/en-US/message-box.md
- examples/docs/en-US/message.md
- examples/docs/en-US/notification.md
- examples/docs/en-US/popover.md
- examples/docs/en-US/steps.md
- examples/docs/en-US/tooltip.md
- examples/docs/zh-CN/dialog.md
- examples/docs/zh-CN/form.md
- examples/docs/zh-CN/installation.md
- examples/docs/zh-CN/loading.md
- examples/docs/zh-CN/message-box.md
- examples/docs/zh-CN/message.md
- examples/docs/zh-CN/notification.md
- examples/docs/zh-CN/popover.md
- examples/docs/zh-CN/steps.md
- examples/docs/zh-CN/tooltip.md
> remove button native modifier

- packages/table/src/table.vue
> Table: fix a script error when show-header is true.

- packages/theme-default/src/checkbox.css
Some CSS resets (including Bootstrap's) contain `*::after{ box-sizing: border-box; }`. This breaks the checkbox component style like this: ![Wrong](http://i.imgur.com/YVAs1MS.png)
Therefor explicitly add box-sizing: content-box to increase compatibility. ![Good](http://i.imgur.com/fJoUngb.png)
> Add box-sizing: content-box for compatibility

- examples/docs/en-US/tree.md
- examples/docs/zh-CN/tree.md
- packages/tree/src/model/tree.js
- packages/tree/src/tree.vue
- test/unit/specs/tree.spec.js
> Tree: add getCheckedKeys & setCheckedKeys API.

- examples/docs/en-US/tree.md
- examples/docs/zh-CN/tree.md
- packages/tree/src/model/node.js
- packages/tree/src/model/tree.js
- packages/tree/src/tree-node.vue
- packages/tree/src/tree.vue
- test/unit/specs/tree.spec.js
> Tree: add filter-node-method prop & filter method.

- FAQ.md
> FAQ: add third-party iconfont usage

- package.json
- packages/pagination/src/pagination.js
> Pagination: fix i18n, fixed #928

- packages/select/src/select.vue
> Select: fix icon and input click, fixed #1220

- examples/docs/en-US/tree.md
- examples/docs/zh-CN/tree.md
> tree 组件文档说明修复

- packages/slider/src/main.vue
- test/unit/specs/slider.spec.js
> Slider: fix can not drag when step < 1

- packages/tree/src/model/node.js
- packages/tree/src/model/tree-store.js
- packages/tree/src/model/util.js
- packages/tree/src/tree-node.vue
- packages/tree/src/tree.vue
> Tree: refactor code & add insert, remove api for tree-store.

- packages/tabs/src/tab-pane.vue
- packages/tabs/src/tabs.vue
- packages/theme-default/src/tabs.css
- test/unit/specs/tabs.spec.js
> Tabs: fix dynamic bug & add closable prop for tab-pane

- packages/slider/src/main.vue
> Slider: fix a NaN value bug, fixed #1282

- examples/docs/zh-CN/popover.md
> fix docs typo

- packages/table/src/table.vue
> Table: fix selectAll option at table selection

- packages/table/src/table-body.js
- packages/table/src/table-column.js
- packages/table/src/table-layout.js
- packages/table/src/table-store.js
- packages/table/src/table.vue
- packages/theme-default/src/table.css
- test/unit/specs/table.spec.js
> Table: improve performance in large data.

- examples/entry.js
- examples/route.config.js
> Site: fix vue-router warn

- packages/date-picker/src/basic/time-spinner.vue
> DatePicker: fix scroll render bug, fixed #1276

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
- packages/table/src/table-column.js
- packages/table/src/table-header.js
- packages/table/src/table-store.js
- packages/theme-default/src/table.css
- test/unit/specs/table.spec.js
> Table: add header group feature.

- packages/table/src/table-column.js
- packages/table/src/table-layout.js
- test/unit/specs/table.spec.js
> Table: fix dynamic prop in table-column cause script error.

- packages/theme-default/src/icon.css
> Font: fix load error in chrome, fixed #1322

- packages/date-picker/src/panel/date.vue
> DatePicker: fix the panel is not updated when value change, fixed #1158

- packages/date-picker/src/picker.vue
> DatePicker: fix prevent clear value when readonly is true, fixed #1238

- packages/input-number/src/input-number.vue
> InputNumber: fix invalid value, Fixed #1327

- packages/table/src/table-column.js
> Table: fix align attribute, Fixed #1337

- examples/docs/en-US/pagination.md
- examples/docs/zh-CN/pagination.md
- packages/pagination/src/pagination.js
- test/unit/specs/pagination.spec.js
> Pagination: fix user can not set currentPage in some condition.

- packages/theme-default/src/table.css
- packages/theme-default/src/tree.css
> Fix empty text display in firefox. fixed #1341

- packages/theme-default/src/button.css
> fix button-group align bug

- packages/tree/src/model/node.js
- packages/tree/src/model/tree-store.js
- packages/tree/src/tree.vue
- test/unit/specs/tree.spec.js
> Tree: fixed default-expanded-keys can not set again.

- packages/select/src/option.vue
- packages/select/src/select.vue
> Select: fix priority of label and value, Fixed #1354 

- packages/select/src/select.vue
> Select: fix clear on remote mode, Fixed #1355

- examples/docs/en-US/custom-theme.md
- examples/docs/zh-CN/custom-theme.md
`node_modules/.bin` 误导性太大 还是用全局安装做演示好了 🌚
> Doc: update custom theme

- src/utils/vue-popper.js
> Popper: fix not destroy in keep-alive mode, fixed #1359

- examples/docs/en-US/input.md
- examples/docs/zh-CN/input.md
- packages/autocomplete/src/autocomplete.vue
> support autocomplete append & prepend

- examples/docs/en-US/form.md
- examples/docs/zh-CN/form.md
- packages/date-picker/src/panel/date.vue
- packages/date-picker/src/panel/time-select.vue
- packages/date-picker/src/panel/time.vue
- packages/form/src/form-item.vue
- packages/form/src/form.vue
- packages/input/src/input.vue
- packages/theme-default/src/input.css
- test/unit/specs/form.spec.js
> support deep object validate in form

- packages/checkbox/src/checkbox-group.vue
- packages/checkbox/src/checkbox.vue
- packages/radio/src/radio-group.vue
- packages/radio/src/radio.vue
- packages/tree/src/tree-node.vue
- src/mixins/emitter.js
- test/unit/specs/checkbox.spec.js
- test/unit/specs/radio.spec.js
> Radio/Checkbox: fix radio-radiogroup checkbox-checkboxgroup nested bug fixed #1152

- packages/theme-default/src/form.css
> fix btn-group style in form-item

- packages/checkbox/src/checkbox-group.vue
- packages/date-picker/src/picker.vue
- packages/form/src/form-item.vue
- packages/form/src/form.vue
- packages/input/src/input.vue
- packages/radio/src/radio-group.vue
- packages/select/src/option-group.vue
- packages/select/src/option.vue
- packages/select/src/select-dropdown.vue
- packages/select/src/select.vue
> normalize the componentName writing

- packages/pagination/src/pagination.js
> support dynamic pageSizes

- examples/docs/en-US/radio.md
- examples/docs/zh-CN/radio.md
- packages/radio/src/radio-button.vue
- packages/radio/src/radio-group.vue
- packages/theme-default/src/radio.css
- test/unit/specs/radio.spec.js
> support radio button custom style

- packages/date-picker/src/basic/year-table.vue
- packages/date-picker/src/panel/date.vue
- packages/date-picker/src/picker.vue
> fix datepicker year select mode bug

- examples/docs/en-US/menu.md
- examples/docs/zh-CN/menu.md
- packages/menu/src/menu-item-group.vue
> support the title slot in menu-group

- packages/form/src/form.vue
Fixed: https://github.com/ElemeFE/element/issues/1317
> Form: Fixed validation issue with dynamic rules (issue #1317)

- examples/docs/en-US/upload.md
- examples/docs/zh-CN/upload.md
- packages/theme-default/src/upload.css
- packages/upload/src/index.vue
> support upload default fileList

- README.md
> add customize theme link

- examples/docs/en-US/upload.md
- examples/docs/zh-CN/upload.md
- packages/upload/src/index.vue
> dynamic default-file-list & doc improve

- packages/checkbox/src/checkbox.vue
> fix checkbox label type

- src/locale/lang/fr.js
* [] Add some descriptions and refer relative issues for you PR.
Do not display "Annee" in the date picker (e.g. en locale file has empty string for same key)
> Update "fr" locale

- examples/components/header.vue
> fix header background

- examples/docs/en-US/pagination.md
- examples/docs/zh-CN/pagination.md
> fix pagination docs

- packages/theme-default/src/pagination.css
> Pagination: fix background color

- examples/components/header.vue
> improve header background

- examples/docs/en-US/popover.md
- examples/docs/zh-CN/popover.md
- packages/popover/src/main.vue
- test/unit/specs/popover.spec.js
> Popover: add show/hide event

- packages/tree/src/transition.js
> Tree: try to fix ie10 transition error.

- examples/pages/template/changelog.tpl
> doc: Fix changelog style

- examples/docs/zh-CN/upload.md
> fix upload docs bug

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- examples/docs/en-US/pagination.md
- examples/docs/zh-CN/pagination.md
> update changelog for 1.0.3

- build/deploy-ci.sh
> fix deploy shell

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
> Table: update custom column example

- examples/docs/en-US/tree.md
- examples/docs/zh-CN/tree.md
- packages/tree/src/model/tree-store.js
- packages/tree/src/tree-node.vue
- packages/tree/src/tree.vue
- test/unit/specs/tree.spec.js
> Tree: add setChecked method.

- examples/docs/zh-CN/notification.md
- packages/notification/src/main.js
> Notification: add offset

- build/deploy-ci.sh
> fix build site script

- packages/date-picker/src/picker.vue
> Time-Select: emit input event when clear value 

- examples/docs/en-US/notification.md
- examples/docs/zh-CN/notification.md
- packages/notification/src/main.js
> Notification: improve offset attribute doc

- packages/autocomplete/src/autocomplete.vue
> stop autocomplete enter event bubbling

- examples/docs/en-US/input-number.md
- examples/docs/zh-CN/input-number.md
- packages/input-number/src/input-number.vue
- packages/theme-default/src/input-number.css
- test/unit/specs/input-number.spec.js
> input-number add the controls support

- build/bin/build-all.js
> fix : this didn't run on windows

- packages/slider/src/main.vue
> Slider: fix drag bug, Fixed #1458

- examples/docs/zh-CN/datetime-picker.md
- test/unit/specs/date-picker.spec.js
> fix datetimepicker test

- examples/docs/en-US/loading.md
- examples/docs/zh-CN/loading.md
- packages/loading/src/index.js
- test/unit/specs/loading.spec.js
> Loading: full screen loading is now singleton

- packages/input/src/input.vue
- packages/theme-default/src/input.css
> fix input-group style

- src/locale/lang/tr-TR.js
Created tr-TR.js for Turkish Language Support
> Created tr-TR.js for Turkish Language Support

- packages/checkbox/src/checkbox-group.vue
- packages/checkbox/src/checkbox.vue
> fix checkbox dynamic init bug, fix #1492

- packages/tabs/src/tabs.vue
- packages/theme-default/src/alert.css
> Alert: improve style

- packages/slider/src/main.vue
> Slider: fix a decimal display bug

- examples/docs/en-US/select.md
- examples/docs/zh-CN/select.md
- packages/pagination/src/pagination.js
- packages/select/src/option.vue
- packages/select/src/select.vue
- packages/theme-default/src/pagination.css
- packages/theme-default/src/select-dropdown.css
- packages/theme-default/src/select.css
- test/unit/specs/select.spec.js
先不合，我要再加点测试测一测，就不放在 1.0.3 里了。修了 #1353 和 #1262 。
> Select: refactor and bug fix

- packages/checkbox/src/checkbox.vue
- packages/radio/src/radio-button.vue
- packages/radio/src/radio-group.vue
- packages/radio/src/radio.vue
- test/unit/index.js
> fix radio dynamic init bug

- packages/table/src/table-layout.js
> Table: fix update scrolly not working bug

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
- packages/table/src/table-body.js
- test/unit/specs/table.spec.js
> Table: add row-dblclick event. closed #1362

- packages/table/src/table-header.js
- packages/theme-default/src/table.css
> Table: fix column label not visible in some condition.

- packages/tree/src/model/node.js
> Tree: fix leaf state not update bug.

- packages/tree/src/tree-node.vue
> Tree: fix can not update children in some condition.

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
> update changelog for 1.0.4

- packages/theme-default/src/col.css
The offset value of sm and lg don't have the right layout in  Col.
> Col: fix a style bug about responsive layout

- packages/select/src/select.vue
> Select: fix remote filter not showing dropdown issue

- packages/autocomplete/src/autocomplete.vue
- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/panel/date.vue
- packages/date-picker/src/panel/time-range.vue
- packages/date-picker/src/panel/time-select.vue
- packages/date-picker/src/panel/time.vue
- packages/dropdown/src/dropdown-menu.vue
- packages/form/src/form-item.vue
- packages/menu/src/submenu.vue
- packages/select/src/select.vue
- packages/table/src/filter-panel.vue
- packages/tag/src/tag.vue
- packages/theme-default/src/common/transition.css
- packages/upload/src/cover.vue
remove unuse transition class and normalize them
> normalize transition class name

- packages/upload/src/index.vue
> make upload creat url for all file #1467

- packages/theme-default/src/step.css
> fix steps style bug in ie9

- packages/select/src/select.vue
> Select: fix async bug/fix object-typed value init issue

- src/locale/lang/de.js
German native speaker here,
did my best to improve the locale.
Could not see the actual usage of some items like select.noMatch so I hope it still matches the use case.
> Improve German locale

- packages/select/src/select.vue
> Select: show dropdown when options are given in remote mode

- packages/slider/src/main.vue
> Slider: avoid clicking triggering right after dragend

- packages/theme-default/src/date-picker/time-picker.css
- packages/theme-default/src/date-picker/time-range-picker.css
- packages/theme-default/src/date-picker/time-spinner.css
- packages/theme-default/src/spinner.css
> TimeSelect: remove flexbox style, fixed #1335

- README.md
- examples/docs/en-US/i18n.md
- examples/docs/en-US/message-box.md
- examples/docs/zh-CN/i18n.md
- examples/docs/zh-CN/message-box.md
> add translation team members.

- examples/docs/en-US/i18n.md
- examples/docs/zh-CN/i18n.md
> doc: IgnorePlugin => NormalModuleReplacementPlugin, fixed #1315

- build/deploy-ci.sh
> CI: fix and test deploy script

- src/locale/lang/fa.js
> :sparkles: Added fa locale

- packages/table/src/table.vue
> :bug: [Table] fixed incompatibility with vue-i18n (#1587)

- packages/select/src/option.vue
- packages/select/src/select.vue
> Select: fix display issue of object-typed value in remote mode

- src/locale/lang/th.js
> Added Thai translation

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
> fix table docs(fix #1563)

- examples/docs/en-US/tabs.md
- examples/docs/zh-CN/tabs.md
- packages/tabs/src/tab-pane.vue
- packages/tabs/src/tabs.vue
- packages/theme-default/src/tabs.css
- test/unit/specs/tabs.spec.js
> support tab disabled(fix #1598)

- examples/docs/en-US/switch.md
- packages/switch/src/component.vue
- packages/theme-default/src/switch.css
`switch` 组件 `disabled` 状况下自定义颜色不正常，如此例中：http://jsfiddle.net/j95axgwh/
- `mounted` 时 `disabled` 的组件 enable 后自定义颜色不生效
- 一旦触发自定义颜色生效则 `disabled` 样式的颜色不生效
> Fixed switch custom color with disabled.

- packages/select/src/option.vue
- packages/select/src/select.vue
> Select: fix clearable still working bug in disabled mode

- examples/docs/en-US/form.md
- examples/docs/zh-CN/form.md
> Modify document error

- packages/upload/src/ajax.js
- test/unit/specs/upload.spec.js
> Upload: remove 'X-Requested-With' header

- README.md
> Add awesome-element link

- src/locale/lang/tr-TR.js
> locale: fix tr-TR

- packages/table/src/table-body.js
> Table: add missing ElCheckbox

- packages/upload/src/index.vue
> Upload: fix thumbnailed upload slow bug, fixed #1641

- packages/table/src/table.vue
- packages/theme-default/src/table.css
> Table: fix a style bug when fixed=right.

- build/cooking.demo.js
- packages/table/src/table-column.js
- packages/table/src/table.vue
- packages/theme-default/src/table-column.css
> Table: fix column[type=selection] style issue in ie9+.

- packages/date-picker/src/basic/time-spinner.vue
- packages/date-picker/src/panel/time.vue
- packages/theme-default/src/date-picker/time-picker.css
- packages/theme-default/src/date-picker/time-spinner.css
- packages/theme-default/src/time-select.css
> TimePicker: fix HH:mm style

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- examples/docs/en-US/i18n.md
- examples/docs/zh-CN/i18n.md
> Changelog: update for 1.0.6

- examples/docs/en-US/table.md
- packages/table/src/table-body.js
This PR adds the event "row-contextmenu" which is triggered when user right clicks on a table row.
> Add contextmenu event on table row element.

- packages/select/src/option-group.vue
- packages/select/src/select.vue
> Select: fix filterable group bug, fixed #1678

- packages/tabs/src/tabs.vue
> Tabs: fix empty tab-pane issue, fixed #1608

- packages/input-number/src/input-number.vue
> add old value for input-number change event

- packages/theme-default/src/upload.css
> Upload: fix file list style

- packages/input-number/src/input-number.vue
> support input-number append prepend slot

- README.md
> README: add donation

- examples/docs/en-US/table.md
- packages/table/src/table-layout.js
- packages/table/src/table.vue
- packages/theme-default/src/table.css
- test/unit/specs/table.spec.js
> Feature table maxHeight (#1560)

- examples/docs/en-US/tag.md
- examples/docs/zh-CN/tag.md
- packages/tag/src/tag.vue
- packages/theme-default/src/common/var.css
- packages/theme-default/src/tag.css
- test/unit/specs/tag.spec.js
> support tag color property(#1665)

- examples/docs/en-US/select.md
- examples/docs/zh-CN/select.md
- packages/select/src/select.vue
- packages/theme-default/src/select.css
> Select: add size property

- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/panel/date.vue
- packages/date-picker/src/panel/time-range.vue
- packages/date-picker/src/panel/time.vue
- packages/date-picker/src/picker.vue
- packages/theme-default/src/date-picker/picker-panel.css
- test/unit/specs/date-picker.spec.js
> DatePicker: fix clear button, fixed #1690

- examples/docs/en-US/date-picker.md
- examples/docs/en-US/datetime-picker.md
- examples/docs/en-US/message-box.md
- examples/docs/en-US/rate.md
- examples/docs/en-US/steps.md
- examples/docs/en-US/time-picker.md
- examples/docs/en-US/tree.md
- examples/docs/zh-CN/date-picker.md
- examples/docs/zh-CN/datetime-picker.md
- examples/docs/zh-CN/loading.md
- examples/docs/zh-CN/message-box.md
- examples/docs/zh-CN/rate.md
- examples/docs/zh-CN/steps.md
- examples/docs/zh-CN/switch.md
- examples/docs/zh-CN/time-picker.md
- examples/docs/zh-CN/tree.md
- examples/pages/template/component.tpl
- packages/message-box/src/main.vue
> MessageBox: add customClass

- examples/docs/en-US/button.md
- examples/docs/zh-CN/button.md
> improve button docs

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
- packages/table/src/table.vue
> Table: add  slot, closed #1737, closed #1730

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
> Table: update docs

- examples/docs/en-US/message.md
- examples/docs/en-US/notification.md
- examples/docs/zh-CN/message.md
- examples/docs/zh-CN/notification.md
- packages/message/src/main.vue
- packages/notification/src/main.vue
- packages/theme-default/src/message.css
- packages/theme-default/src/notification.css
- test/unit/specs/message.spec.js
> Message & Notification: add iconClass and customClass, fixed #1664

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
> Changelog: update for 1.0.7

- packages/tabs/src/tab-pane.vue
> fix the tab bar dynamic bug

- src/utils/vue-popper.js
> Popup: prevent click event bubbles, fixed #1677

- packages/date-picker/src/panel/date-range.vue
> DatePicker: fix datetimerange, fixed #1758

- examples/docs/en-US/upload.md
- examples/docs/zh-CN/upload.md
- packages/upload/src/index.vue
> add progress hook function property

- src/locale/lang/id.js
Hi,
just translating this awesome project to Indonesian.
Thank you
> Add Indonesian translation

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
- packages/table/src/table-body.js
- test/unit/specs/table.spec.js
> Table row click

- examples/docs/en-US/tree.md
- examples/docs/zh-CN/tree.md
- packages/tree/src/model/node.js
- packages/tree/src/model/tree-store.js
- packages/tree/src/tree-node.vue
- packages/tree/src/tree.vue
- test/unit/specs/tree.spec.js
> Tree: add current-change event & current-node-key.

- examples/docs/zh-CN/installation.md
> npm i element-ui -D => npm i element-ui -S

- packages/slider/src/main.vue
> Slider: fix change event

- packages/select/src/option.vue
- packages/select/src/select.vue
> Select: fix a dropdown update bug

- examples/docs/en-US/installation.md
- packages/theme-default/src/loading.css
> Loading: update spinner animation, fixed #1786

- packages/checkbox/src/checkbox.vue
> support use checkbox without transport value(fix #1736)

- packages/theme-default/src/input.css
> fix input line-height(fix #1815)

- examples/docs/en-US/tree.md
- examples/docs/zh-CN/tree.md
- packages/tree/src/tree-node.vue
- packages/tree/src/tree.vue
- test/unit/specs/tree.spec.js
> Tree: add expand-on-click-node prop.

- packages/date-picker/src/picker.vue
> DatePicker: fix set value, fixed #1773

- examples/docs/en-US/custom-theme.md
- examples/docs/zh-CN/custom-theme.md
> Doc: fix custom theme, fixed #1828

- .github/CONTRIBUTING.md
- examples/docs/en-US/select.md
- examples/docs/zh-CN/select.md
- packages/select/src/select.vue
- test/unit/specs/select.spec.js
> Select: add visible-change event

- packages/theme-default/src/switch.css
> Switch: update style

- examples/docs/en-US/form.md
- examples/docs/zh-CN/form.md
- packages/form/src/form-item.vue
> fix form validate callback params(fix #1659)

- examples/docs/en-US/menu.md
- examples/docs/zh-CN/menu.md
- packages/menu/src/menu-item-group.vue
- packages/menu/src/menu-item.vue
- packages/menu/src/menu-mixin.js
- packages/menu/src/submenu.vue
- packages/theme-default/src/menu.css
> add suport for mutil level submenu

- examples/docs/en-US/pagination.md
- examples/docs/zh-CN/pagination.md
- packages/pagination/src/pagination.js
- test/unit/specs/pagination.spec.js
> Pagination: fix slot

- examples/docs/en-US/form.md
- examples/docs/zh-CN/form.md
- packages/form/src/form-item.vue
> fix form validate callback params

- src/utils/clickoutside.js
> fix typo in clickoutside directive

- examples/docs/en-US/form.md
- examples/docs/zh-CN/form.md
- packages/form/src/form-item.vue
This reverts commit 87b13bf0e07c0ce8ac183ecd2020088c26a81de0.
> Revert "fix form validate callback params"

- packages/checkbox/src/checkbox.vue
> fix checkbox isGroup bug in computed cached

- packages/date-picker/src/basic/date-table.vue
> DatePicker: fix #1827

- examples/docs/en-US/tabs.md
- examples/docs/zh-CN/tabs.md
- packages/tabs/src/tabs.vue
> add param to label-content render function(fix #1820)

- examples/assets/styles/fonts/style.css
- package.json
- yarn.lock
> Dialog: fix z-index of non-modal dialogs

- examples/docs/en-US/date-picker.md
- examples/docs/en-US/datetime-picker.md
- examples/docs/en-US/select.md
- examples/docs/en-US/time-picker.md
- examples/docs/en-US/tooltip.md
- examples/docs/zh-CN/date-picker.md
- examples/docs/zh-CN/datetime-picker.md
- examples/docs/zh-CN/select.md
- examples/docs/zh-CN/time-picker.md
- examples/docs/zh-CN/tooltip.md
- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/panel/date.vue
- packages/date-picker/src/panel/time-range.vue
- packages/date-picker/src/panel/time-select.vue
- packages/date-picker/src/panel/time.vue
- packages/date-picker/src/picker.vue
- packages/select/src/select-dropdown.vue
- packages/select/src/select.vue
- packages/tooltip/src/main.vue
- test/unit/specs/select.spec.js
- test/unit/specs/tooltip.spec.js
> add popper-class for DatePicker, Select and Tooltip

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
- packages/table/src/table-column.js
- packages/table/src/table-store.js
- test/unit/specs/table.spec.js
> Table: add filter change event & add column-key for column.

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- examples/docs/en-US/i18n.md
- examples/docs/zh-CN/i18n.md
> Changelog: update for 1.0.8

- examples/docs/en-US/dropdown.md
- examples/docs/zh-CN/dropdown.md
- packages/dropdown/src/dropdown.vue
- test/unit/specs/dropdown.spec.js
- test/unit/specs/popover.spec.js
> add dropdown hide-on-click prop

- examples/docs/en-US/radio.md
- examples/docs/zh-CN/radio.md
> Radio: fix doc, text-color,fill are Radio-group's props

- packages/pagination/src/pagination.js
> fix the code style issue to pass eslint

- examples/docs/zh-CN/table.md
- packages/table/src/table-column.js
- packages/table/src/table-header.js
- test/unit/specs/table.spec.js
> Table: add header-align, Fixed #1424

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
> Table: update header-align docs

- examples/docs/en-US/dropdown.md
- examples/docs/en-US/tabs.md
- examples/docs/zh-CN/dropdown.md
- examples/docs/zh-CN/tabs.md
> imrpove dropdown & tabs docs

- packages/select/src/option.vue
- packages/select/src/select.vue
> Select: optimize filterable, fixed #1933

- packages/form/src/form.vue
> fix form async validate bug(fix #1882)

- packages/checkbox/src/checkbox.vue
- packages/radio/src/radio.vue
- packages/theme-default/src/checkbox.css
- packages/theme-default/src/radio.css
- test/unit/specs/table.spec.js
调整checkbox radio状态类的class位置和为label加上disabled状态对应的样式
#1911
> fix checkbox radio status class && disable style（fix #1911）

- packages/table/src/table-header.js
- test/unit/specs/table.spec.js
> Table: modify table sort, Fixed #1759

- packages/tree/src/tree-node.vue
> Tree: Remove undefined variable, fixed #1945

- examples/docs/en-US/time-picker.md
- examples/docs/zh-CN/time-picker.md
- packages/date-picker/src/panel/time-select.vue
- test/unit/specs/time-select.spec.js
> TimeSelect: add maxTime, resolve #1826

- examples/index.tpl
- package.json
> Add unpkg and style into package.json & Fix ga

- packages/table/src/table-body.js
> Table: remove highlight class after data change

- components.json
- examples/docs/en-US/collapse.md
- examples/docs/zh-CN/collapse.md
- examples/nav.config.json
- packages/collapse-item/index.js
- packages/collapse/_index.js
- packages/collapse/cooking.conf.js
- packages/collapse/index.js
- packages/collapse/package.json
- packages/collapse/src/collapse-item.vue
- packages/collapse/src/collapse.vue
- packages/theme-default/src/collapse.css
- packages/theme-default/src/common/var.css
- packages/theme-default/src/index.css
- src/index.js
- test/unit/specs/collapse.spec.js
> add collapse

- examples/docs/en-US/input.md
- examples/docs/zh-CN/input.md
- packages/input/src/input.vue
- test/unit/specs/input.spec.js
修正 Input 内部的绑定属性为 `currentValue`，并补全一些测试和文档
> fix input value binding bug

- examples/docs/en-US/date-picker.md
- examples/docs/en-US/datetime-picker.md
- examples/docs/en-US/time-picker.md
- examples/docs/zh-CN/date-picker.md
- examples/docs/zh-CN/datetime-picker.md
- examples/docs/zh-CN/time-picker.md
- packages/date-picker/src/picker.vue
- test/unit/specs/date-picker.spec.js
> add clearable api

- packages/collapse/src/collapse-item.vue
- packages/scrollbar/src/bar.js
> Remove wind-dom

- packages/select/src/select.vue
> Select: fix disabled multiple tag delete

- packages/pagination/src/pagination.js
> Pagination: add button type

- examples/docs/en-US/tabs.md
- examples/docs/zh-CN/tabs.md
- package.json
- packages/tabs/src/tab-pane.vue
- packages/tabs/src/tabs.vue
- packages/theme-default/src/tabs.css
- test/unit/specs/tabs.spec.js
- yarn.lock
> add support for v-model & fix tabs initial width bug & improve docs

- packages/theme-default/src/col.css
> fix xs resolution style

- examples/docs/en-US/collapse.md
> Collapse: update English doc

- packages/input-number/src/input-number.vue
> InputNumber: fix float number

- examples/components/footer.vue
- examples/components/side-nav.vue
> upgrade version

- examples/docs/zh-CN/input.md
- packages/input-number/src/input-number.vue
- packages/input/src/input.vue
> fix input blur event bug

- examples/docs/zh-CN/carousel.md
- packages/carousel/src/item.vue
- packages/carousel/src/main.vue
- packages/theme-default/src/carousel-item.css
> Carousel: improve arrow hover behavior in card mode

- examples/docs/en-US/date-picker.md
- examples/docs/zh-CN/date-picker.md
- packages/date-picker/src/basic/date-table.vue
- packages/date-picker/src/panel/date.vue
- test/unit/specs/date-picker.spec.js
> DatePicker: custom fisrt day of week #1061

- examples/docs/en-US/date-picker.md
- examples/docs/en-US/datetime-picker.md
- examples/docs/en-US/time-picker.md
- examples/docs/zh-CN/date-picker.md
- examples/docs/zh-CN/datetime-picker.md
- examples/docs/zh-CN/time-picker.md
- packages/theme-default/src/date-picker/picker.css
> DatePicker: input display style changes to block, fixed #2018

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
- packages/table/src/table-body.js
- packages/table/src/table-column.js
- packages/table/src/table-store.js
- packages/table/src/table.vue
- packages/theme-default/src/table.css
- test/unit/specs/table.spec.js
> Table: add expand row feature.

- examples/docs/en-US/date-picker.md
- examples/docs/en-US/datetime-picker.md
- examples/docs/en-US/time-picker.md
- examples/docs/zh-CN/date-picker.md
- examples/docs/zh-CN/datetime-picker.md
- examples/docs/zh-CN/time-picker.md
- packages/theme-default/src/date-picker/picker.css
This reverts commit b3095a703c5b0413aa479b600843fe488fbe3183.
> Revert "DatePicker: input display style changes to block, fixed #2018"

- examples/components/side-nav.vue
- examples/nav.config.json
> website minor updates

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
- examples/docs/zh-CN/tree.md
- packages/table/src/table-store.js
- packages/table/src/table.vue
- test/unit/specs/table.spec.js
> Table: add current-row-key prop.

- packages/upload/src/index.vue
> Upload: fix ssr suppport

- examples/docs/en-US/alert.md
- examples/docs/zh-CN/alert.md
- packages/alert/src/main.vue
- test/unit/specs/alert.spec.js
> Alert: replace render function with default slot

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
- package.json
- packages/table/src/table-body.js
- packages/table/src/table-column.js
- test/unit/specs/table.spec.js
> Table: expand row feature only supports scoped slot.

- packages/date-picker/src/picker.vue
- packages/dropdown/src/dropdown-menu.vue
- packages/rate/src/main.vue
- src/utils/vue-popper.js
> Fix overwritten warn in Vue 2.1.8, fixed #2040

- examples/docs/en-US/badge.md
- examples/docs/zh-CN/badge.md
- packages/badge/src/main.vue
> Badge: add hidden prop, close #2042

- packages/date-picker/src/basic/time-spinner.vue
> TimePicker: fix scrolltop error

- packages/pagination/src/pagination.js
- packages/table/src/table.vue
> remove obsolete migrating hints

- packages/date-picker/src/picker.vue
> DatePicker: dynamic picker-options, close #2013

- packages/theme-default/src/scrollbar.css
> Scrollbar: fix the style vars

- packages/collapse/src/collapse-item.vue
- packages/collapse/src/collapse.vue
- test/unit/specs/collapse.spec.js
> fix collapse toggle bug

- examples/docs/en-US/tabs.md
- examples/docs/zh-CN/tabs.md
- packages/tabs/src/tabs.vue
- packages/theme-default/src/tabs.css
- test/unit/specs/tabs.spec.js
- Tabs 的盒模型变更为 'block'
- 移除 Tab Pane 的 `label-content` 属性
> change tabs box-model to 'block' & remove 'label-content' property

- examples/docs/en-US/i18n.md
- examples/docs/zh-CN/i18n.md
> Doc: update docs about vue-i18n, close #2039

- examples/docs/en-US/input.md
- examples/docs/zh-CN/input.md
- packages/autocomplete/src/autocomplete-suggestions.vue
- packages/autocomplete/src/autocomplete.vue
- packages/theme-default/src/autocomplete.css
- test/unit/specs/autocomplete.spec.js
> insert autocomplete suggestions to body

- packages/dropdown/src/dropdown-menu.vue
> Dropdown: fix placement

- packages/date-picker/src/picker.vue
- packages/date-picker/src/util/index.js
> DatePicker: fix change event trigger multiple times, fixed #2060

- examples/docs/zh-CN/form.md
- packages/form/src/form-item.vue
> fix valida field params bug

- packages/autocomplete/src/autocomplete-suggestions.vue
- packages/autocomplete/src/autocomplete.vue
> fix autocomplete dropdown reference element

- packages/input-number/src/input-number.vue
- test/unit/specs/input-number.spec.js
> fix input-number invalid value reset bug(fix #2063)

- examples/docs/en-US/layout.md
- examples/docs/zh-CN/layout.md
> improve layout docs

- examples/docs/en-US/collapse.md
- examples/docs/zh-CN/collapse.md
- packages/collapse/src/collapse-item.vue
> remove collapse scoped slot title && add named slot title

- packages/tabs/src/tabs.vue
> fix tab remove bug

- packages/input/src/input.vue
> Feat input

- packages/select/src/select.vue
- packages/theme-default/src/select-dropdown.css
> Select: fix dropdownUl undefined bug

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> Update github template

- packages/date-picker/src/picker.vue
> TimePicker: fix range timepicker

- packages/input-number/src/input-number.vue
- test/unit/specs/date-picker.spec.js
1. Add `max` and `min` to `el-input`.
2. Replace `acAdd, accSub` with `_increase, _decrease`.
3. Add `precision`.
4. Change default `min` to `-Infinity`.
> InputNumber, DatePicker: Clearify the logic of increase and decrease. Fix date-picker.spec.js bugs.

- examples/docs/zh-CN/tree.md
> Tree: fix a doc error.

- FAQ.md
> FAQ: remove inline-template

- packages/dropdown/src/dropdown.vue
> Dropdown: import button/button-group, fixed #2159

- packages/date-picker/src/panel/time-select.vue
- test/unit/specs/time-select.spec.js
> TimeSelect: fix maxTime range, fixed #2158

- packages/select/src/option.vue
- packages/select/src/select.vue
> Select: fix allowCreate bug

- examples/app.vue
联动 https://github.com/ElemeFE/element/issues/1703
没用到的字体，会引起编译错误，建议去除。
> remove useless examples/assets/fonts/style.css

- packages/date-picker/src/basic/date-table.vue
> Fix the next year is calulated incorrectly, fixed #2152

- examples/docs/zh-CN/tabs.md
- packages/tabs/src/tab-bar.vue
- packages/tabs/src/tab-pane.vue
- packages/tabs/src/tabs.vue
- packages/theme-default/src/tabs.css
- test/unit/specs/tabs.spec.js
> fix tab-bar initial status bug

- packages/theme-default/src/tabs.css
http://jsfiddle.net/75pvm529/
这个问题
> Tabs: fix invalid type prop when tabs in other tabs

- packages/theme-default/src/pagination.css
> Pagination: fix ul style in IE9, fixed #2209

- packages/tree/src/tree-node.vue
> Fix tree bug

- examples/docs/en-US/menu.md
- examples/docs/zh-CN/menu.md
- packages/menu/src/menu-item.vue
- packages/menu/src/menu-mixin.js
- packages/menu/src/menu.vue
- packages/menu/src/submenu.vue
- packages/theme-default/src/menu.css
- test/unit/specs/menu.spec.js
1. 代码改善，强化通过数据更新来改变组件状态
2. 文档增加外链的例子
3. 修复 #2178 中指出的问题
4. 对3的bug的单元测试补全
> improve code & fix inittial submenu active bug

- build/bin/build-entry.js
- examples/docs/en-US/i18n.md
- examples/docs/zh-CN/i18n.md
- src/index.js
- src/locale/index.js
> Locale: customize i18n handler, close #2129

- packages/table/src/table-column.js
- test/unit/specs/table.spec.js
> Table: fix header-align bug, Fixed #2220

- packages/select/src/select.vue
- test/unit/specs/select.spec.js
> Select: fix filterable init value issue, fixed #2196

- examples/docs/en-US/input.md
- examples/docs/zh-CN/input.md
- packages/autocomplete/src/autocomplete-suggestions.vue
- packages/autocomplete/src/autocomplete.vue
- test/unit/specs/autocomplete.spec.js
1. 修正 autocomplete 在 blur 事件触发 suggestions 时没有收起的问题 #2155
2. 补充 trigger-on-focus 的文档
> fix autocomplete do not hide on blur bug

- examples/docs/en-US/input.md
- examples/docs/zh-CN/input.md
- packages/input/src/calcTextareaHeight.js
- packages/input/src/input.vue
> Input: support resize prop

- test/unit/specs/table.spec.js
> Table: fix unit test, fixed #2243

- examples/docs/en-US/input.md
- examples/docs/zh-CN/input.md
- packages/theme-default/src/input.css
1. 修正 textarea 的对齐问题
2. 补充 textarea 的自适应高度文档例子
> fix textarea style & improve docs

- examples/docs/en-US/input.md
- examples/docs/zh-CN/input.md
> Input: update doc

- examples/docs/en-US/popover.md
- examples/docs/en-US/tooltip.md
- examples/docs/zh-CN/popover.md
- examples/docs/zh-CN/tooltip.md
- packages/popover/src/main.vue
> Popover: add disabled feature, close #2221

- examples/docs/en-US/notification.md
- examples/docs/zh-CN/notification.md
- packages/message-box/src/main.vue
- packages/notification/src/main.js
- packages/notification/src/main.vue
- packages/theme-default/src/notification.css
- src/utils/vdom.js
- test/unit/specs/notification.spec.js
> Notification: Support HTML, close #1885

- build/config.js
- packages/menu/src/submenu.vue
- packages/tabs/src/tab-pane.vue
- packages/tree/src/tree-node.vue
- src/transitions/collapse-transition.js
> add submenu transition

- src/locale/index.js
> Locale: fix empty string

- src/locale/index.js
> Loacle: fix i18n handler

- packages/carousel/src/main.vue
> Carousel: fix autoplay props

- src/locale/lang/pl.js
> Create pl.js - Polish translation

- packages/input-number/src/input-number.vue
- test/unit/specs/input-number.spec.js
- test/unit/specs/slider.spec.js
> fix input-number change event(fix #1964)

- packages/select/src/select.vue
> Select: fix multiple style issue

- packages/tabs/src/tab-bar.vue
> add tab-bar transform prefix

- examples/docs/en-US/form.md
- examples/docs/zh-CN/form.md
- packages/form/src/form-item.vue
- packages/form/src/form.vue
- test/unit/specs/form.spec.js
> add show-message support

- packages/input-number/src/input-number.vue
- test/unit/specs/input-number.spec.js
> input-number auto adjust min max value

- examples/docs/en-US/steps.md
- examples/docs/zh-CN/steps.md
- packages/steps/README.md
- packages/steps/src/step.vue
- packages/steps/src/steps.vue
- packages/theme-default/src/steps.css
> Steps: add center property, resolve #2315

- examples/docs/en-US/slider.md
- examples/docs/zh-CN/slider.md
- packages/slider/src/main.vue
> Slider: add show-input-controls, fixed #2304

- packages/theme-default/src/tree.css
- src/transitions/collapse-transition.js
> fix fast click on submenu collapse transition bug

- packages/table/src/table-body.js
> Table: table-body revert to  v1.1.2, fixed #2312

- packages/table/src/table-header.js
- test/unit/specs/table.spec.js
> fix bug: default-sort-prop is not defined but trigger sort-change event

- examples/pages/template/changelog.tpl
> Doc: username converted to GitHub profile link in changelog page

- examples/docs/en-US/notification.md
> Notification(doc): missing api information

- packages/collapse/src/collapse-item.vue
> use collapse transition in collapse(fix #2325)

- packages/message-box/src/main.js
> MessageBox: fix multi alert bug, Fixed #2352

- packages/date-picker/src/util/index.js
> DatePicker: fix null value shows 1970, fixed #2388

- packages/select/src/option.vue
- packages/select/src/select.vue
> Select: fix filterable error with number-typed value

- packages/table/src/table-layout.js
> Table: fix fixed column height when empty data, fixed #2300

- packages/table/src/table-column.js
> Table: missing filteredValue prop, fixed #2348

- packages/menu/src/menu.vue
#2391
在 router 模式下不在手动更新 `activedIndex`，通过 `watch` 来执行 `activedIndex` 的更新
> fix first enter do not active the menu bug(fix #2391)

- packages/table/src/table.vue
> Table: fix body width when no data

- packages/loading/src/directive.js
- packages/loading/src/index.js
- packages/loading/src/loading.vue
- packages/theme-default/src/loading.css
- test/unit/specs/loading.spec.js
> Loading: add fading animations

- examples/docs/en-US/message-box.md
- examples/docs/zh-CN/message-box.md
- packages/message-box/src/main.js
- packages/message-box/src/main.vue
- test/unit/specs/message-box.spec.js
> MessageBox: add beforeClose

- examples/docs/en-US/checkbox.md
- examples/docs/zh-CN/checkbox.md
- packages/checkbox/src/checkbox-group.vue
- packages/checkbox/src/checkbox.vue
1. 修正 Checkbox Group 在绑定值改变时会触发 `change` 事件的问题（原则上应该在手动改变checkbox时）才会触发`change`事件
2. 增加半选状态的文档例子
> fix checkbox gourp change event && improve docs

- examples/docs/en-US/input.md
- examples/docs/zh-CN/input.md
- packages/input/src/input.vue
- packages/theme-default/src/input.css
增加图标点击的钩子函数可以通过其是否存在来判定 hover 时的手势
> support input icon click hook function

- examples/docs/en-US/form.md
- examples/docs/zh-CN/form.md
- packages/form/src/form-item.vue
1. 当 `label-position` 为 'top' 时移除 form-item-label 和 form-item-content 的 label 样式
2. 优化 label position 的🌰文档
> remove labelWidth when labelPosition is 'top'

- examples/docs/en-US/input-number.md
- examples/docs/zh-CN/input-number.md
> add input-number size docs

- examples/docs/en-US/radio.md
- examples/docs/zh-CN/radio.md
- packages/radio/src/radio-button.vue
- packages/radio/src/radio-group.vue
- packages/radio/src/radio.vue
- packages/theme-default/src/common/var.css
- packages/theme-default/src/radio.css
- test/unit/specs/radio.spec.js
1. 支持 radio group 的 disabled 属性
2. 修复 radio button 在 active 和 disabled 同时触发时样式仍然是 active 状态的问题
3. 改进文档
> feature: Radio Group disabled  && radio button style bug fix

- examples/docs/en-US/input.md
> Fix doc en-US language

- packages/table/src/filter-panel.vue
其实是一个简单的错误，就是第一个过滤项的`filterValue `是0，然后在代码中有
```
if (filterValue) 
```
这样的判断，于是就不对了
> 修复在table组件中，选择第一个过滤项，在filter-change事件中，得到的选择元素的下标有误

- examples/docs/en-US/table.md
- examples/docs/zh-CN/table.md
- packages/table/src/table-header.js
- packages/table/src/table.vue
> revise table default sort api

- packages/tree/src/tree-node.vue
- packages/tree/src/tree.vue
修复 Tree accordion 模式下点击三角图标没有触发 accordion 效果的问题
> fix tree accordion bug when click on icon

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- examples/docs/en-US/i18n.md
- examples/docs/zh-CN/i18n.md
> update i18n docs

- packages/menu/src/menu.vue
This reverts commit ef06717f64bc1a54c10b6549948056669ab5a85c.
修复 #2446 中提到的问题，同意 Menu 组件确实不应该跟路由有太强的绑定关系，路由与 Menu `activeIndex` 关联应该在用户项目中建立路由与 `activeIndex` 的映射来实现联动。
> Revert "fix first enter do not active the menu bug (#2399)"

- packages/collapse/src/collapse.vue
> support collapse value type(fix #2452)

- examples/docs/en-US/tag.md
- examples/docs/zh-CN/tag.md
> add improve tag docs

- packages/message-box/src/main.js
> MessageBox: add default customClass, fixed #2438

- examples/docs/en-US/time-picker.md
- examples/docs/zh-CN/time-picker.md
> TimeSelect(doc): fix format api, fixed #2416

- packages/select/src/select.vue
> Select: update style if initially invisible

- examples/docs/en-US/radio.md
- examples/docs/zh-CN/radio.md
- packages/radio/src/radio-group.vue
> RadioGroup: allow boolean value, fixed #2442

- packages/table/src/table-column.js
- packages/table/src/table-store.js
> Table: fix columnKey, fixed #2322

- packages/date-picker/src/picker.vue
- packages/select/src/select-dropdown.vue
- packages/tooltip/src/main.js
- src/utils/vue-popper.js
> change vue-popper 'options' to 'popperOptions'
