ElemeFE/element

- packages/loading/src/directive.js
> Loading: fix after-leave execution when init value is false

- packages/theme-chalk/src/table.scss
> fix table border when v-loading is true

- packages/menu/src/menu.vue
> fallback menu active when route change cancel

- examples/docs/en-US/tree.md
- examples/docs/es/tree.md
- examples/docs/zh-CN/tree.md
- packages/tree/src/model/node.js
- packages/tree/src/model/tree-store.js
- packages/tree/src/tree-node.vue
- packages/tree/src/tree.vue
- test/unit/specs/tree.spec.js
Fix #6247 
Fix #6994 
Fix #5653
> add api for tree

- examples/docs/en-US/tree.md
- examples/docs/es/tree.md
- examples/docs/zh-CN/tree.md
> update tree docs for children & isLeaf

- examples/docs/en-US/tree.md
- examples/docs/es/tree.md
- examples/docs/zh-CN/tree.md
- packages/tree/src/model/tree-store.js
- packages/tree/src/tree-node.vue
- packages/tree/src/tree.vue
- test/unit/specs/tree.spec.js
Fix #8537 
Fix #7979
Fix #9295
> Add check event and getHalfChecedNodes method for Tree

- examples/docs/en-US/menu.md
- examples/docs/zh-CN/menu.md
- packages/menu/src/submenu.vue
- packages/theme-chalk/src/menu.scss
> fix mutil level submenu in horizontal mode

- examples/components/side-nav.vue
- examples/docs/en-US/tree.md
- examples/docs/es/menu.md
- examples/docs/es/tree.md
- examples/pages/template/index.tpl
> Chore: update docs for Tree and Menu

- packages/switch/src/component.vue
> Switch: fix click event triggering twice

- examples/docs/en-US/menu.md
- examples/docs/es/menu.md
- examples/docs/zh-CN/menu.md
- packages/menu/src/menu-item.vue
- packages/menu/src/submenu.vue
- packages/theme-chalk/src/menu.scss
- test/unit/specs/menu.spec.js
> support menu disabled

- packages/menu/src/menu.vue
> improve vertical collapse transition

- packages/date-picker/src/basic/date-table.vue
- packages/dropdown/src/dropdown.vue
- packages/form/src/form-item.vue
- packages/input/src/input.vue
- packages/message-box/src/main.vue
- packages/progress/src/progress.vue
- packages/row/src/row.js
- packages/upload/src/iframe-upload.vue
使用es6规范声明变量
- 使用let、const声明，而不是用var
- 在变量需要改变赋值的时候使用let
- 变量不需要再次被赋值的时候使用const
- 确保没有使用变量提升
> use the es6 'let' and 'const' to declare variables

- packages/theme-chalk/src/color-picker.scss
In case some users like me declare `box-sizing: border-box` globally and may causing unexpected problems.
> ColorPicker: explicit declare box-sizing: content-box

- examples/docs/en-US/i18n.md
- examples/docs/en-US/select.md
- examples/docs/es/i18n.md
- examples/docs/es/select.md
- examples/docs/zh-CN/i18n.md
- examples/docs/zh-CN/select.md
- packages/select/src/select-dropdown.vue
- packages/select/src/select.vue
- packages/theme-chalk/src/select.scss
Fixed #7468 
Fixed #9674
Fixed #6271
Fixed #2441
> Select: add popper-append-to-body

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
- build/bin/version.js
- build/deploy-ci.sh
- build/deploy-faas.sh
- examples/components/footer.vue
- examples/docs/en-US/menu.md
- examples/docs/en-US/quickstart.md
- examples/docs/es/menu.md
- examples/docs/es/quickstart.md
- examples/docs/zh-CN/quickstart.md
> Changelog: update for 2.2.0

- examples/docs/es/menu.md
> Menu: update es doc

- CHANGELOG.en-US.md
- CHANGELOG.es.md
> Doc: update changelogs

- .github/CONTRIBUTING.en-US.md
- .github/CONTRIBUTING.es.md
- .github/CONTRIBUTING.zh-CN.md
- package.json
> Chore: update contribution guide

- package.json
- packages/theme-chalk/src/aside.scss
- packages/theme-chalk/src/footer.scss
- packages/theme-chalk/src/header.scss
> Container: forbid shrinking for Aside, Header and Footer

- packages/menu/src/menu.vue
- packages/theme-chalk/src/select.scss
> Select: fix style for inline popper

- examples/components/side-nav.vue
- packages/table/src/table-layout.js
> Table: fix js pending in ssr

- packages/table/src/table-store.js
> Table: calc layout after row expansion changes

- examples/docs/en-US/installation.md
- examples/docs/en-US/quickstart.md
- examples/docs/es/installation.md
- examples/docs/es/quickstart.md
- examples/docs/zh-CN/installation.md
- examples/docs/zh-CN/quickstart.md
1. vue-cli 已经不是一个初始化模板的工具了，因此移除掉相关介绍
2. 直接使用 jsfiddle embed 替代代码块，方便演示效果
3. 增加 Nuxt.js 例子
4. 又自动 format markdown 文件了 hhhh
> docs: update quickstart demo, close #9883

- examples/docs/en-US/slider.md
- examples/docs/es/slider.md
- examples/docs/zh-CN/slider.md
- packages/slider/src/button.vue
- packages/slider/src/main.vue
- types/slider.d.ts
> Slider: add tooltip-class

- packages/input-number/src/input-number.vue
> InputNumber: prevent drag event

- packages/select/src/select.vue
> Select: fix an emptyText visibility bug

- examples/docs/en-US/transfer.md
- examples/docs/es/transfer.md
- examples/docs/zh-CN/transfer.md
- packages/transfer/src/main.vue
- test/unit/specs/transfer.spec.js
- types/transfer.d.ts
> Transfer: add target-order

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
- examples/docs/en-US/quickstart.md
- examples/docs/es/quickstart.md
- examples/docs/zh-CN/quickstart.md
> Changelog: update for 2.2.1

- packages/popover/src/main.vue
- packages/tooltip/src/main.js
> Popover & Tooltip: focus reference element on tab if it's focusable

- packages/color-picker/src/color.js
- packages/color-picker/src/components/picker-dropdown.vue
> ColorPicker: support hsl/hsv model input

- packages/slider/src/main.vue
> Slider: warn against min being greater than max

- packages/select/src/select.vue
- test/unit/specs/select.spec.js
> Select: remove unnecessary remote query when focused

- packages/rate/src/main.vue
> Rate: make icon classes responsive

- packages/button/src/button.vue
- test/unit/specs/button.spec.js
fix https://github.com/ElemeFE/element/issues/10018
simplifies internal implementation
> button: loading implies disabled

- packages/table/src/table.vue
> Table: shouldUpdateHeight should be true when maxHeight is set

- examples/docs/en-US/popover.md
- examples/docs/es/popover.md
- examples/docs/zh-CN/popover.md
- packages/pagination/src/pagination.js
- packages/popover/src/main.vue
> Popover: add after transition events

- packages/theme-chalk/src/input.scss
> Input: update line-height

- packages/menu/src/submenu.vue
> Menu: update SubMenu to allow custom component

- packages/form/src/form-item.vue
- packages/select/src/select.vue
> Select: trigger validation after resetField

- packages/theme-chalk/src/date-picker/picker.scss
> DatePicker: fix style for ranged picker after #10064

- packages/select/src/select.vue
> Select: remove scrollToOption after selection

- packages/table/src/table.vue
> fix fixed column style on safari

- packages/theme-chalk/src/reset.scss
> fix text looks unclear

- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/panel/date.vue
> fix: Fix unexpected blur for time picker

- examples/docs/en-US/slider.md
- examples/docs/es/slider.md
- examples/docs/zh-CN/slider.md
- packages/slider/src/main.vue
- packages/theme-chalk/src/slider.scss
- types/slider.d.ts
> Slider: add input-size

- packages/pagination/src/pagination.js
> Pagination: update pager value when page size changes

- examples/pages/template/resource.tpl
> update resource links

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
> Changelog: update for 2.2.2

- packages/table/package.json
- packages/theme-chalk/src/common/var.scss
- packages/theme-chalk/src/table.scss
> Table: added scss variable $--table-border-color

- packages/form/src/form-item.vue
> Form: make filter conditions for getFilteredRule clearer

- packages/tabs/src/tab-nav.vue
> Tabs: fix exception in scrollToActiveTab

- packages/theme-chalk/src/form.scss
> Form: fix label alignment with input-group

- examples/docs/en-US/menu.md
- examples/docs/en-US/table.md
- examples/docs/es/menu.md
- examples/docs/es/table.md
- examples/docs/zh-CN/table.md
- test/unit/specs/table.spec.js
- types/table.d.ts
> Table: add test for selectOnIndeterminate

- types/autocomplete.d.ts
- types/date-picker.d.ts
- types/input-number.d.ts
- types/input.d.ts
- types/select.d.ts
- types/time-picker.d.ts
- types/time-select.d.ts
> Chore: declare focus method in form component types

- packages/form/src/form-item.vue
> Form: rule key supports both dot-separated and nested

- types/menu.d.ts
- types/table.d.ts
- types/transfer.d.ts
- types/tree.d.ts
- types/upload.d.ts
In this pull request, I completed the declaration of the methods specified in the documentation. Please help to review the changes, thank you.
> Chore: complete the method declarations in the documentation

- packages/table/src/table.vue
> Table: update column width before updating height

- examples/docs/en-US/color-picker.md
- examples/docs/es/color-picker.md
- examples/docs/zh-CN/color-picker.md
- packages/color-picker/src/components/predefine.vue
- packages/theme-chalk/src/color-picker.scss
> ColorPicker: update docs for predefine

- packages/loading/src/directive.js
- packages/theme-chalk/src/table.scss
> Table: transparent border when loading

- packages/popover/src/directive.js
> Popover: fix error when reference comes before popover

- packages/button/src/button.vue
> Button: inherit disabled from wrapping Form

- packages/upload/src/index.vue
- packages/upload/src/upload-dragger.vue
> Upload: filter accepted file types in dragger

- examples/docs/en-US/form.md
- examples/docs/es/form.md
- examples/docs/zh-CN/form.md
- packages/form/src/form-item.vue
- packages/form/src/form.vue
- test/unit/specs/form.spec.js
- types/form.d.ts
> Form: add invalidFields as a second param of validation callback

- packages/table/src/table.vue
> Table: fix wrapper width of fixed table

- src/utils/menu/aria-menuitem.js
> Menu: fix arrow navigation of SubMenu

- examples/docs/en-US/menu.md
- examples/docs/zh-CN/menu.md
which should be indexes of the sub-menu
> Menu: fix default-openeds description

- packages/input/src/input.vue
> Input: disabled Input should not show clear icon

- packages/theme-chalk/src/col.scss
> Layout: iteration starts from 0

- examples/docs/en-US/form.md
- examples/docs/es/form.md
- examples/docs/zh-CN/form.md
- packages/form/src/form-item.vue
- test/unit/specs/form.spec.js
> Form: add validate event

- examples/docs/en-US/progress.md
- examples/docs/es/progress.md
- examples/docs/zh-CN/progress.md
- types/progress.d.ts
> Progress: update docs for color prop

- packages/date-picker/src/picker.vue
> fix: Do not generate id if empty

- packages/message-box/src/main.vue
MessageBox: should allow showInput when message is empty
> MessageBox: allow showInput when message is empty

- packages/theme-chalk/src/date-picker/time-spinner.scss
> TimePicker: remove unnecessary margin-left

- packages/table/src/filter-panel.vue
> Table: filter-panel should hide when new one shows

- examples/docs/en-US/button.md
- examples/docs/es/button.md
- examples/docs/zh-CN/button.md
- packages/button/src/button.vue
- packages/theme-chalk/src/button.scss
- test/unit/specs/button.spec.js
Resolves #9006
[Button](http://element-cn.eleme.io/#/zh-CN/component/button)
Button 增加 `circle` 属性，与 `round` 属性相区别。`round` 为圆角，`circle` 为纯圆形，适合一些图标按钮。
```
<el-button icon="el-icon-search" circle></el-button>
```
测试用例顺便补充上了 `round` 测试用例。
---
> Button: add circle attribute

- examples/docs/en-US/button.md
- examples/docs/es/button.md
- examples/docs/zh-CN/button.md
- packages/theme-chalk/src/time-picker.scss
> TimePicker: fix missing dependency style files

- packages/input/src/input.vue
> Input: bind native attrs to input and textarea element

- packages/table/src/table-header.js
> Table: fix filter panel reference element to the trigger span

- packages/input/src/input.vue
> Input: add inheritAttrs

- packages/dropdown/src/dropdown-menu.vue
> Dropdown: fix arrow offset

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
- build/bin/version.js
- build/deploy-ci.sh
- build/deploy-faas.sh
> Changelog: update for 2.3.0

- packages/autocomplete/src/autocomplete.vue
> Autocomplete: 为el-autocomplete-suggestions添加popperOptions属性

- packages/autocomplete/src/autocomplete.vue
> Autocomplete: fix popper options

- examples/docs/en-US/card.md
- examples/docs/es/card.md
- examples/docs/zh-CN/card.md
- types/card.d.ts
> Card: update docs for shadow attribute

- CHANGELOG.es.md
- examples/docs/es/select.md
> Changelog: update for 2.3.2

- packages/badge/src/main.vue
> Badge: fix hidden value of zero

- packages/tree/src/tree.vue
> Tree: fix drag event error

- examples/docs/en-US/input.md
- examples/docs/es/input.md
- examples/docs/zh-CN/input.md
- packages/autocomplete/src/autocomplete.vue
- types/autocomplete.d.ts
> Autocomplete: add placement attribute

- src/locale/lang/pl.js
* [x ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x ] Add some descriptions and refer relative issues for you PR.
> filled gaps in translation

- packages/tree/src/tree.vue
> Tree: address some draggable issues

- examples/docs/en-US/datetime-picker.md
- packages/date-picker/src/panel/date-range.vue
- packages/date-picker/src/panel/date.vue
- packages/date-picker/src/util/index.js
- test/unit/specs/date-picker.spec.js
PR for issue: https://github.com/ElemeFE/element/issues/10078
> DateTimePicker: Enable default-time attribute in date picker

- packages/tabs/src/tab-nav.vue
> Tabs: remove box shadow when browser hidden / blur

- packages/input/src/input.vue
- packages/select/src/select.vue
> Input / Select: shouldn't fire input event during composition

- examples/docs/es/popover.md
> Fixed a strange visual error in spanish popover.md

- examples/docs/en-US/upload.md
- examples/docs/es/upload.md
- examples/docs/zh-CN/upload.md
> Docs: update Upload docs

- examples/docs/en-US/breadcrumb.md
- examples/docs/es/breadcrumb.md
- examples/docs/zh-CN/breadcrumb.md
- packages/breadcrumb/src/breadcrumb-item.vue
- packages/theme-chalk/src/breadcrumb.scss
> Breadcrumb: remove visual feedback for non-link items

- packages/input-number/src/input-number.vue
> InputNumber: change event should fire after input event

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
> Changelog: update for 2.3.3

- examples/components/footer.vue
- examples/docs/en-US/input.md
- examples/docs/en-US/table.md
- examples/docs/en-US/transfer.md
- examples/docs/en-US/tree.md
- examples/docs/es/input.md
- examples/docs/es/table.md
- examples/docs/es/transfer.md
- examples/docs/es/tree.md
- examples/docs/zh-CN/input.md
- examples/docs/zh-CN/table.md
- examples/docs/zh-CN/transfer.md
- examples/docs/zh-CN/tree.md
- packages/transfer/src/transfer-panel.vue
> Transfer: support scoped slot for data items

- packages/theme-chalk/src/radio-button.scss
> Radio: remove native input's offset of radio button

- packages/pagination/src/pagination.js
- test/unit/specs/date-picker.spec.js
> Pagination: ensure currentPage is updated in current-change handler

- packages/table/src/table-layout.js
> Table: update resizeState when updateColumnsWidth(#10265)

- packages/pagination/src/pagination.js
- packages/theme-chalk/src/pagination.scss
> Pagination: disabled prev and next buttons should not trigger click

- packages/input/src/input.vue
> Textarea: fix undefined in ssr when v-model not set

- packages/theme-chalk/src/select.scss
> Select: fix tags style in IE10

- packages/tabs/src/tab-nav.vue
- packages/theme-chalk/src/tabs.scss
> Tabs: fix text color for disabled border-card

- examples/docs/en-US/table.md
- examples/docs/es/table.md
- examples/docs/zh-CN/table.md
- packages/table/src/table-column.js
> Table: add $index as formatter's param

- types/element-ui.d.ts
> Types: add missing CheckboxButton export

- packages/rate/src/main.vue
> Rate: rename method name

- CHANGELOG.es.md
> Changelog: update for 2.3.4

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
> Changelog: fix a 2.3.4 typo

- packages/date-picker/src/basic/date-table.vue
- packages/date-picker/src/util/index.js
- test/unit/specs/date-picker.spec.js
Fixes #10704
Should check year and weekNumber to determine highlight. 😂
> date-picker: fix week selection range highlight

- packages/input/src/input.vue
> Input: fix when value is zero

- packages/rate/src/main.vue
> '修复rate评分组件，当disabled状态时，按左右方向键还能改变评分的bug'

- examples/docs/en-US/select.md
- examples/docs/es/select.md
- examples/docs/zh-CN/select.md
- packages/select/src/select.vue
- packages/theme-chalk/src/select.scss
> Select: update docs for automatic-dropdown

- src/locale/lang/de.js
Hi: pagination.pagesize should have a whitespace on German, or it will be incorrectly.
> German Locale: update pagination.pagesize

- examples/docs/en-US/pagination.md
- examples/docs/es/pagination.md
- examples/docs/zh-CN/pagination.md
- packages/pagination/src/pagination.js
- types/pagination.d.ts
> Pagination: update docs for pager-count

- examples/docs/en-US/form.md
- examples/docs/es/form.md
- examples/docs/zh-CN/form.md
> Form: fix a typo in docs

- examples/docs/en-US/tree.md
- examples/docs/es/tree.md
- examples/docs/zh-CN/tree.md
- packages/tree/src/tree.vue
- types/tree.d.ts
> Tree: add type as allow-drop's 3rd param

- packages/select/src/select.vue
> Select: focus input in setSoftFocus when available

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
> Changelog: update for 2.3.5

- packages/breadcrumb/src/breadcrumb-item.vue
> breadcrumb-item: 代码优化

- packages/tree/src/tree.vue
> Tree: fix allowDrop's type behavior

- packages/select/src/option.vue
- packages/select/src/select.vue
- test/unit/specs/select.spec.js
> Select: remove blur emit after soft focus

- examples/docs/en-US/quickstart.md
- examples/docs/es/quickstart.md
- examples/docs/zh-CN/quickstart.md
> Chore: update Nuxt example link

- CHANGELOG.es.md
> Changelog: update for 2.3.6

- packages/table/src/table.vue
> Table: update columns width after filter

- examples/docs/es/radio.md
> Spanish Documentation. A display error. I'm not sure I did it right. 

- packages/switch/src/component.vue
> Switch: support native attrs on input element

- .travis.yml
> Chore: use lts node version in travis

- packages/switch/src/component.vue
- packages/theme-chalk/src/switch.scss
transform x value not flexiable, tight coupling with the `width` prop
> switch transformx value not flexiable

- examples/docs/en-US/popover.md
- examples/docs/en-US/table.md
- examples/docs/es/popover.md
- examples/docs/es/table.md
- examples/docs/zh-CN/popover.md
- examples/docs/zh-CN/table.md
> Docs: update popover and table

- examples/docs/zh-CN/input.md
Other input types are also valid.
> Input: update type attribute's doc

- examples/assets/images/duotai.svg
- examples/components/side-nav.vue
- examples/docs/en-US/input.md
- examples/docs/es/input.md
- examples/docs/zh-CN/input.md
- examples/pages/template/index.tpl
> Chore: update duotai sponsorship

- packages/color-picker/src/main.vue
only emit active-change event source from dropdown, ignore from setting props
Closes #10901
> ColorPicker: fixed emit active-change event bug, fixed #10901 

- README.md
- packages/color-picker/src/main.vue
- packages/select/src/select.vue
> Select: input should be readonly when options menu not visible

- packages/input-number/src/input-number.vue
> InputNumber: fix accessing missing $refs in updated hook

- packages/pagination/src/pagination.js
- test/unit/specs/pagination.spec.js
> Pagination: emit current-change after current page is manually updated

- build/deploy-ci.sh
- build/deploy-faas.sh
- src/utils/scroll-into-view.js
> Utils: scroll-into-view should consider target element's offset parents

- examples/docs/en-US/select.md
- examples/docs/es/select.md
- examples/docs/zh-CN/select.md
- packages/select/src/select.vue
- test/unit/specs/select.spec.js
> Select: add prefix named slot

- examples/app.vue
> Chore: fix suggestJump should not take effect in dev mode

- packages/tree/src/tree-node.vue
- test/unit/specs/menu.spec.js
> Tree: drag events should return if not draggable

- packages/theme-chalk/src/dialog.scss
> Dialog: remove unnecessary body line-height

- packages/input/src/input.vue
> Input: fix clear icon overlapping

- packages/message-box/src/main.vue
- packages/table/src/table-layout.js
> Table: fix an undefined issue in ssr

- examples/docs/en-US/tree.md
- examples/docs/es/tree.md
- examples/docs/zh-CN/tree.md
- packages/tree/src/tree-node.vue
- packages/tree/src/tree.vue
- test/unit/specs/tree.spec.js
- types/tree.d.ts
> Tree: add checkOnClickNode

- packages/table/src/table-body.js
> Table: use Range to determine text overflow

- build/bin/iconInit.js
> fix TypeError for IconInit.js writeFile call

- packages/table/src/table-body.js
> Table: optimize tooltip logic

- packages/message-box/src/main.vue
- packages/theme-chalk/src/common/popup.scss
- src/utils/popup/index.js
- src/utils/vue-popper.js
- test/unit/specs/mixin.vue-popup.spec.js
Fixes #11086
Remove redundant code in popup, MessageBox and vue-popper
> popup: fix bug and remove redundant code

- CHANGELOG.es.md
- examples/docs/es/form.md
- examples/docs/es/quickstart.md
- examples/docs/es/select.md
- examples/docs/es/tree.md
> Changelog: spanish update for 2.3.8

- packages/autocomplete/src/autocomplete-suggestions.vue
> Autocomplete: avoid popper creation in updated hook

- packages/progress/src/progress.vue
- test/unit/specs/progress.spec.js
> Progress: fix missing icon when status is exception

- packages/message-box/src/main.vue
>  MessageBox: try to add a hashchange event listener in Vue.nextTick

- examples/docs/en-US/tree.md
- examples/docs/es/tree.md
- examples/docs/zh-CN/tree.md
- packages/tree/src/model/tree-store.js
- test/unit/specs/tree.spec.js
> Tree: setCurrentKey cancels highlight when param is null

- packages/table/src/table-body.js
> Table: showOverflowTooltip compatibility with IE11

- CHANGELOG.es.md
- examples/docs/es/card.md
- examples/docs/es/message-box.md
- examples/docs/es/transfer.md
- examples/docs/es/tree.md
> Update spanish documentation

- examples/docs/en-US/input.md
- examples/docs/es/input.md
- examples/docs/zh-CN/input.md
- packages/autocomplete/src/autocomplete-suggestions.vue
- packages/autocomplete/src/autocomplete.vue
- types/autocomplete.d.ts
> Autocomplete: add hide-loading

- packages/popover/src/main.vue
> Popover: execute focus on instance only if it is a function

- examples/docs/en-US/dialog.md
- examples/docs/es/dialog.md
- examples/docs/zh-CN/dialog.md
> Dialog: add tips on lazy render

- build/bin/build-entry.js
- examples/docs/en-US/quickstart.md
- examples/docs/es/quickstart.md
- examples/docs/zh-CN/quickstart.md
- src/index.js
- src/utils/popup/popup-manager.js
> popup: allow user to set initial z-index for modal boxes (#8695)

- examples/docs/en-US/tabs.md
- examples/docs/es/tabs.md
- examples/docs/zh-CN/tabs.md
- packages/tabs/src/tabs.vue
- test/unit/specs/tabs.spec.js
- types/tabs.d.ts
> Tabs: add before-leave hook

- src/locale/lang/ja.js
> i18n: improve Japanese translation

- packages/checkbox/src/checkbox.vue
- test/unit/specs/form.spec.js
> Checkbox: support validation for single checkbox. Closes #5787

- packages/breadcrumb/src/breadcrumb-item.vue
> Breadcrumb: fix regression of dynamic `to` support

- packages/radio/src/radio-button.vue
- packages/radio/src/radio.vue
> Radio: prevent changing value when radio is disabled. resolves #11296

- packages/color-picker/src/main.vue
> ColorPicker: prevent active-change event when picker is closed

- packages/table/src/filter-panel.vue
- packages/theme-chalk/src/table-column.scss
> Table: fix oversized filter list. Resolves #11314

- packages/autocomplete/src/autocomplete.vue
> Autocomplete: fix suggestions data bug (#8665)

- packages/theme-chalk/src/checkbox.scss
- packages/theme-chalk/src/radio.scss
> Radio & Checkbox: replace ease-in with cubic-bezier

- packages/theme-chalk/src/tooltip.scss
> Tooltip: add min-width

- packages/table/src/table-store.js
- test/unit/specs/table.spec.js
> Table: retain currently selected row when sorting the table.

- src/utils/popup/index.js
- test/unit/specs/mixin.vue-popup.spec.js
> MessageBox: remove body's hidden class when using MessageBox twice (#11341)

- packages/tree/src/model/util.js
> Tree: fix markNodeData error when data is falsy

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
- build/bin/version.js
- build/deploy-ci.sh
- build/deploy-faas.sh
- examples/components/footer.vue
> Changelog: update for 2.4.0

- build/deploy-ci.sh
> Chore: fix deploy-ci.sh

- packages/tabs/src/tabs.vue
> Tabs: remove focus state when before-leave return a resolved promise

- types/autocomplete.d.ts
> Autocomplete: remove duplicate prop in types

- packages/tree/src/model/tree-store.js
> Tree: when tree nodes filtered, don't expand node in lazy mode (#9799)

- packages/popover/src/main.vue
- src/utils/vue-popper.js
> Popover: when Popover is disabled, don't emit event and don't create … (#11396)

- packages/theme-chalk/src/select.scss
> Select: fix arrow align in FireFox

- test/unit/specs/menu.spec.js
- test/unit/specs/radio.spec.js
- test/unit/specs/slider.spec.js
- test/unit/specs/switch.spec.js
> improve the test coverage

- packages/select/src/select.vue
> Select: hide clear icon when value is null

- packages/theme-chalk/src/radio.scss
> Radio: remove box-shadow when disabled

- packages/tabs/src/tab-pane.vue
- packages/tabs/src/tabs.vue
- test/unit/specs/tabs.spec.js
> Tabs: fix lazy loading

- packages/tree/src/model/node.js
fix bug in issue 10684 : https://github.com/ElemeFE/element/issues/10684
> Tree : mark node data in lazy mode

- packages/table/src/table-body.js
> Table: retain currently selected row when expanding row.

- examples/docs/en-US/tabs.md
- examples/docs/es/tabs.md
- examples/docs/zh-CN/tabs.md
- packages/tabs/src/tab-nav.vue
- packages/tabs/src/tabs.vue
- packages/theme-chalk/src/tabs.scss
- test/unit/specs/tabs.spec.js
- types/tabs.d.ts
> Tabs: add stretch attribute

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
> Changelog: update for 2.4.1

- yarn.lock
> Chore: update yarn.lock

- packages/tabs/src/tab-nav.vue
- packages/theme-chalk/src/tabs.scss
> Tabs: fix tabs style

- test/unit/specs/container.spec.js
- test/unit/specs/radio.spec.js
- test/unit/specs/tabs.spec.js
> improve the test coverage 

- packages/table/src/table-body.js
> Table: fix highlightCurrentRow regression

- src/locale/lang/sk.js
No code change, pure translation PR.
> updates Slovak translation

- packages/theme-chalk/src/button.scss
> Button: fix style of single round/circle button in a group

- README.md
- examples/app.vue
> Chore: update sponsor, optimize suggestJump

- packages/pagination/src/pagination.js
- packages/theme-chalk/src/pagination.scss
> Pagination: add size to nested select

- packages/table/src/table-column.js
> Table: fix class-name & label-class-name  prop is not reactive issue

- packages/cascader/src/main.vue
- packages/cascader/src/menu.vue
- test/unit/specs/cascader.spec.js
> Cascader: close when option clicked

- examples/docs/zh-CN/tree.md
- packages/tree/src/tree.vue
> Tree: optimize not-allowed dropping cursor

- packages/pagination/src/pagination.js
currentValue in input component's data object didn't refresh when changeHandle emited
> Pagination:  input bug

- packages/autocomplete/src/autocomplete.vue
> Autocomplete: passes id to nested native input

- packages/menu/src/submenu.vue
> Menu: fix open method error when collapse is changed

- build/bin/new.js
> Chore: add missing file when create new component

- README.md
- examples/components/footer.vue
- examples/nav.config.json
> fix link of element react

- packages/date-picker/src/picker.vue
https://github.com/ElemeFE/element/issues/11621
> date-picker: guards common but incorrect usage

- types/loading.d.ts
> Loading: add missing definition of directive

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
> Changelog: update for 2.4.2

- packages/cascader/src/main.vue
> Cascader: hide label when user inputs

- packages/input-number/src/input-number.vue
> InputNumber: remove undocumented slots

- packages/tree/src/tree.vue
> Tree: fixed tree node dragged to wrong position

- src/locale/lang/lv.js
> [Locale] lv.js - translations updated;

- package.json
> Chore: use rimraf when deploying

- packages/form/src/form-item.vue
- packages/select/src/select.vue
> Select: revert #10105

- CHANGELOG.es.md
- examples/docs/es/form.md
- examples/docs/es/message-box.md
> update spanish Doc 2.4.3

- types/message-box.d.ts
> MessageBox: add missing declaration

- packages/table/src/table-column.js
- packages/table/src/table-header.js
> Table: disable filter when filters is an empty array

- packages/table/src/table-store.js
> Table: changing current-row-key when current-row-key is assigned to null

- packages/theme-chalk/src/button.scss
> button scss className  optimize

- packages/radio/src/radio-button.vue
- packages/radio/src/radio.vue
> Radio: stop event propagation on radio label

- packages/theme-chalk/src/collapse.scss
- packages/theme-chalk/src/menu.scss
- packages/theme-chalk/src/tree.scss
> Chore: add missing style

- src/locale/lang/it.js
Fix - [Bug Report] Localization #11961
> Fix - [Bug Report] Localization #11961

- packages/input/src/input.vue
> Input: add missing readonly prop

- packages/spinner/src/spinner.vue
Most components use the directive shorthands.
https://github.com/ElemeFE/element/search?q=v-bind&unscoped_q=v-bind
> Spinner: v-bind:style -> :style

- packages/form/src/form-item.vue
Most components use the directive shorthands.
https://github.com/ElemeFE/element/search?q=v-bind&unscoped_q=v-bind
> FormItem: v-bind:style -> :style

- packages/tree/src/tree.vue
> Tree: fix keydown event in Tree

- packages/table/src/table-body.js
- packages/table/src/table-column.js
> Table: support class-name when type=expand

- types/message-box.d.ts
> MessageBox: fix type definition

- examples/docs/en-US/cascader.md
- examples/docs/es/cascader.md
> Doc: update Cascader doc

- build/bin/new.js
> Chore: add es doc for new component

- examples/docs/en-US/table.md
- examples/docs/es/table.md
- examples/docs/zh-CN/table.md
- packages/table/src/table.vue
- test/unit/specs/table.spec.js
- types/table.d.ts
> Table: add toggleAllSelection method

- types/message-box.d.ts
> MessageBox: add missing type

- packages/tree/src/model/node.js
> Tree: not check node in lazy mode

- packages/theme-chalk/src/option.scss
Closes https://github.com/ElementUI/theme-chalk/issues/19
移除多余的样式
> Select: remove redundant style

- packages/input/src/input.vue
- test/unit/specs/input.spec.js
fix wrong style of Input suffix when ElInput contains ElSelect https://jsfiddle.net/zhiyang/xyu2jbv7/
> Input: fix wrong style of Input suffix

- build/bin/build-entry.js
- src/index.js
> Chore: optimize entry script

- packages/dialog/src/component.vue
- test/unit/specs/dialog.spec.js
> Dialog: ignore width when fullscreen is true

- examples/docs/en-US/installation.md
- examples/docs/en-US/quickstart.md
- examples/docs/es/installation.md
- examples/docs/es/quickstart.md
- examples/docs/zh-CN/installation.md
- examples/docs/zh-CN/quickstart.md
> Docs: improve quickstart doc

- packages/table/src/table-header.js
> Table: fix async filters

- packages/select/src/select.vue
> Select: debounce query

- packages/theme-chalk/src/main.scss
> Main: fix IE compatibility issues

- packages/theme-chalk/src/common/var.scss
- packages/theme-chalk/src/menu.scss
> Menu: make font-size constant into variable

- packages/cascader/src/main.vue
- packages/select/src/option.vue
- src/utils/util.js
Bug fixed: https://jsfiddle.net/h1f4a9nq/
> Cascader: escape special characters for regexp

- packages/slider/src/button.vue
> Slider: avoid NaN when min and max values ​​are equal

- packages/theme-chalk/src/radio-button.scss
> Radio: fix focus style

- examples/docs/en-US/tree.md
- examples/docs/es/tree.md
- examples/docs/zh-CN/tree.md
- packages/tree/src/model/tree-store.js
- packages/tree/src/tree.vue
>  Tree: register node after dragging

- packages/popover/src/main.vue
> Popover: show popper when InputNumber focused

- packages/select/src/option.vue
> Select: not clear text when filtering

- src/utils/util.js
> Select & Cascader: add default value for query string

- packages/tree/src/model/node.js
> Tree: fix adding node bug in lazy mode

- CHANGELOG.es.md
- examples/docs/es/input.md
> ES doc Changelog: update for 2.4.6

- packages/cascader/src/main.vue
- packages/theme-chalk/src/cascader.scss
> Cascader: highlight input when menu clicked

- examples/docs/en-US/form.md
- examples/docs/es/form.md
- examples/docs/zh-CN/form.md
- packages/form/src/form-item.vue
- packages/form/src/form.vue
- test/unit/specs/form.spec.js
- types/form-item.d.ts
- types/form.d.ts
> Form: add `error` attribute

- packages/theme-chalk/src/menu.scss
http://element-cn.eleme.io/#/en-US/component/menu#top-bar
> Menu: fix submenu style

- examples/docs/en-US/message-box.md
- examples/docs/es/message-box.md
> MessageBox: update doc

- packages/date-picker/src/picker.vue
https://github.com/ElemeFE/element/issues/12520
> Date Picker: turn off autocomplete for date picker range

- packages/pagination/src/pagination.js
> Pagination: assign 1 to default page count

- packages/pagination/src/pagination.js
> Pagination: fix emit order of page size

- packages/cascader/src/menu.vue
> fix：在收起cascaderMenu的时候，不再响应

- packages/table/src/table-column.js
- packages/table/src/table-header.js
> Table: fix table filter

- README.md
> Chore: update donation qrcode

- src/locale/lang/vi.js
> Locale: translation of the remaining items of Vietnamese language 

- examples/docs/en-US/quickstart.md
Current link is https://element.eleme.io/nuxtjs.org instead of https://nuxtjs.org/.
> Fix invalid link

- packages/upload/src/index.vue
ref [pull/12536](https://github.com/ElemeFE/element/pull/12356)
> Upload: create blob URL when picture displays

- packages/tree/src/model/node.js
- Closes #12674 #12664 #12647 #12421
> Tree: fix tree node not deleted

- examples/docs/es/quickstart.md
- examples/docs/zh-CN/quickstart.md
Add 'Vue.use(Transfer)' in `quickstart.md`.
> Quickstart: add 'Vue.use(Transfer)'

- packages/select/src/select.vue
> Select: use initial height to reset height of input

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
> Changelog: update for 2.4.7

- CHANGELOG.es.md
- examples/docs/es/form.md
- examples/docs/es/input.md
>  Update Spanish Doc

- packages/theme-chalk/src/switch.scss
> Switch: not display outline when focused

- packages/tree/src/tree.vue
- Closes #12792
- Closes #12112
> Tree: show indicator in drop node

- test/unit/specs/form.spec.js
> test: update test case for form

- packages/date-picker/src/panel/date-range.vue
update comments to reflect current code
> chore: update date-picker comment notes

- packages/table/src/table-column.js
- packages/table/src/table-header.js
- Closes #12848
- Closes #6159
> Table: called render header in index column

- CHANGELOG.es.md
- examples/docs/es/dialog.md
- examples/docs/es/form.md
- examples/docs/es/upload.md
> Changelog for 2.4.8 Spanish update

- src/locale/lang/hu.js
> Fix hungarian locale

- examples/docs/en-US/badge.md
- examples/docs/es/badge.md
- examples/docs/zh-CN/badge.md
- packages/badge/src/main.vue
- packages/theme-chalk/src/badge.scss
> badge: add type attribute

- src/locale/lang/ug-CN.js
> 年前面加上“-”， 在维语中年前面要写“-”表示第几年

- packages/select/src/select.vue
- test/unit/specs/select.spec.js
> select: refactoring icon reverse

- packages/date-picker/src/basic/time-spinner.vue
- packages/date-picker/src/util/index.js
- test/unit/specs/time-picker.spec.js
> TimePicker: selectable range will affect to column minutes in spinner

- packages/tabs/src/tabs.vue
- Closes #13027
- Closes #13041
> Tabs: fixed last TabNav unable  to be deleted

- examples/docs/en-US/select.md
- examples/docs/es/select.md
- examples/docs/zh-CN/select.md
- packages/select/src/select.vue
- close #6399
`npm run test` 不通过，大概是我使用的方法不对？不过看起来并不是我的问题。人肉测试没有发现问题。
> [Select] make clearable work for multi select (#6399)

- packages/form/src/form.vue
- packages/upload/src/upload-list.vue
> Upload: use uid as upload-list key

- src/locale/lang/sl.js
Date-picker: set year to '', add missing translations.
Pagination: translate /page
> Add missing translations

- examples/docs/en-US/menu.md
- examples/docs/es/menu.md
- examples/docs/zh-CN/menu.md
> NavMenu: fix typo

- packages/select/src/select.vue
Select 的 v-show 为 false 时，size 属性不生效。https://jsfiddle.net/mmx38qxw/6585/
> Select: fix size attribute not working

- packages/tag/src/tag.vue
> Tag: optimize code

- packages/dialog/src/component.vue
role dialog was missing on component dialog.
> [dialog] add role dialog

- examples/docs/en-US/alert.md
- examples/docs/es/alert.md
- examples/docs/zh-CN/alert.md
- packages/alert/src/main.vue
- test/unit/specs/alert.spec.js
> Alert: add support for title slot

- examples/docs/zh-CN/table.md
- packages/table/src/table-column.js
update doc https://github.com/ElemeFE/element/pull/13012
> Table: update Chinese doc

- packages/tabs/src/tab-nav.vue
- Closes #13146
- related pr https://github.com/ElemeFE/element/pull/12846
> Tabs: set TabNav key

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
> changelog for 2.4.9

- packages/input/src/input.vue
> Input: not display clear icon in disabled form

- packages/theme-chalk/src/button.scss
> Button: fix disabled button style bug

- packages/theme-chalk/src/progress.scss
> Progress: add transition support

- packages/radio/src/radio-button.vue
- packages/radio/src/radio.vue
> chore: optimize code

- src/locale/lang/fi.js
> Add missing Finnish translations

- src/locale/lang/es.js
> Add missing Spanish translation

- packages/select/src/select.vue
提高健壮性的同时支持动态表单空值写入表单对象，2.4.8是OK的。
> Fix select multiple null value, replace #13227

- CHANGELOG.es.md
- examples/docs/es/table.md
> Spanish Doc Update 2.4.9

- examples/docs/en-US/i18n.md
- examples/docs/es/i18n.md
- examples/docs/zh-CN/i18n.md
- src/locale/lang/eu.js
> Add Basque translation

- examples/docs/en-US/carousel.md
- examples/docs/es/carousel.md
- examples/docs/zh-CN/carousel.md
- packages/carousel/src/item.vue
- packages/carousel/src/main.vue
> Carousel: add prop `loop` which can control whether display in loop (#12869)

- packages/theme-chalk/src/tooltip.scss
> Tooltip: fix word wrap for long words

- packages/select/src/select.vue
> Select: fix repeat clicking to display dropdown menu

- examples/docs/en-US/input-number.md
- examples/docs/es/input-number.md
- examples/docs/zh-CN/input-number.md
- packages/input-number/src/input-number.vue
> InputNumber:(feat) add placeholder attributes

- packages/collapse/src/collapse-item.vue
- packages/theme-chalk/src/collapse.scss
> Collapse: slot header use display flex instead of float(#13277)

- packages/autocomplete/src/autocomplete.vue
> AutoComplete: add clear event(#13317)

- packages/menu/src/submenu.vue
> Menu:(fix) clickoutside hide submenu

- examples/docs/en-US/tree.md
- examples/docs/es/tree.md
- examples/docs/zh-CN/tree.md
- packages/tree/src/model/node.js
- packages/tree/src/tree-node.vue
- packages/tree/src/tree.vue
- types/tree.d.ts
> Tree: add iconClass attribute

- examples/docs/en-US/alert.md
- examples/docs/es/alert.md
- examples/docs/zh-CN/alert.md
- packages/alert/src/main.vue
> Alter: title is not a required prop

- packages/table/src/table-header.js
> Table: stop event propagation for checkbox

- packages/cascader/src/main.vue
> Cascader: set separator when filtering

- packages/transfer/src/main.vue
> Transfer: fix bug sometimes component crash when target order is push(#13320)

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
> Changelog for 2.4.10

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
> fixed changelog typo

- packages/menu/src/submenu.vue
> Menu: revert #13296

- packages/theme-chalk/src/common/var.scss
> [Col] fix the bug about responsive size caused by 'xs' variable.

- CHANGELOG.es.md
> Update Spanish doc 2.4.11

- examples/docs/en-US/tree.md
- examples/docs/es/tree.md
- examples/docs/zh-CN/tree.md
- types/tree.d.ts
> Tree: update doc and definition file

- packages/date-picker/src/basic/time-spinner.vue
- packages/date-picker/src/panel/time-select.vue
append `key` prop to `v-for` loop
> [date-picker] add key prop to 'v-for'

- packages/cascader/src/menu.vue
- packages/theme-chalk/src/cascader.scss
- 文字过长时，避免 icon 图标遮住文字 https://jsfiddle.net/caxh926y/2/
> Cascader: update cascader style

- packages/theme-chalk/src/autocomplete.scss
> Autocomplete: update autocomplete style

- examples/docs/en-US/table.md
- examples/docs/es/table.md
- examples/docs/zh-CN/table.md
> Table: fix docs type

- packages/tabs/src/tab-nav.vue
> Tabs: fix auto scroll bug

- packages/tabs/src/tab-bar.vue
> Get the correct tab through tab name

- examples/pages/template/component.tpl
> Website fix: fix error anchor link

- packages/cascader/src/menu.vue
This removes deprecated computed cache: false property
> Cascader : remove deprecated computed cache: false property

- packages/tabs/src/tab-bar.vue
> [Tabs] bugfix use paneName instead of name

- examples/pages/template/resource.tpl
> Chore: add Axure component

- packages/theme-chalk/src/autocomplete.scss
fix pr #13266 bug in issues #13129
> Autocomplete: update style

- packages/slider/src/main.vue
> chore: fix slider indent

- README.md
> chore: add group qr code to readme

- README.md
> chore: update readme qr code src

- packages/date-picker/src/basic/date-table.vue
relates to https://github.com/ElemeFE/element/issues/13832
> [DatePicker]: fix wrong-active line

- examples/index.tpl
- package.json
- packages/form/src/form.vue
> chore: use shadow CDN and fix typo

- packages/theme-chalk/src/checkbox.scss
The style is not elegant enough now.
When the checkbox wraps, it cannot be aligned.
Online demo: https://jsfiddle.net/cz1okwvf/
After adjust:
https://jsfiddle.net/cz1okwvf/1/
> Checkbox: refine style

- examples/docs/en-US/date-picker.md
- examples/docs/en-US/datetime-picker.md
* [y] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [y] Make sure you are merging your commits to `dev` branch.
* [y] Add some descriptions and refer relative issues for you PR.
> Document: Fix a document difference

- src/locale/lang/ca.js
> i18n: add missing Catalan translations

- src/locale/lang/fi.js
Fixes to grammar and translations.
> Lang: Fix Finnish translations

- packages/theme-chalk/src/radio.scss
The purpose of this pr is the same as #14127 . 
Before that, I had to override the style manually.
refer: #14127
> Radio: refine style

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
- Build
- upgrade to webpack@4 (#14173) (by @jikkai)
- Autocomplete
- update autocomplete  style (#13597) (by @ziyoung)
- update style (#13762) (by @liuchuzhang)
- Carousel: stop timer before component destroyed (#13820) (by @elfman)
- Cascader
- remove deprecated property (#13737) (by @iamkun)
- correct type definitions of CascaderOption (#13613) (by @NateScarlet)
- update cascader style (#13596) (by @ziyoung)
- Checkbox: refine style (by @PanJiaChen)
- DatePicker
- add key prop to 'v-for' (#13547) (by @Ende93)
- add validate-event attribute (#13531) (by @ziyoung)
- fix week highlight on year boundary (#13883) (by @suyi91)
- Input
- simplify el-input implementation (#13471) (by @wacky6)
- fix textarea ref …
> Doc: add changelog for 2.5.0

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
大佬们看一下重新整理的 changelog 
--
TODO: 
* 合并以后更新 release tag
* 跟进法语翻译
> chore: update 2.5.0 changelog

- build/bin/version.js
- build/deploy-ci.sh
- build/deploy-faas.sh
> docs: keep 2.4.11 docs && new sub folder for 2.5+

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.zh-CN.md
> chore: add 2.5.1 changelog

- CHANGELOG.es.md
> Update ChangeLog ES 2.5.1

- build/webpack.conf.js
> Build: delete unremoved comments in umd module `lib/index.js`

- .babelrc
> Build: fix export error fired in commonjs module used in nuxt.js

- packages/tabs/src/tab-bar.vue
> Tabs: fix error tab bar style

- examples/docs/en-US/table.md
- examples/docs/es/table.md
- examples/docs/zh-CN/table.md
>  修改文档表格自定义表头tableData7为tableData，防止在线运行报错

- README.md
> Docs: Add IssueHunt button

- package.json
- yarn.lock
> chore: retire gh-pages

- .babelrc
> CollapseTransition: Fix bug when build commonjs with babel

- examples/docs/es/datetime-picker.md
- examples/docs/zh-CN/datetime-picker.md
According to english doc here 
https://github.com/ElemeFE/element/blob/dev/examples/docs/en-US/datetime-picker.md
> Docs: (datetime-picker): fix format doc error

- components.json
- examples/docs/en-US/table.md
- examples/docs/en-US/timeline.md
- examples/docs/es/table.md
- examples/docs/es/timeline.md
- examples/docs/zh-CN/table.md
- examples/docs/zh-CN/timeline.md
- examples/nav.config.json
- packages/table/src/table-body.js
- packages/theme-chalk/src/common/var.scss
- packages/theme-chalk/src/index.scss
- packages/theme-chalk/src/timeline-item.scss
- packages/theme-chalk/src/timeline.scss
- packages/timeline-item/index.js
- packages/timeline/index.js
- packages/timeline/src/item.vue
- packages/timeline/src/main.vue
- src/index.js
- test/unit/specs/timeline.spec.js
- types/element-ui.d.ts
- types/timeline-item.d.ts
- types/timeline.d.ts
> Chore: cherry pick two commits from next branch

- examples/docs/en-US/i18n.md
- examples/docs/es/i18n.md
- examples/docs/zh-CN/i18n.md
- src/locale/lang/hy-AM.js
> Created Armenian locale

- examples/docs/en-US/custom-theme.md
- examples/docs/es/custom-theme.md
- examples/docs/zh-CN/custom-theme.md
> Docs: update custom-theme docs

- types/message-box.d.ts
`MessageBoxData` may be a action string
https://github.com/ElemeFE/element/blob/b2f0958089a197907afdbea450a9faec69b48f02/packages/message-box/src/main.js#L57-L62
> MessageBox: Correct type definition

- test/unit/specs/autocomplete.spec.js
add unit test for https://github.com/ElemeFE/element/pull/14269
> test: add autocomplete highlight-first-item

- packages/menu/src/submenu.vue
fix #13913
修复切换页面触发focus事件弹出菜单
> Menu:fix subMenu focus bug

- packages/upload/src/index.vue
> Upload: optimize code (#13786)

- .github/CONTRIBUTING.en-US.md
- .github/CONTRIBUTING.es.md
- .github/CONTRIBUTING.zh-CN.md
- examples/play/index.vue
> Docs: Add more detail about how to run play mode for contribution

- .github/stale.yml
> Chore: install stale for issue handling

- .github/CONTRIBUTING.fr-FR.md
- .github/PULL_REQUEST_TEMPLATE.md
- examples/docs/fr-FR/custom-theme.md
- examples/docs/fr-FR/i18n.md
- examples/docs/fr-FR/icon.md
- examples/docs/fr-FR/input.md
- examples/docs/fr-FR/select.md
- examples/docs/fr-FR/table.md
- examples/docs/fr-FR/timeline.md
- examples/nav.config.json
---
- Update the french translation (fr-FR) according to the latest updates in the english doc, including the new Timeline component.
- Add the CONTRIBUTING.fr-FR.md file.
- Add a link in the PULL_REQUEST_TEMPLATE.md accordingly.
> Update french documentation, contributing guide and github templates

- build/release.sh
- package.json
- yarn.lock
> chore: use cli to select release version

- build/webpack.demo.js
- package.json
- yarn.lock
> build: Minimizing for production

- packages/scrollbar/src/bar.js
> prevent right button click for thumb of scroll-bar

- README.md
---
- Add french links to the website and the contributing guide to the README (sorry, i forgot about that in my previous PR..).
> Add french links to the README

- examples/docs/en-US/input.md
- examples/docs/es/input.md
- examples/docs/fr-FR/input.md
- examples/docs/zh-CN/input.md
> Input: update input password

- examples/docs/en-US/pagination.md
- examples/docs/es/pagination.md
- examples/docs/fr-FR/pagination.md
- examples/docs/zh-CN/pagination.md
> fix document style bug

- packages/theme-chalk/src/dropdown.scss
- packages/theme-chalk/src/tabs.scss
- Closes #14005
- Closes #14069
> Tabs & Dropdown: fix style

- examples/docs/en-US/menu.md
- examples/docs/es/menu.md
- examples/docs/fr-FR/menu.md
- examples/docs/zh-CN/menu.md
- packages/menu/src/menu-item.vue
- packages/menu/src/menu.vue
- types/submenu.d.ts
> Menu: add support for el-menu-item without index

- packages/alert/src/main.vue
> feat(Alert): update alert description default slot class

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
- Timeline
- Add timeline component (by @jikkai in #14248)
- DropdownItem
- Add icon prop to `el-dropdown-item` (by @gabrielboliveira in #14088)
- Input
- Add show-password props (by @phshy0607 in #13966)
- Select
- Add slot `empty` (by @elfman in #13785)
- Autocomplete
- Add highlight-first-item prop (by @YamenSharaf in #14269)
- I18n
- Created Armenian locale (by @hamletbarsamyan in #14214)
- Docs
- French translation (by @smalesys in #12153, #14418, #14434)
- Alert
- Update alert description default slot class (by @iamkun in #14488)
- Input
- Update input password (by @iamkun in #14480)
- InputNumber
- Remove unnecessary parseFloat (by @JuniorTour in #14172)
- Menu
- Add support for `el-menu-item` without …
> Docs: changelog for 2.6.0

- build/bin/version.js
> Chore: change build version

- package.json
Fix https://github.com/ElemeFE/element/pull/14508#issuecomment-468688157
> chore: Fix error node version setting

- build/deploy-faas.sh
> Chore: change doc directory

- CHANGELOG.en-US.md
- CHANGELOG.fr-FR.md
- examples/docs/en-US/form.md
- examples/docs/en-US/time-picker.md
- examples/docs/en-US/upload.md
- examples/docs/fr-FR/form.md
- examples/docs/fr-FR/input.md
- examples/docs/fr-FR/upload.md
---
- Update the french changelog according to latest updates
- Update the french documentation as well
- Fix some spotted typos and issues in both french and english documentation
Tell me if there is anything else.
> Update french doc for 2.6.1 and fix typos

- .eslintrc
- examples/components/theme-configurator/index.vue
- examples/index.tpl
- examples/pages/template/resource.tpl
> chore: update ga tracking

- examples/components/header.vue
> chore: better show theme

- build/bin/gen-indices.js
> chore: add french search index

- examples/docs/en-US/table.md
- examples/docs/es/table.md
- examples/docs/fr-FR/table.md
- examples/docs/zh-CN/table.md
> docs: fix the tableData(2,3,4,5,6) to tableData

- examples/docs/en-US/upload.md
- examples/docs/es/upload.md
- examples/docs/fr-FR/upload.md
- examples/docs/zh-CN/upload.md
修改upload.md文件中 fileList(2,3)为fileList
> docs:fix upload.md the fileList(2,3) to fileList

- build/deploy-ci.sh
> Chore: update ci build script

- packages/date-picker/src/basic/date-table.vue
- test/unit/specs/date-picker.spec.js
> DatePicker: fixes issue #14523

- .github/CONTRIBUTING.fr-FR.md
- examples/docs/fr-FR/border.md
- examples/docs/fr-FR/color.md
- examples/docs/fr-FR/custom-theme.md
- examples/docs/fr-FR/i18n.md
- examples/docs/fr-FR/installation.md
- examples/docs/fr-FR/layout.md
- examples/docs/fr-FR/message-box.md
- examples/docs/fr-FR/quickstart.md
- examples/docs/fr-FR/table.md
- examples/docs/fr-FR/timeline.md
---
* Translate the border.md page into french (fr-FR)
* Update the translation of the color.md page
* Fix some typos
> French translation update

- examples/docs/en-US/form.md
- examples/docs/es/form.md
- examples/docs/fr-FR/form.md
- examples/docs/zh-CN/form.md
> docs: Update Form async validator docs

- examples/components/header.vue
- examples/components/theme-configurator/download.vue
- examples/entry.js
> chore: add more ga event

- README.md
> chore: update discusion group

- packages/steps/src/step.vue
> Steps: fix extra point on simple style

- examples/components/demo-block.vue
- examples/components/footer-nav.vue
- examples/components/footer.vue
- examples/components/header.vue
- examples/components/search.vue
- examples/components/side-nav.vue
- examples/components/theme-picker.vue
- examples/docs/en-US/card.md
- examples/docs/en-US/installation.md
- examples/docs/en-US/rate.md
- examples/docs/es/card.md
- examples/docs/es/installation.md
- examples/docs/es/rate.md
- examples/docs/fr-FR/card.md
- examples/docs/fr-FR/installation.md
- examples/docs/fr-FR/rate.md
- examples/docs/zh-CN/card.md
- examples/docs/zh-CN/installation.md
- examples/docs/zh-CN/rate.md
- examples/i18n/component.json
> chore: use codepen to display demo & fix doc error

- examples/docs/en-US/tooltip.md
- examples/docs/es/tooltip.md
- examples/docs/fr-FR/tooltip.md
- examples/docs/zh-CN/tooltip.md
> docs: Fix tooltip doc error

- packages/input/src/input.vue
- test/unit/specs/input.spec.js
guard against: #14551
fix: #14501, #14521, #14564, #14332, #14575
> input: fix regression

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> changelog for 2.6.2

- examples/demo-styles/cascader.scss
> docs: fix cascader demo style

- packages/theme-chalk/src/common/var.scss
Fixes #14535 
PS: co-author: https://github.com/YangYmimi
> Theme: fix media query is not working in sm-only, md-only, lg-only

- packages/tabs/src/tab-pane.vue
- packages/tabs/src/tabs.vue
fix: Tab active bar doesn't resize when tab label changes dynamically
- Closes #14416 
- Closes #14351
> tab: fix active bar bug (#14416)

- packages/table/src/table-footer.js
> Table: footer follows body cell align

- examples/index.tpl
> chore: Add webpage description

- packages/color-picker/src/color.js
> fix(ColorPicker): Fix handle error hex color string

- packages/select/src/select.vue
Closes #11048
Closes #11069 
Closes #11249
Closes #11549
Closes #11846
> Select: not toggle dropdown when filtering

- packages/tooltip/src/main.js
- src/utils/vdom.js
- src/utils/vue-popper.js
- Closes #14424
- Closes #13368
> Tooltip: displays when initial value is true

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> changelog for 2.7.0

- build/bin/version.js
- build/deploy-ci.sh
- build/deploy-faas.sh
> chore: update doc sub folder

- packages/select/src/select.vue
- test/unit/specs/select.spec.js
> Select: set value to null when cleared (#14322)

- CHANGELOG.es.md
- examples/docs/en-US/border.md
- examples/docs/es/badge.md
- examples/docs/es/border.md
- examples/docs/es/date-picker.md
- examples/docs/es/datetime-picker.md
- examples/docs/es/dialog.md
- examples/docs/es/form.md
- examples/docs/es/input.md
- examples/docs/es/pagination.md
- examples/docs/es/quickstart.md
- examples/docs/es/select.md
- examples/docs/es/table.md
- examples/docs/es/tag.md
- examples/docs/es/timeline.md
- examples/docs/es/transfer.md
- examples/docs/es/tree.md
> Update spanish docs

- build/bin/new.js
> chore: Add French doc for new component

- packages/input/src/input.vue
- test/unit/specs/input.spec.js
> input: update DOM dependent values on type change

- packages/table/src/table-body.js
- packages/table/src/table-store.js
- test/unit/specs/table.spec.js
> Table: `defaultExpandAll` works when expand column exists

- examples/docs/en-US/tabs.md
- examples/docs/es/tabs.md
- examples/docs/fr-FR/tabs.md
- examples/docs/zh-CN/tabs.md
> docs: Optimize Tabs docs

- packages/theme-chalk/src/common/var.scss
- packages/theme-chalk/src/dialog.scss
> Dialog: background color can be configured

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> chore: Update 2.7.1 changelog

- build/deploy-faas.sh
> fix: Fix faas deploy mkdir error

- examples/docs/en-US/card.md
- examples/docs/es/card.md
- examples/docs/fr-FR/card.md
- examples/docs/zh-CN/card.md
> docs: Fix doc img link error

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> chore: Add 2.7.2 changelog

- CHANGELOG.zh-CN.md
> chore: Update changelog zh-cn

- examples/docs/en-US/tabs.md
- examples/docs/en-US/timeline.md
- examples/docs/en-US/transfer.md
- examples/docs/en-US/tree.md
- examples/docs/es/tabs.md
- examples/docs/es/timeline.md
- examples/docs/es/transfer.md
- examples/docs/es/tree.md
- examples/docs/fr-FR/tabs.md
- examples/docs/fr-FR/timeline.md
- examples/docs/fr-FR/transfer.md
- examples/docs/fr-FR/tree.md
- examples/docs/zh-CN/tabs.md
- examples/docs/zh-CN/timeline.md
- examples/docs/zh-CN/transfer.md
- examples/docs/zh-CN/tree.md
> Docs:rename variable in Tree,Transfer,Timeline,Tabs docs

- build/md-loader/containers.js
> chore: hide demo description when it's empty

- examples/docs/zh-CN/upload.md
> docs: Fix upload doc error

- examples/docs/en-US/checkbox.md
- examples/docs/en-US/color-picker.md
- examples/docs/en-US/date-picker.md
- examples/docs/en-US/input-number.md
- examples/docs/es/checkbox.md
- examples/docs/es/color-picker.md
- examples/docs/es/date-picker.md
- examples/docs/es/input-number.md
- examples/docs/fr-FR/checkbox.md
- examples/docs/fr-FR/color-picker.md
- examples/docs/fr-FR/date-picker.md
- examples/docs/fr-FR/input-number.md
- examples/docs/zh-CN/checkbox.md
- examples/docs/zh-CN/color-picker.md
- examples/docs/zh-CN/date-picker.md
- examples/docs/zh-CN/input-number.md
> Docs:rename variable in InputNumber,ColorPicker,Checkbox,DatePicker docs

- build/webpack.demo.js
> chore: use sourcemap when demo dev

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> chore: Fix 2.6.0 changelog error

- examples/docs/en-US/form.md
- examples/docs/es/form.md
- examples/docs/fr-FR/form.md
- examples/docs/zh-CN/form.md
> docs: Update Form custom validator doc

- packages/table/src/table-body.js
- test/unit/specs/table.spec.js
> Table: fix load bug in lazy mode

- examples/docs/en-US/cascader.md
- examples/docs/en-US/datetime-picker.md
- examples/docs/en-US/form.md
- examples/docs/en-US/input.md
- examples/docs/es/cascader.md
- examples/docs/es/datetime-picker.md
- examples/docs/es/form.md
- examples/docs/es/input.md
- examples/docs/fr-FR/cascader.md
- examples/docs/fr-FR/datetime-picker.md
- examples/docs/fr-FR/form.md
- examples/docs/fr-FR/input.md
- examples/docs/zh-CN/cascader.md
- examples/docs/zh-CN/datetime-picker.md
- examples/docs/zh-CN/form.md
- examples/docs/zh-CN/input.md
> Docs:rename variable Cascader,DatetimePicker,Form,Input docs

- examples/docs/en-US/tabs.md
- examples/docs/es/tabs.md
- examples/docs/fr-FR/tabs.md
- examples/docs/zh-CN/tabs.md
上次讨论结论：  文档展示竖形 Tabs 不然容易被用户忽略
> docs: Update Tabs docs to display vertical tabs

- examples/app.vue
> chore: use new domain  eleme.cn

- packages/theme-chalk/src/form.scss
- Closes #15035
- related pr #15049
> Form: required FormItem displays asterisk when label is auto

- packages/rate/src/main.vue
- test/unit/specs/rate.spec.js
> Rate: Fix decimal display support in disabled mode

- build/config.js
- build/webpack.conf.js
> config.js : fix  reg match, webpack.conf.js: minify it

- packages/theme-chalk/src/upload.scss
> fix: Fix Upload transparent picture display style

- examples/demo-styles/rate.scss
- examples/docs/en-US/rate.md
- examples/docs/es/rate.md
- examples/docs/fr-FR/rate.md
- examples/docs/zh-CN/rate.md
- packages/rate/src/main.vue
- src/utils/types.js
- test/unit/specs/rate.spec.js
- types/rate.d.ts
Rate: add custom colors and icon-classes by passing a object
> Rate: add custom colors and icon-classes by passing a object

- components.json
- examples/demo-styles/divider.scss
- examples/demo-styles/index.scss
- examples/docs/en-US/divider.md
- examples/docs/es/divider.md
- examples/docs/fr-FR/divider.md
- examples/docs/zh-CN/divider.md
- examples/nav.config.json
- packages/divider/index.js
- packages/divider/src/main.js
- packages/theme-chalk/src/divider.scss
- packages/theme-chalk/src/index.scss
- src/index.js
- test/unit/specs/divider.spec.js
- types/divider.d.ts
- types/element-ui.d.ts
> Divider: add divider component

- examples/docs/en-US/alert.md
- examples/docs/es/alert.md
- examples/docs/fr-FR/alert.md
- examples/docs/zh-CN/alert.md
- packages/alert/src/main.vue
- packages/theme-chalk/src/alert.scss
- test/unit/specs/alert.spec.js
- types/alert.d.ts
> Alert: Add dark theme

- types/alert.d.ts
> Alert: update type definition

- examples/docs/en-US/collapse.md
- examples/docs/es/collapse.md
- examples/docs/fr-FR/collapse.md
- examples/docs/zh-CN/collapse.md
- packages/collapse/src/collapse-item.vue
- packages/theme-chalk/src/collapse.scss
- types/collapse-item.d.ts
> Collapse: collapse item can be disabled

- packages/form/src/form-item.vue
- packages/form/src/form.vue
close [#14985](https://github.com/ElemeFE/element/issues/14985)
> Form: fix switching the rules in el-form not work (#14985)

- examples/demo-styles/carousel.scss
- examples/docs/en-US/carousel.md
- examples/docs/es/carousel.md
- examples/docs/fr-FR/carousel.md
- examples/docs/zh-CN/carousel.md
- packages/carousel/src/item.vue
- packages/carousel/src/main.vue
- packages/theme-chalk/src/carousel.scss
- src/utils/util.js
- test/unit/specs/carousel.spec.js
- types/carousel.d.ts
> Carousel: add direction attribute and support vertical direction

- examples/docs/en-US/pagination.md
- examples/docs/es/pagination.md
- examples/docs/fr-FR/pagination.md
- examples/docs/zh-CN/pagination.md
- packages/pagination/src/pagination.js
- test/unit/specs/pagination.spec.js
- types/pagination.d.ts
> Pagination: add hide-on-single-page attribute

- examples/docs/en-US/slider.md
- examples/docs/es/slider.md
- examples/docs/fr-FR/slider.md
- examples/docs/zh-CN/slider.md
- packages/slider/src/main.vue
- packages/slider/src/marker.js
- packages/theme-chalk/src/slider.scss
- test/unit/specs/slider.spec.js
- types/slider.d.ts
> Slider: add marks attribute

- examples/docs/en-US/input.md
- examples/docs/es/input.md
- examples/docs/fr-FR/input.md
- examples/docs/zh-CN/input.md
- packages/input/src/input.vue
- packages/theme-chalk/src/input.scss
- src/utils/util.js
- test/unit/specs/input.spec.js
- types/input.d.ts
> Input: add show-word-count attribute

- examples/nav.config.json
> fix: Fix Image route name

- packages/table/src/table-body.js
issue link：http://jsrun.net/AzXKp/edit
> Table: fix cell width when colspan is grater than 1

- examples/i18n/page.json
> fix: Remove duplicated fr translation

- packages/tree/src/model/node.js
- packages/tree/src/model/tree-store.js
- packages/tree/src/tree-node.vue
- types/tree.d.ts
> Tree: performance optimization

- examples/docs/en-US/dropdown.md
- examples/docs/en-US/popover.md
- examples/docs/en-US/tooltip.md
- examples/docs/es/dropdown.md
- examples/docs/es/popover.md
- examples/docs/es/tooltip.md
- examples/docs/fr-FR/dropdown.md
- examples/docs/fr-FR/popover.md
- examples/docs/fr-FR/tooltip.md
- examples/docs/zh-CN/dropdown.md
- examples/docs/zh-CN/popover.md
- examples/docs/zh-CN/tooltip.md
- packages/dropdown/src/dropdown.vue
- packages/popover/src/main.vue
- packages/tooltip/src/main.js
- types/dropdown.d.ts
- types/popover.d.ts
- types/tooltip.d.ts
Closes #11875
Closes #11519
Closes #11512
>  Tooltip, Dropdown, Popover: support tabindex attribute

- packages/theme-chalk/src/dropdown.scss
> Dropdown: 恢复弹窗显示箭头样式

- build/webpack.demo.js
> Build: add hmr

- packages/pagination/src/pagination.js
> fix issue 14663 - slot in ElPagination is not updating

- packages/slider/src/button.vue
* [√] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [√] Make sure you are merging your commits to `dev` branch.
* [√] Add some descriptions and refer relative issues for you PR.
- #14778
> Slider: fix issue #14778 - keyboard a11y

- packages/tabs/src/tab-pane.vue
- packages/tabs/src/tabs.vue
- Closes #15138
- Closes #15136
- Closes #14601
- Closes #14626
> Tabs: rerender when slot changes

- packages/table/src/table-body.js
> Table: improve performance

- examples/i18n/theme-editor.json
- packages/theme-chalk/src/common/var.scss
> Chore: Theme

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> Changelog for 2.8.0

- packages/theme-chalk/src/cascader.scss
- packages/theme-chalk/src/select-dropdown.scss
> Fix: icon error of cascader and select

- packages/theme-chalk/src/link.scss
> Link: fix underline color

- build/bin/version.js
- build/deploy-ci.sh
- build/deploy-faas.sh
> Chore: update build script

- src/mixins/migrating.js
- src/utils/util.js
> Fix: migrating config not compatible with camel case props and events

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> changelog for 2.8.1

- examples/demo-styles/form.scss
- examples/demo-styles/input.scss
> Docs: fix Form and Input demo style

- packages/image/src/main.vue
> Image: remove scrollContainer type restrict

- examples/components/search.vue
> chore: Fix html tag error

- packages/link/src/main.vue
> Link : prevent opening href on disabled el-link

- types/element-ui.d.ts
> Fix: Update link type definition

- packages/calendar/src/date-table.vue
Calendar:fix not correct day of week when the day is Sunday
> Calendar:fix not correct day of week when the day is Sunday

- CHANGELOG.fr-FR.md
- README.md
- examples/docs/en-US/table.md
- examples/docs/fr-FR/alert.md
- examples/docs/fr-FR/calendar.md
- examples/docs/fr-FR/carousel.md
- examples/docs/fr-FR/collapse.md
- examples/docs/fr-FR/divider.md
- examples/docs/fr-FR/dropdown.md
- examples/docs/fr-FR/form.md
- examples/docs/fr-FR/image.md
- examples/docs/fr-FR/input-number.md
- examples/docs/fr-FR/input.md
- examples/docs/fr-FR/link.md
- examples/docs/fr-FR/pagination.md
- examples/docs/fr-FR/popover.md
- examples/docs/fr-FR/rate.md
- examples/docs/fr-FR/slider.md
- examples/docs/fr-FR/table.md
- examples/docs/fr-FR/tabs.md
- examples/docs/fr-FR/tooltip.md
---
Update french documentation and changelog to 2.8.2
Tell me if there is anything wrong.
> Update french doc and changelog (2.8.2)

- CHANGELOG.es.md
- examples/docs/es/alert.md
- examples/docs/es/calendar.md
- examples/docs/es/carousel.md
- examples/docs/es/collapse.md
- examples/docs/es/divider.md
- examples/docs/es/dropdown.md
- examples/docs/es/image.md
- examples/docs/es/input-number.md
- examples/docs/es/input.md
- examples/docs/es/link.md
- examples/docs/es/pagination.md
- examples/docs/es/rate.md
- examples/docs/es/slider.md
> docs: Documentation update to Spanish 2.8.2

- packages/image/src/main.vue
- packages/theme-chalk/src/image.scss
> Image:  fix ssr and object-fit compatibility.

- examples/docs/en-US/cascader.md
- examples/docs/es/cascader.md
- examples/docs/fr-FR/cascader.md
- examples/docs/zh-CN/cascader.md
> Docs: Fix cascader dynamically load example

- build/md-loader/index.js
- build/md-loader/util.js
- examples/index.tpl
- package.json
- yarn.lock
> chore: upgrade dependencies and fix demo bug

- examples/docs/en-US/image.md
- examples/docs/es/image.md
- examples/docs/fr-FR/image.md
- examples/docs/zh-CN/image.md
- packages/image/src/main.vue
- types/image.d.ts
> Image: add referrerPolicy prop

- build/bin/new.js
> Chore: Update make new component logic

- packages/theme-chalk/src/tabs.scss
> Tabs: fix basic tab nested in card tab padding error

- packages/theme-chalk/src/form.scss
> Form: input-group within form-item height error

- packages/tooltip/src/main.js
- test/unit/specs/tooltip.spec.js
- closes #15610
- clsoes #15413
> Tooltip: fix custom tabindex not work

- examples/play/index.vue
- packages/loading/src/directive.js
> loading: 1.修复loading状态更新过快的情况下，loading的dom没有发生变化.

- types/element-ui.d.ts
- types/icon.d.ts
> Type: add Icon type

- packages/select/src/select.vue
- test/unit/specs/select.spec.js
Reverts ElemeFE/element#14650
fix: #15329
move to 3.0
> Revert "Select: set value to null when cleared (#14322)"

- examples/components/theme-configurator/index.vue
- packages/theme-chalk/src/common/popup.scss
- packages/theme-chalk/src/common/var.scss
> Theme: Add popup background design token (Message Dialog)

- types/loading.d.ts
> type: update loading type definition

- examples/demo-styles/tag.scss
- examples/docs/en-US/tag.md
- examples/docs/es/tag.md
- examples/docs/fr-FR/tag.md
- examples/docs/zh-CN/tag.md
- packages/tag/src/tag.vue
- packages/theme-chalk/src/common/var.scss
- packages/theme-chalk/src/tag.scss
- test/unit/specs/tag.spec.js
- types/tag.d.ts
> Tag: add prop effect.

- packages/theme-chalk/src/tabs.scss
> Tabs: left align title when type is card

- packages/radio/src/radio.vue
> radio fix issue 14808

- examples/pages/template/component.tpl
> Docs: fix el-backtop prop type error in component.tpl

- packages/link/src/main.vue
> Link: fix link icon style class

- packages/form/src/form-item.vue
> Form: Fix resetFields issue #(15181)

- packages/slider/src/button.vue
> Slider: Fix style problem when clicking slider bar

- examples/docs/en-US/infiniteScroll.md
- examples/docs/es/infiniteScroll.md
- examples/docs/fr-FR/infiniteScroll.md
> infiniteScroll: update doc

- packages/tag/src/tag.vue
> Tag: fix stop propagation problem

- examples/pages/template/component.tpl
> Docs: fix the side effect by global el-scrollbar style

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> Changelog for 2.9.0

- types/infiniteScroll.d.ts
> Revert "Update infiniteScroll.d.ts"

- types/element-ui.d.ts
- types/infiniteScroll.d.ts
> Chore: Update infiniteScroll type

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> Chore: update changelog 2.9.0

- examples/components/header.vue
- examples/components/theme/loader/api.js
> Chore: update api host

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> Changelog for 2.9.1

- examples/docs/fr-FR/tree.md
> Docs-fr : fix spelling mistakes

- packages/tree/src/model/tree-store.js
> Tree: fix setCurrentNodeKey

- types/upload.d.ts
> fix(types): update the parameter `fileList` type for `ElUpload` hooks

- packages/tree/src/model/tree-store.js
* [ ✔️] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [✔️ ] Make sure you are merging your commits to `dev` branch.
* [✔️ ] Add some descriptions and refer relative issues for you PR.
原来的写法意思是循环所有的chilren,
但其实只要有一个孩子节点的visible为true,则allHidden就为false,在这个场景下用Array.some比较合适
> Tree: Modify loop conditions to improve performance

- examples/components/theme/loader/api.js
> Chore: Update test api host

- packages/table/src/store/tree.js
- packages/table/src/table-body.js
> Table: fixed  loading icon not display

- test/unit/specs/upload.spec.js
> Upload: fix type error in unit test

- examples/docs/zh-CN/divider.md
> Docs: fix Divider attribute type in zh-cn

- packages/select/src/select.vue
> Select: fix initialInputHeight

- types/message.d.ts
https://github.com/ElemeFE/element/commit/384c56381ce109b6fe1ab081fac4c9a7c2c392bf#diff-baba82a3fc93637f3cf1aac284f335f2R213
> Added type def for Message offset option

- examples/docs/en-US/quickstart.md
- examples/docs/es/quickstart.md
- examples/docs/fr-FR/quickstart.md
- examples/docs/zh-CN/quickstart.md
> doc:add missing components in quickstart;

- packages/table/src/store/current.js
- packages/table/src/store/index.js
- packages/table/src/store/watcher.js
- packages/table/src/table.vue
- Closes #15861
- current-row-key 的 bug 重现链接：http://jsrun.net/dVyKp/edit
> Table: fix current-row-key and select event bug

- packages/timeline/src/main.vue
> Timeline: fix reverse broken

- examples/docs/en-US/button.md
- examples/docs/es/button.md
- examples/docs/fr-FR/button.md
- examples/docs/zh-CN/button.md
- packages/theme-chalk/src/button.scss
- packages/theme-chalk/src/common/var.scss
> Button: Revert adding compact size

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
- test/unit/specs/upload.spec.js
> Chore: Release 2.9.2

- packages/theme-chalk/src/form.scss
> Form: remove success status

- packages/badge/src/main.vue
> Badge: update prop check

- packages/dialog/src/component.vue
> Revert "Dialog: Fix close bug (#15000)"

- examples/components/theme/components-preview.vue
- packages/theme-chalk/src/avatar.scss
- packages/theme-chalk/src/common/var.scss
> Avatar: Update theme config var

- examples/docs/en-US/page-header.md
- examples/docs/es/page-header.md
- examples/docs/fr-FR/page-header.md
Deleting the display of "html" text inside the component and the code in the documentation.
> Docs: delete an incorrect closing html tag and empty block code

- CHANGELOG.es.md
> Update changelog 2.9.2 Spanish

- packages/select/src/select.vue
> Select: fix double import problem

- packages/table/src/store/index.js
- packages/table/src/store/watcher.js
> Table: fix reserve-selection not work

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> Chore: Add changelog for 2.10.0

- README.md
> Chore: Update Dingtalk Group QR image

- examples/pages/template/index.tpl
> Chore: update index page theme intro english css style

- packages/table/src/store/watcher.js
- test/unit/specs/table.spec.js
Reproduce link: https://codepen.io/anon/pen/BeygzE
After click `Sort by Name` sort icon from `Date` column not hidden.
I found that need clear `sortingColumn.order` when change sort column.
> Table: fix sort icon

- packages/table/src/table.vue
- packages/theme-chalk/src/table.scss
> Table: fix layout break when append slot exists

- packages/tag/src/tag.vue
- Closes #16191
- Closes #16161
> Tag: compatible with IE

- packages/table/src/filter-panel.vue
> Table: register scrollbar in filter-panel

- packages/table/src/table-column.js
> Table: fix table column prop showOverflowTooltip not reactive.

- packages/theme-chalk/src/checkbox.scss
If `.el-checkbox` is not parent element last child, `:last-child` will invalid
> Checkbox: enhance css selector

- packages/tree/src/model/tree-store.js
setCurrentKey(null) 时需要先设置节点的isCurrent的为false
https://codesandbox.io/s/vue-template-iexmx?fontsize=14
- Closes #16127
> Tree: set isCurrent prop to False

- packages/cascader-panel/src/cascader-node.vue
> Cascader: fix level 1 children is empty update problem (#16348)

- examples/components/theme/loader/api.js
> Chore: update theme base api

- examples/components/header.vue
- examples/components/theme/loader/api.js
> Chore: update theme inner api

- packages/select/src/option.vue
fix: #16074
reproduction link:  https://codepen.io/island205/pen/orarPy
> Select: Fix memory leak issue

- packages/cascader-panel/src/cascader-panel.vue
> Cascader: add sets default values when lazy is true

- examples/pages/template/component.tpl
> Chore: Fix doc anchor bug

- packages/theme-chalk/src/common/var.scss
- packages/theme-chalk/src/form.scss
> Form: Add theme token

- src/locale/lang/th.js
> I18n: Update translation of Thai language

- packages/theme-chalk/src/avatar.scss
[issue](https://codepen.io/zlc52547/pen/RzJNQx)
> Avatar: fix image not center vertically issue

- examples/docs/en-US/dialog.md
- examples/docs/es/dialog.md
- examples/docs/fr-FR/dialog.md
- examples/docs/zh-CN/dialog.md
- packages/dialog/src/component.vue
- test/unit/specs/dialog.spec.js
- types/dialog.d.ts
> Dialog: add destroyOnClose attribute

- examples/docs/en-US/image.md
- examples/docs/es/image.md
- examples/docs/fr-FR/image.md
- examples/docs/zh-CN/image.md
- packages/image/src/image-viewer.vue
- packages/image/src/main.vue
- packages/theme-chalk/src/image.scss
- src/utils/util.js
- test/unit/specs/image.spec.js
- types/image.d.ts
> Image: Add big Image preview feature (#16333)

- build/bin/version.js
- build/deploy-ci.sh
- build/deploy-faas.sh
> Chore: Update build folder

- packages/image/src/image-viewer.vue
- src/utils/util.js
> Image: Fix image ssr (#16737)

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> Chore: Changelog 2.11.1

- packages/carousel/src/main.vue
> Carousel: Fix onChange emit value

- packages/notification/src/main.js
> Notification: Fix modifying incoming option object

- test/unit/specs/date-picker.spec.js
> Test: correct spelling error

- types/upload.d.ts
> Upload: Fix upload type error (#16252)

- packages/theme-chalk/src/cascader-panel.scss
- packages/theme-chalk/src/tree.scss
close #16795
- Cascader: delete surplus style
- Tree: increase css weight to reset margin value
> Tree: Increase css weight

- packages/date-picker/src/basic/time-spinner.vue
Issues : [#16685](https://github.com/ElemeFE/element/issues/16685#event-2522503138l)
> fix bug #16685,use Math.round instead of Math.floor

- packages/table/src/table-header.js
> Table: prevent click handler after drag

- packages/tabs/src/tab-bar.vue
>  Tab: fix tabs-item's padding cause active-bar's width and transform err(  … #15355)

- examples/docs/en-US/custom-theme.md
- examples/docs/es/custom-theme.md
- examples/docs/fr-FR/custom-theme.md
- examples/docs/zh-CN/custom-theme.md
> Docs: Update custom theme

- CHANGELOG.es.md
- examples/docs/es/date-picker.md
- examples/docs/es/datetime-picker.md
- examples/docs/es/dialog.md
- examples/docs/es/drawer.md
- examples/docs/es/image.md
- examples/docs/es/popover.md
>  DOC: update spanish doc 2.11.1

- examples/docs/en-US/i18n.md
- examples/docs/es/i18n.md
- examples/docs/fr-FR/i18n.md
- examples/docs/zh-CN/i18n.md
- src/locale/lang/eo.js
**Please SQUASH my pull request**
> Locales: add Esperanto translation

- packages/input/src/input.vue
> Input: the click event of clear button is not trigger when using v-loading

- packages/tabs/src/tab-nav.vue
Close #16563
Close #16532
Tabs `scrollToActiveTab` 之前没有考虑竖向滚动的情况
> Tabs: fix activated tab is out of visual range bug

- packages/radio/src/radio-group.vue
> Fix: Radio Group does not produce valid HTML in tables

- packages/table/src/store/tree.js
> Table: toggleTreeExpansion

- packages/checkbox/src/checkbox.vue
- packages/table/src/store/helper.js
- packages/table/src/store/watcher.js
- test/unit/specs/table.spec.js
> Table: set toggleAllSelection as instance property

- packages/theme-chalk/src/dialog.scss
> Change hard-coded padding of dialog body to be responsive to sass var

- packages/calendar/src/main.vue
> Calendar: fix locale error

- packages/theme-chalk/src/transfer.scss
> Transfer: fix style error

- packages/select/src/select.vue
close #16559 
pick from #12210
> Select: not toggle dropdown when filtering (#16559)

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> changelog for 2.12.0

- build/bin/version.js
- build/deploy-ci.sh
- build/deploy-faas.sh
> chore: update folder

- examples/docs/zh-CN/time-picker.md
fix typo  :(
https://github.com/ElemeFE/element/issues/17243
> doc: fix time-select typo

- README.md
I only fixed a small typo error.
> README: fixed small error

- packages/theme-chalk/src/avatar.scss
> Avatar: remove no-used css-property

- packages/theme-chalk/src/table.scss
> Table: update table header cell style

- packages/table/src/store/current.js
- packages/table/src/store/watcher.js
- packages/table/src/table-layout.js
> Table: fix table header height after filter

- packages/table/src/table-body.js
- test/unit/specs/table.spec.js
> Table: fixed row-style with display not work

- build/webpack.demo.js
> Chore: fix locale

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
> Update Spanish changelog 2.12.0

- packages/calendar/src/main.vue
- packages/theme-chalk/src/calendar.scss
> Calender: import el-button and el-button-group

- packages/message-box/src/main.vue
- packages/theme-chalk/src/message-box.scss
> MessageBox: Fix icon position error

- src/locale/lang/es.js
> update locale es.js

- README.md
> Chore: update readme Dingtalk QR code

- packages/message/src/main.js
> Message: fix close instace offsetHeight（#17564）

- examples/docs/fr-FR/avatar.md
- examples/docs/fr-FR/cascader.md
- examples/docs/fr-FR/date-picker.md
> Docs-fr : Update avatar french translation 

- packages/menu/src/menu.vue
> Menu: fix router NavigationDuplicated error when using vue-router@^3.1.0

- types/dropdown.d.ts
> Dropdown: update type file

- build/release.sh
- test/ssr/require.test.js
> Feat/test SSR test

- examples/docs/en-US/progress.md
- examples/docs/es/progress.md
- examples/docs/fr-FR/progress.md
- examples/docs/zh-CN/progress.md
- packages/progress/src/progress.vue
- types/progress.d.ts
> Progress: add strokeLinecap prop

- packages/image/src/image-viewer.vue
- packages/image/src/main.vue
- test/unit/specs/image.spec.js
close #16985
当 preview-src-list 包含 src时，点击图片放大定位到 src 所在的index，将图片设置为当前预览项。
> Image: Perfect picture preview behavior (#16985)

- packages/theme-chalk/src/avatar.scss
> Revert "Avatar: remove no-used css-property"

- src/locale/lang/sv-SE.js
Some of the entries in the swedish locale file were incomplete or wrong.
> Update locale sv-SE.js

- examples/docs/en-US/input.md
sorry for that, i did not delete the repeat change event in my early PR #18061
This PR  fix for this.
> docs: delete Input  repeat change event

- packages/theme-chalk/src/scrollbar.scss
> ScrollBar: Fix FF scroll bar width

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
- build/bin/version.js
- build/deploy-ci.sh
- build/deploy-faas.sh
> Chore/release 2.13.0

- examples/docs/en-US/popconfirm.md
- examples/docs/es/popconfirm.md
- examples/docs/fr-FR/popconfirm.md
- examples/docs/zh-CN/popconfirm.md
> chore: popconfirm doc update

- packages/carousel/src/item.vue
When I go through the source code of carousel component, I found a type error, so I make this pull request to fix it.
> Carousel: fix console typo bug

- examples/docs/en-US/input-number.md
- examples/docs/es/input-number.md
- examples/docs/fr-FR/input-number.md
- examples/docs/zh-CN/input-number.md
* [-] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [-] Make sure you are merging your commits to `dev` branch.
* [-] Add some descriptions and refer relative issues for you PR.
> [Input Number]: fix step-strictly docs typo

- packages/image/src/main.vue
Fix preview dose not show when preview list not contain src(#18975 )
> Image: Fix preview dose not show when preview list not contain src issue (#18975)

- examples/pages/template/index.tpl
> chore: remove index intro

- packages/image/src/main.vue
- test/unit/specs/image.spec.js
> Image: Fix shortcut key not work at second time issue (#18983)

- examples/docs/en-US/steps.md
- examples/docs/es/steps.md
- examples/docs/fr-FR/steps.md
- examples/docs/zh-CN/steps.md
The type mentioned in demo, as in the above image, is not consistent with the one in the description in attributes part, as in the following image.
> Docs: fix a type error in document of steps component.

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
- examples/pages/template/changelog.tpl
> Chore: Update Changelog

- packages/autocomplete/src/autocomplete.vue
> Autocomplete: fix change event

- packages/image/src/main.vue
> Image: 解决当src是一个错误的地址时，立刻变成正确的地址后，onerror会在后续回调中继续执行，导致正确的图片显示加载失败

- src/locale/lang/ca.js
- src/locale/lang/es.js
Added some missing translations for Spanish and Catalan :smile:
> Added Catalan and Spanish translations

- src/locale/lang/id.js
> Update Locale Indonesia (id.js)

- README.md
> chore: Update Discussion Group Link

- packages/progress/src/progress.vue
> fix(progress): attribute error

- README.md
add migration guide to Vue 3.0
> chore: update README (Vue 3.0)

- examples/docs/zh-CN/color-picker.md
Fix Color-Picker default value typo
修复 Color-Picker 写错的默认值
-----
> Docs: fix color-picker default value typo

- src/locale/lang/ar.js
* [ X ] Make sure you follow Element's contributing guide.
* [ X ] Make sure you are merging your commits to `dev` branch.
* [ X ] Add some descriptions and refer relative issues for you PR.
Popconfim text buttons wasn't translated with a comment "to be translated", i find that the proposed translation suitable as my native language is Arabic.
> [popconfirm] Complete Arabic Translation

- README.md
Now that Vue.js 3.0 has been release, it'll be nice to let users/developers know that we are working on the migration there.
fix #20198 #19964 #19587 #20174 #20061 #19857 
> Add link to Vue.js 3.0 Migration repository

- packages/popover/src/main.vue
fix #17274
fix #18587
fix #18586
> Popover: compatible with 2.6 new v-slot syntax

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> chore: update change log

- .github/ISSUE_TEMPLATE/config.yml
> chore: update issue template

- packages/popconfirm/src/main.vue
> fix: fix Popconfirm i18n bug

- examples/docs/fr-FR/datetime-picker.md
> DatetimePicker: fix typo in french translation of datetime-picker.md

- packages/drawer/src/main.vue
- packages/theme-chalk/src/drawer.scss
> Drawer: fix focus bug

- packages/image/src/image-viewer.vue
- packages/popconfirm/src/main.vue
- packages/theme-chalk/src/image.scss
- test/unit/specs/image.spec.js
图片预览功能优化 #20505 #19330
1. 支持 appendToBody
2. 支持点击 mask 关闭
3. 优化 close 按钮样式
> Image: preview optimization

- packages/drawer/src/main.vue
`size` 属性增加对 `number` 类型的支持。
ref: #20636
> Drawer: fix size bug

- packages/image/src/main.vue
Fixes #15278  #17610
Re-open PR from #17611 (Base from #15346)
> Image: fix incorrect object fit ratio in IE

- examples/pages/template/resource.tpl
ref https://github.com/ElementUI/Resources/pull/10
> chore: update Axure resource v2.1.0

- packages/cascader-panel/src/cascader-panel.vue
> Cascader: fix cascader panel active path

- packages/color-picker/src/color.js
> fix:修复color.js对长度8的井号颜色表达式的判断错误

- packages/calendar/src/date-table.vue
> fix: fix calendar component i18n bug

- examples/components/header.vue
- examples/pages/template/index.tpl
> chore: update header banner

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> Doc: add change log

- examples/components/header.vue
- examples/components/theme/loader/api.js
> chore: remove getTestEle

- packages/input/src/input.vue
> Input: fix show password cursor

- packages/theme-chalk/src/input.scss
> Input: fix show password icon in edge

- src/utils/types.js
> fix: isFunction

- packages/carousel/src/item.vue
- packages/carousel/src/main.vue
fix: #20916
* [-] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [-] Make sure you are merging your commits to `dev` branch.
* [-] Add some descriptions and refer relative issues for you PR.
> Carousel: fix interval and scale bug

- packages/cascader/src/cascader.vue
> Cascader: fix delete tag bug

- packages/theme-chalk/src/drawer.scss
> Drawer: add overflow auto

- components.json
- examples/demo-styles/index.scss
- examples/demo-styles/skeleton.scss
- examples/docs/en-US/skeleton.md
- examples/docs/es/skeleton.md
- examples/docs/fr-FR/skeleton.md
- examples/docs/zh-CN/skeleton.md
- examples/nav.config.json
- packages/skeleton-item/index.js
- packages/skeleton/index.js
- packages/skeleton/src/img-placeholder.vue
- packages/skeleton/src/index.vue
- packages/skeleton/src/item.vue
- packages/theme-chalk/src/common/var.scss
- packages/theme-chalk/src/index.scss
- packages/theme-chalk/src/skeleton-item.scss
- packages/theme-chalk/src/skeleton.scss
- src/index.js
- test/unit/specs/skeleton.spec.js
- types/element-ui.d.ts
- types/skeleton-item.d.ts
- types/skeleton.d.ts
> Skeleton: add skeleton component

- src/locale/lang/hr.js
fix: #21037 
ref: https://github.com/moment/moment/blob/develop/locale/hr.js#L92
> Local: fix week translations for hr locale

- packages/table/src/store/tree.js
> Table: fix lazy load data

- packages/drawer/src/main.vue
- test/unit/specs/drawer.spec.js
ref: https://github.com/ElemeFE/element/issues/20339
> Fix drawer destroy

- examples/docs/en-US/layout.md
- examples/docs/es/layout.md
- examples/docs/fr-FR/layout.md
- examples/docs/zh-CN/layout.md
- packages/row/src/row.js
- packages/theme-chalk/src/row.scss
> Row: fix align top

- packages/select/src/select.vue
> Select: fix the bug when the value is Boolean

- packages/calendar/src/date-table.vue
> Calendar: fix first-day-of-week

- types/skeleton.d.ts
> Skeleton: fix skeleton.d.ts

- types/element-ui.d.ts
> CascaderPanel: export type

- types/element-ui.d.ts
- types/spinner.d.ts
> Spinner: add spinner.d.ts

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> feat: add changelog

- components.json
- examples/demo-styles/descriptions.scss
- examples/demo-styles/index.scss
- examples/docs/en-US/descriptions.md
- examples/docs/es/descriptions.md
- examples/docs/fr-FR/descriptions.md
- examples/docs/zh-CN/descriptions.md
- examples/nav.config.json
- packages/descriptions-item/index.js
- packages/descriptions/index.js
- packages/descriptions/src/description-item.js
- packages/descriptions/src/descriptions-row.js
- packages/descriptions/src/index.js
- packages/theme-chalk/src/common/var.scss
- packages/theme-chalk/src/descriptions-item.scss
- packages/theme-chalk/src/descriptions.scss
- packages/theme-chalk/src/index.scss
- src/index.js
- test/unit/specs/descriptions.spec.js
- types/descriptions-item.d.ts
- types/descriptions.d.ts
- types/element-ui.d.ts
> Descriptions: add description component

- packages/message/src/main.js
> Message: fix message[type]

- packages/carousel/src/main.vue
> Carousel: reset the timer when setActiveItem method is called

- packages/tree/src/model/node.js
> Tree: fix insertChild

- packages/select/src/select.vue
fix: #21142
fix: #21178
fix: #21089
fix: #19499
close: #21143
> Select: fix a bug that makes the browser jitter in zoom mode

- packages/select/src/select.vue
> Select: fix resetInputHeight

- CHANGELOG.en-US.md
- CHANGELOG.es.md
- CHANGELOG.fr-FR.md
- CHANGELOG.zh-CN.md
> chore: add changelog

- packages/cascader/src/cascader.vue
> Cascader: fix a bug that makes the browser jitter in zoom mode

- src/locale/lang/it.js
Problem:
The name is the same for two different meanings.
> fix: italian mistake

- packages/cascader/src/cascader.vue
> Cascader: optimize performance

- packages/theme-chalk/src/select-dropdown.scss
- packages/theme-chalk/src/select.scss
> Select: fix long text overflow in multiple mode

- packages/radio/src/radio-button.vue
- packages/radio/src/radio.vue
> Radio: fix checked state when browser go back

- packages/badge/src/main.vue
- test/unit/specs/badge.spec.js
> Badge: fix type class when is-dot

- .github/workflows/preview.yml
> Chore: create preview.yml

- packages/descriptions/src/descriptions-row.js
- packages/theme-chalk/src/descriptions-item.scss
> Descriptions: fix label slot bug

- packages/table/src/config.js
- packages/table/src/table-header.js
close: #21274
close: #21267
close: #21305
> Table: fix toggleAllSelection bug when table is empty

- packages/button/src/button.vue
> Button: fix disabled priority

- packages/table/src/store/index.js
- packages/table/src/table-body.js
- packages/table/src/table-layout.js
- packages/table/src/table-row.js
- packages/table/src/table.vue
> Table: revert sync fixed table rows height

- src/locale/lang/az.js
> locale: Added Azerbaijani language

- examples/components/demo-block.vue
- examples/docs/en-US/i18n.md
- examples/docs/es/i18n.md
- examples/docs/fr-FR/i18n.md
- examples/docs/zh-CN/i18n.md
> fix: vue version explicitly to 2.x

- src/locale/lang/is.js
> Locale Icelandic

- packages/date-picker/src/basic/time-spinner.vue
Method name typo, `bindFuntion` should be `bindFunction`.
> DatePicker: fix function name typo

- src/locale/lang/sw.js
* [ x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ x] Add some descriptions and refer relative issues for you PR.
> Swahili Locale

- packages/tooltip/src/main.js
> Tooltip:fix getFirstElement

- src/locale/lang/si.js
භාෂාවේ නම: Sinhalese / Sinhala
දේශීය නම: සිංහල
කේතය: සිං / si
> නව භාෂාවක් එකතු කිරීම

- src/locale/lang/ms.js
> 国际化：增加马来西亚语

- packages/loading/src/directive.js
- packages/loading/src/index.js
> loading: 解决：定位方式为sticky的DOM使用loading时，会失去粘性

- examples/docs/en-US/skeleton.md
- examples/docs/es/skeleton.md
- examples/docs/fr-FR/skeleton.md
> Docs: Update skeleton.md redundant content

- src/utils/date-util.js
> date_util: pref_修改获取月份最后一天函数可读性_0815

- src/locale/lang/ms.js
> i18n: Fix Malaysian translation

- packages/statistic/src/main.vue
statistic：Fixed the thousandth bit bug
> statistic：Fixed the thousandth bit bug

- README.md
> docs: repair document links

- package.json
> chore: missing web-types after publishing

- packages/statistic/src/main.vue
> statistic : slot display bug

- .gitignore
- src/directives/repeat-click.js
- src/utils/util.js
> inputNumber: fix touch one click trigger twice on the window touch pad

- examples/docs/zh-CN/pagination.md
> docs: 修复layout属性的siezs属性值在第一个示例中显示错误 issue(#22220)

- examples/docs/en-US/datetime-picker.md
> docs(en-US): [DateTimePicker]

- examples/docs/es/input.md
- examples/docs/fr-FR/input.md
> docs: Input Events Table remove repeated input event.

- src/locale/lang/es.js
This was already changed in the DatePicker
> Spanish translation "Despejar" doesn't make sense in this case. 

- README.md
- examples/components/footer.vue
- examples/components/header.vue
- examples/i18n/component.json
> docs: update readme and website example links

- examples/docs/en-US/tooltip.md
- examples/docs/es/tooltip.md
- examples/docs/fr-FR/tooltip.md
- examples/docs/zh-CN/tooltip.md
Update documents link of Popper. The older one is 404 now.
> Update documents link of Popper. The older one is 404 now.

- packages/image/src/image-viewer.vue
> Img: delete referrerpolicy prop
